### ISSUE TITLE
Generere utskriftsvennlig versjon av utstedt skifteattest

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#100]
Aktør involvert: domstolene

Knyttet til brukerhistorie: Generere utskriftsvennlig versjon av utstedt skifteattest

beskrivelse: det er utenfor scope for MVP at det sendes varsel til aktørene om at det foreligger digital representasjon av skifteattesten - aktørene i prosjektet ønsker ikke automatisk trigging av sine forretningsprosesser. Vi bør derfor vurdere om det skal være mulig for arvinger/fullmektig å ha en papirversjon av skifteattesten.

Relatert til #99 

Frist:

**Comment by TageGitHub** [comment]
Hensyntatt i #222
