### ISSUE TITLE
Opprette instans i Altinn Dødsbo

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#101]
#### Brukerhistorie:
Som et  system
ønsker jeg å opprette en ny instans fra et dødsfall
slik at jeg får etablert et nytt unikt digitalt dødsbo.

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser: N/A
Lenke til design: N/A
Lenke til arkitektur:

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- Verifiser at instansen er opprettet (f.eks med postmann)  i Altinn tjeneste 3.0
- Unik ID (Unik ID = dnummer/fødselsnummer) på instans
- Endepunktet fra DA må sikres at det ikke inneholder arvinger som er reservert mot digital kommunikasjon

#### Annen info til brukerhistorien:
- DA leverer første utkast av sitt API. Vi setter kravene til dette.
- DA skal "legge inn" dødsfallet digitalt slik at det er tilgjengeliggjort for Altinn Dødsbo.
- Det skal inneholde flere felter. Første versjon kan være bare fødselsnummer/d-nummer

- OED leser fra DA API og oppretter instans

- Første versjon av API'et trenger bare å gi oss at det har skjedd et dødsfall_ - m/ fødselsnummer på avdøde

Avklaringer som må tas:
- [x] Er det korrekt at instansen opprettes FØR kontaktperson og rolle opprettes? Ja
- [ ] Hva trigger opprettelsen av instansen? Notifikasjon fra DA/Spørring fra oss @RogerKjaernsrod  @HenningNormann - tanker?
- [ ] Domstolene er ny autoritativ kilde for Altinn autorisasjon
- [ ] Se #102 - Har DA selv noen formening om hvordan Altinn Dødsbo skal få greie på at det har skjedd et nytt dødsfall?

#### Juridiske forbehold for å få realisere denne brukerhistorien:
- [ ] Vi får rettslig grunnlag til å opprette en instans på et avdødes fødselsnummer. Digdir må ha et rettslig grunnlag (for full MVP) som sier at den skal stille en slik tjeneste tilgjengelig, for hvem, hva som skal utføres i tjenesten, med hvilke aktører, hvem som har rett på hvilke opplysninger, hvilke opplysninger Altinn dødsbo har rett på fra domstol m.v. 
- [ ] At Domstolene har lov til å videreformidle informasjon om avdøde til oss (Fødselsnr og d-nr)

- [ ] Vi får lov å lagre denne informasjonen på Tjeneste 3.0 for hver instans i appen

- [ ] Hva skal til for at domstolene blir autoritativ kilde for Altinn autorisasjon og OED-appen?

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by lillelars** [comment]
@benedicteos "Endepunktet fra DA må sikres at det ikke inneholder arvinger som er reservert mot digital kommunikasjon" 
Stemmer det at du kan benytte deg av applikasjonen OED selv om du er reservert mot digital kommunikasjon?

**Comment by lillelars** [comment]
@JanAage99  Har vi fått avklart videre med Altinn autorisasjon angående hvordan de skal motta at det har skjedd et dødsfall og det blir opprettet en instans ?

**Comment by benedicteos** [comment]
> @benedicteos "Endepunktet fra DA må sikres at det ikke inneholder arvinger som er reservert mot digital kommunikasjon"
> Stemmer det at du kan benytte deg av applikasjonen OED selv om du er reservert mot digital kommunikasjon?

Nei, dersom du er reservert mot digital kommunikasjon får OED aldri informasjon om det aktuelle dødsboet fra DA. DA skal sjekke om noen arvinger er reservert, dersom de er det, så er boet ikke aktuelt for OED. De som er reservert kan ikke bruke OED,

**Comment by TageGitHub** [comment]
Videreført i #171
