### ISSUE TITLE
Hvordan får Altinn Dødsbo beskjed om at et nytt dødsfall inntreffer?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#102]
Aktør involvert:
- DA
Knyttet til brukerhistorie:
#101 

beskrivelse:
I det et nytt dødsfall inntreffer så skal DA f.eks legge det ut på et endepunkt som vi lytter til?
Alternativt at DA gir oss beskjed/notification hver gang et dødspunkt inntreffer.

DA ønsker å legge ut nye LOVISA-saker i en digital liste fortløpende ettersom de kvalifiserer for å publiserers i denne listen. Nye saker identifiseres med (stigende (antagelse)) løpe-/saksnummer. Denne listen inneholder også et felt som identifiserer hva slags sak det er feks dødsfall, tvangsfullbyrdelse eller andre Samarbeidspartnere til DA slik som OED tar selv ansvar for og holder rede på hvilke dødsfall som er hentet fra listen. Når nye dødsfall skal hentes i neste kall, skal da OED hente dødsfall som er nyere/har høyere løpenummer enn det siste / høyeste som ble hentet ved siste kall. 
Når et kall har returnert et sett med saksnummer kan et API med utfyllende informasjon kalles for å få mer informasjon om dødsfall og arvinger. 
Mønster med liste som det blir lagt til entries på fortløpende er analogt med hvordan det gjøres i DSOP-prosjekt Kontrollinfo

Avklaringer:
Her får OED en mer aktiv rolle ifht å danne autorative data iom at OED først må sjekke liste og deretter hente data for dødsfall/arvinger. Er det OK ? 
Vil være nyttig om liste også har et felt som sier om det er ny entry eller bare endret entry eller slettet entry ?

**Comment by lillelars** [comment]
Fra møte med DA 24.06:
DA kommer opp med et forslag til hvordan de eksponerer denne informasjonen. DA har ambisjon om å stille med offentlige API'er.

**Comment by TageGitHub** [comment]
Videreført i #156
