### ISSUE TITLE
Arvinger skal relateres til instans av Altinn Dødsbo

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#103]
#### Brukerhistorie:
Som et system
ønsker jeg at arvinger skal kunne knyttes til instans av Altinn dødsbo
slik at arving får tilgang til riktig dødsbo med riktige roller og rettigheter

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser: N/A
Lenke til design: N/A
Lenke til arkitektur: 

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- Systemet skal ha minst en arving på instansen av dødsboet. (For Scenario 1 skal det maks være 1 arving pr dødsbo) (171
- Systemet skal hente roller og rettigheter fra Altinn Autorisasjon
- Instans av Altinn dødsbo knyttes til Dnummer/Fnr til avdøde som identifikator
- Arvinger relateres til instans av dødsbo via eget Dnummer/Fnr som relateres til avdødes Dnummer/Fnr

#### Mer info til behov:
- Del to av API'et fra DA: 
 - inneholder:
- navn på arvinger
- fødselsnummer til arving
- relasjon mot avdøde (IKKE MVP).

#### Forbehold for å få realisere denne brukerhistorien:
- [ ] Altinn Autorisasjon har hentet inn korrekte roller og rettigheter fra DA
- [ ] Dersom en av arvingene har reservert seg mot digital kommunikasjon i KRR skal det ikke være mulig for noen arvinger å bruke OED. Det er ikke pr uke 36 avklart om DA eller OED skal sjekke med KRR om arving er reservert. 
- [ ] Rolle og rettighetskart må være etablert

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by lillelars** [comment]
@JanAage99 hva er status med denne? Har vi noe kontakt med Siv i AltinnAutorisasjon enda?

**Comment by TageGitHub** [comment]
Overført til #171 og #172
