### ISSUE TITLE
Hva er merkevaren/verdien/visjonen/målene ? Skal vi forholde oss til Altinn som merkevare eller ikke?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#106]
Aktør involvert:
Altinn

Knyttet til brukerhistorie:

beskrivelse:
Skal vi forholde oss til Altinn som merkevare eller skal vi implementere Altinn Dødsbo som en egen tjeneste og merkevare det som et egen apllikasjon?

Frist:
ASAP

**Comment by lillelars** [comment]
@curlingnina  Hei Nina.. Denne er er en showstopper for hvordan vi designer løsningen. Dette må avklares asap (men bli frisk først ) :) )

**Comment by curlingnina** [comment]
Denne saken er allerede løftet til ledelsen. Se mail.

**Comment by lillelars** [comment]
oppdatering: Skal tas en beslutning tirsdag 18. August

**Comment by curlingnina** [comment]
Det er besluttet at OED skal forholde sesg til Altinn som mekrevare. Dvs benytte Altinn designsystem, og altinn.no
