### ISSUE TITLE
DAs API for dødsfall

### ISSUE THREAD

**Issue by JanAage99** [Altinn/oed#109]
#### Brukerhistorie:
Som et system
ønsker jeg å tilby Rest-API for dødsfall
slik at det kan konsumeres av eksterne konsumenter

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):
1 - kritisk

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- bruker skal se....
- bruker skal bli tatt til...

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by benedicteos** [comment]
Realiseres av #101
