### ISSUE TITLE
Hva skal stå i det digitale brevet til arvingene?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#110]
Aktør involvert:
DA

Knyttet til brukerhistorie:
#59
beskrivelse:

- [ ]  Hvor mye må vi ha med i brevet kontra løsning angående info om roller/rettigheter osv..?
JÅB: Både informasjon om roller og rettigheter (i OED) og opplysningsplikt som DA har ivaretas i OED-app og ikke i brev. 

- [ ] Skal brevet inneholde informasjon om det konkrete dødsfallet eller skal dette være et generelt brev?
JÅB: Brev må som et minimum ha informasjon om hvem som har gått bort. Ellers bør resten være generell informasjon om OED og at videre informasjon finnes der. 

Frist:

**Comment by lillelars** [comment]
@kajabystol Bør Domstolenes opplysningsplikt ivaretas med dette digitale brevet, eller kan det håndteres i informasjonsflyten med appen vår?

**Comment by kajabystol** [comment]
@lillelars Jeg tenker at dette skal dekkes under informasjonsflyten i selve tjenesten. Det kan lett bli information overload og forvirring for arvinger hvis vi skal informere om dette i tillegg til bruk av tjenesten.

**Comment by TageGitHub** [comment]
Videreført i #170
