### ISSUE TITLE
Hvordan skal vi formidle skifteform til Domstolene og hva skal den inneholde?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#111]
Aktør involvert:
DA

Knyttet til brukerhistorie:
#26
#116 

beskrivelse:

- [ ] Vi skal formidle ønsket skifteform til Domstolene. 
JÅB: OED skal bare dekke privat skifte. Det må således informeres i brev/ved innlogging at OED bare skal brukes ved privat skifte (og hva privat skifte er for noe ifht andre skifteformer slik at rett form velges). Så må det videre informeres om at ved andre skifteformer så må dette tas manuelt med aktuell tingrett. 

- [ ] Trenger Domstolen hele skifteformen eller bare deler av den?
JÅB: Del av skifteform ? 

Frist:

**Comment by TageGitHub** [comment]
Videreført i #228
