### ISSUE TITLE
Innhenter domstolene info om tinglyst ektepakt fra brreg selv?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#112]
Aktør involvert:
DA

Knyttet til brukerhistorie:

beskrivelse:
Innhenter domstolene ektepakt selv fra Ektepaktregisteret, eller skal Altinn dødsbo oversende tinglyste ektepakter til domstolen?
JÅB: Kan vi unngå å være relay-punkt for ektepakt hadde det forenklet løsning og sånn sett vært en fordel. På den annen side, dersom vi/OED trenger kontroll på om DA har fått ektepakt for logge-formål eller annet, bør vi formidle ektepakt videre til DA.

Frist:

**Comment by TageGitHub** [comment]
Videreført i #256
