### ISSUE TITLE
Hvordan skal Domstolene få beskjed om status?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#113]
Aktør involvert:
DA
Knyttet til brukerhistorie:
#62

beskrivelse:
Appen oppretter flere statuser gjennom prosessen. Hvordan skal domstolene få denne?
JÅB: Notifikasjon/API etableres som gir DA status fra OED. Må spekkes opp videre i samarbeid med DA

Frist:

**Comment by TageGitHub** [comment]
Videreført i #159 og andre bh der info utveksles med Domstolene
