### ISSUE TITLE
Arving velger å aktivt ikke signere for å påta seg ansvar for avdødes gjeld og andre forpliktelser

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#114]
#### Brukerhistorie:
Som en arving
ønsker jeg å la være og signere for gjeldsansvar
slik at jeg ikke påtar meg gjeldsansvar etter avdøde.

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:
JÅB: På en av dialogsidene/kortene må arving kunne huke av for å ønske å skifte privat og dermed påta seg gjeldsansvar. Dette er et aktivt valg som må gjøres av arving. Tar ikke arving stilling til dette så påtar ikke arving seg gjeldsansvar. 
Videre må det være en oppsummeringsside som tilsvarer skifteerklæring som vises for arvingene ved gjennomføring av prosess med å samtykke til/signere for oversendelse av skifteerklæring.
Denne må kunne tas ut på pdf/automatisk sendes på pdf til DPI. Arving må informeres om at denne pdf bare er for egen dokumentasjon. Dvs at prosess går videre uten å sende/bruke denne pdf til noe. 

**Godkjent Juridisk (OK // N/A // Ikke godkjent)**
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- bruker skal se....
- bruker skal bli tatt til...

#### Forbehold for å få realisere denne brukerhistorien:

**SCENARIO X:**

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by benedicteos** [comment]
Se brukerhistorie #28

**Comment by TageGitHub** [comment]
Videreført i #225 og #227
