### ISSUE TITLE
Avklare konsekvenser av arvingens valg vedrørende signering og ikke signering

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#115]
Aktør involvert:
DA

Knyttet til brukerhistorie:
#116 

beskrivelse:
Vi må definere roller og rettigheter ved signering, og hva som skjer dersom arving velger og ikke signere.
JÅB: Det må etableres detaljert hva man har rettigheter til i dag i manuell prosess dersom en ikke har signert kontra om en har signert i samarbeid med DA. Deretter hvilke konsekvenser dette har for hva du kan gjøre i OED og modellere opp dette sammen med Altinn autorisasjon. Når du påtar deg gjeldsansvar har du rett til å peke ut fullmektig og å forestå skiftet. 

Frist:

**Comment by TageGitHub** [comment]
Videreført av #228
