### ISSUE TITLE
Innsending av erklæring om privat skifte til DA

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#116]
#### Brukerhistorie:
Som et system
ønsker jeg å tilgjengeliggjøre informasjon om signering av privatskifte
slik at domstolene får informasjonen de trenger for å starte prosessen om privat skifte hos seg.

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:
Notifikasjon/API

**Godkjent Juridisk (OK // N/A // Ikke godkjent)**
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- Domstoler skal få tilgjengeliggjort signering
- Domstolene skal få tilgjengeliggjort personopplysninger

#### Forbehold for å få realisere denne brukerhistorien:
-Arvingen skal kreve privat skifte

**SCENARIO X:**

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by benedicteos** [comment]
dette er vel selve innsendingen av arvingenes erklæring om privat skifte til domstol?

**Comment by TageGitHub** [comment]
Videreført i #228
