### ISSUE TITLE
Utvidelse av roller og rettigheter ved utstedelse av skifteattest

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#117]
#### Brukerhistorie:
Som et system
ønsker jeg å få tilgjengeliggjort alle roller en arving kan ha
slik at jeg vet alle rettigheter arvingen kan gjøre i mitt system

(Handler også om å lage en digital representasjon av skifteattest)

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

**Godkjent Juridisk (OK // N/A // Ikke godkjent)**
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- NB! Kan også komme endringer for roller og rettigheter, der DA må oppdatere disse.

#### Forbehold for å få realisere denne brukerhistorien:
- Hele rolle og tjenestekartet være ferdig utviklet (Se #56  )

**SCENARIO X:**

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by TageGitHub** [comment]
Hensyntatt i #220
