### ISSUE TITLE
Skal DA gjøre spørring mot reservasjonsregisteret for å finne ut om arving er reservert mot digital kommunikasjon?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#119]
Aktør involvert:
DA

Knyttet til brukerhistorie:
#101 

beskrivelse:
Diskuterer hvorvidt DA skal gjøre denne spørringen, eller om vi skal gjøre det på vår side før vi oppretter en instans.
JÅB: Vi kan godt opprette instans uansett, men sørge for at ingen har tilgang i første omgang. Når vi vet at digital kommunikasjon kan brukes så åpner vi for tilgang til OED. Det kan uansett skje at brukere/arvinger "blir digitale" når det blir klart at dødsbo kan gjennomføres digitalt. Da bør instans være opprettet. 

Frist:

**Comment by TageGitHub** [comment]
Videreføres i #158
