### ISSUE TITLE
Hvilken avgivertype skal OED være knyttet til ? Trengs det ny avgivertype ? 

### ISSUE THREAD

**Issue by JanAage99** [Altinn/oed#120]
Aktør involvert:
Digdir

Knyttet til brukerhistorie:
Alle

Beskrivelse:
OED-app må knyttes til en juridisk/Altinn-enhet. Eksempler på enheter som finnes i Altinn i dag er personer, organisasjoner slik som AS'er, foreninger osv osv. OED er jo knyttet til en person, men spørsmålet er om det blir riktig å knytte OED-app til denne avdøde personen eller om det må lages en ny avgivertype for dødsbo ?
Dette må bl.a. være klart før vi kan jobbe med Altinn autorisasjon og det får konsekvenser for hvordan vi setter opp roller og rettigheter. 

Funnet ut JÅB 20200821:
Pratet med Benedikte og tungvekterne i 3.0 om dette. Konklusjon er at mer teknisk i Altinn vil OED app være en instans av en app knyttet til avgivertype person og mer spesifikt den avdøde. Deretter får arvinger, fullmektig osv tilgang til denne instansen via gjeldende roller.

Frist:
Raskt

**Comment by curlingnina** [comment]
Før jul gikk det en dialog mellom Siv, Morten og meg om hvem som skal eie en instans av Altinn Dødsbo. Jeg husker dessverre ikke deres detaljerte vurderinger, og dokumentasjonen ble lagt på Confluence - vi var jo da fortsatt i BR. @JanAage99  Anbefaler deg å ta kontakt med Siv og Morten.

**Comment by TageGitHub** [comment]
Videreført i #172
