### ISSUE TITLE
Bruker skal se en landingsside av Altinn Dødsbo Dashboard

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#121]
### Brukerhistorie:
**Intro**
Som en arving
ønsker jeg å se en landingsside
slik at jeg kan ser informasjon om skifteprosessen

**Krav/akseptansekriterier**  _(detaljering av BH med tilhørende akseptansekriterier)_
Gitt at.. jeg har fått informasjon om at et bo er tilgjengelig i OED appen 
når...jeg har logget meg på OED appen
så... kommer jeg til OED appen sin landingsside. (Avklaring: Når velger man blant flere bo? tage)
og ... jeg kan se en oversikt over informasjon og tilgjengelige valg (se GUI skisse)

**Utfyllende tekst**
 - Scenario 1.  Bare en arving der det ikke finnes registrert testament eller ektepakties
 - Trenger ikke å logge seg på i denne bh. Holder å mocke opp en bruker. Det etableres ny bh for å logge på.
 - informasjon som vises trenger ikke å være hentet fra reelle kilder/repository.

### Utfyllende informasjon
**Funksjonelt**

Status (ok, under avklaring, n/a): ok
Avklaringsområder: 
Dokumentasjon: 

**Trådskisse/GUI** 
Status: (ok, under avklaring, n/a): OK
Avklaringsområder: 
Dokumentasjon: 
lenke til skjermbilde https://eggedosis.github.io/oed/redirects/design/dashboard/concept-3.html
Lenke til trådskisser: https://eggedosis.github.io/oed/menu.html
Skal innehold ny banner i toppmeny: https://eggedosis.github.io/oed/designsystem/illustrations/dodsbo.svg

- [ ] Skal inneholde komponenter som tar bruker til ulike dummy-informasjonssider:  (geldende? tage)

- [ ] Skal inneholde en dummy-aktivitetskomponent m/ noe dummytekst (gjeldende? tage)

- [ ] Skal inneholde aksjonskomponenter som tar bruker til dummy-aksjonsider (gjeldende? tage)

**Teknisk** 
Status(ok, under avklaring, n/a):  under avklaring
Avklaringsområder: 
Dokumentasjon: 
[Lenke til overordnet arkitektur fra T3.0 ](https://teams.microsoft.com/l/file/e030e81b-c9a3-4fbb-bd76-1f22c05a2939?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=vsdx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%2520dokumenter%2FGeneral%2FRealiseringsfasen%2FTekniske%2520dokumenter%2FOed%2520i%2520T3.0%2520fra%2520Rune.vsdx&serviceName=recent)

**Juridisk**
Status(ok, under avklaring, n/a):  
Avklaringsområder:
Dokumentasjon: 

### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): må
Teknisk modenhet (høy, medium, lav): høy
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): na

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): 

---
### Forslag nye brukerhistorier:
 - Pålogging til OED appen (autentisering og autorisasjon)
 - Hente informasjon fra reelle kilder
---
### Åpne punkter - lukkes før sprint

---
### Annet

---
### Scenario X _Opprettes før lukking av denne BH_

**Forslag nye brukerhistorier Scenario X (MVP)**  
 

**Avklaringer scenario X**

---
---

**Comment by kajabystol** [comment]
@eggedosis @lillelars link til dashboard Figma over.

**Comment by eggedosis** [comment]
@kajabystol Gull! Men jeg får dessverre ikke åpnet den. Tror du må endre innstilling sånn at alle med lenke kan se, ikke bare de som er innlogget 😊

**Comment by kajabystol** [comment]
Uproft av meg. I`m on it! 😊

**Comment by lillelars** [comment]
@benedicteos Hvis vi scoper ned denne brukerhistorien til at vi mocker opp bruker for autorisering, og vi ser bare på scenariene som beskrevet over - er dette da godkjent for utvikling?

**Comment by TageGitHub** [comment]
utgår Erstattes av 124, 143...
