### ISSUE TITLE
Arving skal ha mulighet til å se informasjon om boet

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#123]
### Brukerhistorie
**Intro**
Som en .... arving 
ønsker jeg å .... se informasjon om dødsboet
slik at jeg ... få bedre oversikt over avdødes bo.

**Krav/akseptansekriterier**  _(detaljering av BH med tilhørende akseptansekriterier)_
(Tage: **Avklaring** skal faktisk informasjon vises eller kun tilrettelegging av skjermbilder?)

Gitt at.. jeg har logget meg på OED løsningen
når...jeg er på side for informasjon om boet
så...skal navnet mitt vises på siden sammen med de andre som er blitt gitt rettigheter til boet. (Tage **Avklaring**: Hva er kriteriet for å ha blitt gitt rettigheter til boet. At man er arving?)

Gitt at.. jeg har logget meg på OED løsningen
når...jeg er på side for informasjon om boet
så...skal det vises om det er ikke er funnet et testament (Tage: **Avklaring :** Hva er bakgrunnen for dette kravet? Ikke funnet betyr at senere funn ikke har betydning?)

Gitt at.. jeg har logget meg på OED løsningen
når...jeg er på side for informasjon om boet
så...skal det vises om det ikke finnes ektepakt (se brukerhistorie #74 for faktisk visning av ektepakt.) (Tage: **Avklaring :** Ikke funnet betyr at senere funn ikke har betydning?)

**Prosa**
Arving skal få vite at det _ikke_ finnes et testamentet (Her holder det altså med oppslag og vise informasjonen at det 
ikke_ finnes testamentet. Dersom det finnes testamentet håndterer vi det i scenario X)

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): under avklaring
Avklaringsområder: se over, samt avklaringspunkter under.
Dokumentasjon: 

**Trådskisser**
Status (ok, under avklaring, n/a): n/a
Avklaringsområder:
Dokumentasjon: 

**GUI** 
Status: (ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon: https://www.figma.com/proto/yO6LtMoTol4UCNneZcAtbu/Designskisser?node-id=1%3A2&viewport=17%2C-44%2C0.8152644038200378&scaling=scale-down

**Teknisk** 
Status(ok, under avklaring, n/a):  
Avklaringsområder:
Dokumentasjon: 

**Juridisk**
Status(ok, under avklaring, n/a):  
Avklaringsområder:
Dokumentasjon: 

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): bør
Teknisk modenhet (høy, medium, lav): høy
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): n/a

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier Scenario 1:
 
 -  Faktisk uthenting og visning av informasjon på skjermbilder.
 -  Opprette nytt behov (brukerhistorie)  der arving skal se relasjon til avdøde + relasjon for andre arvinger. 
 -  Opprette nytt behov for å håndtere at det finnes testament.

---
### Åpne punkter - lukkes før sprint
 - renskrive tekst på brukerhistorie slik at den reflekterer korrekt informasjon som skal vises. (Tage: gjort?)
 - Bør informasjon om roller og rettigheter ligge på samme sted som dette? @kajabystol 
 - Arving skal se navn til avdøde? UX må avklare @kajabystol 
 - Får vi lov til å hente ut informasjon om relasjoner til avdøde - se nytt behov angående relasjon mot arving?
---
### Annet

---
### Forslag nye brukerhistorier **Scenario X** (MVP) _Opprettes  før lukking av denne BH_
 - arving skal se navn og fødselsnummer på alle arvinger
 - arving skal se relasjon andre arvinger har til avdøde
 - arving skal se egen relasjon til avdøde
 - arving skal få vite dersom det finnes ektepakt (se brukerhistorie #74 for mer informasjon og visning av ektepakt)
 - arving skal se kontaktinformasjon som er lagt inn om "kontaktperson". Dette er informasjon hentet inn fra DA og bør inneholde fødselsnr, navn og kontaktinfo. Dette bør ikke være editerbart før i Scenario X dersom bruker ser behovet for å endre på det i løsningen vår.

**Avklaringer scenario X**
 - Vi må følge opp hvorvidt vi kan innhente og vise kontaktinformasjon til en person som _ikke_ har en rolle i boet. @benedicteos

**Comment by TageGitHub** [comment]
Utgår erstattes av EPOS #144
