### ISSUE TITLE
Landingsside 'dine rettigheter' 

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#125]
#### Brukerhistorie
Som arving
ønsker jeg å se landingssiden i Altinn dødsbo
slik at jeg får tilgang til løsningens funksjonaliteter.

**Krav/akseptansekriterier** 
Gitt at jeg har logget meg på Altinn dødsbo.
Når jeg kommer til landingssiden 
skal jeg se informasjon og menyvalg som gir tilgang til mer beskrivelse relevant for mine rettigheter (ihht GUI under)
og
jeg får tilgang til menyvalg knyttet til Arvinger, Testament og Skifteform.

---

### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: Gjeldende design:  https://eggedosis.github.io/oed/redirects/design/dashboard/concept-3.html

**Teknisk** 
Status(ok, under avklaring, n/a):  
Avklaringsområder: 
Dokumentasjon: 

**Juridisk**
Status(ok, under avklaring, n/a):  
Avklaringsområder: Offentlig informasjon om arvinger.  Kan disse deles vedrørende arvinger ( j/n)?, Hva må eventuelt avklares?
Dokumentasjon: 

**Akseptansetest**
**Godkjent**. Enkelte forhold tas videre ref. log

### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): må
Teknisk modenhet (høy, medium, lav): medium
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): under avklaring
Forretningsbehov (høy, medium lav): høy

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier dette scenariet:
 
 
---
### Åpne punkter - lukkes før sprint

---
### Annet
tidligere bh 12/4

Brukerhistorie:
Som en  arving
ønsker jeg å se data knyttet til arvinger på landingssiden
slik at jeg raskt får oversikt over dette 

Krav/akseptansekriterier
Gitt at informasjon om arvinger er hentet fra Domstolene
når jeg ser på landingssiden 
så ser jeg  informasjon knyttet til disse
og denne informasjonen er: navn til arving og  relasjon til avdøde.

**Utfyllende tekst**
---
### Scenario X _Opprettes før lukking av denne BH_

**Forslag nye brukerhistorier Scenario X (MVP)**  

**Avklaringer scenario X**

**Comment by lillelars** [comment]
@benedicteos hvis vi ser på denne brukerhistorien i et vakum, så stemmer det vel at alle arvinger skal få se denne inngangen/komponenten. Det betyr at vi kan utvikle den. Har du innvendinger mot dette?

**Comment by lillelars** [comment]
@TageGitHub Lar denne stå, så kan vi skrive om ift ny komponentinngang

**Comment by lillelars** [comment]
@TageGitHub klar for akseptanse

**Comment by OlgaKoz** [comment]
Godkjent med oppfølgingspunkter som følges opp i #305 
 1.) Bør “Bli kjent med dine rettigheter” hete “Informasjon til arvinger”? Rasjonale – lede inn til informasjonsside. 
2.) Introteksten må oppdateres

**Comment by lillelars** [comment]
Foreldet. Lukker saken,.
