### ISSUE TITLE
Informasjon om Fellesgjeld og/eller fellesformue fra ulike boliger - hvor får vi denne informasjonen fra?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#126]
Aktør involvert:
Kartverket?
Skattetaten? 

Knyttet til brukerhistorie:
#39 
beskrivelse:
Mesteparten av informasjonen vi trenger angående bolig får vi fra kartverket. Men hva med informasjon om fellesgjeld/formue for hver enkelt bolig? Må dette hentes fra Skattetaten og skal det eventuelt vises samme sted?
Frist:

**Comment by TageGitHub** [comment]
Overført til #187
