### ISSUE TITLE
Hente data om avdødes konto

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#127]
#### Brukerhistorie
Som en arving
ønsker jeg å få oversikt over innholdet i avdødes kontoer
slik at jeg er informert om dette under det videre arbeidet med boet

**Krav/akseptansekriterier** 
Gitt at formuesfullmakt eksisterer 
når jeg logger meg på OED
så blir informasjon fra avdødes banker hentet

**Utfyllende tekst**

### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon:

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 
Trådskisse: 
skjermbilde: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder: 
- [ ] Tilgang til test-API kontrollinformasjon. De skal undersøke innhold i test-API, om dette faktisk er anonymisert informasjon og hva kravene er for få tilgang. Underliggende banker hadde ytret bekymring mtp AI, slik at selv om de var anonymisert kunne de av-anonymiseres. Dette kan nok vær en risiko, men om avtale fins bør dette reguleres der, med ansvar, sikkerhet og konsekvenser. De kjente ikke til slik avtale i Bits, men skulle undersøke det og. Det samlede svar angående tilgang hit kommer tirsdag 6. oktober.

Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder: 
- [ ] For at KAR skal kunne benyttes av Altinn dødsbo for uthenting av informasjon må regelverket som ligger til grunn for KAR (internbankreglene/KAR-regelverket) endres. 
- [ ] - avklaring #80 må på plass før denne kan utvikles
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): må
Teknisk modenhet (høy, medium, lav): høy
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier:

---
### Åpne punkter - lukkes før sprint

---
### Annet
Innledende juridisk vurdering av APIer fra bank og forsikring. Innen 21. oktober leverer de en GAP-analyse mtp de 7 ulike APIene. De vurderer bl.a.  innhold i APIene, hvilken informasjon arving har rett på, hva har de rett på når, videreformidlerrollen til digitalt dødsbo, taushetsplikt m.v.

---
### Scenario X _Opprettes før lukking av denne BH_

**Forslag nye brukerhistorier Scenario X (MVP)**  

**Avklaringer scenario X**

**Comment by benedicteos** [comment]
For bruk i DSOP-sammenheng kan KAR benyttes til å avdekke i hvilken bank en gitt person har (eller har hatt) et konto- eller disposisjonsforhold slik at Altinn dødsbo kun behøver å rette henvendelse om detaljert informasjon til de aktuelle bank(er).

**Comment by lillelars** [comment]
Avklaringer mot Bankene:
Bankene trenger å vurdere om vi får tilgang på API'er deres ettersom noen av API'ene kan inneholde sensitiv informasjon vi ikke får tilgang på.
De skal også vurdere hvorvidt de da kan skrelle ned på API'ene og gi oss bare det vi har behov for.
Vurderingen skal være klar til 21. Okt
@JanAage99 @TageGitHub 

I tillegg skal BITS komme tilbake til oss på førstkomennde tirsdag hvorvidt vi får tilgang på deres test-anonymiserte data.

**Comment by TageGitHub** [comment]
Ikke nødvendig at avdøde ber om bankinformasjon når henting av dette skjer automatisk
