### ISSUE TITLE
Hvordan skal vi få informasjon at fullmektig har godtatt å være fullmektig? og trenger vi det?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#129]
Aktør involvert:
FUFINN?
https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/digitaliseringsradet/laer-av-andre/statens-sivilrettsforvaltning-fufinn-vergemal

Knyttet til brukerhistorie:
#122 
beskrivelse:
Når fullmektig har godtatt å være fullmektig for en arving, bør dette vises i Digitalt dødsbo?

Frist:

**Comment by TageGitHub** [comment]
Videreført i #178
