### ISSUE TITLE
Preutfylling av erklæring om privat skifte

### ISSUE THREAD

**Issue by benedicteos** [Altinn/oed#130]
#### Brukerhistorie:
Som et .... system
ønsker jeg å ....preutfylle erklæring om privat skifte 
slik at jeg ... fyller ut erklæringen med allerede innhentet informasjon.. 

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- bruker skal se....
- bruker skal bli tatt til...

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by TageGitHub** [comment]
Ivaretatt av #227
