### ISSUE TITLE
Informasjon om ikke tinglyst ektepakt

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#131]
#### Brukerhistorie:
Som en .... arving 
ønsker jeg å .... få vite hvordan jeg skal forholde meg til ikke tinglyst ektepakt
slik at jeg .... tar hensyn til dette i skifteoppgjøret

#### Forretningsverdi 3(1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- bruker skal se.... informasjon om at ektepakt nødvendigvis ikke trenger å være tinglyst
- bruker skal bli tatt til.. link til veiledning hos Brreg (?)

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by TageGitHub** [comment]
videreført i #257
