### ISSUE TITLE
Arving bekrefter eller avkrefter kjennskap til nattbordstestamente

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#133]
#### Brukerhistorie:
Som en .... arving
ønsker jeg å .... gjennomgående i prosessen bekrefte eller avkrefte kjennskap til testamente som ikke er registrert hos tingretten
slik at jeg ... tar hensyn til dette i skifteoppgjøret

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

**Godkjent Juridisk (OK // N/A // Ikke godkjent)**
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- bruker skal se.... informasjon om at testamente kan oppbevares andre steder enn hos tingretten
(KBJ spm: hvordan er dette hvis testamente ligger hos en advokat? Har de kommunikasjon med tingretten etter et dødsfall?)
- bruker skal bli tatt til... avhuke for JA/NEI/VET IKKE at det foreligger et originalt testamente
- bruker skal se... informasjon om innsendelse av dokumenter med kontaktinformasjon til riktig tingrett

#### Forbehold/avklaringr for å få realisere denne brukerhistorien:
- Arving skal avhuke for NEI/VET IKKE det finnes ikke et nattbordstestamente
- Angående oppbevaring av "nattbordstestamente". Dette er hentet ut fra domstolenes sider: "Et testament kan ha bestemmelser om gjennomføring av gravferd i tillegg til fordeling av arv. Det er derfor viktig at det så tidlig som mulig avklares om avdøde hadde opprettet et testament. Som hovedregel må testamentet være i original". Vi har skissert at arving må ha mulighet til å krysse av for JA/NEI/VET IKKE nattbordstestamente tidlig i prosessen. Hva jeg leser her, vil jo egentlig dette komme for sent HVIS det i tillegg handler om gjennomføring av gravferd? (SIden vi ikke skal være de første som opplyser om dødsfall, og har sagt tjenesten opprettes etter 5-7 dager. Da vil jo et begravelse allerede, eller stort sett blitt gjennomført. 
Har vi dabehov for denne avhukingen for arving tidlig, og om det holder med når de skal sende inn erklæring? Er det arvingenes ansvar å sørge for å oppfylle testamentets bestemmelser om feks gravferd, slik at domstol ikke har en rolle her, og det er tilstrekkelig med informasjon om nattbordstestamentet i erklæring om skifte?
Hvordan håndterer domstolen bestemmelser om gravferd i testament registrert i testamentregisteret?

**SCENARIO X**

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by TageGitHub** [comment]
Slått sammen med #198
