### ISSUE TITLE
Tilgang til gruppelivsdekninger

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#135]
I april-19, juni-20 og august-20 tok KLP kontakt med DSOP v/Nils Inge. Sak: i dag er det slik at ca 30 % av etterlatte hvor den avdøde var ufør ikke får utbetalt uføreforsikring. 

Gruppelivforsikring fungerer som en såkalt selvadministrert ordning.  Dette betyr at forsikringsselskapene ikke har registrert hvem som er omfattet av forsikringen.  Arbeidsgiver tegner forsikring for alle sine ansatte og uførepensjonister uten at personopplysninger blir registrert hos forsikringsselskapet. Det er derfor ikke mulig å løse dette pt i OED, siden vår søkestreng er den avdødes fødselsnummer.

I april-19 sendte prosjektets forsikringsaktører en utfyllende begrunnelse til KLP. Pr aug-20 har ikke situasjonen endret seg.

**Comment by TageGitHub** [comment]
Videreføres i #243  der det pr nå er et åpent punkt knyttet til hvilke forsikringsinstrument som skal med i MVP
