### ISSUE TITLE
Kvittering for innsendt erklæring om privat skifte

### ISSUE THREAD

**Issue by benedicteos** [Altinn/oed#137]
#### Brukerhistorie:
Som en ....
ønsker jeg å ....
slik at jeg ...

Kvittering er inkludert en oversikt over hvordan erklæringen som er sendt ut ser ut, komplett, inkl. behandlingstid.

Se #33 - den skal inkluderes i denne brukerhistorien.

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

#### Akseptansekriterier (minimum happy-case):
-[ ] bruker skal se....
-[ ] bruker skal bli tatt til...

#### Avklaring for å få realisere denne brukerhistorien:
-[ ] ...
-[ ] ...

#### Testscenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by TageGitHub** [comment]
Ivaretatt i #227, #228
