### ISSUE TITLE
Domstolens behov for informasjon om utpekt fullmektig

### ISSUE THREAD

**Issue by benedicteos** [Altinn/oed#138]
Har domstolen behov for informajson om at arvingene har utpekt en fullmektig?
Når har de behov for denne informajsonen?
hvordan håndtere at arvingene ønsker at skifteattest utstedes til fullmektig..?

#### Brukerhistorie:
Som en ....
ønsker jeg å ....
slik at jeg ...

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

#### Akseptansekriterier (minimum happy-case):
-[ ] bruker skal se....
-[ ] bruker skal bli tatt til...

#### Avklaring for å få realisere denne brukerhistorien:
-[ ] ...
-[ ] ...

#### Testscenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by TageGitHub** [comment]
Videreføres i #180
