### ISSUE TITLE
Autentisering mot eksterne API

### ISSUE THREAD

**Issue by JanAage99** [Altinn/oed#139]
#### Brukerhistorie:
Som en app 
ønsker jeg å kunne autentisere meg mot eksterne API på forskjellige måter
slik at jeg kan få tilgang til ressursene som API eksponerer

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:
OED skal kunne autentisere seg mot:
SVV
Matrikkelen
Norsk pensjon
KAR
Banker
Skatt
DA

Autentiseringsmekanismer som brukes etableres iterativt

#### Akseptansekriterier (minimum happy-case):
-[ ] bruker skal se....
-[ ] bruker skal bli tatt til...

#### Avklaring for å få realisere denne brukerhistorien:
-[ ] ...
-[ ] ...

#### Testscenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by JanAage99** [comment]
Link til 3.0 sin brukerhistorie om dette:
https://github.com/Altinn/altinn-studio/issues/1127

**Comment by JanAage99** [comment]
OED skal integrere seg mot Norsk pensjon. De vil lage rest-api spesielt for OED. De har som krav ifht sikkerhet/autentisering/autorisering at følgende støttes: 
Https,
2 veis SSL med sertifikater,
IP-whitelisting

**Comment by lillelars** [comment]
Dette er håndtert per API
