### ISSUE TITLE
Custom ekstern GUI

### ISSUE THREAD

**Issue by JanAage99** [Altinn/oed#140]
#### Brukerhistorie:
Som en app
ønsker jeg at GUI lages utenfor Altinn studio 
slik at GUI kan lages fritt tilpasset uten begrensninger som ligger i Altinn studio

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

#### Akseptansekriterier (minimum happy-case):
-[ ] bruker skal se....
-[ ] bruker skal bli tatt til...

#### Avklaring for å få realisere denne brukerhistorien:
-[ ] ...
-[ ] ...

#### Testscenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by JanAage99** [comment]
3.0 sin brukerhistorie:
https://github.com/Altinn/altinn-studio/issues/4629

**Comment by lillelars** [comment]
Utgått/ugyldig
