### ISSUE TITLE
Event rammeverk for å la aktører holde seg oppdatert på OED

### ISSUE THREAD

**Issue by JanAage99** [Altinn/oed#141]
#### Brukerhistorie:
Som en app
ønsker jeg å eksponere events
slik at aktører og interessenter kan holde seg oppdatert på viktige hendelser i OED

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:
Kandidater for events:
Kontaktinformasjon, Status, Skifteattest, Fullmektig mfl.

#### Akseptansekriterier (minimum happy-case):
-[ ] bruker skal se....
-[ ] bruker skal bli tatt til...

#### Avklaring for å få realisere denne brukerhistorien:
-[ ] ...
-[ ] ...

#### Testscenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by JanAage99** [comment]
3.0 sin brukerhistorie for event-rammeverk:
https://github.com/Altinn/altinn-studio/issues/1783

**Comment by lillelars** [comment]
Løses først for DA i #383, så får andre aktører henge seg på på sikt.
