### ISSUE TITLE
Varsel til arving

### ISSUE THREAD

**Issue by JanAage99** [Altinn/oed#142]
#### Brukerhistorie:
Som en app
ønsker jeg å kunne sende varsel til en arving
slik at arving blir klar over at digitalt dødsbo er blitt opprettet og informasjon rundt dette

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

#### Akseptansekriterier (minimum happy-case):
-[ ] arving skal motta lenke til OED-app som gjør arving i stand til å åpne app på smidig måte
-[ ] bruker skal bli tatt til...

#### Avklaring for å få realisere denne brukerhistorien:
-[ ] ...
-[ ] ...

#### Testscenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by JanAage99** [comment]
3.0 sin historie:
https://github.com/Altinn/altinn-studio/issues/4275

**Comment by lillelars** [comment]
Arving får varsler nå. Lukker saken.
