### ISSUE TITLE
Landingsside 'dine oppgaver i boet'

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#143]
#### Brukerhistorie

Som arving
ønsker jeg å se landingssiden i Altinn dødsbo
slik at jeg får tilgang til løsningens funksjonaliteter og kan se noe kjerneinformasjon fra aktører

**Krav/akseptansekriterier** 
Gitt at jeg har logget meg på Altinn dødsbo.
Når jeg kommer til landingssiden 
ønsker jeg å se informasjon  knyttet til ' dine oppgaver i boet'' ihht design under

Gitt at jeg har logget inn i Altinn Dødsbo
når jeg klikker på lenken "arvinger" 
så  skal jeg bli tatt til en side som gir mer informasjon om arvingene

Gitt at jeg har logget inn i Altinn Dødsbo
når jeg klikker på lenken "testamente" 
så  skal jeg bli tatt til en side som gir mer informasjon om testamente

Gitt at jeg har logget inn i Altinn Dødsbo
når jeg klikker på lenken "Skifteform" 
så skal jeg bli tatt til en side som gir mer informasjon om mine rettigheter

**Utfyllende tekst**
Innhenting av data fra aktør skjer i annen bh

**Utfyllende tekst**
  - Alle lenkene skal være selvforklarende slik at bruker forstår hva den gjør (en tekst som forteller bruker hva inngangen gjør)
  - Skjermbilde utformes  iht. vedlagt design

### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): ok
Avklaringsområder: 
 - (aktiva/passiva = formue/gjeld? i tilfelle beslutt begrep) - Besluttet bruk av Formue/gjeld i skjermbilde ettersom dette er mer brukernært begrep.
 - kun skjermbilde, bruk av datakilder i senere BH?) - Ja vi viser bare inngangen til skjermbilde 
- Når får navn på arving og relasjon til avdøde fra API'et?
 - (Til avklaring: 'andre arvinger'. Bør vi endre til 'arvinger' og ta med 'jeg' i listen? Svar Ja Kaja)

**Dokumentasjon**

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:

- [ ] Endre fra 'Rett til arv i boet' til 'Informasjon om arvinger og deres rettigheter.

Dokumentasjon: https://eggedosis.github.io/oed/redirects/design/dashboard/concept-3.html

**Teknisk**
Status(ok, under avklaring, n/a): ?
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): ?
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): må
Teknisk modenhet (høy, medium, lav): høy
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): n/a

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier:
 - vurder og skisser om bruker skal kunne se en indikasjon på fremgang i prosess (f.eks en progresjonsbar) => Vurderes ikke som kritisk for løsningen. tas ev. opp på nytt dersom brukerbehovet blir tydeligere (tage).
 - Populering av skjermbilder med reelle data.

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

### Scenario X _Opprettes før lukking av denne BH_

**Forslag nye brukerhistorier Scenario X (MVP)**  
 - pålogging av bruker mot Altinn Autorisasjon 

**Avklaringer scenario X**

**Comment by lillelars** [comment]
@TageGitHub endret forøvrig tekst og akseptansekriterier på denne.

**Comment by lillelars** [comment]
@TageGitHub Denne er klar for å tas videre i prosessen.

**Comment by TageGitHub** [comment]
Ser på det straks..

________________________________
Fra: Lars M Riiser Haraldsen <notifications@github.com>
Sendt: Sunday, October 4, 2020 11:18:15 AM
Til: Altinn/oed <oed@noreply.github.com>
Kopi: Bryn, Tage <tage.bryn@digdir.no>; Mention <mention@noreply.github.com>
Emne: Re: [Altinn/oed] Komponent for 'rett til arv i boet' (#143)


@TageGitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTageGitHub&data=02%7C01%7C%7Cdc69d7bbd2d548f9f8f308d868466d47%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637373999540450702&sdata=AZS01pEHLtbIar%2FRvGhu%2B97MHevDDvR164R3cNK2YlY%3D&reserved=0> Denne er klar for å tas videre i prosessen.

**Comment by lillelars** [comment]
Håndteres av #147
