### ISSUE TITLE
Se landingsside

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#144]
#### Epos:
Som en arving 
ønsker jeg å en landingssiden i altinn dødsbo
slik at jeg får en oversikt over boet når jeg har startet applikasjonen

Se design: https://eggedosis.github.io/oed/redirects/design/dashboard/concept-3.html

- arving skal se en landingsside....
- arving skal se siste aktivitet på boet
- arving skal se enkel informasjon om 'formue og gjeld' og kunne ta seg videre til sider om dette
- arving skal se enkel informasjon om 'rett til arv i boet' og kunne ta seg videre til sider med mer informasjon om dette
- arving skal se sine oppgaver i boet, hva som er utført og hva neste oppgave bør være
- arving skal se lenker som gir mer nyttig informasjon 

### Avgrensninger
 - Populering med reelle data skjer i eget epos.

### Avklaringer:
- [x] Skal Sakside vises i Altinn dødsbo. Ja, Dette er koblingen mellom Altinn dødsbo og Domstolenes behandling.
- [x] Skal vi vise når var siste endringer er blitt gjort i bo-instansen. JA (kaja)

Generelle avklaringspunkter:
Forbehold for å få realisere denne brukerhistorien:
 - Et rettslige grunnlag for at bruker skal få logge inn på landingssiden og se personopplysninger om arvingen.

**Comment by lillelars** [comment]
Foreldet. Lukker saken
