### ISSUE TITLE
Se landingsside (med reelle data)

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#148]
#### Epos:
Som en ....arving 
ønsker jeg å en landingssiden i eOED med reelle data
slik at jeg ...umiddelbart får en oversikt over boet

Se design: https://eggedosis.github.io/oed/redirects/design/dashboard/concept-3.html

- arving skal se en landingsside med reelle data
- arving skal se siste aktivitet på boet med reelle data
- arving skal se enkel informasjon om 'formue og gjeld' med reelle data og kunne ta seg videre til sider om dette
- arving skal se enkel informasjon om 'rett til arv i boet' med reelle data og kunne ta seg videre til sider med mer informasjon om dette
- arving skal se menyvalg om sine oppgaver i boet (med reelle data), hva som er utført og hva neste oppgave bør være
- arving skal se lenker som gir mer nyttig informasjon 

### Avgrensninger

Generelle avklaringspunkter:
Forbehold for å få realisere denne brukerhistorien:
 - Et rettslige grunnlag for at bruker skal få logge inn på landingssiden og se personopplysninger om arvingen.

**Comment by lillelars** [comment]
@TageGitHub Ser du denne

**Comment by TageGitHub** [comment]
Jopp

________________________________
Fra: Lars M Riiser Haraldsen <notifications@github.com>
Sendt: Friday, October 9, 2020 1:29:11 PM
Til: Altinn/oed <oed@noreply.github.com>
Kopi: Bryn, Tage <tage.bryn@digdir.no>; Mention <mention@noreply.github.com>
Emne: Re: [Altinn/oed] Se landingsside (med reelle data) (#148)


@TageGitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTageGitHub&data=02%7C01%7C%7C3221c2d25f874bb8abe908d86c468beb%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637378397534369758&sdata=jZMixgu98oteLBw4j1QmzA40L%2Bxz0a1F0KsmEA7sYUk%3D&reserved=0> Ser du denne

**Comment by TageGitHub** [comment]
Erstattes av #144
