### ISSUE TITLE
Landingsside Testament - reelle data

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#150]
#### Brukerhistorie
**Intro**
Som en .... arving
ønsker jeg å ....se informasjon om testament med reelle data 
slik at jeg ... får en oversikt over om det eksisterer slike

**Krav/akseptansekriterier**  _(detaljering av BH med tilhørende akseptansekriterier)_
Gitt at.. jeg har logget inn på eOED landingsside
når.. jeg ønsker å se informasjon om testament
så... skal jeg se et menyvalg som heter "testament"
og... i tilknytning til denne ser jeg reell informasjon om det er registret et testamentet eller ikke

Gitt at.. jeg ser et menyvalg 'testament'
når...jeg klikker på menyen "testament" 
så... skal jeg bli tatt til en side som gir mer informasjon om testament

**Utfyllende tekst**
 - Skjermbilde utformes  iht. vedlagt design

### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
**Dokumentasjon**

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: https://eggedosis.github.io/oed/redirects/design/dashboard/concept-3.html

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): må
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): n/a

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier:

---
### Åpne punkter - lukkes før sprint

---
### Annet

---
### Scenario X _Opprettes før lukking av denne BH_

**Forslag nye brukerhistorier Scenario X (MVP)**  
 - pålogging av bruker mot Altinn Autorisasjon 

**Avklaringer scenario X**

**Comment by lillelars** [comment]
Lukkes. Når vi nærmer oss pilot/produksjon opprettes egne issues mot produksjonsmiljøet.
