### ISSUE TITLE
Visningsside informasjon om arv, arveoppgjør og veiledning

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#152]
#### Brukerhistorie
Som en arving
ønsker jeg å se informasjon knyttet til mine rettigheter i boet
slik at jeg blir bedre i stand til å gjøre riktige valg ifm bo-oppgjøret

**Krav/akseptansekriterier** 
Gitt at jeg har logget inn i Altinn Dødsbo landingsside.
Når jeg ser 'dine rettigheter' 
så ser jeg en kort introtekst til hva dette innebærer

Gitt at jeg har klikket på 'dine rettigheter'
Når  utfyllende informasjon vises 
så ser jeg  mer informasjon om mine rettigheter som arving

- Denne tar for seg GENERELL informasjon om:
- skifteform
- 60 dagers fristen
- privat skifte i Altinn dødsb
- Andre måter å utføre skifteform på

**Utfyllende tekst**
Innhold i tekst:

Bakgrunnsinformasjon for tekstene som er skrevet:
- Noe informasjon om arveloven? Introduksjon til? vise til lovdata.no og domstol.no
- Hvem er arvinger? (kilde DA: https://www.domstol.no/Enkelt-domstol/oslo-byfogdembete/arv-og-skifte/om-arv-og-skifte/hvem-er-arvinger/ )
- Sitte i uskiftet bo (kilde: DA: https://www.domstol.no/Enkelt-domstol/oslo-byfogdembete/arv-og-skifte/om-arv-og-skifte/orientering-til-gjenlevende-ektefelle/ )
- Hva er din arverett? 
Når du er barn? Når du er ektefelle? Når du er særskiltsbarn?

- Hvordan skal arven fordeles
- ulike skiftemåter? Privat / offentlig (kilde DA: https://www.domstol.no/arv-og-skifte/dodsfall-og-arv/forskjellige-former-for-skifte/)
- 60-dagers fristen
- digitale representasjoner, begrensninger her,
- konkrete rettigheter i boet ved henvisning til arvelov, formuesfullmakt utover tjenesten
- plikter arving har i et dødsbo ved å henvise til arvelov
- kontakte tingretten hvis det og det

informasjon angående boinstansen (Håndteres i egne issues):
- relasjoner https://github.com/altinn/oed/issues/264
- testament https://github.com/altinn/oed/issues/181
- ektepakt https://github.com/altinn/oed/issues/250

##### Oppgaver:

- [x] Utarbeide forslag til tekst (timbokset) @kajabystol @lillelars - Kaja kaller inn til arbeidsmøte -> Lenket under "Dokumentasjon" lenger ned her. 
- [x] Følger opp gjenstående oppgaver her #305 

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
- [x] Skal informasjonstekst komme fra DA? 
 SVAR Tverrfaglig team: OED står for teksten. DA skal være med å kvalitetssikre.
- [x] Hvilken info skal med, hvilke kilder skal brukes. Foreslå og avstemmes med DA.
SVAR Tverrfaglig team: Lovdata.no og DA sines sider skal brukes. Kvalitetsikres med DA
- [X ] Hvordan skal koblingen mellom landingssiden og underliggende side om rettigheter være (trådskisse).
SVAR Tverrfaglig team: Se designskisser
- [x] Bør vi skille på hvilken informasjon vi presenterer til ulike brukere av løsningen?
SVAR Tverrfaglig team: Dette gjør vi ikke på dette tidspunktet, men ønsker å se på muligheten for dette senere.
**Dokumentasjon**

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Trådskisser: https://www.figma.com/file/2IBVCgEbXzz4yGkj1ShyNR/Brukerflyt?node-id=1526%3A2

- [x] (DA) skal tekst hentes fra DA, eller egenkomponert? Fra ressursfiler
Lenke til design: https://eggedosis.github.io/oed/redirects/design/rights/default-one-d.html
Dokumentasjon: https://eggedosis.github.io/oed/redirects/design/dashboard/concept-3.html

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:

- [x] Hvordan skal informasjon som brukes på tvers av bo-instanser oppbevares og gjøres tilgjengelig.-> Ressursfiler i Altinn studie. Ønskelig med et overbygg for å håndtere dette på sikt. Vil måtte deplyes dersom tekst endres.

Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 

Dokumentasjon:
Dokumentasjon til tekst som skal vises på disse sidene:
https://teams.microsoft.com/l/file/654E1B14-A148-4B3F-AED3-71F0832C9648?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FFunksjonelt%2FTekster%20i%20Oppgj%C3%B8r%20etter%20d%C3%B8dsfall%2Finformasjon%20om%20arv%20og%20retten%20til%20arv.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

**Test**
Systemtest i sprint: 
Akseptanse sprint: godkjenn . Enkelte forhold ivaretas i ny brukerhistorier. Se logg
Integrasjonstest (sprint):

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): må
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): n/a

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier:

---
### Åpne punkter - lukkes før sprint

---
### Annet

---
### Scenario X _Opprettes før lukking av denne BH_

**Forslag nye brukerhistorier Scenario X (MVP)**  

**Avklaringer scenario X**

**Comment by TageGitHub** [comment]
@benedicteos @tblix @kajabystol @LeneSundsbo Ref nyeste design på Landingssiden. Skal det være en separat underside for hvert av temaene Testament, Arvinger, Skifteform? Da må vel GUI skissen justeres?

**Comment by lillelars** [comment]
@TageGitHub klar for akseptanse

**Comment by OlgaKoz** [comment]
Brukerhistorie 152 - godkjent med følgende avklaringspunkter: 

Bør “Bli kjent med dine rettigheter” hete “Informasjon til arvinger”? Rasjonale – lede inn til informasjonsside. 

Introteksten må oppdateres 

Endelig tekst på undersider Arvinger, Testamente, Skifteform må utarbeides og kvalitetssikers av ansvarlige parter.

**Comment by TageGitHub** [comment]
overtas av annen bh
