### ISSUE TITLE
Se bankinfo (uten reelle data)

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#153]
Som en arving
ønsker jeg å se oversikt over bankinfo til avdøde (uten reelle data)
slik at  jeg får en oversikt over avdødes finansielle status

**Krav/akseptansekriterier** 
Gitt at  jeg har logget meg på Altinn dødsbo.
Når jeg ønsker å se bankinfo knyttet til avdøde
så ser jeg oversiktsinformasjon  landingssiden 
og 
detaljert informasjon på 'bank siden'
og 
dette  sees av arvinger som har 'fulle rettigheter' i boet

**Utfyllende tekst**

### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 

- [ ]  Hvilken bankinformasjon skal vises (underlag for første implementering)/søkeinformasjon? (Jan Å)
https://teams.microsoft.com/l/file/44D1B18E-035D-4852-97E2-C55F921ABD1A?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FTeknisk%2FReferater%20og%20teknisk%20dokumentasjon%2FBits%2FAPI%20-%20Bank.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515
- [x] vi skal støtte SBanken og Sparebank1, DNB

Dokumentasjon:
 - Dokumentasjon på kontroll API'etkontrollinformasjon 
https://www.bits.no/project/kontrollinformasjon/

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 
Trådskisse: 
skjermbilde: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder: 
- [x] Arbeidshypotese: Henter og lagrer info i Altinn dødsbo hver gang arvinger logger seg på. Dersom ekstern link er nede brukes info fra forrige lagring. 

Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): må
Teknisk modenhet (høy, medium, lav): høy
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier:

---
### Åpne punkter - lukkes før sprint

---
### Annet

---
### Scenario X _Opprettes før lukking av denne BH_

**Forslag nye brukerhistorier Scenario X (MVP)**  

**Avklaringer scenario X**

**Comment by benedicteos** [comment]
@TageGitHub  - denne brukerhistorien forstår jeg ikke? Den har ikke samme oppsett som øvrige, er den egentlig en brukerhistorie? og om den kun handler om designet du skal møte, hvorfor har man listet opp opplysninger i denne?

**Comment by TageGitHub** [comment]
@benedicteos  - Denne bh er til for at utviklere kan programmere skjermbilde etter GUI designet, men hvor det ikke er nødvendig med visning av reelle data (mockup). Felter  som kan brukes er arbeidshypotese da vi ikke har landet dette enda.

**Comment by TageGitHub** [comment]
@kajabystol @eggedosis Legger dere inn link til GUI.

**Comment by TageGitHub** [comment]
Utgår. Overtas av #205
