### ISSUE TITLE
Informerer DA om status knyttet til opprettelse av bo

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#159]
#### Brukerhistorie
Som  saksbehandler i tingretten
ønsker jeg å bli informert om status knyttet til opprettelse av bo-instans i Altinn dødsbo 
slik at jeg er informert om når arvinger kan benytte  Altinn dødsbo.

**Krav/akseptansekriterier** 
Gitt at bo er opprette og boinstansen er ny.
Når Domstolene skal informeres om at arving kan benytte Altinn dødsbo
så sender Altinn dødsbo denne informasjonen til DA.

**Utfyllende tekst**
Saksbehandlere: kun info på sak, ikke varsel, ikke info om feilstatus). Info om feilstatus i ev logg

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): OK
Avklaringsområder: 
- [x] Ønsker Domstolene å se status om prosessen er i gang? (tb) ja
- [x] DA har signalisert at bruker må kunne trekke seg fra digital behandling selv om vedkommende ikke er reservert. Feks dersom bruker/arving opplever det som for belastende å bruke Altinn dødsbo. (tb)I slikt tilfelle kan arving forholde seg til gjeldende manuelle papirrutiner. (tb) Helt i orden arvinger ikke bruker tjenesten

Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a): **OK**
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder: 

- [ ] Hvilke felter/kode skal brukes?

Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): OK
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Test (sprint)
**Funksjonelt**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**System**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Integrasjon**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Comment by lillelars** [comment]
#159 - 
Som OED app
ønsker jeg gi beskjed til DA om at bo er opprettet i OED app
slik at DA er informert om at arvingene kan få støtte gjennom OED appen

Er dette egentlig avklart med DA?
- Trenger DA å vite at vi har opprettet en instans? Eller vil de vite når en arving logger seg på?

Uansett bør det skrives om som at det er DA som er behovseier for denne brukerhistorien. (Som saksbehandler hos DA....)

**Comment by TageGitHub** [comment]
@lillelars 
Justert bh og opprettet åpne punkter ihht over.
#62 er nå bedre ivaretatt av denne bh

**Comment by lillelars** [comment]
Håndteres av #383
