### ISSUE TITLE
Beslutte

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#16]
#### Epos:
Som en arving
ønsker jeg å å beslutte skifteform 
slik at jeg kan starte med å gjøre opp boet

#### Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenke til målarkitektur:

#### Tilhørende brukerhistorier
#23-33

**Comment by lillelars** [comment]
Benytter labels i stedet for Epics for fasene. Lukker derfor denne.
