### ISSUE TITLE
Oppsett React komponenter landingsside

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#161]
- [x] Skjellettkomponenten - oppsett grid (6h)

- [x] Tittelkomponent (3h)

- [x] Formue og gjeld (3h)
 
- [x] Formue og gjeld - detaljekomponent (3h)

- [x] Rett til arv (3h)

- [x] Aktivitetsliste-komponent (3h)

- [x] "Oppgaver i boet"-komponent (3h)

- [x] Nyttige lenker (3h)

**Comment by OlgaKoz** [comment]
Gammelt.
