### ISSUE TITLE
Dummy-instansiering mot DA-grensesnittet

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#164]
- [x] Se hvordan det er skrudd sammen

- [x] Se på initiell datamodell

- [x] Opprette instansen

- [x] Opprette en datamodell på instansen

- [x] Legge det inn i Altinn kodebasen

- [x] Instansierings-Controller i OED-appen som bruker T3.0 backend, mot DA-grensesnittet

**Comment by OlgaKoz** [comment]
Testet ok - Arving får lov til å begynne oppgjøret.
