### ISSUE TITLE
Beskjed til Domstolene om reservasjon i KRR

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#166]
#### Brukerhistorie
Som  arving
ønsker jeg at Domstolene  skal få beskjed om reservasjon mot elektronisk kommunikasjon
slik at videre behandling av boet kan gjøres uten støtte av OED app

**Krav/akseptansekriterier**  
Gitt at  arving har reservert seg i KRR
Når OED appen oppdager dette 
så skal OED gis det beskjed til Domstolene om funnet og konsekvenser dette medfører (lukke boet for elektronisk behandling)

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 

Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by lillelars** [comment]
@TageGitHub Er dette duplikat av #158 ? Hvertfall ser det slik ut på teksten i beskrivelsen.

**Comment by TageGitHub** [comment]
@lillelars 
Hang med testkriterier fra #158. Dette er nå slettet

**Comment by lillelars** [comment]
Håndteres i #383 Lukker denne.

**Comment by TageGitHub** [comment]
Åpnes da bh ikke er avklart

**Comment by TageGitHub** [comment]
utgår da arving ved reservasjon må håndtere arveoppgjøret utenfor Altinn dødsbo
