### ISSUE TITLE
Avslutte bo-instans ved reservasjon

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#167]
#### Brukerhistorie
Som  arving
ønsker jeg OED tjenesten skal avsluttes for bo der minst en av arvingene har reservert seg i KRR
slik at oppgjøret kan gjøres manuelt

**Krav/akseptansekriterier**
Gitt at  arving har reservert seg mot elektronisk kommunikasjon i KRR
Når OED oppdager dette
så skal OED boet avsluttes (ikke kunne nås av brukere) etter et parametersatt tidspunkt
og
hendelsen 'avslutte bo' sendes til Domstolene (som vil informere arvingen på vanlig måte om videre domstolprosess)
og domstolene varsles

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
- [ ] Hvordan skal et  bo i OED slettes/begrense tilgang?
- [ ] Det må avklares med domstolene om disse skal ha beskjed om at bo lukkes, og at domstolene må informere arvingene om at bo må håndteres utenfor OED.

Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by lillelars** [comment]
@TageGitHub 
Avklaring:
(Kan tas senere)
Hvordan skal arvinger som ikke er registrert i KRR, men allerede logget på i dødsboet få beskjed om at boet avsluttes?
Hva skal skje med boet? skal disse arvingene fortsatt ha tilgang?

**Comment by TageGitHub** [comment]
@lillelars 
Arvinger informeres av domstolene etter pre OED prosedyrer.
Ingen arvinger gis tilgang, dersom minst  èn arving reserverer seg.
Avslutte bo: Tenker at boet merkes 'avsluttet' og ikke lengre vil være tilgjengelig, men fysisk mulig å hentes fram . 
Det er må avklares om eventuell arkiveringskrav treffer prosjektet (Arkivlova). 
Oppdaterte dette som åpne punkter i bh

**Comment by curlingnina** [comment]
Denne BH er basert på hypotesen om at dersom en arving har reservert seg i KRR så kan ikke OED benyttes. Denne hypotesen er under utredning av ASF-juristene, og når deres vurdering foreligger så må vi korrigere denne BH hhv.

**Comment by TageGitHub** [comment]
Overtas av #260
