### ISSUE TITLE
Informasjon om ulike skifteformer

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#17]
**Brukerhistorie:**
Som en arving
ønsker jeg på bakgrunn av boets status å få tilrettelagt informasjon 
slik at jeg kan forstå hva som er rett skifteform for boet

#### Forretningsverdi  (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):
2?

**Godkjent juridisk (OK/NA/Ikke godkjent)**
Ikke godkjent

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

#### Akseptansekriterier (minimum happy-case):
•	Jeg får veiledning i de alternativene jeg har for ulike former for skifte
•	Jeg kan henvises til andre relevante sider
•	Jeg kan henvises til domstolens sider
•	Jeg har informasjon om aktiva, passiva, testamente, ektepakt m.v. 

**Avklaringer/fortusetninger:**
Usikker på om informasjon om ulike skifteformer skal være på bakgrunn av boets status?
Hva mener vi med boets status? 
Og det er ikke sikkert de skal "forstå" hva som er rett skifteform, men det er input til deres beslutning.. 
Informasjonen bør være generell, om privat skifte eller kun lenker ut, ikke tilpasset det aktuelle bo. Da er den generisk og domstol kan bistå i utforming, og senere oppdatering. Domstol bør "eie" informasjonen. 
Er informasjon om ulike skifteformer etc en del av domstolens veiledningsplikt? Kan domstolens veiledningsplikt ivaretas i Altinn dødsbo?
Hvilken informasjon trenger arving i scenario 1?

JÅB: Bør domstolene stå ansvarlig for denne informasjonen slik at vi henter inn info fra domstolenes API som da vil være den infoen som vises her. 
Har vi vår egen info her og domstolene sin info på sine sider kan et potensielt bli forskjell i info som bør være lik. Det beste er å ha bare en kilde og en part som vedlikeholder denne kilden. 

**SCENARIO X Akseptansekriterier (minimum happy-case):**
Hvilken informasjon trenger arvinger i øvrige scenario?

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by TageGitHub** [comment]
Videreført i #224
