### ISSUE TITLE
Arvings aktive avslutning av "tjeneste"

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#18]
#### Brukerhistorie
Som en arving
ønsker jeg å kunne avslutte tjenesten
slik at jeg kan gjennomføre skiftet/skifteoppgjøret på annen måte

**Krav/akseptansekriterier**
Gitt at jeg ønsker å avslutte bobehandling i OED
Når jeg å avslutte
så skal jeg kan henvises videre til riktig veiledning for videre prosess
og
 henvises til domstolen sider for veiledning
og
se kontaktinfo til riktig domstol - BOS: er det nødvendig?
og
tjenesten kan avsluttes ved at arving signerer for dette. Dette skal være mulig gjennomgående inntil det punkt hvor arving har tatt stilling til om fullmektig skal utpekes eller ikke/er utpekt. 
og
se avslutningsrapport/oppsummering i OED (JÅB)
og
se status om boet må oppdateres

**Utfyllende tekst**
- Tjenesten kan avsluttes ved at alle signerer for/er enige om dette. Dette skal være mulig gjennomgående inntil det punkt hvor arvinger har tatt stilling til om fullmektig skal utpekes eller ikke/er utpekt. 

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
- [ ] Trenger domstolene beskjed dersom bruker aktivt avlsutter tjenesten?

Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---
### Forslag nye bh scenarie 2+

**Comment by TageGitHub** [comment]
@kajabystol @curlingnina @JanAage99 - Skal den enkelte arving kunne avslutte bobehandlingen i OED på egnet initiativ? Eller bør dette først  håndteres som et ønske i OED som sendes til domstolene og at det er de som informerer OED?

**Comment by curlingnina** [comment]
@TageGitHub @kajabystol @JanAage99 jeg tenker vi må vurdere dette ift konkrete behov, det kan jo være ulike grunner til at en arving ikke ønsker å fullføre prosessen i den digitale tjenesten. Så vidt jeg vet er det per i dag ikke noe krav om at arvinger aktivt melder fra til tingretten, og en konsekvens er at boet blir flytende (dvs verken arvinger eller det offentlige gjennomfører skiftet). Annet vi må ta stilling til er hvordan vi rigger løsningen slik at alle arvinger må ta aktivt stilling til at de ønsker å avslutte prosessen, og at denne informasjonen tilgjengeliggjøres for DA.

**Comment by JanAage99** [comment]
@TageGitHub @kajabystol @JanAage99 Dette må i første omgang tas med DA og høre hva de tenker. Jeg tror at de gir blaffen i dette fordi de er for sin del ferdig med saksbehandling av skifte når de har utstedt skifteattest ?! I alle fall det Herman alltid har sagt til meg. Da er de ferdig med saksbehandling. Det reflekteres vel på et eller annet vis i LOVISA vil jeg tro. 
Men det er jo etter dette tidspunktet som selve skiftet/avhending av eiendeler/oppgjør av bo skjer. Så jeg tenker at dette bør være noe som alle arvinger er enige om / signerer for evt det kan være en rettighet som fullmektig har og kan gjøre på vegne av boet.
Korriger meg hvis jeg tar feil.

**Comment by JanAage99** [comment]
@TageGitHub @kajabystol @JanAage99 Ifm avslutning av tjeneste er det flere problemstillinger som oppstår:
- Skal det være mulig å åpne igjen feks dersom fullmektig har lukket ved den feiltagelse ?
- Skal det lukkes automatisk dersom det ikke har vært aktivitet på x antall år ?
- Skal instans fysisk slettes når boet lukkes, eller skal det bare sperres for videre bruk slik at det bare er funksjonelt lukket, men fortsatt mulig å gjenskape teknisk ?
- Skal det over i innboks-arkiv til den enkelte arkiv når det er lukket ?

**Comment by lillelars** [comment]
Håndteres i ny issue
