### ISSUE TITLE
Melding til Domstolene om fullmakt

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#180]
#### Brukerhistorie
Som  Saksbehandler hos Domstolene 
ønsker jeg å bli varsle om at fullmektig er utnevnt for boet
slik at Domstolene kan ta hensyn til dette i sin saksbehandling

**Krav/akseptansekriterier**  
Gitt at Fullmektig er opprettet i boet
Når Domstolene skal informeres om dette 
så skal informasjonen legges ut på en hendelsesliste slik at domstolene kan hente dette

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
- [x] Ønsker Domstolene å bli informert om at det er opprettet en fullmektig for arving? Nei. Ref Max 20.11.20
- [x] Når ønsker de denne informasjonen? De ønsker ikke informasjonen
- [ ] Kan en skifteattest utstedes til en fullmektig, og i tilfelle hvordan skal dette håndteres? 

Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by kristoffervp** [comment]
Out of scope. Domstolene/den aktuelle tingretten ønsker/trenger ikke denne informasjonen.
