### ISSUE TITLE
Motta og lagre informasjon om testament

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#182]
Som  Arving
ønsker jeg å vite om det eksisterer et  testament/arvepakt hos domstolen
slik at dette kan hensyntas i booppgjør

**Krav/akseptansekriterier**
Gitt at Domstolene har gjort tilgjengelig melding om at testament/arvepakt eksisterer tilgjengelig i Domstolenes hendelsesliste.
Når ny informasjon er tilgjengelig
så skal Altinn dødsbo hente informasjonen fra hendelseslisten
og
informasjonen skal lagres i Altinn dødsbo repositoriet.

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): **OK**
Avklaringsområder: 

- [x] Hva slags felter skal vi hente ned i MVP'en? (tb) indikator på at testament/arvepakt/gjensidig testament eksisterer hos Domstolen og tilhørende dato for hvert av disse.
- [x] Må opprettelse av bo-instans vente på avklarte testamentforhold? (tb) nei 
- [x] Holder det å vise opplysninger om kun relatert til testament/arvepakt fra testamentregister eller skal vi ha godkjente nattbordstestament/arvepakt også?: (tb) gjelder alle testament/arvepakter fra Domstolene. 
- [x]  type testament?
- [x] Hvem som levert inn skrivebordstestament? 
- [x] Registrert hos tingrett? 
- [x] Skal testamentarvinger oppdateres i AA i MVP? (tb)Kun arvinger med fulle rettigheter og formuesfullmakt.

Dokumentasjon:

**GUI**
Status: (ok, under avklaring, n/a): **OK**
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
- [ ] Kan vi vise hvilke arvinger som krysser av for at det finnes et skrivebordstestament?
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Test (sprint)
**Funksjonelt**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**System**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Integrasjon**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Comment by lillelars** [comment]
Avventer til i minstefall vi får spesifikasjonen fra DA

**Comment by lillelars** [comment]
Håndteres i super skjema om privat skifte #371

**Comment by TageGitHub** [comment]
Overtas av #279
