### ISSUE TITLE
Tilgang data -  skatt 

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#187]
#### Egenskap
Digitalt dødsbo skal gi tilgang til skatteetatens informasjon fra skatt slik at skattemessige forhold til avdød kan vises i DD.

**Krav/akseptansekriterier**
Gitt at Digitalt dødsbo er opprettet.
Når en med tilgang til DD logger seg på løsningen
skal det være mulig å navigere til skatteetatens sider og se informasjon i 'Min skatt'.

**Utfyllende tekst**
Hvilke felter skal vises fra skattemeldingen. (tb) dette vil være ihht skatt sitt design
---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a):  ok
Avklaringsområder: 

Dokumentasjon:

- API skatt (kan være gammel): https://teams.microsoft.com/l/file/319BCB85-93D1-4251-B236-21B186627912?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FDokumentasjon%20fra%20eksterne%20akt%C3%B8rer%2FReferater%20og%20teknisk%20dokumentasjon%2FSKS%2FAPI%20-%20Skatt.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

**GUI**
Status(ok, under avklaring, n/a): OK
Avklaringsområder:
Dokumentasjon:
https://www.figma.com/file/oBtm6UxIjZzOg0xzJganiL/OED-desktop-2023?node-id=0%3A1

**Teknisk**
Status(ok, under avklaring, n/a): OK
Avklaringsområder:
Dokumentasjon:
- [ ] Bjørn legg in dataflyt vedrørende autorisasjon i Digitalt dødsbo.
- [ ] 
Dokumentasjon

> Aktuelt API: Summert skattegrunnlag-api
> 
> API referanse: https://skatteetaten.github.io/datasamarbeid-api-dokumentasjon/reference_summertskattegrunnlag.html
> 
> Maskinporten scope: skatteetaten:summertskattegrunnlag
> 
> Open API spec (med forbehold om at det kan komme mindre endringer): https://app.swaggerhub.com/apis/Skatteetaten_Deling/summert-skattegrunnlag-api/1.0.0
> 
> Rettighetspakken husbanken gir tilgang til svært mange informasjonselementer
> OeD skal benytte følgende informasjonselementer, og se bort fra resten

> **bruttoformue**
> **samletGjeld**

> Informasjonsmodell for tjenesten: Informasjonsmodell summert skattegrunnlag
> Feltliste for årsversjon 2020: Summerte skattegrunnlag for 2020

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
- [ ] Hva er de juridiske implikasjoner knyttet til lagring av info fra skatt.?
- [ ] Hvilke data kan hentes fra skatt avhengig av året?
- [ ] Hva er de juridisk vurdering knyttet til autorisasjon og autentisering. Sjekk PP fra Bjørn?

**Test (sprint)**
Funksjonelt
Akseptert (j/n):
Avvik:
~~[x] Trenger å se at Skatteinfo lagres i digitalt dødsbo => 23.10.23, Aina/Tage: Lagring er oppe til juridisk behandling~~ AE/TB 26.20.23
- [ ] Vi trenger testcase der vi får kontakt med skatt og kan se deres sider.

System
Akseptert (j/n):
Avvik:

 nn
 nn
 nn
Integrasjon
Akseptert (j/n):
Avvik:

 nn
 nn
 nn

**Comment by JanAage99** [comment]
API-Skatt.docx er oppdatert med siste informasjon. Dvs at link til API-Skatt.docx i denne BH gir beste/siste info

**Comment by TageGitHub** [comment]
Lukket ved en feilvurdering

**Comment by erlendoksvoll** [comment]
@TageGitHub Vi lagrer ikke informasjon fra skatteetaten :)

**Comment by TageGitHub** [comment]
@erlendoksvoll @AinaEngen. Brukerhistorien sier at vi skal lagre. Kan ikke se at det er dokumentert noen juridiske vurderinger som tilsier noe annet.

**Comment by erlendoksvoll** [comment]
Det står ganske klart i høringsnotatet, @TageGitHub

**Comment by TageGitHub** [comment]
@DanRJ @CecilieFjellsoy @jost67 Brukerhistorien justert til at vi ikke henter data fra skatt , men kan navigere dit.

**Comment by TageGitHub** [comment]
Overtas av #202
