### ISSUE TITLE
Hente info om pensjon

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#193]
#### Brukerhistorie
**Intro**
Som  Arving 
ønsker jeg at informasjon om pensjon automatisk skal hentes inn i OED
slik at jeg får informasjon som jeg kan bruke i arveoppgjøret

**Krav/akseptansekriterier**  _(detaljering av BH med tilhørende akseptansekriterier)_
Gitt at.. 
Når ...
så skal hente fra norsk pensjon
og... 

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status : Under arbeid: 
Avklaringsområder:
Første utkast til integrasjonsguide er mottatt med følgende felter/info fra NP:
![image](https://user-images.githubusercontent.com/38287850/96573606-b38f2d80-12ce-11eb-9844-da5b224ffbb6.png)

Teknisk løsning
Rest med json

Dokumentasjon:
https://teams.microsoft.com/l/file/A6C69E03-AF55-4E54-B0B0-277675D3D5EF?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=pdf&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FL%C3%B8sningsbeskrivelser%20og%20tekniske%20dok%20fra%20eksterne%2FINDOK-IntegrasjonsguideOED-201020-0629.pdf&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): bør
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by lillelars** [comment]
Ferdigstilt. Lukker saken.
