### ISSUE TITLE
Hente data - Veivesenet

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#195]
#### Egenskap
Som en med tilgang til DD
ønsker jeg at opplysninger om avdødes registrerte kjøretøy skal innhentes ved bruk av DD
slik at jeg får informasjon om de kjøretøy som var registrert på avdøde i Kjøretøyregisteret (SVV)

**Krav/akseptansekriterier**

**Opplysninger som skal innhentes om kjøretøy:**
Eier, medeier,
reg.nr
Type kjøretøy (eks: personbil M1, nyttebil, lastebil, varebil)
Status (registrert/avskiltet/vraket osv)
Sist EU-godkjent

**Krav/akseptansekriterier:**
Gitt at en med tilgang til DD har logget seg på løsningen.
Når DD registrerer dette så skal det gå et kall fra løsningen til statens vegvesen om uthenting av kjøretøyinformasjon
og
Statens vegvesen returnerer med en etterspurt informasjonen.

---
### Utfyllende informasjon

**Funksjonelt**
Status (ok, under avklaring, n/a): ok
Avklaringsområder: 
Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a): ok
Avklaringsområder:
Dokumentasjon: 
Lenke til design (desktop) –

**Teknisk**
Status(ok, under avklaring, n/a): OK
Avklaringsområder:

Dokumentasjon:
- Vegvesenets webtjenester er basert på REST
Mer informasjon er tilgjengelig her om tjenester, miljøer og api: https://vegvesen.github.io/ak-api/
- API som må brukes for å finne kjøretøy basert på personnummer er kjøretøysøk: https://vegvesen.github.io/ak-api/api/#kjoretoysok
- Dokumentasjon av oppslag mot kjøretøy-API hos SVV er dokumentert her: https://vegvesen.github.io/ak-api/api/#kjoretoyoppslag
- Kall for å finne kjøretøy basert på fødselsnummer er dokumentert her: https://vegvesen.github.io/ak-api/api/api_kjoretoysok_45
- Kall som skal gjøres er: http://[env]/ws/no/vegvesen/kjoretoy/felles/v2/rest/distribusjon/kjoretoy/v2.0/sok/fodselsnummer
- Gir kjøretøy-søk-response som er dokumentert her: https://vegvesen.github.io/ak-api/api/api_kjoretoysok_45/definisjoner/#KjoretoysokResponse
- Gir kjøretøy-response som er dokumentert her: https://vegvesen.github.io/ak-api/api/api_kjoretoysok_45/definisjoner/#KjoretoyResponse
- Gir kjøretøy som er dokumentert her: https://vegvesen.github.io/ak-api/api/api_kjoretoysok_45/definisjoner/#Kjoretoy

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
- Ikke avklart juridisk
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): må
Teknisk modenhet (høy, medium, lav): høy
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): Klar

---
### Test (sprint)
**Funksjonelt**
Akseptert (j/n): 
Avvik:
- [x] Trenger å verifisere at informasjon fra Vegvesenet hentes ned fra vegvesenet i det person logger seg på Digitalt dødsbo. OK (erlend)
- [ ] nn
- [ ] nn

**System**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Integrasjon**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Comment by TageGitHub** [comment]
@lillelars bh oppdatert iht reell status i utvikling. Oppfølgingspunkter videreført i #285. Ryddet slik at avklaringspunkter er flyttet dit de hører hjemme blant annet #285 og #197. Sjekk om denne nå kan settes til ferdig utviklet.

**Comment by lillelars** [comment]
Vi har data fra SVV sitt api i testmiljøet. Dette fungerer. Lukekr derfor saken.

**Comment by AinaEngen** [comment]
@kristoffervp - det står en del akseptansekriterier nevnt over, hvorav det meste av dette vises i OED. Basert på hva jeg kan se mangler det
- leasingtaker => vet ikke om dette er avklart at ikke skal vises og at krav ikke har blitt oppdatert. Hvis det skal vises, så må vi sjekke at vi testdata for leasing og en løsning for å vise dette
- Kjøretøy i utlandet og Båter => samme som over, ingenting som vises av dette i dag. Skal det vises?
- Regner med at info om kjøretøyet skal kunne hentes frem via link til SVV? Gjelder bl.a.
   - farge
   - Status (registrert/avskiltet/vraket osv)
  Ingen av disse punktene blir vist i OED i dag 
- Kjøretøysgruppe (personbil M1, nyttebil, lastebil, varebil)  => Dette vises i dag med noen koder i header, men kan dette virke litt kryptisk ovenfor arvingene? Jeg ville ikke skjønt hva M16 eller L3e betyr...

**Comment by AinaEngen** [comment]
Testet ok. Testes sammen med #197

**Comment by TageGitHub** [comment]
Leasingtager fjernet

**Comment by erlendoksvoll** [comment]
@TageGitHub Det er litt uklart hva du har behov for å funksjonelt verifisere her. Blir ikke vegvesendataene lastet inn i appen?

**Comment by TageGitHub** [comment]
Ivaretas av bh  #317
