### ISSUE TITLE
Visning testamentindikator testamentregisteret 

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#198]
Som en Arving
ønsker jeg å se om det er et tinglyst testament knyttet til avdøde
slik at jeg kan bruke denne kunnskapen oppgjøret.

**Krav/akseptansekriterier**
Gitt at jeg har logget meg på Altinn dødsbo
Når jeg ønsker å se om det eksisterer et testament fra testamentregisteret
så skal jeg se dette iht. GUI beskrivelse

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
- [x] Hvilken informasjon om testamentet skal vise i MVP? (kaja?)  indikator på at testament eksisterer

Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:

- [ ] Skisse skjermbilde

Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Har deling av  testamentinfo med alle arvinger juridiske konsekvenser?
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet
- Angående oppbevaring av "nattbordstestamente". Dette er hentet ut fra domstolenes sider: "Et testament kan ha bestemmelser om gjennomføring av gravferd i tillegg til fordeling av arv. Det er derfor viktig at det så tidlig som mulig avklares om avdøde hadde opprettet et testament. Som hovedregel må testamentet være i original". Vi har skissert at arving må ha mulighet til å krysse av for JA/NEI/VET IKKE nattbordstestamente tidlig i prosessen. Hva jeg leser her, vil jo egentlig dette komme for sent HVIS det i tillegg handler om gjennomføring av gravferd? (SIden vi ikke skal være de første som opplyser om dødsfall, og har sagt tjenesten opprettes etter 5-7 dager. Da vil jo et begravelse allerede, eller stort sett blitt gjennomført. 
Har vi dabehov for denne avhukingen for arving tidlig, og om det holder med når de skal sende inn erklæring? Er det arvingenes ansvar å sørge for å oppfylle testamentets bestemmelser om feks gravferd, slik at domstol ikke har en rolle her, og det er tilstrekkelig med informasjon om nattbordstestamentet i erklæring om skifte?
Hvordan håndterer domstolen bestemmelser om gravferd i testament registrert i testamentregisteret?
---

**Comment by lillelars** [comment]
Duplikat av #353

**Comment by TageGitHub** [comment]
Håndteres av #352
