### ISSUE TITLE
Hva skal applikasjonen hete? Og hvem bestemmer dette?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#20]
Aktør involvert: ALLE!

beskrivelse: Vi må få tatt en avgjørelse på hva applikasjonen skal hete?
Er det:
- Altinn Dødsbo
JÅB forslag:
- Informasjon og gjennomføring av skifte ved dødsfall
- Dødsfall: Informasjon og gjennomføring av skifte (av (døds)bo)
- Dødsfall: Hvem, hva, hvor ?
- Noen har gått bort, hva gjør jeg ? 
- Jeg er arving, hva gjør jeg ?
- Død og arv: Informasjon, støtte og gjennomføring av skifte
- Arving: Veien til gjennomført skifte (ved dødsfall)
- Død og arv: Veien gjennom prosessen
(- Oppgjør etter dødsfall)

Frist: asap

**Comment by curlingnina** [comment]
Sukk, hva om dette var en enkel beslutning som vi kunne tatt, men dessverre er det nok mange som bør mene noe om dette... alle aktørene, DSOP, Digdir, KMD (OED utgjør jo en vesentlig del av livshendelsen Dødsfall og arv som KMD eier). Men jeg skjønner ikke hvorfor det haster å få på plass et offisielt navn på tjenesten. Vi skal jo ikke lansere MVP før neste år, så det må da være greit å ha et arbeidsnavn en stund til?

**Comment by lillelars** [comment]
@curlingnina jeg vil gjerne presisere at denne avklaringen lager masse ekstraarbeid og styr for oss. Ønsker at du eskalerer og får tatt denne avklaringen ASAP. (men bli frisk først da :) )

**Comment by curlingnina** [comment]
@lillelars jeg kan ta det med SG, men trenger mer kjøtt på beinet. Min hypotese er at det ikke kommer noen navneavklaring før branding- og designavklaringen er tatt
