### ISSUE TITLE
Visningsside Bank (med reelle data)

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#204]
#### Brukerhistorie
Som en arving 
ønsker jeg å se oversikt over informasjon fra Bank (med reelle data)
slik at jeg er informert når boet skal gjøres opp

**Krav/akseptansekriterier** 

Gitt at en med tilgang til DD og som i) har formuesfullmakt før skifteattest er utstedt, eller ii) har med skifteattest, eller iii) er skiftefullmektig til en med skifteattest, logger seg på DD
Når OED har mottatt og lagret denne informasjonen
så skal jeg se dette i DD

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 
Skjermbilde: https://eggedosis.github.io/oed/redirects/design/fortune/bank/default-one-d.html

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Test (sprint)
**Funksjonelt**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**System**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Integrasjon**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Comment by lillelars** [comment]
Håndteres under #380

**Comment by TageGitHub** [comment]
Feilaktig lukket. Åpnes
