### ISSUE TITLE
Kjøretøy se info (uten reelle data)

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#207]
#### Brukerhistorie
**Intro**
Som funksjonelt ansvarlig
ønsker jeg å se brukergrensesnittet for visning av informasjon fra Statens Vegvesen
slik at dette kan bygges videre på når vi får tilgang til reelle data

**Krav/akseptansekriterier**  _(detaljering av BH med tilhørende akseptansekriterier)_
Gitt at jeg i OED appen har valgt å se brukergrensesnitt for visning av kjøretøy informasjon
Når jeg foretar dette valget 
så skal Skjermdialogen vises med relevante felt (men uten reelle data)

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon
Vise i app kjennemerke, førstegangsregistrering, eierforhold, registreringsdato, dato for siste EU-godkjenning og kontrollfrist for neste EU-godkjenning 

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 
- Lenke til design https://eggedosis.github.io/oed/redirects/design/fortune/viechle/default-one-d.html

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by lillelars** [comment]
Realiseres av #197
