### ISSUE TITLE
Se roller og rettigheter knyttet til OED

### ISSUE THREAD

**Issue by benedicteos** [Altinn/oed#21]
#### Brukerhistorie
**Intro**
Som en arving
ønsker jeg å se  hvem som har tilgang til det digitale dødsboet
slik at jeg forstår hvem som kan gjøre/se hva i boet

**Krav/akseptansekriterier**
Gitt at  
Når 
så skal bruker ser oversikt over tildelte roller
og
bruker skal se informasjon om rettigheter knyttet til de tildelte rollene

Gitt at  
Når 
så skal 

**Utfyllende tekst**
Første gang bruker logger seg på er det viktig å vise informasjon om dette. De neste gangene er det kanskje viktigere å ivareta informasjonen f.eks som en annen side i løsningen vår?

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: hvordan skal et  bo i OED håndteres? slettes/begrense tilgang, Hvilke kriterier skal gjelde? 
Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder: 
- [ ] Vi trenger behandlingsgrunnlag for å kunne vise informasjonen om andre arvinger sine roller og rettigheter (eksponering av personopplysninger)
- [ ] at vi har rettslig grunnlag for å behandle for visning av navn/fødselsnr i skjermbilde
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet
- [ ] Roller og rettigheter må oppdateres for andre arvinger.
- [ ] Må oppdateres ved nye arvinger
---

**Comment by joebrreg** [comment]
@TageGitHub Ikke scenario 1? Det er vel ikke aktuelt å se flere roller, når scenariet er begrenset til å gjelde en rolle?

**Comment by TageGitHub** [comment]
Takker for kommentar. Bare fortsatt å notifye meg. Jeg svarer ikke fortløpende men går igjennom bulkhvis. 😀

________________________________
Fra: joebrreg <notifications@github.com>
Sendt: Thursday, November 12, 2020 3:02:35 PM
Til: Altinn/oed <oed@noreply.github.com>
Kopi: Bryn, Tage <tage.bryn@digdir.no>; Mention <mention@noreply.github.com>
Emne: Re: [Altinn/oed] Se roller og rettigheter knyttet til OED (#21)


@TageGitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTageGitHub&data=04%7C01%7C%7C948c2528606d4b54e19b08d887139c46%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637407865574490173%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WJ4njg42ZWEAMDALm4ZBSoY5cuDrh83HZfw15of0WDs%3D&reserved=0> Ikke scenario 1? Det er vel ikke aktuelt å se flere roller, når scenariet er begrenset til å gjelde en rolle?

**Comment by lillelars** [comment]
Viser detter i dag. Lukker saken.
