### ISSUE TITLE
Utgår? Oppdaterer roller/rettigheter skifteattest i AA

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#220]
#### Egenskap
Roller og rettigheter  og annen informasjon vedrørende mottatt skifteattest skal oppdateres i AA og bo-instansen
slik at dette kan brukes av arving og aktører i det videre arbeidet med skifte.

**Krav/akseptansekriterier**  
Gitt at  oppdatert informasjon  relatert til skifteattest er mottatt i Altinn dødsbo.
Når denne informasjonen skal hensyntas i av boet
så skal roller /og rettigheter og annen informasjon kunne oppdateres i AA
og bo-instansen
og
informasjonen skal kunne opprettes, endres og slettes av tingretten.

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 

- [ ] Hvorfor skal vi/skal ikke bruke AA ifm skifteattest?

Dokumentasjon:

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
- [ ] Er det behov for AA ifm skifteattest?
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Test (sprint)
**Funksjonelt**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**System**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Integrasjon**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Comment by kristoffervp** [comment]
Dekkes i Skifteattest #217

**Comment by TageGitHub** [comment]
Dekkes ikke av #217

**Comment by TageGitHub** [comment]
Utgår da AA ikke skal brukes for skifteattesteer i Digitalt dødsbo
