### ISSUE TITLE
Aktørers tilgang til digital skifteattest via skifteattest-API

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#222]
#### Brukerhistorie
Som aktør med et kundeforhold til en avdød 
ønsker jeg tilgang til skifteattest-API'et i Altinn dødsbo
slik at jeg kan forberede henvendelser fra arving og utføre  handlinger knyttet til skifte uten at annen skifteattest er nødvendig.

**Krav/akseptansekriterier** 
Gitt at en skifteattest er mottatt i Digitalt dødsbo.
Når 
en arving ønsker å dele denne informasjonen med en aktør
så skal 
arvingen fra Digitalt dødsbo appen kunne velge de aktørene som skal kunne hente skifteattest via skifteattest-API'et
og 
Digitalt dødsbo tilgjengeliggjør digital representasjon av skifteattesten i Digdir sin hendelsesliste ut for disse aktørene
og 
varsel sendes aktøren om at skifteattest er klar for å hentes via skifteattest API'et (ev. annen mekaniske som avtales med den enkelte aktør)
og
arvinger skal ha tilgang til logg i DD vedrørende hvilke aktører som har  laste ned skifteattest.

**Utfyllende tekst**
Det er aktører som inngår i MVP som skal informeres.

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 

- [ ] Ønsker aktørene i MVP'en å tilpasse sine forretningsprosesser slik at de kan motta elektronisk representasjon av skifteattesten? Hvis ikke må det fanges opp de som ev. ikke ønsker dette. Disse må fortsatt kunne får papirversjonen. 
- [x] Er dette i/utenfor MVP scope? (tb) hypotesen er at det kan tas med
- [x] Hvilken informasjon skal sendes aktørene? (tb) dne digitale representasjonen av skifteattesten.
- [ ] Skal arvingen kunne velge at alle, eller kun noen spesifikke aktører,  skal kunne laste ned skifteattesten via skifteattest-API'et.
- [ ] Er det kun aktører som er innlemmet i Digitalt dødsbo, med innsendelse av formue/gjeldssituasjon til avdøde, som skal kunne motta skiftefullmakt fra Digitalt dødsbo? Aktøren må vise til Digitalt dødsbo at avdøde har et kundeforhold?

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
- [ ] Hvilket utviklingsmønster
- [ ] Hvilken informasjon skal brukes pr. aktør?

Dokumentasjon:
Ønsker aktører en  hendelsesbasert trigger om at skifteattest er utstedt? I dag er det slik at arvingene leverer skifteattesten. Er det ønskelig med  en tilsvarende løsning i Digitalt dødsbo? 

Antagelse:
Aktør har etablert mottak av dig repr av skifteattest i sine systemer via API. Når arving ønsker det, sendes dig repr av skifteattest fra Digitalt dødsbo til aktørs mottak. 

-For aktører som ikke har etablert mottak av dig repr av skifteattest, varsles domstolene som sende ut sin skifteattest på gamlemåten.
- Må gås opp mer detaljert hva aktører faktisk ønsker 

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat

---
### Test (sprint)
**Funksjonelt**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**System**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Integrasjon**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Comment by curlingnina** [comment]
@TageGitHub : i PL-møtet 9.nov. nevnte både SB1 og DNB at de ønsker å se nærmere på eNotifikasjon. For detaljer snakk med @JanAage99 og @benedicteos, som deltok i møtet (jeg var fraværende pga sykdom).

**Comment by kristoffervp** [comment]
Out of scope MVP

**Comment by TageGitHub** [comment]
Overtatt av aktør spesifikke bh
