### ISSUE TITLE
Arving begjærer offentlig skifte

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#229]
#### Brukerhistorie
Som Arving 
ønsker jeg å kunne be om offentlig skifte
slik at dette kan hensyntas i boet

**Krav/akseptansekriterier**
Gitt at jeg har lest informasjon om skifteform
Når  jeg ønsker å opplyse om at jeg begjærer offentlig skifte
så skal dette kunne gjøres fra Altinn dødsbo
og 
jeg skal kunne se et preutfylt skjema
og
jeg skal kunne legge til tilleggs informasjon
og
jeg skal kunne signere
og
dette skal være synlig i Altinn dødsbo
og
arvinger og domstolene skal informeres om dette
og
Altinn dødsbo instansen avsluttes

**Utfyllende tekst**
Denne bh bør deles opp i flere egne bh.

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
- [ ] Er hele denne  del av MVP?
- [ ] Vurder alternativ funksjonalitet der Arving  begjærer offentlig skifte på gamlemåten hos Domstolene. I dette scenariet vil Altinn dødsbo måtte motta melding om bortvalg av privat skifte fra DA slik at bo-instansen kan avsluttes.

Dokumentasjon

- Prosess
https://teams.microsoft.com/l/file/78CF0A7A-A34F-4E00-A3AC-746DD4BB791E?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=pptx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FFunksjonelt%2FProsess%20Applikasjon%20Dataflyt%2FEpos%20223%20Valg%20av%20skifteform.pptx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by lillelars** [comment]
Dette dekkes av #379 . Lukker saken.

**Comment by TageGitHub** [comment]
håndteres av #226
