### ISSUE TITLE
Avslutter bo-instans etter melding fra Domstolene

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#233]
#### Brukerhistorie

> Som arving
> ønsker jeg at bo-instans avsluttes når et bo går ikke skal skiftes privat
> slik at jeg ikke lengre trenger å forholde meg til Altinn dødsbo appen

**Krav/akseptansekriterier** 

> Gitt at  melding om at boet ikke skal ha privat skifte er mottatt fra Domstolene
> Når OED appen oppdager dette 
> så skal boet avsluttes 
> OG
> alle arvinger med tilgang til Altinn Dødsbo varsles

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
- [ ] Ved avslutting av boet: Skal informasjon knyttet til boet faktisk slettes eller skal informasjonen beholdes men ikke lengre være tilgjengelig for arvinger men tilgjengelig for  feks.  administrator av OED app? 

Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by lillelars** [comment]
Dette dekkes av #379 . Lukker saken.

**Comment by TageGitHub** [comment]
overttt av #232
