### ISSUE TITLE
Innhenter opplysninger om eiendom fra Kartverket

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#235]
#### Egenskap
Når en arving med formuesfullmakt logger som på DD så skal informasjon om avdødes eiendom automatisk hentes fra Kartverket.

**Krav/akseptansekriterier**
Gitt at en arving med formuesfullmakt har logget seg på DD.
Når DD registrerer dette 
så skal  DD automatisk sende en forespørsel om å få informasjon om avdødes tinglyste eiendommer og rettigheter/heftelser
~~og
informasjonen fra Kartverket mottas og lagres i DD~~  
og
informasjonen  skal være iht listen under
og 
dette skal skje hver gang arving med formuesfullmakt logger seg på

**Utfyllende tekst**
- Andre arvinger enn den påloggede skal ikke ha få noe melding fra DD om at det er skjedd endringer i opplysninger om avdødes eiendom og rettigheter/heftelser, slik at den må logge seg på og se endringene.

Ytterligere informasjon om eiendom og rettigheter: 
I tillegg skal vi konstruere en lenke som tar brukeren til mer informasjon om bolig/eiendom i Se Eiendom: Håndteres i  #308

---
### Utfyllende informasjon
**Funksjonelt**
Status: OK

Avklaringsområder: 
- [x] Kan vi få se en visning av hvordan informasjonen ser ut for arving dersom eier er på fortrolig adresse? Visning håndteres av #39
- [x] Kan vi få ulike eksempler på kategorier av eiendommer? @lars
SVAR: Ja det kan vi. Det bestilles så fort vi har enighet om test-fødselsnumre som skal brukes for alle aktører. I mellomtiden får vi ulike registerenheter - Borettslagsandel, Matrikkelenhet, Festegrunn, Seksjon.
- [x] Hva er kodeverdi?
SVAR: brøk
Kodeverdi gir deg ikke noe ekstra i forhold til navnet ('Eiendomsrett'). Det er helt likeverdig med f.eks. 'Landkode: NO, Navn: Norge'. Eiendomsretten som returneres i svaret kan gjelde en eller flere personer. Hvis det er flere aktive andeler på registerenhetsretten, vil det være andre personer med eiendomsrett i tillegg til forespurte fnr.
- [x] Hvilket navn er det vi får tilbake fra API'et? Utgår ikke forstått
- [x] Kan vi få medeier? -> trenger medeier dersom vi får brøk? @lillelars 
SVAR fra kartverket: Vi kan få medeier. Det heter bare "Eiere". Dette bestilles hos kartverket til neste leveranse fra de.
Navn/fødselsnummer på medeiere er ikke en del av dataene. Hvis dette er et krav, må vi ta det opp i et møte og diskutere det.
- [x] Hvordan identifisere vi leilighet/bolig/hybel osv? @lillelars 
SVAR fra kartverket: I første omgang får vi rettigheter fra Grunnboken. Her ligger bl.a andelsleiligheter. Legger inn ny bestilling så vi får tilgang til andre typer eiendommer. Dette må hentes fra Matrikkelen.

Flere oppfølgingspunkter:
https://teams.microsoft.com/l/file/16690009-9F90-4886-9DA8-83AB6433EE8F?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FDokumentasjon%20fra%20eksterne%20akt%C3%B8rer%2FReferater%20og%20teknisk%20dokumentasjon%2FKartverket%2FOppf%C3%B8lging%20kartverket.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

Dokumentasjon
Felter som skal brukes: https://syntest.grunnbok.no/oed/swagger-ui.html#/

- Enheter
```
Matrikkelenhet: et nærmere beskrevet areal som er opprettet i matrikkelen, grunneiendom, anleggseiendom, eierseksjon, jordsameie eller festegrunn (matrl § 3 bokstav b)
Respons: Ident for en matrikkelenhet, bestående av kommune (kommunenummer og kommunenavn), gårdsnummer, bruksnummer, festenummer og seksjonsnummer

Borettslagsandel: er en eierandel i et borettslag
Ident for en borettslagsandel, bestående av et borettslag og et andelsnummer
borettslag: Ident for et borettslag, bestående av organisasjonsnummer og navn organisasjonsnummer

Felles for matrikkelenhet og borettslagsandel:
RegisterenhetsrettRespons: Resultatsett med liste av registerenhetsretter, og et flagg som markerer om foreløpige registreringer er inkludert
Registerenhetsrett: Ident som består av en registerenhetsrettstype og en matrikkelenhet/borettslagsandel
Registerenhetsrettstype: Kode for hvilken eierform en rettighetshaver har til en registerenhet (matrikkelenhet eller borettslagsandel)
Registerenhet: Ident for matrikkelenhet eller borettslagsandel

```
- Rettigheter og heftelser
```
HeftelseRespons: Resultatsett med liste av Heftelse/Rettighet, hver av disse igjen med en liste over registerenhetsretter som er involvert i den, og et flagg som markerer om foreløpige registreringer er inkludert
Heftelse: Rettsstiftelse av type Heftelse/Rettighet med en liste over registerenhetsretter som er involvert i den
Rettsstiftelse: Ident for en rettsstiftelse, bestående av dokumentår, dokumentnummer, embetenummer, rettsstiftelsetype og rettsstiftelsesnummer
Registerenhetsrett: Ident som består av en registerenhetsrettstype og en matrikkelenhet/borettslagsandel
Registerenhetsrettstype: Kode for hvilken eierform en rettighetshaver har til en registerenhet (matrikkelenhet eller borettslagsandel)
Registerenhet: Ident for matrikkelenhet eller borettslagsandel
```

**GUI**
Status: (ok, under avklaring, n/a): ok
Avklaringsområder:

Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): ok
Avklaringsområder:
Dokumentasjon:
- Et eksempelsøk i kartverket: https://seeiendom.kartverket.no/eiendom/1815/17/42/0/0
Kartverket skal levere en slik full URL på de eiendommene avdøde har eid i API

- https://etgltest.grunnbok.no/grunnbok/modell/grunnbok-domene-v2-modell/index.html
- https://etgltest.grunnbok.no/grunnbok/docs/Innsendingskodeidenter.html
- https://syntest.grunnbok.no/oed/swagger-ui.html#/

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
- [ ] forslag til  håndtering av fullmakt ok? (Trine) Håndteres i bh #212

Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet
Tidligere versjon bh 19/4 
Som arving
ønsker jeg at opplysninger om avdødes tinglyste eiendommer og rettigheter/heftelser skal innhentes ved bruk av Altinn dødsbo
slik at jeg får informasjon om de eiendommer og rettigheter/heftelser som er tinglyst på avdøde i Grunnboken

**Krav/akseptansekriterier**
Gitt at jeg ønsker å få informasjon om avdødes tinglyste eiendommer og rettigheter/heftelser
Når Altinn dødsbo ber Kartverket om eiendomsopplysninger
så skal Kartverket returnere med de etterspurte opplysningene

Opplysninger om avdødes eiendommer og rettigheter/heftelser innhentes fra Kartverket hver gang en arving med formuesfullmakt (rollenavn) logger seg på.
Opplysninger om avdødes eiendommer og rettigheter/heftelser  skal ikke innhentes fra Kartverket uten at en arving med formuesfullmakt logger på.
Arving skal ikke gjøre en aktiv handling for at opplysninger om avdødes eiendom og rettigheter/heftelser skal innhentes.
Arving skal ikke ha få noe melding fra Altinn dødsbo om at det er skjedd endringer i opplysninger om avdødes eiendom og rettigheter/heftelser, slik at den må logge seg på og se endringene.
I den første versjonen av dette skal ikke innhentede opplysninger lagres.

**Opplysninger om eiendom som skal innhentes fra Kartverket**

https://syntest.grunnbok.no/oed/swagger-ui.html#/

**_Enheter_**
Matrikkelenhet: et nærmere beskrevet areal som er opprettet i matrikkelen, grunneiendom, anleggseiendom, eierseksjon, jordsameie eller festegrunn (matrl § 3 bokstav b)
Respons: Ident for en matrikkelenhet, bestående av kommune (kommunenummer og kommunenavn), gårdsnummer, bruksnummer, festenummer og seksjonsnummer

Borettslagsandel: er en eierandel i et borettslag
Ident for en borettslagsandel, bestående av et borettslag og et andelsnummer
borettslag: Ident for et borettslag, bestående av organisasjonsnummer og navn organisasjonsnummer

Felles for matrikkelenhet og borettslagsandel:
RegisterenhetsrettRespons: Resultatsett med liste av registerenhetsretter, og et flagg som markerer om foreløpige registreringer er inkludert
Registerenhetsrett: Ident som består av en registerenhetsrettstype og en matrikkelenhet/borettslagsandel
Registerenhetsrettstype: Kode for hvilken eierform en rettighetshaver har til en registerenhet (matrikkelenhet eller borettslagsandel)
Registerenhet: Ident for matrikkelenhet eller borettslagsandel

_**Rettigheter og heftelser**_
HeftelseRespons: Resultatsett med liste av Heftelse/Rettighet, hver av disse igjen med en liste over registerenhetsretter som er involvert i den, og et flagg som markerer om foreløpige registreringer er inkludert
Heftelse: Rettsstiftelse av type Heftelse/Rettighet med en liste over registerenhetsretter som er involvert i den
Rettsstiftelse: Ident for en rettsstiftelse, bestående av dokumentår, dokumentnummer, embetenummer, rettsstiftelsetype og rettsstiftelsesnummer
Registerenhetsrett: Ident som består av en registerenhetsrettstype og en matrikkelenhet/borettslagsandel
Registerenhetsrettstype: Kode for hvilken eierform en rettighetshaver har til en registerenhet (matrikkelenhet eller borettslagsandel)
Registerenhet: Ident for matrikkelenhet eller borettslagsandel

Ytterligere informasjon om eiendom og rettigheter: 
I tillegg skal vi konstruere en lenke som tar brukeren til mer informasjon om bolig/eiendom i SeEiendom: Håndteres i  #308

**Funksjonell test:**

- [x] Ved første gangs åpning av skjermbilde går ventespinner rundt i mer enn ett minutt før feilmelding vises. 02.11.23 (tb) nå fikset.
![image](https://github.com/Altinn/oed/assets/71013993/e0233b9c-f7a7-442d-860e-2f092bc45023)
- [x] Aina sjekker om det er avvik på feltnivå på GUI, BH ok (aina 02.11.23)
- [x] Trenger å verifisere at informasjon hentes ned fra kartverket i det arvingen logger seg på Digitalt dødsbo.(tb)
- [x] Blir informasjonen lagret i DD (for gjenbruk når forbindelsen er brutt ved nedlasting fra aktør? 26.10.23 AE/TB Dette er flyttet til ETTER MVP da vi ikke enda har mottatt juridisk dokumentasjon på at dette kan gjøres.
- [ ] Trenger testdata knyttet til rettighetshaver og heftelser for å sjekke at dette er implementert.
- [x] Ønsker å se hvordan eiendomssiden ser ut dersom det ikke er noen eiendom tilknyttet avdøde. @CecilieFjellsoy

**Comment by lillelars** [comment]
Første iterasjon ferdigstilt. Lukkes

**Comment by TageGitHub** [comment]
Feilaktig lukking av BH

**Comment by TageGitHub** [comment]
Lagring flyttet til #663  da juridisk vurdering ikke er dokumentert.

**Comment by TageGitHub** [comment]
Utgår, erstattes av bh #319
