### ISSUE TITLE
Informasjon om nattbordsektepakt til domstol

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#24]
**Brukerhistorie:**
Som en arving
ønsker jeg å gi tingretten informasjon om ektepakter som ikke er tinglyst
slik at skifteprosess og oppgjøret kan skje i henhold til ektepakt.

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

**Godkjent juridisk (OK/NA/Ikke godkjent)**

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:
Ektepakt som er registrert i registeret skal kunne vises via API for arving. 

#### Akseptansekriterier (minimum happy-case):
•	Jeg kan avhuke for å bekrefte
•	Alle arvinger må vel gjøre dette ?
•	JÅB: Notifikasjon via API må sendes til domstolene fortløpende ettersom arving huker av/fjerner avhuking for dette? 

**Avklaring/forutsetning**
- Skal det være fortløpende eller gjennomgående?
- Skal domstol ha informasjon om ektepakt som ikke er registrert i ektepaktregisteret? Arvelov: arving skal opplyse om alle økonomiske forhold. 

**SCENARIO X Akseptansekriterier (minimum happy-case)**

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by benedicteos** [comment]
Denne brukerhistorien mener jeg ikke er nødvendig, dersom det ikke foreligger noe krav om at arving må informere domstol om at ektepakt tinglyst i ektepaktregisteret eller nattbordsektepakt eksisterer. Må undersøkes.

**Comment by TageGitHub** [comment]
Videreført i #255
