### ISSUE TITLE
Innhenter info om avdødes livs- og pensjonsforsikringer

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#243]
#### Egenskap
Når en arving med formuesfullmakt logger som på DD så skal informasjon om avdødes livs- og pensjonsforsikring automatisk hentes fra Norsk Pensjon ~~og lagres i DD.~~ AE/TB 26.20.23

**Krav/akseptansekriterier**  

Gitt at bo-instans er opprettet OG arving med formuesfullmakt har logget seg på DD.
Når arving logger seg på DD
så skal DD automatisk hente informasjon om info om avdødes livs- og pensjonsforsikringer fra Norsk Pensjon ihht vedlagt API beskrivelse og GUI skisse.
og
DD mottar  informasjon/ URL til kontaktside for hvert enkelt selskap (mottas/oppdateres ved hvert mottak fra MVP selskap og muligens andre selskaper men det må avklares ref NP)
og
DD mottar informasjon fra alle selskaper som NP har og som avdøde hadde er kundeforhold til
og
Forsikringsselskapene filtrere ut avtaler ved oversendelse der selskapet har mulighet til dette (eks. hundeforsikring..)

**Utfyllende tekst**

- Arving skal ikke ha få noe melding fra Altinn dødsbo om at det er skjedd endringer i opplysninger om avdødes livsforsikring og pensjon, slik at den må logge seg på og se endringene.

---

### Utfyllende informasjon

**Funksjonelt**

Status (ok, under avklaring, n/a): ok
Avklaringsområder internt: 

- [x] Skal informasjonen lagres i OED utover brukerøkten? (tb) ja, slik at informasjonen kan brukes i tilfeller der info ikke kan hentes fra NP.
- [ ] Dersom produktet ikke skal til utbetaling til dødsboet, og NP fortsatt kan levere denne produkttypen, ønsker vi da denne informasjonen? (tb) ønsker helst at selskapene filtrerer vekk avtaler 
som ikke er til utbetaling til arvinger eller andre som følge av dødsfallet. Dette er opp til selskapene å bestemme.
- [x] Må vi ha informasjon om hvem som er begunstiget i forsikringen for å kunne vise dette for arving? (tb) Nei. 
- [x] Kun visning til arving som er begunstiget? (tb) nei, visning til alle.
- [x] Hvilken informasjon skal med i forespørselen? se GUI.
- [x] Fødselsnummer - har vi behov for det? Trenger vi det for å sikre at informasjonen havner i riktig bo i DD. Får kun svar på relatert til avdødes fødselsnummer.
- [x] Navn på pensjonsinnretning = navn på selskapet hvor avdøde har sin polise
- [x] Pensjonsinnretnings organisasjonsnummer = org.nr til selskapet hvor avdøde har sin polise 
- [x] Produkttype: se egen liste

Dokumentasjon
- Dersom det skal henses annen informasjon:
I april-19, juni-20 og august-20 tok KLP kontakt med DSOP v/Nils Inge. Sak: i dag er det slik at ca 30 % av etterlatte hvor den avdøde var ufør ikke får utbetalt uføreforsikring. 

**Felter som mottas ihht Swagger-def:** 
**Gjelder fortsatt? :** 
https://teams.microsoft.com/l/file/CED14B7E-6E93-44AE-B390-785498289000?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=pdf&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FDokumentasjon%20fra%20eksterne%20akt%C3%B8rer%2FReferater%20og%20teknisk%20dokumentasjon%2FNorsk%20Pensjon%2FSwagger_OED.pdf&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

**Felter detaljert beskrivelse:** 
**Gjelder fortsatt?**
https://teams.microsoft.com/l/file/3DDF4174-84A0-461D-A573-1458EE4FBCB0?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=pdf&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FDokumentasjon%20fra%20eksterne%20akt%C3%B8rer%2FReferater%20og%20teknisk%20dokumentasjon%2FNorsk%20Pensjon%2FNorsk%20Pensjon%20-%20L%C3%B8sningsforslag%20OED%20v2.pdf&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

**API-beskrivelse**
**Gjelder fortsatt?**
https://teams.microsoft.com/l/file/39AF7577-3AEB-40CA-9E22-F39F998187C5?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FDokumentasjon%20fra%20eksterne%20akt%C3%B8rer%2FReferater%20og%20teknisk%20dokumentasjon%2FNorsk%20Pensjon%2FAPI%20-%20Forsikring.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

**GUI**
Status: (ok, under avklaring, n/a): ok
Avklaringsområder:
Dokumentasjon: 
**Gjelder fortsatt?**
https://www.figma.com/file/RekR9eVXajV3F0PPsUbHsn/OED-Research-og-wireframes?node-id=3%3A2** (trådskisser)

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:
- Norsk pensjon samler inn og konsoliderer data fra de enkelte pensjons/forsikrings-ordningene/foretak. Norsk pensjon vil skreddersy et API for OED
- Løsningsforslag fra Norsk pensjon ligger her:   https://brabts.sharepoint.com/sites/opgj_dodsfall/

- Vi henter fra API for hver enkelt avtale:
**Gjelder fortsatt?:**
| Felt  | Påkrevd | Validering | Lengde | 
| ------------- | ------------- | ------------- | ------------- | 
| Fødselsnummer | Ja | Gyldig norsk fødselsnummer/D-nummer | 11 siffer | 
| Opplysningsdato | Ja | Dato med format YYYYMMDD | | 
| Referanse | Ja | Selskapets interne referanse for polisen (f.eks. polisenr/avtalenr). String, ikke tom. Behøver ikke være unik. | [1..30] | 
| Dekningstype | Nei | Gyldige verdier: alderspensjon, dodsdekning - Med «dodsdekning» menes etterlattepensjon/livsforsikring | | 
| Navn på pensjonsinnretning | Ja |  | [1..50] | 
| Pensjonsinnretnings organisasjonsnummer | Ja | | 9 siffer | 
| Produkttype | | | | 
| Lenke til nesttside | | URL til nettside hos leverandøren av produktet | | 

**Gjelder fortsatt?:**
- [ ] Hvilke av de følgende ordninger skal være med i MVP?
Følgende ordninger kan bli del av OED:
| Ordningstype | Produkttype | Utbetales til boet ? |  
| ------------- | ------------- | ------------- |
| Kollektiv | Innskuddsbasert kollektiv pensjon | Kanskje |
| Kollektiv | Ekstrapensjon | Kanskje |
| Kollektiv | Personalforsikring | Kanskje |
| Privat | IPS | Kanskje |
| Privat | IPA | Kanskje |
| Privat | Individuell uførepensjon | Kanskje |
| Privat | Barneforsikring | Kanskje |
| Privat | Uføreforsikring | Kanskje |
| Privat | Sykeforsikring | Kanskje |
| Privat | Spareavtale | Ja |

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Annet
Følgende type forsikringer (produkttyper) mottar vi informasjon om:  

**Gjelder fortsatt?:**
Innskuddsbasert kollektiv pensjon: Dersom ingen berettigede etter LOI § 7-7, utbetales kapitalen som et engangsbeløp til dødsboet
- I hvilke scenarier vil denne utbetalingen inngå i dødsboet?
- Dersom utbetalingen ikke inngår i dødsboet, vil arvingene ha rett på informasjon om denne produkttypen?

Ytelsesbasert kollektiv pensjon: Dersom avtalen er tilknyttet pensjon til fordel for etterlatte utbetales pensjon til denne/disse
- I hvilke scenarier vil denne utbetalingen inngå i dødsboet?
- Dersom utbetalingen ikke inngår i dødsboet, vil arvingene ha rett på informasjon om denne produkttypen?
- Er denne produkttypen regulert i lov/forskrift eller er det kun avtalebasert? 
- Med etterlatte her, mener man alle arvinger etter avdøde eller kun ektefelle/samboer og barn? 

Ekstrapensjon: Utbetales til den som er berettiget, eller dødsboet
- I hvilke scenarier vil denne utbetalingen inngå i dødsboet?
- Dersom utbetalingen ikke inngår i dødsboet, vil arvingene ha rett på informasjon om denne produkttypen?
- Er denne produkttypen regulert i lov/forskrift eller er det kun avtalebasert? 

Fripolise med investeringsvalg: Dersom avtalen er tilknyttet pensjon til fordel for etterlatte utbetales
pensjon til denne/disse
- I hvilke scenarier vil denne utbetalingen inngå i dødsboet?
- Dersom utbetalingen ikke inngår i dødsboet, vil arvingene ha rett på informasjon om denne produkttypen?
- Er denne produkttypen regulert i lov/forskrift eller er det kun avtalebasert? 
- Med etterlatte her, mener man alle arvinger etter avdøde eller kun ektefelle/samboer og barn? 

Hybridpensjon: Dersom avtalen er tilknyttet pensjon til fordel for etterlatte utbetales
pensjon til denne/disse
- I hvilke scenarier vil denne utbetalingen inngå i dødsboet?
- Dersom utbetalingen ikke inngår i dødsboet, vil arvingene ha rett på informasjon om denne produkttypen?
- Er denne produkttypen regulert i lov/forskrift eller er det kun avtalebasert? 
- Med etterlatte her, mener man alle arvinger etter avdøde eller kun ektefelle/samboer og barn? 

Personalforsikring: Forsikringen utbetales i henhold til forsikringsavtalen. Kan utbetales
til boet, typisk kommunegruppeliv.
- I hvilke scenarier vil denne utbetalingen inngå i dødsboet?
- Dersom utbetalingen ikke inngår i dødsboet, vil arvingene ha rett på informasjon om denne produkttypen?
- Er denne produkttypen regulert i lov/forskrift eller er det kun avtalebasert? 

Individuell pensjonssparing (IPS): Dersom ingen berettigede etter LOI § 7-7, utbetales kapitalen som et
engangsbeløp til dødsboet
- I hvilke scenarier vil denne utbetalingen inngå i dødsboet?
- Dersom utbetalingen ikke inngår i dødsboet, vil arvingene ha rett på informasjon om denne produkttypen?
- Er denne produkttypen regulert i lov/forskrift eller er det kun avtalebasert? 

Privat pensjon: 
- Hva er denne produkttypen? Har ingen beskrivelse i løsningsforslaget. 
- I hvilke scenarier vil denne utbetalingen inngå i dødsboet?
- Dersom utbetalingen ikke inngår i dødsboet, vil arvingene ha rett på informasjon om denne produkttypen?
- Er denne produkttypen regulert i lov/forskrift eller er det kun avtalebasert? 

Barneforsikring: Se vilkårene, kan være sammensatt produkt
- Hva er denne produkttypen? Har ingen beskrivelse i løsningsforslaget. 
- I hvilke scenarier vil denne utbetalingen inngå i dødsboet?
- Dersom utbetalingen ikke inngår i dødsboet, vil arvingene ha rett på informasjon om denne produkttypen?
- Er denne produkttypen regulert i lov/forskrift eller er det kun avtalebasert? 

Livrente: Forsikringen utbetales i henhold til forsikringsavtaleloven
- I hvilke scenarier vil denne utbetalingen inngå i dødsboet?
- Dersom utbetalingen ikke inngår i dødsboet, vil arvingene ha rett på informasjon om denne produkttypen?
- Er denne produkttypen regulert i lov/forskrift eller er det kun avtalebasert? 

Livsforsikring / dødsfallsforsikring: Forsikringen utbetales i henhold til forsikringsavtaleloven
- I hvilke scenarier vil denne utbetalingen inngå i dødsboet?
- Dersom utbetalingen ikke inngår i dødsboet, vil arvingene ha rett på informasjon om denne produkttypen?
- Er denne produkttypen regulert i lov/forskrift eller er det kun avtalebasert? 

Spareavtale: Skal til dødsboet. Hvis ikke kreditorvern
- I hvilke scenarier vil denne utbetalingen inngå i dødsboet?
- Dersom utbetalingen ikke inngår i dødsboet, vil arvingene ha rett på informasjon om denne produkttypen?
- Er denne produkttypen regulert i lov/forskrift eller er det kun avtalebasert? 

Et tomt valg – i tilfelle kategorien ikke passer og ikke er lagt inn enda. Hva innebærer dette? 
- Kommer det fritekst i dette feltet? 
- På hvilke kriterier kan dette feltet bli tatt i bruk? Vil det skje ofte? Er det stor variasjon i de produkttypene de ulike aktørene har, slik at de ikke vil kjenne seg igjen i kategoriene, slik at denne vil bli brukt? 

Produkttyper som er strøket over i løsningsforslaget: 
IPA
Individuell uførepensjon
Foreningsgruppeliv
Uføreforsikring
Sykeforsikring 

- Hvorfor er disse strøket over? 
- Har aktørene beskrevet alle sine produkter, eller har de allerede plukket ut noen produkter når de laget løsningsforslaget? 

- Opplysningsdato - hva er det? Registrert dato eller innhentet dato? Vi vil gjerne vise både registrert dato og innhentet dato (dato vi innhenter opplysningene) 
- Det er ønskelig å få verdier knyttet til produktypene nevnt over. Er dette mulig, hva skal til? 
- Dekningstype. Er strøket over i løsningsforslaget, men er med i swagger-fila deres. Det ønsker vi en forklaring på.
-Lenke til nettside = generell lenke til leverandøren av produktet. Kan lenken gå direkte til det aktuelle produktet? Evt til kontaktperson hos leverandøren?
---

---
### Test (sprint)
**Funksjonelt**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**System**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Integrasjon**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Comment by curlingnina** [comment]
@TageGitHub denne BH var tagget som scenario x, jeg mener dette er feil og har har endret til scenario1. Ta kontakt dersom du er uenig i min vurdering.

**Comment by curlingnina** [comment]
@TageGitHub gruppelivforsikringer er IKKE data som NP sitter på, og uansett finnes det ingen løsning i dag for å innhente gruppelivsdata på individnivå. Jeg mener derfor at det som står om gruppeliv er irrelevant for denne BH, og at BH #135 skal bestå men da som utenfor scope.

**Comment by lillelars** [comment]
Lukker denne - er implementert.

**Comment by TageGitHub** [comment]
Feilaktig lukket, åpnes.

**Comment by TageGitHub** [comment]
Lagring ivaretas av #663 ved senere implementering
