### ISSUE TITLE
Mottar og lagrer informasjon om pensjonsforhold

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#244]
#### Brukerhistorie
Som arving
ønsker jeg at informasjon fra avdødes  pensjonsforhold skal mottas i OED
slik at Dette blir tilgjngelig for gjennomsyn der

**Krav/akseptansekriterier** 
Gitt at Norsk Pensjon har hentet informasjon fra avdødes pensjonsforhold
Når dette skal tilgjengeliggjøres for OED
så skal OED motta og lagre denne informasjonen

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
- [ ] Hvilke felter skal mottas
- [ ] Skal informasjonen lagres i OED utover brukerøkten?

Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by benedicteos** [comment]
Håndteres av #243
