### ISSUE TITLE
Oversikt over innhentet og utfylt data

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#25]
**Brukerhistorie:**
Som en arving
ønsker jeg en oppsummering over innhentet data og data jeg har fylt ut selv
slik at jeg har en oversikt over innhentet og utfylt data

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):
1

**Godkjent juridisk (OK/NA/Ikke godkjent)**

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:
JÅB: Denne brukerhistorien kan også komme til anvendelse i #18 når en beslutter å bruke annen skifteform

#### Akseptansekriterier (minimum happy-case):
•	Jeg kan se informasjon om testamentets (inkl. nattbord) eksistens der det er aktuelt (del av scenario 1?)
•	Jeg kan se informasjon om ektepakts (inkl. nattbord) eksistens der det er aktuelt  (del av scenario 1?)
•	Jeg kan se oversikten over aktiva/passiva fra alle aktører 
•	Jeg kan se forbehold om at dette ikke er en komplett oversikt over avdødes aktiva/passiva
•	Jeg kan se all nødvendig informasjon om hva mer jeg bør innhente av informasjon/data fra ulike aktører (må også skje i visningsvindu i oversikts-fasen)

**Avklaringer/forutsetninger:**

**SCENARIO X Akseptansekriterier:**

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by TageGitHub** [comment]
@kajabystol @curlingnina @JanAage99 - usikker på om denne brukerhistorien har livets rett. Er ikke denne dekket opp gjennom den innhentingen og visning vi gjør fra aktører som allerede er beskrevet. Skal vi ha med mer i MVP?

**Comment by curlingnina** [comment]
@TageGitHub og @kajabystol så vidt jeg kan se er dette dekket i BH landingssiden (eks #148 )

**Comment by JanAage99** [comment]
@TageGitHub @curlingnina @kajabystol  Det som hentes inn automatisk fra aktører osv er allerede dekket i #148. Det jeg stusser på er " innhentet data og data jeg har fylt ut selv". Data man har fylt ut selv vet jeg ikke om er dekket av #148 eller det er gått opp mer spesifikt hva som ligger i dette.
