### ISSUE TITLE
Aktivitetslogg

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#259]
## Introduksjon
Aktivitetsloggen i Altinn Dødsbo-løsningen er tiltenkt å gi arvingene oversikt over relevante hendelser og aktiviteter knyttet til dødsboet.

Relevante lenker:

## Funksjonalitet (MVP)
- Signert/samtykket/innsendt skjema for erklæring om privat skifte

## Tilleggs funksjonalitet (utenfor MVP)
 - Oppdatering fra Tingretten
 
## Interessenter

**Comment by kristoffervp** [comment]
Lukkes. Førsteversjon av aktivitetslogger er på plass, videre funksjonalitet og hendelser i loggen håndteres i øvrige epics/brukerhistorier hvor vi finner behov. Samt innspill fra brukertest.

**Comment by TageGitHub** [comment]
@CecilieFjellsoy @DanRJ 
Gjennåpnet da den ikke skulle vært slettet
