### ISSUE TITLE
Utfylling av erklæring om privat skifte

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#26]
**Brukerhistorie:**
Som en arving
ønsker jeg å fylle ut en erklæring om privat skifte 
slik at boet gjøres opp i henhold til mine ønsker.

#### Forretningsverdi  (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):
1

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

**Godkjent Juridisk (OK // N/A // Ikke godkjent)**
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
•	Jeg kan velge privat skifte
•	Jeg kan velge å endre JA/NEI for testament som ikke er identifisert tidligere av tingretten. 
•	Jeg kan se innholdet i erklæringen om privat skifte før den sendes til signering
- Erklæring om privat skifte må oppfylle lovens krav/domstolens krav

**Avklaringer/Forutsetninger:**
- Hva er krav til innhold i erklæring om privat skifte etter arvelov og tilhørende forskrift? Hvilken informasjon preutfylles fra system?
- Skal arving informere domstol om eksistens av nattbordsektepakt?
- #23 - sjekk denne brukerhistorien. Er den nødvendig?
- Dersom arving skal se erklæring om privat skifte etter den er signert, før den sendes til domstol, så må vel det håndteres i brukerhistorie for signering?

**SCENARIO X** 

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by benedicteos** [comment]
Denne tror jeg vi må skrive om, skal den egentlig handle om utfylling og signering av erklæring om privat skifte? @kajabystol @curlingnina  @lillelars @JanAage99

**Comment by curlingnina** [comment]
@benedicteos , @kajabystol , @JanAage99 : ja mener jeg, dersom regelverket krever utfylling og signering av erklæring om privat skifte også i OED.

**Comment by benedicteos** [comment]
> @benedicteos , @kajabystol , @JanAage99 : ja mener jeg, dersom regelverket krever utfylling og signering av erklæring om privat skifte også i OED.

Ja, i alle fall må vi sikre at nødvendige krav til innhold og signering er oppfylt ved oversendelse til domstolen, og arvingene må selvsagt skjønne hva de gjør. Samtidig ønsker vi å pre-utfylle om vi får rettslig grunnlag for dette.

**Comment by JanAage99** [comment]
Denne må harmoneres opp med andre relaterte issues

**Comment by TageGitHub** [comment]
Videreføres i #227
