### ISSUE TITLE
Oppdatere arvinger komponenten på startsiden til å hente korrekt fødselsnr/arving

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#261]
Oppdatere grensesnitt for å hente korrekt arving.

Arvingen(e)s navn og fødselsnummer ligger i instansens data og kan hentes direkte fra Redux i react komponenten.
Arvinger react komponenten henter derfor ut disse uten å gjøre et kall til en MVC kontroller.
Nå vises kun første arving i komponenten. Det må avklares med "Design" om det er kun en som skal vises eller om det alltid skal vises alle arvinger. Hvis det feks er 10 arvinger så vil den "boksen" bli mye større en de andre boksene på startsiden.

**Comment by RogerKjaernsrod** [comment]
Arvingen(e)s navn og fødselsnummer ligger i instansens data og kan hentes direkte fra Redux i react komonenten.
Arvinger react komponenten henter derfor ut disse uten å gjøre et kall til en MVC kontroller.
Nå vises kun første arving i komponenten. Det må avklares med "Design" om det er kun en som skal vises eller om det alltid skal vises alle arvinger. Hvis det feks er 10 arvinger så vil den "boksen" bli mye større en de andre boksene på startsiden.

**Comment by lillelars** [comment]
Outdated - lukker saken.
