### ISSUE TITLE
Behandlingsgrunnlag for persondata / medeier SVV

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#262]
Aktør involvert: SVV

Knyttet til brukerhistorie:
#195 

beskrivelse:
Vi må få en avklaring på hvorvidt vi får ta i mot, behandle og lagre persondata (medeier / leasingeier av kjøretøy).
 
Frist:

**Comment by tblix** [comment]
Opplysningene om medeier (og tidligere eiere) er tilgjengelig for offentligheten ved innlogging i dag, se  her [https://www.vegvesen.no/kjoretoy/Kjop+og+salg/Kjøretøyopplysninger/finn-kjoretoyets-eier](url).

De deles av SVV med hjemmel i offentleglova. 

Jeg kan i utgangspunktet ikke se at det skulle være noe problem at vi deler dette i tjenesten, så lenge vi får på plass databehandleravtale mellom oss og SVV.

**Comment by lillelars** [comment]
@tblix forstår det på deg at vi da kan kjøre videre med denne uten å være redd for å bryte med personvern osv?
@TageGitHub

**Comment by benedicteos** [comment]
Håndteres i #285
