### ISSUE TITLE
 Skal DA gjøre spørring mot reservasjonsregisteret for å finne ut om arving er reservert mot digital kommunikasjon?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#263]
Ref lang diskusjon på teams og dette dokumentet:

https://teams.microsoft.com/l/file/1958806F-20A1-43A4-A6BD-8A1F2D6FC436?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FJuridisk%2FAkt%C3%B8rene%2FDomstol%2F(4)%2020201103%20domstolene%20vurdering%20kontakt-og-reservasjonsregisteret.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

Benedicte:
Denne må avklares og begrunnes ASAP. 

Aktør involvert:
DA, OED, AA
Knyttet til brukerhistorie:
#171 
beskrivelse:

Frist:

**Comment by tblix** [comment]
Løses på #158
