### ISSUE TITLE
Bli kjent med dine rettigheter

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#264]
#### Epos:
Som en arving
ønsker jeg å se informasjon knyttet til ' rett til arv i boet'
slik at jeg får en oversikt over alle arvinger og relasjoner

Krav/akseptansekriterier (detaljering av BH med tilhørende akseptansekriterier)
Gitt at.. jeg har logget inn i Altinn Dødsbo
så skal jeg se en komponent som heter "rett til arv i boet"
og den skal inneholde informasjon om arvinger
og den skal inneholde informasjon om det er registret et testamentet eller ikke
og den skal inneholde informasjon om mine rettigheter

Gitt at jeg har logget inn i Altinn Dødsbo
når jeg klikker på lenken "arvinger"
så skal jeg bli tatt til en side som gir mer informasjon om arvingene

Gitt at jeg har logget inn i Altinn Dødsbo
når jeg klikker på lenken "testamente"
så skal jeg bli tatt til en side som gir mer informasjon om testamente

Gitt at jeg har logget inn i Altinn Dødsbo
når jeg klikker på lenken "Dine rettigheter"
så skal jeg bli tatt til en side som gir mer informasjon om mine rettighet

Tekst angående dette kan finnes her:
https://teams.microsoft.com/dl/launcher/launcher.html?url=%2F_%23%2Fl%2Ffile%2F654E1B14-A148-4B3F-AED3-71F0832C9648%3FtenantId%3D008e560f-08af-4cec-a056-b35447503991%26fileType%3Ddocx%26objectUrl%3Dhttps%253A%252F%252Fdigdir.sharepoint.com%252Fsites%252FProsjekt_DSOPOppgjretterddsfall%252FDelte%2520dokumenter%252FGeneral%252FRealiseringsfasen%252FFunksjonelt%252FTekster%2520i%2520Oppgj%25C3%25B8r%2520etter%2520d%25C3%25B8dsfall%252Finformasjon%2520om%2520arv%2520og%2520retten%2520til%2520arv.docx%26baseUrl%3Dhttps%253A%252F%252Fdigdir.sharepoint.com%252Fsites%252FProsjekt_DSOPOppgjretterddsfall%26serviceName%3Dteams%26threadId%3D19%3A3d13bc45f93147f0b8f98e48eae64227%40thread.skype%26groupId%3D2215cbdb-4e72-48c6-9c37-e73d84001515&type=file&deeplinkId=c5068691-b745-4e76-935d-5f26eb68365a&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true

**Comment by OlgaKoz** [comment]
Testet her https://teams.microsoft.com/l/file/F253CE1F-22B5-44C1-B09E-1781C6C741B7?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FTest%2FTest%20Planer%2FTest%20plan%20Sprint%201%2FTest%20Cases%20Dine%20Rettigheter.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

**Comment by kristoffervp** [comment]
Denne lukkes og følges videre opp i #384. FYI @OlgaKoz @lillelars
