### ISSUE TITLE
Mappe data fra SVV til en JSON struktur

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#266]
Hentet fra behov: #195 

- [x] legge til resterende felter GUI trenger for å populere all data (avklare hvilke felter gui har mot API'et) (1d)
- [x] lagre JSON-filen på selve instansen - Skal det lagres utenom hovedinstansen eller som et eget dataelement? Besluttet: Vi går for det som allerede er laget. Det betyr at det lagres på instansen, men separat for hver aktør/ekstern kilde  (ettersom det er mulig med flere ulike grupperinger på selve instansen) ( X )

Testdata for SVV må følge samme fødselsnr vi benytter @JanAage99 - hvor langt er vi her?

**Comment by OlgaKoz** [comment]
Ferdig.
