### ISSUE TITLE
Info om prosess, steg og rettigheter

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#27]
#### Brukerhistorie:
Som en arving 
ønsker jeg informasjon om steg, prosess og rettigheter 
slik at jeg kan bestemme om jeg fortsatt ønsker å bruke tjenesten

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- bruker skal se....
Jeg kan henvises til domstolens sider
....
- bruker skal bli tatt til...
- tekst må kvalitetssikres

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by lillelars** [comment]
duplikat
