### ISSUE TITLE
Tilgang til DD dødsbo

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#272]
#### Brukerhistorie 
(Som arving med formuesfullmakt)
Når en person med tilgang til DD  har logget seg på løsningen 
ønsker jeg at DD har informasjon om dette 
slik at denne kan få se informasjon om avdødes formue og gjeld i Altinn dødsbo

**Krav/akseptansekriterier**

Gitt at personen som har logget seg på DD ikke er arving.
Når DD mottar informasjon om denne
så skal det alltid først være opprettet en dødsfall instans i DD **(valideringsregel)**
og
personen skal være gitt tilgang til 

**Utfyllende tekst**
Informasjon fra Statens vegvesen hentes automatisk til Altinn dødsbo når en person med tilgang til DD  har logget seg på.

**Krav/akseptansekriterier** 
Gitt at en person med tilgang til DD  har logget seg på løsningen og DAN har hentet token for tilgang til kjøretøyregisteret  fra Maskinporten.
Når informasjon hentes
så skal en forespørsel om dette sendes fra DAN til Statens vegvesen sitt system
og
informasjonen som mottas  gjøres tilgjengelig i DD
og
UTGÅR: informasjonen lagres og kan gjenbrukes dersom det ikke fås kontakt med aktør ved neste gangs pålogging av arving.) tb 22/8

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): **OK**

- [x] Skal Domstolene indikere at en arvinger gitt formuesfullmakt? (tb) nei

Avklaringsområder: 

Dokumentasjon:

**GUI**
Status: (ok, under avklaring, n/a): **OK**
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:

Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): **OK**
Avklaringsområder:
Dokumentasjon:

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Test (sprint)
**Funksjonelt**
Akseptert (j/n): n
Avvik:
- [ ] Ønsker å få verifisert at formuesfullmakt informasjon kommer som eksplisitt informasjon fra DA, slik at vi også kan trekke tilbake igjen formuesfullmakt ved bruk av dette feltet ( 23.10.23, Aina/Tage)
- [ ] Trenger testdata/scenarier der arvinger som ev. mottas fra DA, **uten** at det er mottatt et tilhørende dødsbo, slik at DA blir varslet om at arvinger ikke er lagret i løsningen. DD skal håndtere dette kontrollert slik at løsningen ikke kræsjer => 23.10.23, Aina/Tage: Hva skjer i løsningen hvis det kommer en arving før dødsboet er opprettet (kræsj, feilmelding, melding til DA etc)? Vi ønsker å se hvordan dette fungerer
- [ ] nn, 

**System**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Integrasjon**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Comment by lillelars** [comment]
Håndteres i #387

**Comment by TageGitHub** [comment]
@erlendoksvoll @elsand @DanRJ @CecilieFjellsoy 
Oppdatert med avklaringer pr 23.03.2023

**Comment by erlendoksvoll** [comment]
@TageGitHub Informasjon om formuesfullmakt vises i applikasjonen som arvinger/testes ved at man har tilgang til Digitalt dødsbo som arving med formuesfullmakt. 

Varsling til DA avklares i drift/forvaltningssporet, men det er ikke teknisk mulig å motta arvinger uten dødsbo - siden det vi mottar fra DA er dødsbo med/uten arvinger.

**Comment by TageGitHub** [comment]
utgår da denne BH er ivaretatt i andre BH
