### ISSUE TITLE
Arving signerer for å ikke påta seg ansvar for avdødes forpliktelser

### ISSUE THREAD

**Issue by benedicteos** [Altinn/oed#273]
#### Brukerhistorie
**Intro**
Som en arving
ønsker jeg å signere for at jeg ikke påtar meg ansvaret for avdødes forpliktelser
slik at erklæring om privat skifte skal kunne sendes til behandling før 60-dagers fristen

**Krav/akseptansekriterier**  _(detaljering av BH med tilhørende akseptansekriterier)_
Gitt at..
Når ...
så skal ... 
og... 

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:

- [ ] Skifteattest utstedes ved utløpet av fastsatt frist (som normalt er 60 dager fra dødsdagen) til de arvinger som har påtatt
seg gjeldsansvaret. Skifteattest kan også utstedes om alle arvinger har påtatt seg gjeldsansvar. Arvinger som ikke ønsker å
overta gjeldsansvaret, kan samtykke til at skifteattest utstedes før 60-dagers fristen er utløpt. Slikt samtykke gis i dag på eget ark.
Er det også mindreårige arvinger, kan ikke skifteattest utstedes før vergene for disse har samtykket i privat skifte. Dette avtalerettslige samtykke hvor du velger å ikke signere for avdødes forpliktelser må håndteres i tjenesten. Er fortsatt arving. Veiledning må utarbeides i samarbeid med DA. 

Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by lillelars** [comment]
Denne håndteres i issues under #371. Lukker saken.

**Comment by TageGitHub** [comment]
Håndteres av #228
