### ISSUE TITLE
Hente opplysninger fra DA - rettslig grunnlag

### ISSUE THREAD

**Issue by tblix** [Altinn/oed#274]
Aktør:
- DA

Knytter seg til brukerhistorie:
#156

Beskrivelse: 
Det må sørges for at det eksisterer rettslig grunnlag for å oppheve taushetsplikt etter domstolloven, samt behandlingsgrunnlag for utlevering av personopplysningene til Altinn autorisasjon ved TE, samt behandlingsgrunnlag for behandling av personopplysningene i Altinn.

**Comment by lillelars** [comment]
Håndteres av #387. Lukker saken.
