### ISSUE TITLE
Hente info fra DA - krav fra Altinn Autorisasjon

### ISSUE THREAD

**Issue by tblix** [Altinn/oed#275]
Aktør involvert: 
- DA
- Altinn Autorisasjon

Knyttet til brukerhistorie: #156

beskrivelse:
Det må sørges for at krav fra Altinn autorisasjon om at de skal ha tilstrekkelig og god dokumentasjon knyttet til dataene, hva de ulike elementene betyr, kvaliteten, hvordan opplysningene er skapt og verifisert, hvilket rettslig grunnlag ligger bak dataene, hvordan kan de brukes iht rettslig grunnlag/avtale/tillatelse etc er oppfylt. Disse må spesifiseres og dokumenteres i samspill med ASF.

Frist:

**Comment by lillelars** [comment]
Håndteres av #387. Lukker saken.
