### ISSUE TITLE
Endring i GUI-kjøretøysside 

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#286]
Se design: https://eggedosis.github.io/oed/redirects/design/fortune/viechle/default-one-d.html

- [x] Sørge for at fonter har riktig størrelse

- [x] Sørge for at fonter skalerer riktig til mobil
- [x] Lenke på mobil skal ikke brekke lenken (ordmessig)
- [x] Minske linjeavstand i blått tittelfelt på mobil

- [x] Oppdatere til nye ikoner (eks. buss

**Comment by OlgaKoz** [comment]
@DanRJ Når bruker går inn på Kjøretøy siden, havner man alltid i midten av listen. Syns det er logisk hvis man havner i begynnelsen av listen når man klikker på overskriften, og på aktuelle kjøretøyet i listen hvis man trykken på den på hovedsiden.

**Comment by DanRJ** [comment]
Enig, man burde havne øverst på siden.
Det er ikke implementert at man kan trykke på et spesifikt element (eksempelvis ett spesifikt kjøretøy)

**Comment by DanRJ** [comment]
Da er "scroll to the top" funksjonaltiet på plass, men er ikke fan av koden, så må nok bruke litt tid på å se på den på et tidspunkt

**Comment by OlgaKoz** [comment]
Testet ok i Edge, Chrome, Safari, Firefox.
