### ISSUE TITLE
Utvikling av frontend for eiendomsside

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#287]
- [x] Ferdigstilling av design fra [Eiendom desktop](https://www.figma.com/proto/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=372%3A29070&scaling=min-zoom) og [Eiendom mobil](https://www.figma.com/proto/uXMQ9hTE747oy99MRCA58q/OED-%F0%9F%93%B1-mobile?node-id=565%3A4261&viewport=574%2C116%2C0.08896282315254211&scaling=min-zoom)
- [x] Kartlegge og mappe data fra API'et
- [x] Tester (enhet + accessibility)

**Comment by OlgaKoz** [comment]
@DanRJ Er enhetstester laget på denne?

**Comment by DanRJ** [comment]
Yes, med React testing library og accessibility tester via Cypress

**Comment by OlgaKoz** [comment]
Testet ok i Chrome, Safari, Firefox, Edge
