### ISSUE TITLE
Status på hva den enkelte arving har besluttet

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#29]
#30 Brukerhistorie:
Som en arving
ønsker jeg å se om de andre arvingene har signert, 
slik at jeg vet når erklæring om privat skifte sendes domstolene.

#### Forretningsverdi 2 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):
Relatert til #28 

Lenke til trådskisser:
Lenke til design: 
Lenke til arkitektur:
JÅB: Når sendes erklæring til domstolene ? Når sistemann har signert og det skjer da automatisk ? Hvem som helst kan trykke på en SEND-knapp når alle har valgt om de vil signere eller ikke ? Bare kontaktperson for bo kan trykke på SEND ? 

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
•	Jeg kan se status i aktivitetsloggen som innlogget bruker i Altinn dødsbo
•	Jeg kan se i liste over arvinger hvem som har signert (status for hver arving)

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by TageGitHub** [comment]
Videreført i #230
