### ISSUE TITLE
Synliggjøring av kontaktperson i boet

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#30]
Brukerhistorie:

> Som en arving 
> ønsker jeg at kontaktperson skal synliggjøres i boet 
> slik at at jeg vet hvem aktørerene kommer til å kontakte ved behov

**Comment by lillelars** [comment]
@JanAage99 trenger vi egentlig denne brukerhistorien for et MVP perspektiv? Er det kanskje like greit å avvente med denne og se ann etter eventuell brukertest er gjennomført?

**Comment by curlingnina** [comment]
@kajabystol etter hvert er det fint om du kan avklare med finansaktørene om de fortsatt har et reelt behov for en kontaktperson for boet.
