### ISSUE TITLE
Oppdatere landingssiden - desktop

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#300]
Relatert til BH: #308 

Se design:
https://www.figma.com/proto/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=1088%3A49384&viewport=4568%2C-12601%2C1.3522047996520996&scaling=min-zoom

- [x] Oppdatere main content GUI
- [x] oppdatere navigering mellom sider
- [ ] Responsivitet

**Comment by OlgaKoz** [comment]
Lukkes - foreldet. Taes ny design i neste sprint.
