### ISSUE TITLE
DAs informasjon til arvinger ved et dødsfall om Altinn dødsbo

### ISSUE THREAD

**Issue by benedicteos** [Altinn/oed#303]
#### Hva skal gjøres?
- [ ] Bør arvinger kunne få informasjon om hvor man kan finne ut mer om digitalt dødsbo evt. uten å logge seg inn på digitalt dødsbo?  Altså informasjon som ikke ligger i OED-app, men utenfor.? (Skjemaforside i Altinn)
- [ ] ..
- [ ] ..

**Comment by lillelars** [comment]
Håndteres i ny issue. #384
