### ISSUE TITLE
Oppdatere relasjoner med testbrukere

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#307]
Lenke til fil for testdata:

https://teams.microsoft.com/l/file/D34DBCC0-2E86-41F1-906D-AB6F2711FF49?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FTeknisk%2FTestbrukere.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

Relatert til brukerhistorie/epos: #
Lenke til design:

- [ ] .. 

- [ ] .. 

- [ ] ..

**Comment by OlgaKoz** [comment]
@HenningNormann 
Ståle Håv f.nr 02045900390 har ikke tilknytting til en avdød. Kan du knytte den til avdøde MULLER ODDVAR  04103300113?

**Comment by HenningNormann** [comment]
I spesifikasjonen står det at Ståle Hov skal kobles mot Jenny Hex. Dette skal meg bekjent fungere. Hvis det skal gjøres endringer, foreslår jeg at spesifikasjonen av testdata oppdateres.

**Comment by OlgaKoz** [comment]
Var ikke kjent med spesifikasjon. Det er ok å koble det til Jenny Hex.

**Comment by OlgaKoz** [comment]
Testet OK.
