### ISSUE TITLE
Landingsside 'oversikt formue gjeld'

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#308]
#### Brukerhistorie
Som arving
ønsker jeg å se landingssiden i Altinn dødsbo
slik at jeg får tilgang til løsningens funksjonaliteter og kan se noe kjerneinformasjon.

**Krav/akseptansekriterier** 
Gitt at jeg har logget meg på Altinn dødsbo.
Når jeg kommer til landingssiden 
så skal siden vise oversikt formue og gjeld ihht gjeldende design (se under)

**Utfyllende tekst**
Innhenting av data fra aktør skjer i annen bh

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: Gjeldende design:  https://eggedosis.github.io/oed/redirects/design/dashboard/concept-3.html

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
Akesptansetest: Godkjent

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by lillelars** [comment]
@TageGitHub klar for akseptanse

**Comment by TageGitHub** [comment]
overtatt av #235
