### ISSUE TITLE
Eiendom: gjenstående punkter

### ISSUE THREAD

**Issue by benedicteos** [Altinn/oed#309]
Gjenstående punkter innhenting av opplysninger om eiendom fra Kartverket #235 #39 

**Lagring**
- [ ] Det må vurderes om innhentede opplysninger skal lagres, etter første versjon. Formål med lagring kan være: vi ønsker å vise endringer i opplysningene til arving fra et oppslag til et annet, vi ønsker tilgjengelige opplysninger i fall Kartverket har nedetid (feilhåndtering), og for senere spørsmål knyttet til revisjon som tjenesteeier har ansvar for og dermed behov for historikk og logg, utover tidspunkt for når vi spurte. (Skal Kartverket eller TE ha ansvar for hvilke opplysninger ble gitt på konkret tidspunkt.) 

- [ ] Dersom innhentede opplysninger skal lagres, må vi beskrive hvor disse lagres.

**Adresse**
- [ ] Eiendommens adresse og eiers adresse er ikke en del av de API Kartverket har utviklet for Altinn dødsbo. Adresseopplysninger er ikke del av Grunnbok, de er en del av Matrikkelen. Vi må vurdere om arving har behov for eiendommens adresse og eiers adresse i Altinn dødsbo, eller om arving skal se disse opplysningene på Se eiendom.no? Adresser kan kanskje hentes fra Skatt, men må passe på fortrolig adresse.

- [ ] Postkode/postnummer. Hvis vi får seksjonsnr, idnr og lignende – kan vi ikke gjøre adresseoppslaget selv? Grunn til at det ikke er med nå, er fordi det er utlevering fra Grunnbok, adresse hentes fra Matrikkelen. Se ovenfor ang. Skatt

- [x] Dersom avdøde har rettigheter i egen eiendom, hvor det er tinglyst heftelser på en annens eiendom, skal arving få grunnboksinformasjon om adresse om den andre eiendommen? SVAR: JA. Du får rettsstiftelsestypen, registerenhetsretten og matrikkelenheten.

- [ ] Er borettslag sin adresse tilgjengelig fra Grunnbok og da inkludert i et av de to API-ene?  

- [ ] Har vi behov for bolignummer (som er en del av adresseopplysning fra matrikkel), og om så, kan det inkluderes i API? Eller skal evt arving se informasjonen i Se eiendom?

- [ ] Vurder om vi ønsker å innhente kommune (kommunenummer og kommunenavn). Er det tilstrekkelig med postnummer og sted på eiendommen? Skal vi ha kommunenavn, og ikke kommunenummer? Dersom vi ikke får adresse på eiendommen, så bør vi innhente kommune (?). 

- [ ] Fortrolig og strengt fortrolig adresse, hvordan håndteres dette i avgivelsen fra Kartverket og Matrikkelen? Adresse på en eiendom - selve adresseinformasjonen om en eiendom fra matrikkelen (som henter fra grunnboken) er åpen, jf § 3 2. ledd. Men ikke når det er fortrolig adresse. I tjenesten Altinn dødsbo vil det være en lenke til Se Eiendom, der er det listet opp all åpen eiendomsinfo, ikke fortrolig adresse. Hva står det i Se eiendom dersom det er fortrolig adresse? Hva om det lever personer på samme adresse som avdøde, som har vedtak om fortrolig adresse, har alle på samme adresse slikt vedtak? I og med at en personopplysning om en avdød person vil omfattes av lovens og forordningens regler hvis opplysningen samtidig er en personopplysning om en levende person. SVAR: personer med strengt fortrolig eller fortrolig adresse vil ikke være søkbare i grunnbok eller matrikkel. @lillelars - vi ønsker et eksempel på hvordan responsen ser ut derssom noen har fortrolig eller strengt fortrolig adresse? 

- [ ] FORUTSETNING: legger til grunn at dersom arving eller avdød har fortrolig adresse skal de ikke inn i OED - oppdateres i #168

- [ ] Hvordan skal vi håndtere visning av gnr, bnr, seksjonnr m.m i de tilfeller hvor avdøde, eller andre på samme adresse, levde/lever på fortrolig adresse? Disse opplysningene vil gi et eksakt koordinat på eiendommen

 > Oppdater brukerhistorie #39 etter møtet med Kartverket!

**Eiendomsopplysninger fra Skatt**
- [ ] Markedsverdi av boligen: er det en opplysning vi kan innhente fra Skatteetaten, men vise i underside Eiendom? 

- [ ] Ikke-tinglyste eiendommer: er det en opplysning vi kan innhente fra Skatteetaten, men vise i underside Eiendom? 

**Landbrukseiendom**
- [ ] Er det Landbruksdirektoratet eller Skatteetaten som kan avgi opplysning om avdødes landbrukseiendom, iht krav i arvelov/erklæring om privat skifte? Opplysningen skal bl.a gjenbrukes i erklæring om privat skifte, opplysningen bør være fra kilden - hvem er den korrekte kilden til informasjon om landbrukseiendom? Må gå opp hva krav i arveloven/erklæring om privat skifte er. 
- [ ] Foreløpig funksjonell diskusjon med Trude hos KV og Per Kristian hos LD har kommet fram til mulig løsning:
1. Kall mot etablert API fra KV returnerer hvilke Gnr/Bnr og Kommune, avdøde eide eiendommer i.
2. Gnr/Bnr og Kommune fra 1. Kall mot KV, brukes som input til framtidig API-kall mot landbruksreg. Dette framtidige API returnerer True/False dersom eiendom har over 5 dekar dyrket mark eller 25 dekar produktiv skog. 
Løsning over er en initiell skisse. Må gås opp juridisk, funksjonelt m.m. 

**Feilhåndtering**
- [ ] Det må beskrives hvordan feilhåndtering skal håndteres. Eksempelvis dersom Kartverket har nedetid. Behovsteam må delta i spesifisering av akseptansekriterier. 

**Opplysninger fra Matrikkelen som vi ønsker**
- eiendelsbrøk
- alle eiere
- Ulike enheter fra Matrikkelen - ikke bare registerenheter fra Grunnboken: Hus, leiligheter som ligger i matrikkelen, fritidsbolig, andre?

**Heftelse**
- [ ] heftelse (rettigheter og plikter) i annen eiendom enn avdøde var eier av. Feks tinglyst veirett, vil denne rettigheten avdøde har i en annen eiendom fremkomme av grunnboksbladet på eiendommen til den avdøde? Eller vil det kun fremkomme på grunnboksbladet til den eiendommen hvor heftelsen påhviler? 

- [ ] I responsHeftelse: får man informasjon om rettigheter og heftelser andre (personer, eiendommer, virksomheter) har i avdødes eiendom?

- [ ] Er alle rettigheter (også personlig bruksrett til annen persons eiendom) tinglyst på grunnboksbladet til avdøde, eller er det kun registrert på personnummer, og så sammenstiller Kartverket slik at HeftelseRespons er en sammenstilling av grunnboksbladet til avdøde og annen informasjon på personnummer til avdøde?

- [ ] Hvordan sikrer vi at en eiendom som i Kartverket er oppført som heleid av avdøde, men som i realiteten er i sameie med andre (søsken, ektefelle el.) eller der en nabo har veirett, rett til brygge etc., ikke vil gi arvingene misvisende informasjon? Ev. leder til avhending av annens eiendom etc? -> Informativ tekst til arving @kaja

- [ ] Når arving gjør oppslag (søk) på avdødes fødselsnummer, så får man treff på hvilke matrikkelenheter/borettslagsandeler vedkommende eier, samt hvilken registerenhetsrettstype det er. (det vil si at arving får opp eiendomsidenten, gnr/bnr/fnr/snr,), hvilke heftelser vedkommende er AKTIV rettighetshaver til - for følgende rettstyper; SR, SP, AH, RE, CR, PE, FL, OB, CP, HL, CS, CN (dette er forkortelser for rettigheten, og arving vil få opp navnet på rettigheten, ikke koden) og hvilke heftelser vedkommende er AKTIV saksøker i - for følgende rettstyper TV, CT, TL, CU, CM. Hva betyr saksøker i dette tilfellet? Er man aktiv saksøker også etter død? Hva om motsatt, at noen saksøker avdøde, hvor er den informasjonen? 

**Ved manglende opplysninger**
- [ ] hvordan skal det presenterers dersom det ikke finnes informasjon? det kan være flere scenarioer, f.eks at det faktisk ikke finnes noe informasjon, eller at grensesnittene er nede. 
- [ ] Skissere opp de ulike alternativene@kajabystol og @juliearving1 

**JSON-fil knyttet til API**
- [ ] Trenger mer innsikt i begrepsbruk

**Bistand fra Kartverket**
- [ ] Kvalitetssikre veiledningstekst
- [ ] Kvalitetssikre hjelpetekst
- [ ] Bistand på beslutningsstøtte

**Comment by kristoffervp** [comment]
Evt. videre avklaringer logges i #234
