### ISSUE TITLE
Informasjon om videre prosess hvis en arving ikke godtar skifte

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#31]
#31 Brukerhistorie:
Som en arving
ønsker jeg god informasjon om hva som skjer hvis ikke alle arvinger godtar skifte 
slik at jeg kan planlegge prosessen videre i arveoppgjøret.

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:
JÅB: Hva vil forskjellen bli i OED app mellom ikke å signere for gjeldsansvar og å ikke godta skifte ? En og samme operasjon eller må det skilles på dette i to distinkte opreasjoner av sluttbruker/arving ? 

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
•	Jeg kan se status på hva de andre arvingene har besluttet
•	Jeg kan se informasjon om prosessen videre
•	Jeg kan henvises til domstolen for mer informasjon
•	Jeg kan se estimert tid før arveoppgjøret kan fortsette
•	Jeg kan ikke komme videre i prosessen før tidsfristen har gått ut 

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by benedicteos** [comment]
denne henger vel sammen med #28 ? Det vi mener med denne brukerhistorien er ren informasjonstekst om skifteprosessen?

**Comment by TageGitHub** [comment]
Videreføres i #224
