### ISSUE TITLE
Inngang "Bli kjent med dine rettigheter"

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#311]
Relatert til brukerhistorie/epos: #125

Se design: https://www.figma.com/proto/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=1395%3A55676&viewport=-23511%2C-1551%2C0.6027415990829468&scaling=min-zoom&page-id=372%3A0

- [x] Implementering

- [x] testing

- [ ]

**Comment by OlgaKoz** [comment]
Testet på Mac i Chrome - ok
Laget en oppfølgingssak til Kaja og Julie
