### ISSUE TITLE
Implementering av underside for informasjon 

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#312]
Relatert til brukerhistorie/epos: #152 #265 og #151

TIPS Til @DanRJ : Husk å del opp denne oppgaven dersom det dukker opp nytt design el.lignende

Lenke til design: 
https://eggedosis.github.io/oed/redirects/design/rights/default-one-d.html

- [x] Legg inn tekster om testament
- [x] Legg inn tekster om arvinger
- [x] Legg inn tekster om rettigheter
- [x] Lag felles komponent for informasjonsinnhold (grå bakgrunn, tittel og innhold)
- [x] Lag komponent for dropdown (undersøk hva som finnes fra før av)

**Comment by lillelars** [comment]
Seksjon for: "Formuesfullmakt for arvinger" finnes både under "ARVINGER" og "TESTAMENT"
Dette er vel ikke helt riktig
![image](https://user-images.githubusercontent.com/39513382/116515207-420ee800-a8cc-11eb-8152-3d452f7da6bb.png)

**Comment by OlgaKoz** [comment]
Jeg har observert at
1) Teksten under "Formuesfullmakt for arvinger" ble gjentatt i neste seksjon "Arv etter slektskap og sivilstand". - Teksten i "Arv etter slektskap og sivilstand" må slettes.
2) I listen over slektskap har "Samboers arverett" og "Ektefellers arverett" byttet plass - i designskisser står Ektefellers... først og så Samboers...
<img width="1535" alt="Skjermbilde 2021-04-29 kl  13 21 53" src="https://user-images.githubusercontent.com/82213706/116543451-2b798880-a8ee-11eb-9820-449719803f2a.png">

**Comment by DanRJ** [comment]
Ref alle spørsmål tilknyttet tekster er alt basert på selve designet i figma, jeg avklarte med @juliearving1 om jeg skulle bruke trådskissene eller designet ettersom de ikke stemte overens, og for denne oppgaven ble det bestemt at vi gikk for designet i figma.

Kan være at man skal lage en restans oppgave for å endre til trådskissene.

**Comment by OlgaKoz** [comment]
Ok! Skal avklare det. Jeg syns det er bør ikke stå samme tekst i to bokser rett etter hverandre. 
Men rekkefølgen da. Den er vel feil likevel.

**Comment by juliearving1** [comment]
Stemmer det Daniel sier, og det er en glipp fra meg at samme tekst står på to steder. I brukerhistorie #305 har vi i behovsteamet gjenstående punkter som handler om å utarbeide manglende tekst og kvalitetssikre tekstene som står på disse informasjonssidene. Dette tar vi for oss i neste uke, så det vil komme tekstlige oppdateringer. Håper dette oppklarte litt.

**Comment by OlgaKoz** [comment]
Testet OK i Safari, Chrome, Edge, Firefox; Mac, Win 10, iPhone, Android.
