### ISSUE TITLE
Formuesfullmakt og maskinporten - Skatteetaten

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#318]
**Egenskap**
Informasjon fra Skatteetaten hentes automatisk til Altinn dødsbo når en arving med formuesfullmakt har logget seg på.

**Krav/akseptansekriterier** 
Gitt at en arving med formuesfullmakt har logget seg på Altinn dødsbo og token for tilgang til Skatteetatens system er hentet fra Maskinporten.
Når informasjon hentes fra Skatteetaten
så skal en forespørsel om dette sendes fra Altinn dødsbo til Skatteetatens system
og
informasjonen som mottas gjøres tilgjengelig for arvingen
og
informasjonen lagres og kan gjenbrukes dersom det ikke fås kontakt med aktør ved neste gangs pålogging av arving.

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 

- [ ] Hva trenger skatt av data fra Altinn dødsbo for å returnere informasjon? 
- [ ] Trenger skatt å vite hvem formues fullmektig er?

- [ ] Ønsker aktør en eksplisitt beskjed om at forespørselen er kommer fra person med formuesfullmakt, eller er det ok at aktør godtar en implisitt formuesfullmakt, dvs at når en forespørsel kommer fra Altinn dødsbo så har Altinn dødsbo allerede godkjent aktøren med tilhørende formuesfullmakt?

Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
- [ ] Hvilken overføringsmekanisme brukes for å hente data fra aktør (pull/push)? (tb) DAN
Dokumentasjon:
- [ ] Legg inn link til API beskrivelsen

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:

- [ ] Det må avklares med Skatteetaten om implisitt formuesfullmakt uten videreformidling til Skatt er ok.
- [ ] Det må avklares om mottak av opplysningene bryter mot lovverk som Skatteetaten er underlagt.
- [ ] Det må avklares om informasjon vi mottar er personopplysninger.
- [ ] Avklare om Altinn dødsbo må ha fullmakt fra arving
- [ ] Er det noe implikasjoner knyttet til at Altinn dødsbo lagrer informasjon fra aktører til bruk i tilfeller der forbindelsen til aktør er nede.

Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Test (sprint)
**Funksjonelt**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**System**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Integrasjon**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Comment by TageGitHub** [comment]
status uklar. Ikke akseptansetestet

**Comment by TageGitHub** [comment]
@erlendoksvoll @elsand @DanRJ @CecilieFjellsoy 
Oppdatert med avklaringer pr 23.03.2023

**Comment by AinaEngen** [comment]
Er duplikat - testes av #187.  Lukker denne.
