### ISSUE TITLE
Delegering av roller og rettigheter

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#32]
#### Brukerhistorie
**Intro**
Som en arving 
ønsker jeg å delegere min rolle som arving
slik at representant kan utføre oppgaver på vegne av meg i det digitale dødsboet

**Krav/akseptansekriterier**
Gitt at  
Når 
så skal 
- Jeg bruker fødsels-og personnummer til vedkommende som input
- Jeg kan bekrefte at jeg gir denne personen fullmakt
- Jeg kan se en bekreftelse på verifisert person med fullmakt som har mulighet til å håndtere boet på mine vegne

**Utfyllende tekst**
JÅB: Ref Benedikte sin kommentar under. Vi bør bare sørge for at denne rollen ikke er delegerbar da delegering ikke skal støttes. 

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder: 

Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by kajabystol** [comment]
Delegering av rollen. Vil DA akseptere at rolle/ arving er mulig å delegere

**Comment by benedicteos** [comment]
Vi må benytte arving, ikke livsarving. Er heller ikke sikker på om vi som tjenesteeier ønsker at denne rollen Arving skal være delegerbar. Blant annet siden rettighetene til en arving er direkte knyttet til arvingen selv,  feks formuesfullmakten, utleveringsforskriften etc, mtp grunnlaget vi skal benytte for å innhente opplysninger, aktørene taushetsplikt m.m.. I tillegg vil det bli kronglete rettsgrunnlag å skape for å vise personopplysninger til den det er delegert til fra arving, til andre arvinger, og vi må ha med informajson om delegeringen ut, osv. Tror vi bare bør dokumentere at rollene i Altinn dødsbo IKKE skal være delegerbar, og det er veldig viktig at vi får det med i etableringen av rolle- og rettigheter i autorisajson. @lillelars @kajabystol @curlingnina @JanAage99

**Comment by TageGitHub** [comment]
Videreføres i #176 og #175
