### ISSUE TITLE
Motta data - Bankene

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#320]
#### Egenskap
Informasjon fra banker ( aktuelle dersom kundeforhold: Sparebanke1, DnB og Nordea) hentes automatisk dersom kriterier er oppfylt (se under).

**Krav/akseptansekriterier** 
Gitt at en med tilgang til DD og som i) har formuesfullmakt før skifteattest er utstedt, eller ii)  har med skifteattest, eller iii) er skiftefullmektig til en med skifteattest, logger seg på DD.
Når informasjon hentes fra bankene
så skal en forespørsel om dette sendes fra DAN til bankenes system
og
informasjonen som mottas gjøres tilgjengelig for arvingen i DD
og
det skal ikke forespørres eller hentes data fra banker der den døde ikke har et kundeforhold.

(Utgår: informasjon lagres i DD slik at den kan gjenbrukes der dersom informasjonen ikke kan hentes fra aktør ved neste gangs pålogging eller lagring skjer for å kunne vise ved ev. manglende utstedt skifteattest til arving 16/5 24 (tage) utgår oktober TB 22/8 2024)

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
Kan det mottas data fra banker etter at skifteattest er utstedt? tb 22/8 2024

Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a): OK
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
- [ ] Ønsker aktør en eksplisitt beskjed om at forespørselen er kommer fra person med formuesfullmakt, eller er det ok at NP godtar en implisitt formuesfullmakt, dvs at når en forespørsel kommer fra DAN så har Altinn dødsbo allerede godkjent aktøren med tilhørende formuesfullmakt?
- [ ] Hvorfor kan ikke Digdir godta ikke syntetiske data fra DnB?
Dokumentasjon:

- [ ] Legg inn link til API beskrivelser (pr bank)

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:

- [ ] Må vi ha egne avtaler med alle småbanker eks SP1?

Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Test (sprint)
**Funksjonelt**
Akseptert (j/n): n
Avvik:
- [ ] Trenger test case der informasjon gis til arving i DD dersom kommunikasjonen til en aktør er nede. (cec 16/24)
- [x] @erlendoksvoll Kan du bekrefte at vi nå er enig med bankene og har implementert henting av data fra bank slik det er beskrevet i brukerhistorien.
- [1] Trenger testdata fra bankene som er med i samarbeidet, ønsker data også når det ikke registrert et bankforhold på den døde, (tb 16/5 24)

**System**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Integrasjon**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Comment by TageGitHub** [comment]
@erlendoksvoll @elsand @DanRJ @CecilieFjellsoy 
Oppdatert med avklaringer pr 23.03.2023

**Comment by erlendoksvoll** [comment]
@TageGitHub vi lagrer ikke data fra bankene, jf juridiske vurderinger

**Comment by TageGitHub** [comment]
erstattes med #249
