### ISSUE TITLE
Tekst mangler på "Bli kjent med dine rettigheter"

### ISSUE THREAD

**Issue by OlgaKoz** [Altinn/oed#321]
#### Hva skal gjøres?
- [ ] Her trenges det tekst 
<img width="349" alt="Skjermbilde 2021-04-20 kl  12 25 15" src="https://user-images.githubusercontent.com/82213706/115381207-a0084500-a1d3-11eb-8ba3-383f8f1a82c3.png">

- [ ] ..
- [ ] ..

**Comment by lillelars** [comment]
Lukker denne. Håndteres i #384
