### ISSUE TITLE
Videreutvikle landingssiden m/ banner og overskrift

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#327]
Se design:
https://eggedosis.github.io/oed/redirects/design/dashboard/concept-3.html

Mobil: https://eggedosis.github.io/oed/redirects/design/dashboard/concept-3-one-m.html

Relatert til #144 

- [x] Overskrift m/ ingress 1t
- [x] Banneren bak 12t
- [x] Responsivitet  6t
- [x] Hindre at banner blir med til andre sider 3t

Jeg startet på denne på mandag og jobbet med den aktivt frem til idag torsdag(29.4).
Jeg har brukt ca 21t (6t per dag) og vi har en [restanse på hindring av banner blir med til....](https://github.com/Altinn/oed/issues/332)

**Comment by OlgaKoz** [comment]
Testet ok på Edge, Chrome, Firefox, Safari, iPhone, Mac, Win 10, Android
