### ISSUE TITLE
Eiendomssiden - legge til rettigheter, oppdatere design med mer

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#328]
Se [design](https://www.figma.com/proto/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?page-id=372%3A0&node-id=2195%3A1838&viewport=1156%2C-54%2C0.3307258188724518&scaling=min-zoom)

Relatert til brukerhistorie/epos: #39 
Lenke til design:

- [x] Varsling/informasjonsboks i blått (1h)
- [x] Oppdatere design side for eiendom - desktop 12t
- [x] Fiks informasjonsboksens farger
- [x] Endre farge på tekst, fra sort til blå
- [x] Oppdatere design side for eiendom - mobil 3t
- [x] Implementere seksjon for rettigheter - backend - 3t

Timer:
Torsdag 29.04 3t
Fredag 30.04 4t
Mandag 3.05 6t
Tirsdag 4.05 6t
Onsdag 5.05 6t
Torsdag 6.05 6t
Fredag 07.05 6t (3t på en bug med vag feilmelding)

**Comment by OlgaKoz** [comment]
Hallo @DanRJ ! Ser det mangler seksjon "Viktig å vite før valg av skifteform".
<img width="1434" alt="Skjermbilde 2021-05-25 kl  12 40 17" src="https://user-images.githubusercontent.com/82213706/119485650-a00dde80-bd57-11eb-9848-54aa7376f7d2.png">

**Comment by DanRJ** [comment]
Ja, bra funnet!

Lene og Julie og jeg ble enige om at den er ikke en del av oppgaven da den er fortsatt under arbeid / utenfor scope av oppgaven.

**Comment by OlgaKoz** [comment]
@DanRJ Det er også forskjellig tekst i  informasjonsbobla i Eiendom- seksjonen. Det er Implementert  "Beregnet formuesverdi hentet fra Skatteetaten" men i skissen er det "Her vises beregnet markedsverdi av hele eiendommen".

**Comment by DanRJ** [comment]
Mhm, tenker du på den gule boksen? Jeg tenker tekstlig innhold generelt i løsningen (såfremt de ligger på korrekt plass) burde fikses på et senere tidspunkt da det er mye tekster under arbeid og mye som ikke betyr noe. Hva tenker dere, @OlgaKoz @LeneSundsbo @juliearving1 ?

**Comment by OlgaKoz** [comment]
Nei, jeg mener teksten under spørsmålstegnet som dukker opp ved mouseover.

**Comment by LeneSundsbo** [comment]
@DanRJ Ja, enig. Viktigst nå er at vi har tekstbokser. Tekstene vil med stor sannsynlighet oppdateres og poleres på et senere tidspunkt, så det er helt greit for meg at vi flicker på dette når vi har vasket alle tekster.

**Comment by OlgaKoz** [comment]
Testet Ok i Chrome, Safari, Edge, Firefox. OS: Mac, Win10, Android, iOS
