### ISSUE TITLE
Restanse - underside av informasjon

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#329]
Relatert til brukerhistorie/epos: #
Lenke til design: https://eggedosis.github.io/oed/redirects/design/rights/default-one-d.html

Bulletpoints på "Skifteform":

- [x] Avsjekk med Nina (ressurs filene har mulighet for Markdown)
- [x] Skriv et lite script som håndterer bulletpoints (Vi bruker Markdown)
- [x] Verifiser at dette ser bra ut

- Vurdere hva Altinn har gjort?
- Vurdere mulighet for å parse tekst på en annen måte (Vi går for Altinns måte å gjøre dette på som er med Markdown)

3t

**Comment by DanRJ** [comment]
Innspill, det er ganske tungvint å bruke Markdown i tekstene og slet med å bruke <br /> vs \n.
Markdown etter <br/> ble ikke lest som Markdown men etter \n ble det lest som Markdown

**Comment by OlgaKoz** [comment]
Testet OK i Safari, Chrome, Edge, Firefox; Mac, Win 10, iPhone, Android.
