### ISSUE TITLE
Informasjon om behandlingstid av erklæring om privat skifte

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#33]
**Brukerhistorie:**
Som en arving
ønsker jeg en tilbakemelding på estimert behandling av erklæring om privat skifte
slik at jeg vet når arveoppgjøret kan starte

#### Forretningsverdi 2 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design: 
Lenke til arkitektur:

**Godkjent Juridisk (OK // N/A // Ikke godkjent)**
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
•	Jeg får en bekreftelse på signering av skifte
•	Jeg kan se estimert behandling fra domstolene hvor lang tid det tar å behandle
•	Jeg kan ikke gå videre i prosessen. Dvs steg som kommer etter ustedelse/mottak av skifteattest som feks valg av fullmektig kan ikke påbegynnes før skifteattest er klar.  

#### TODO
- [ ] Avklare om tingretten kan informere om estimert behandlingstid i hver enkelt sak
- [ ] Skal dette heller være en kvittering for innsendelsen til tingrett, hvor vi legger på informasjon om estimert behandlingstid i tillegg til kvitton? Må se på akseptsansekriteriene når vi har avklart dette. 

Forbehold/avklaringer
- Er dette informasjon domstolene burde være master for ? Skal det være et løpende estimat basert på domstolenes faktiske kapasitet til enhver tid eller mer standard tekst som kommer fra domstolene ?

**SCENARIO X:**

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by TageGitHub** [comment]
Videreført i #228 , #176
