### ISSUE TITLE
BUG: Hele bilde flytter seg ved klikk på ulike undersider

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#331]
Gjenskap:
Testet i Chrome:
1) Trykk på "Arvinger", trykk deretter på "Testament"
2) Se at hele bildet forskyver seg noen piksler. Dette bør være helt i ro.
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/c131c00a-74ad-4394-b639-a54fb4f3dfe5)

**Comment by DanRJ** [comment]
Etter nærmere research, så er denne oppgaven større enn forventet, vi får ta en nærmere titt på denne, reestimere og få implementert dette en annen gang.

**Comment by lillelars** [comment]
Dette ser ut som er løst. @OlgaKoz vil du verifisere?

**Comment by OlgaKoz** [comment]
@lillelars  @DanRJ Bildet beveger seg fortsatt på Win10 både i Chrome, Edge og Firefox. Men på Mac det er løst - Chrome og Safari.

**Comment by DanRJ** [comment]
Denne faller ut når vi flytter undersidene inn på veilederen. Kan lukkes? @kristoffervp

**Comment by kristoffervp** [comment]
Kan være vi likevel vurderer å beholde undersidene, på tross av at mye av informasjonen flyttes til hovedappen. 

Avventer til siste versjon fra Cecilie og designteamet.

**Comment by DanRJ** [comment]
Utgår pga legacy og nytt design
Avtalt med Kristoffer
