### ISSUE TITLE
Restanse / kodegjeld - Banner, flytt logikk til redux istedenfor å bruke callbacks

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#332]
Da banner ble implementert, måtte man ha en måte å fjerne banneret på, for undersider som ikke skulle ha banneret.
For effektivitetens del, ble det implementert callback slik at children komponenter kunne endre state'n til parent komponenter.
Dette burde legges i redux istedenfor å bruke callback metoder.
Relatert til brukerhistorie/epos: #327

- [x] Flyttet callback logikken til React Context

6t, funka ikke med context, deretter ikke med redux, deretter fungerte det med redux også context

**Comment by OlgaKoz** [comment]
Testet OK i Safari, Chrome, Edge, Firefox; Mac, Win 10, iPhone, Android.
