### ISSUE TITLE
Utfylling av

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#338]
#### Brukerhistorie
Som arving 
ønsker jeg å fylle ut erklæring om privat skifte
slik at denne kan sendes inn til DA for behandling

**Funksjonelle Krav/akseptansekriterier** 
Gitt at jeg har valgt privat skifte.
Når jeg går videre i løsningen og ønsker å fylle ut erklæring om privat skifte
så skal feltene tilsvare de som er i oppdatert versjon av 'erklæringen om privat skifte av dødsbo' (se under)
og
det skal fylles ut ett skjema pr arving
og
DA gjør sammenstillingen om hvilke arvinger som har valgt privat skifte samt har tatt på seg gjeldsansvar.

**Kvalitetskrav/akseptansekriterier** 
Gitt at..
Når ...
så skal ... 
og... 

**Utfyllende tekst**
Arbeidshypotese: Det fylles ut en erklæring om privat skifte pr. arving i Altinn dødsbo. Disse sendes separat til DA.

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 

Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:

Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Test**
Systemtest i sprint: 
Akseptanse sprint:
Integrasjonstest (sprint):

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Åpne punkter - lukkes før sprint

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Annet

---

**Comment by lillelars** [comment]
Dekkes av #371
