### ISSUE TITLE
Varsel om at erklæring om privat skifte er ferdigbehandlet

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#34]
**Brukerhistorie:**
Som en arving
ønsker jeg å få et varsel når erklæring om privat skifte er ferdig behandlet 
slik at jeg kan starte arveoppgjøret

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:
JÅB: Jeg leser denne brukerhistorien som mottak av digital skifteattest. Standard Altinn-varsel sendes ut til arvinger/interessenter når denne skifteattesten er klar. 
Relatert til #90 

**Godkjent Juridisk (OK // N/A // Ikke godkjent)**
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
•	Jeg får et varsel om behandlet skifte 
•	Jeg kan se informasjon om 
- besluttet skifteform
- hvem som har rett til å arve hva  (bla testamentsarving)
- hvem som har påtatt seg gjeldsansvaret
- annen nødvendig informasjon om boet (eks: skifteattesten gjelder hele eller deler av boet)

**SCENARIO X:**

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by TageGitHub** [comment]
Videreføres i #221
