### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#340]
Implementer footer som vist i skissene, denne kommer garantert til å endre seg derfor vil det være unødvendig å legge mye tid inn i denne per nå.

Lenke til design:
[Bla nederst til footeren](https://www.figma.com/proto/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=1395%3A55676&viewport=-23511%2C-1551%2C0.6027415990829468&scaling=min-zoom&page-id=372%3A0)

- [x] Implementer footer

Det tok ca 2t

**Comment by OlgaKoz** [comment]
Testett Ok i Chrome, Safari, Edge, Firefox. OS: Mac, Win10, Android, iOS
