### ISSUE TITLE
Brødsmuler på undersider for å finne veien tilbake

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#342]
Implementer brødsmuler for undersider
Lenke til design:
[Brødtekst](https://www.figma.com/proto/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=372%3A28950&viewport=-23511%2C-1551%2C0.6027415990829468&scaling=min-zoom&page-id=372%3A0)
- [ ] Implementer brødtekst

**Comment by OlgaKoz** [comment]
Testett Ok i Chrome, Safari, Edge, Firefox. OS: Mac, Win10, Android, iOS
