### ISSUE TITLE
Inngang for oppgaven skifteerklæring

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#344]
Relatert til brukerhistorie/epos: #223 
Lenke til design:
[Forsiden som inneholder inngangen til skifteerklæringssiden](https://www.figma.com/proto/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=1395%3A55676&viewport=-23511%2C-1551%2C0.6027415990829468&scaling=min-zoom&page-id=372%3A0)

- [x] Oppgaven for inngangen fra landingssiden
Det tok ca 6t + footer

**Comment by DanRJ** [comment]
Lene og jeg ble enige om at dette dekker behovet for nå.
![chrome-capture (5)](https://user-images.githubusercontent.com/3437949/119646596-a1a2d980-be1f-11eb-8040-27050f240f8b.gif)

**Comment by OlgaKoz** [comment]
Testet på Chrome, Safari på Mac; Chrome, Edge, Firefox på Win10; Android og iOS
