### ISSUE TITLE
Skjelett av siden "erklæring om privat skifte av dødsbo"

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#346]
Beskrivelse av oppg: Begynne på siden om erklæringen for privat skifte
Relatert til brukerhistorie/epos: #343

Lenke til design:
https://eggedosis.github.io/oed/redirects/design/tasks/probate-default-d.html

- [x] brødsmulesti
- [x] tekster
- [x] styling?/Markdown??

Kommentar:
Det ble lagt til støtte for markdown filer, med variabler og html, slik at man kan inserte data og ha custom css.

Tok ca 18t

Til info:
Relasjoner tilknyttet avdøde er statisk da vi ikke får slik informasjon fra DA.
Med det menes da ektefelle / samboer / relasjon til arvinger o.l.
Det samme gjelder landbruk og testamente spørsmålene.
Knappene gjør ingenting per nå

**Comment by OlgaKoz** [comment]
Ser det er forskjell på implementering og skissen. Lurer på om skissen er oppdatert? 
<img width="1326" alt="Skjermbilde 2021-06-04 kl  11 35 48" src="https://user-images.githubusercontent.com/82213706/120784357-48782b80-c52c-11eb-9706-98fe32d9679a.png">

**Comment by OlgaKoz** [comment]
@DanRJ 😄 
Nå har Lene oppdatert skissen. Her er hva som bør endres:
1 - mangler "/dødsbo" 
2 - Navnet til påloggede/arving bør være i samme farge som altinn-ikone
3 - Fargen på linja på knappen "jeg ønsker ikke å signere" er rød
4 - overskriften bør endres
5 og 6 - til oppfølging for oss fremover
<img width="1461" alt="Skjermbilde 2021-06-04 kl  14 07 06" src="https://user-images.githubusercontent.com/82213706/120799918-a06c5d80-c53f-11eb-950f-6191712433da.png">

**Comment by DanRJ** [comment]
Supert!

1. og 2. er tilknyttet header, det er ikke en del av denne oppgaven, men det er absolutt noe vi burde se på og diskutere. Jeg fikser derimot 2. ettersom det er en liten fiks. /dødsbo må diskuteres.
2. er fikset
3. er fikset
4. er fikset

5 og 6 tar vi som oppfølging, som du skriver.

**Comment by OlgaKoz** [comment]
Testet Ok
