### ISSUE TITLE
Norsk pensjon side

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#347]
Implementer design som ligger her:

Relatert til brukerhistorie/epos: #297 Utvikling av pensjonssiden
Lenke til design:
[Design](https://www.figma.com/proto/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=3200%3A66192&viewport=-23511%2C-1551%2C0.6027415990829468&scaling=min-zoom&page-id=372%3A0)
Designet kan også lokaliseres i figma ved å gå fra forsiden inn til forsikring.

- [x] Utvid / fiks modeller fra vår app, gjør de brukbare for frontend
- [x] Implementer boksene
- [x] Legg til statiske tekster
- [ ] Finn ut av navnet på feltet som skal beskrive kategoriene og legg det til (out of scope)

**Comment by OlgaKoz** [comment]
Testet Ok
