### ISSUE TITLE
Fiks forsiden mtp. forsikring og pensjon

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#348]
Fiks slik at forsikring og pensjon vises korrekt på forsiden
Relatert til brukerhistorie/epos: #297
Lenke til design:
[Design](https://www.figma.com/proto/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=1395%3A55676&viewport=-23511%2C-1551%2C0.6027415990829468&scaling=min-zoom&page-id=372%3A0)

- [x] Vis forsikring og pensjon korrekt
- [x] Vis antall forsikringer / poliser i navigasjonen
- [x] Pass på at man kun kaller 1 gang

**Comment by DanRJ** [comment]
La til slik at kall mot SVV, kartverket og norsk pensjon kun vil skje en gang uansett hvor man navigerer seg i løsningen, selv når man går inn på en underside og tilbake til forsiden.

**Comment by OlgaKoz** [comment]
Testet ok i Chrome, Edge, Firefox, OS: Mac, Win10, Android, iOs
