### ISSUE TITLE
Bruker skal se informasjon om at det finnes testament registrert i testamentregisteret

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#35]
#### Brukerhistorie:
Som en arving 
ønsker jeg informasjon om det finnes et testamente i testamentregisteret
slik at jeg tar hensyn til dette i skifteoppgjøret 

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur: 

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- Jeg kan lese informasjon fra tingretten at det ikke finnes et testamente (NEI)
- Jeg kan se informasjon fra Altinn dødsbo at testamente kan oppbevares andre steder enn hos DA

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Avklaring/forutsetning:**
- Gitt scenario 1 skal det IKKE foreligge et testamente
- Vi/OED sender denne informasjonen om man er kjent med et originalt testamente (JA/NEI/VET IKKE) til DA via notifikasjon/API

**SCENARIO X Akseptansekriterier (minimum happy-case):**
- Jeg kan lese om testamente, og hvilken betydning det har for skifteoppgjøret
- Jeg kan lese informasjon fra tingretten om det foreligger testamente JA/NEI
- Hvis ja, kan jeg ikke lese selve testamente, men informasjon om å ta kontakt med aktuell tingrett for videre prosess

TODO

**Comment by benedicteos** [comment]
Riktig tittel her er vel nattbordstestament, at arving skal kunne informere om at det foreligger nattbordstestament?

**Comment by TageGitHub** [comment]
Slått sammen med #182
