### ISSUE TITLE
Vise indikator nattbordtestament

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#353]
#### Brukerhistorie
Som arving 
ønsker jeg å 
slik at ...

**Funksjonelle Krav/akseptansekriterier** 
Gitt at..
Når ...
så skal ... 
og... 

**Kvalitetskrav/akseptansekriterier** 
Gitt at..
Når ...
så skal ... 
og... 

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Test**
Systemtest i sprint: 
Akseptanse sprint:
Integrasjonstest (sprint):

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Åpne punkter - lukkes før sprint

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Annet

---

**Comment by lillelars** [comment]
Duplikat av #354

**Comment by TageGitHub** [comment]
Hånderes av #352
