### ISSUE TITLE
Flere arvinger på 1 dødsbo krasjer løsningen pga bug i siste aktiviteter

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#356]
Feilen oppstår hvis en avdød har flere arvinger.
Det skjer pga Siste aktiviteter der man henter ut person og partyId men finner ikke person eller partyId.

**Gjenskape feilen**
Steg for å gjenskape:
1.  Gå til en instans av OED som innehar flere arvinger
2.  Den krasjer 

**Skjermdump av feilen**
![image.png](https://images.zenhubusercontent.com/5d765941eb71d10001e81ae7/b79f0f0e-57b8-44c9-bd3e-19b3cbfcbefb)

**Comment by DanRJ** [comment]
Fikset ved å bytte fra parties til datamodellen, der vi henter ut arvtakere og finner ut hvem av de er tilknyttet hvilken party id

![image](https://user-images.githubusercontent.com/3437949/121877263-bc73ba00-cd0a-11eb-9da9-67bbbf9496eb.png)

**Comment by OlgaKoz** [comment]
Testet ok
