### ISSUE TITLE
Kjøretøysiden krasjer pga mystisk eier

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#358]
Feilen er som følger:
Hvis vi mottar mellomrom (som det skjer i dette tilfellet) på eier feltet, vil frontend krasje.
Det er nå fikset slik at hvis vi mottar mellomrom som navnet på eier, vil vi vise en tom streng, mao. vi viser ingenting i eier feltet.

**Comment by OlgaKoz** [comment]
Testet ok
