### ISSUE TITLE
Feilretting: Kjøretøy uten eier vises i oppgjøret

### ISSUE THREAD

**Issue by OlgaKoz** [Altinn/oed#359]
**På kjøretøysiden vises det blant annet kjøretøy uten oppgitt eier eller medeier**

**To Reproduce**
1. Hent opp oppgjør etter Trones Niclas
2. Gå til kjøretøysiden

**Expected behavior**
Kjøretøy som tilhører avdøde skal vises. Avddøde skal stå som eier eller medeier

**Screenshots**
![Skjermbilde 2021-06-22 kl. 10.19.40.png](https://images.zenhubusercontent.com/60780fbb8c86432adea47a17/01ef89da-bc08-4886-a7fa-a2ae00f14eb7)

**Comment by DanRJ** [comment]
Denne er fikset slik at det står "Ingen" innunder eier hvis eierfeltet er mellomrom eller tomt.
Ref #358

**Comment by kristoffervp** [comment]
@AinaEngen denne kan retestes

**Comment by kristoffervp** [comment]
@AinaEngen klar til retest

**Comment by AinaEngen** [comment]
Får fortsatt samme feil som opprinnelig innmeldt feil, samme testdata brukt (Stein Eidem, oppgjør etter Niclas Trones)
![image](https://user-images.githubusercontent.com/49443711/151995351-efdb482d-7ebc-4b20-8939-d42e40d28a95.png)

@DanRJ @kristoffervp

**Comment by DanRJ** [comment]
Uheldig, nå mottar vi tom streng på Eier fra SVV, er det testdataen som er feil? Kan det være mulig å få en bil uten eier på liste over kjøretøy avdøde er eier/deleier i? Har det noe hensikt at det står ingen på Eier egentlig? @kristoffervp @AinaEngen

**Comment by kristoffervp** [comment]
@AinaEngen Kan du sjekke med SVV vedrørende testdata?

**Comment by AinaEngen** [comment]
Strengt tatt burde vel ikke det eksemplet over vises på avdøde; hvis avdøde verken var eier eller medeier skal vel ikke arvingene håndtere det i oppgjøret? Ser ut som testdata-feil, da dette et eller annet sted knyttes mot avdøde.
@kristoffervp - har du noen kontaktpersoner hos SVV som jeg kan kontakte vedr. testdata?
