### ISSUE TITLE
Avdødes skatteoppgjør

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#36]
#### Brukerhistorie:

Som en arving 
ønsker jeg innsyn i avdødes siste skatteoppgjør 
slik at jeg kan tilegne meg en oversikt over skattemessige aktive/ passiva og andre disposisjoner

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):

•	Jeg kan se et visningsvindu av avdødes siste skatteoppgjør i Altinn dødsbo 
•	Jeg kan få veiledning om øvrige opplysninger
- Skrive inn kriterier for innhold av skatteoppgjør

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Avklaring/forutsetning:**
- Burde kobles til forhåndssetting av skatt i boet i brukerhistorie .....? 
- Skatt gir forskjellig informasjon som kommer til anvendelse i OED (annet relevant info fra Skatt)
- Bruker blir tatt til... url til skatteetaten om videre veiledning 
- Informasjon om innhold må avklares med Skatt

**SCENARIO X Akseptansekriterier (minimum happy-case):**

TODO

**Comment by kajabystol** [comment]
Veiledning om øvrige opplysninger må gåes opp med Skatt

**Comment by TageGitHub** [comment]
Videreføres i #187
