### ISSUE TITLE
Oppdater logo og fiks mobilvisning mtp tekst som overskrider

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#360]
Oppdater logo til ny logo og fiks mobilvisning på de ulike undersidene.

Relatert til brukerhistorie/epos: #
Lenke til design:
[Design](https://eggedosis.github.io/oed/redirects/design/dashboard/concept-3-one-m.html)

- [x] Last ned de nye logoene og fiks logo for de ulike sidene
- [x] Se på mobilvisning, frisk de opp

**Comment by OlgaKoz** [comment]
@DanRJ Ser på Android (Chrome) teksten overskrider boksen fortsatt. Men holder seg innenfor på pc(Win10) og Mac. Både i Chrome, Firefox og Edge.
