### ISSUE TITLE
Inngang for å registrere informasjon om Testament/ektepakt

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#365]
Se under "Dine oppgaver i boet"
Relatert til brukerhistorie/epos: #
Lenke til design:
https://eggedosis.github.io/oed/redirects/design/dashboard/concept-3.html
(Design, ref #370, kommer senere)

- [x] Lenke som tar bruker til side for registrere testament

- [x] Lenke som tar bruker til side for å registrere ektepakt

- [x] Brødsmuletekst

- [x] Navigasjon

**Comment by LeneSundsbo** [comment]
Viderefør designet i TT02 inntil jeg har oppdatert designet i skissene (ca uke 27).

**Comment by juliearving1** [comment]
Brødsmuleteksten skal være det samme som navigasjonsteksten (knappeteksten).

**Comment by OlgaKoz** [comment]
Testet ok
https://digdir.sharepoint.com/:w:/r/sites/Prosjekt_DSOPOppgjretterddsfall/Delte%20dokumenter/General/Realiseringsfasen/Test/Test%20Planer/Test%20plan%20Sprint%201/Test%20Cases%20Ektepakt.docx?d=wbba4ef45348545919233d6d096f8f99b&csf=1&web=1&e=Y8dpjy
https://digdir.sharepoint.com/:w:/r/sites/Prosjekt_DSOPOppgjretterddsfall/Delte%20dokumenter/General/Realiseringsfasen/Test/Test%20Cases/Test%20Cases%20Testamente.docx?d=wa0d3c98f5b804a96b3357468b96eeabb&csf=1&web=1&e=sg8PBE
