### ISSUE TITLE
Arving registrerer kunnskap om testament

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#366]
Beskrivelse av oppg.....
Relatert til brukerhistorie/epos: #354
Lenke til design:
https://eggedosis.github.io/oed/redirects/design/tasks/edit-testament-default-d.html
- [x] Funskjonalitet for å legge til testament

- [x] Side for å registrere/redigere kunnskap om testament

- [x] Funksjonalitet for å fjerne eget registrert testament

**Comment by juliearving1** [comment]
Brødsmuleteksten skal være det samme som navigasjonsteksten (knappeteksten).

**Comment by LeneSundsbo** [comment]
Det er i orden for meg at sjekkboks ikke er 100% i tråd med skisse på dette tidspunktet.

**Comment by OlgaKoz** [comment]
Testet ok
https://digdir.sharepoint.com/:w:/r/sites/Prosjekt_DSOPOppgjretterddsfall/Delte%20dokumenter/General/Realiseringsfasen/Test/Test%20Cases/Test%20Cases%20Testamente.docx?d=wa0d3c98f5b804a96b3357468b96eeabb&csf=1&web=1&e=2x0gw1
