### ISSUE TITLE
Arving registrerer kunnskap om Ektepakt

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#367]
Relatert til brukerhistorie/epos: #349 
Lenke til design:
https://eggedosis.github.io/oed/redirects/design/tasks/edit-marriage-pact-default-d.html
- [x] Legg til Ektepaktregister integrasjonen, og vis det

- [x] Funskjonalitet for å legge til ektepakt

- [x] Side for å registrere/redigere kunnskap om ektepakt

- [x] Funksjonalitet for å fjerne eget registrert ektepakt

- [x] mobilvisning

- [x] tester

**Comment by juliearving1** [comment]
Brødsmuleteksten skal være det samme som navigasjonsteksten (knappeteksten).

**Comment by OlgaKoz** [comment]
Testet ok
https://digdir.sharepoint.com/:w:/r/sites/Prosjekt_DSOPOppgjretterddsfall/Delte%20dokumenter/General/Realiseringsfasen/Test/Test%20Planer/Test%20plan%20Sprint%201/Test%20Cases%20Ektepakt.docx?d=wbba4ef45348545919233d6d096f8f99b&csf=1&web=1&e=flNc0I
