### ISSUE TITLE
Implemetering av feltet "Informasjon om avtalen" på Pensjon

### ISSUE THREAD

**Issue by OlgaKoz** [Altinn/oed#369]
Relatert til brukerhistorie/epos: #297 Utvikling av pensjonssiden
[Se design her.](https://www.figma.com/proto/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=3200%3A66192&viewport=-23511%2C-1551%2C0.6027415990829468&scaling=min-zoom&page-id=372%3A0) 
 
 

- [ ] Finn ut av navnet på feltet som skal beskrive kategoriene og legg det til

**Comment by OlgaKoz** [comment]
Har kontaktet Norsk Pensjon og spurt om status - de regner med å levere det neste uke (uke 26)

**Comment by lillelars** [comment]
@OlgaKoz hva er status på denne? har vi det vi trenger for dette feltet?

**Comment by OlgaKoz** [comment]
Testet ok.
