### ISSUE TITLE
Avdødes bankforhold

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#37]
#### Brukerhistorie:
Som en arving 
ønsker jeg en oversikt over avdødes bankforhold
slik at jeg ser aktiva og passiva

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

Kontrollinformasjon er beskrevet her:

https://www.bits.no/project/kontrollinformasjon/

API vi skal bruke er beskrevet her:

https://bitsnorge.github.io/dsop-accounts-api/

Vi henter fra API følgende info for hver konto: 

Kontotype (type: loanAccount, salaryAccount, currencyAccount, savingsAccount, clientAccount, taxDeductionAccount, businessAccount), 
Saldo (balance), 
Status (status: enabled, disabled, deleted),
Valuta (currency),
Kontonavn (name),
Transaksjonshistorikk (transaction ) - hva innebærer dette ? 

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### TODO:
 - finne ut om all informasjon vi trenger fra aktøren er tilgjengelig via API'et
(- arving skal se dersom ikke all informasjon fra aktøren er tilgjengelig ?) 

#### Akseptansekriterier (minimum happy-case):

- Jeg kan se et visningsvindu med saldo, innskudd/gjeld, kontonavn, kontotype
- Jeg kan se kontaktinformasjon til den gjeldende bank
- Vi skal støtte SBanken og Sparebank1 (DNB?)
- Jeg kan se at listen nødvendigvis ikke er uttømmende

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Avklaring/forutsetning:**
- I første omgang trenger vi ikke å vise informasjon fra andre banker utover SBanken og Sparebank1 (se #80 )
- 

**SCENARIO X Akseptansekriterier (minimum happy-case):**

**Comment by kajabystol** [comment]
Avklaring som må plass hvilke banker det kan gjelde (om arving kan få info om bank som ikke er med i MVP). 
HUSK! Banker som ikke er med i KAR (men annet register)

**Comment by TageGitHub** [comment]
lukkes. erstattes av #153
