### ISSUE TITLE
Implementere design for Dine oppgaver boksen på forsiden

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#370]
Implementere design for Dine oppgaver boksen på forsiden
Relatert til brukerhistorie/epos: #365
Lenke til design:
[Design](https://eggedosis.github.io/oed/redirects/design/dashboard/concept-3.html)

- [ ] Oppdater til nytt design

**Comment by lillelars** [comment]
Denne skal sees på på nytt av funskjonelle. Lukker utviklingsoppgaven.
