### ISSUE TITLE
Erklæring om privat skifte

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#371]
## Introduksjon

De fleste arvinger velger å stå for et skifte av et dødsbo selv. Privat skifte kan først starte når en har fått skifteattest.

**I dag** benyttes pdf-skjemaet "Erklæring om privat skifte av dødsbo", https://www.domstol.no/globalassets/upload/da/domstol.no/skjema/arv-og-skifte/bokm-privat-skifte.pdf . 
Skjemaet **må** **fylles ut av en eller flere arvinger** for å **overta ansvaret for avdødes gjeld**.  Skjemaet sendes som oftest via brevpost, eventuelt e-post, til domstolen der avdøde bodde. Skjemaet **må ha original underskrift (signatur).** Innen 60 dager etter dødsfallet **må** skjema være sendt inn.

Den eller de som sender inn skjemaet, er selv ansvarlig for at retten har fått en fullstendig oversikt over hvem som er arvinger. 

Denne epic-en beskriver en førsteversjonen av en digital erklæring om privat skifte som skal kunne inngå i tjenesten Altinn Dødsbo, hvor arvinger vil kunne fylle ut, signere og sende inn søknad om privat skifte i Altinn Dødsbo, uten å måtte oppsøke tingretten.

Relevante lenker:
https://www.domstol.no/arv-og-skifte/dodsfall-og-arv/privat-skifte
https://www.domstol.no/arv-og-skifte/dodsfall-og-arv/forskjellige-former-for-skifte
https://www.domstol.no/arv-og-skifte/dodsfall-og-arv/hvem-er-arvinger

## Tilleggs informasjon
- Det tilbys per dags dato en løsning for å signere erklæring om privat skifte digitalt som kan benyttes først etter at skjema er sendt inn per brevpost eller e-post, hvor enkelte eller flere av arvingene ber om å få signere digitalt.

- Hvis alle arvingene har påtatt seg gjeldsansvaret, vil domstolen sende skifteattesten i løpet av 1-2 uker etter å ha mottatt skjemaet.

## Funksjonalitet (MVP)

Fyll ut skjema for erklæring om privat skifte #372
Signering av skjema for erklæring om privat skifte #373 
Endre på utfylt skjema for erklæring om privat skifte #374 
Påkrevde felter for skjema erklæring om privat skifte #431
Signere på at arving ikke påtar seg gjeldsansvar #375
Sende inn erklæring om privat skifte #376
Varsling og statusoppdatering ifbm. erklæring om privat skifte #435
Tekster i skjema erklæring om privat skifte #436
Preutfylling i skjema for erklæring om privat skifte #437
Håndtere uskifte _TBD_

## Tilleggs funksjonalitet (utenfor MVP)
- Veivalg mellom felter skjema erklæring om privat skifte #432
- Legge ved testament/-ektepakt #422
- Det digitale skjemane for erklæring om privat skifte skal kunne benyttes også utenfor en instans av Altinn Dødsbo som separate (enkelt) tjenester
- Hvis det er utstedt et proklama/pågående proklamaperiode (6 uker) skal **ikke** skjema for erklæring om privat skifte kunne sendes inn
- Støtte for utenlandsk adresse
- Tilgang til slektskap fra FREG for preutfylt data/info
- (Tilsvarende Samordnet Registermelding) Oppslag på fødselsnummer o.l. fra FREG for å finne f.eks. Avdødes ektefelle m.v.
- Preutfylling av Landbrukseiendom

## Funksjonelle krav

- Det skal ikke være mulig å endre preutfylt informasjon, det skal kun være mulig å legge til ny informasjon, dersom arving mener den preutfylte informasjonen er feil. All informasjon som ikke er preutfylt (utenom fødselsnummer), hvor arvingene legger inn informasjon selv, skal kunne ses og endres av alle arvinger. 
- Minst en av arvingene må påta seg fullt ansvar for avdødes gjeld før Erklæring om privat skifte sendes inn
- Arvinger som er ektefelle/samboer eller av Arveklasse 1 og 2 skal kunne benytte skjemaet
- Erklæring om privat skifte må være signert av en arving som påtar seg gjeldsansvaret innen 60 dager etter dødsfallet
- Utfylt erklæring om privat skifte skal sendes inn etter 60 dager om minst en har signert på at arvingen påtar seg gjeldsansvaret, selv om alle/øvrige arvinger ikke har signert. Fristen skal dog ikke settes absolutt i Altinn Dødsbo.
- Støtte en eller flere arvinger
- Arvingene skal fylle ut på samme instans av Erklæring om privat skifte
- Skjemaet skal kunne sendes inn så mange ganger arvingene ønsker
- Samtykke til privat skifte fra verger for arvinger som er mindreårige eller fratatt rettslig handleevne er _out of scope_
- For all data som eventuelt preutfylles skal det tydelig fremkomme hvem som er kilden

## Design krav
- Det er ofte en misoppfatning blant arvinger at de MÅ signere skjema for erklæring av privat skifte for å ha rett på arv. Dette bør tas høyde for i designet.

Trådskisser: https://www.figma.com/file/RekR9eVXajV3F0PPsUbHsn/OED-Research-og-wireframes?node-id=41%3A874

GUI, siste versjon: Prototype: https://eggedosis.github.io/oed/redirects/design/tasks/probate-default-d.html
Enkeltskjermbilder: https://www.figma.com/file/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=4035%3A22488

GUI, til utvikling: https://www.figma.com/proto/IcY5YuDiedu72nIpHIrKhA/OED-🖥-desktop?page-id=4035%3A22488&node-id=4037%3A23070&viewport=241%2C48%2C0.1&scaling=min-zoom&starting-point-node-id=4113%3A29287&show-proto-sidebar=1

## Tekniske og ikke-funksjonelt
**Kilder**
Opplysninger om avdøde
Navn, Fødselsnummer, Dødsdato = Lovisa
Boligadresse, Postnr, Posted = FREG

Testament
Informasjon om oppbevart testament = Lovisa

Ektepakt
Informasjon om tinglyst ektepakt = Ektepaktregisteret/Løsøreregisteret

Arvinger
Navn på arvinger, fødelsdato = Lovisa

- Datamodell må ikke være basert på SERES
- Skjemaet bør ha forskjellige _states_, eksempelvis; "Ny", "Under arbeider", "Sendt", "Godkjent" og "Avslått"

LENKE TIL TEGNINGER:
https://miro.com/app/board/o9J_l21uZvM=/

![image](https://user-images.githubusercontent.com/39513382/129558203-9d707c78-ffbd-40e5-a6cc-696e92cf80a7.png)

![image](https://user-images.githubusercontent.com/39513382/129166165-63cc6392-1551-439f-a827-4ec2375f7408.png)

## Avhengigheter

- #217 
 
## Avklaringer
- Boligadresse - Hvordan følger vi opp dette dersom vi må melde fra om avvik fra Folkeregisteret?
- Krav til sikkerhetsnivå på signering?
- (DA) Skal det tydelig fremkomme i Erklæring om privat skifte skjema at arvinger evt. "bestrider" at f.eks. Ektepakt eller Testament registrert i et offentlig register er feil/ugyldig?
- (Julie/Trine/Ben) Når vi oppgir kilden til evt. preutfylt data, skal vi da oppgi "registeret" eller skal vi oppgi "organisasjonen"? Bør vi da også ta med kontaktinformasjon?
- (Trine/Ben) Hvordan skal vi håndtere visning av preutfylt (mao. registrerte Ektepakter) i ulike scenarioer? Bør ta avsjekk med ressurser i BR som jobber med Ektepakt-registeret, og Domstoladministrasjonen
- (Kris) Hvordan håndterer vi at preutfylte data er _dynamiske_? F.eks. det tilkommer flere arvinger løpende, det finnes nye/andre testamenter med videre..
- (DA) Er Boligadresse (under informasjon om avdøde) det samme som bostedsadresse (i FREG)?
- (DA) Hvorfor er det ikke mulig å oppgi om avdøde ved sin død var samboer, i dagens skjema? Er det noen tanke bak? 
- (DA) Skal vi sende inn skjema hvis alle arvinger IKKE påtar seg ansvaret?
- Vil det være en utfordring for en arving å signere hvis de ikke har sett hele fødselsnummeret?
- (Brukervennlighet) Skal vi bruke navnet på den avdøde ("Svein Svendsen") i tekster, spørsmål etc. eller holde oss til "den avdøde"
- (DA) Hvordan forholder vi oss til informasjonsteksten på side 2 av det papirbaserte skjemaet?
- (DA) Ektepakt: Preutfylt tinglyst ektepakt: Er retten interessert i å få tinglysningsdatoen (Dette er datoen vi får)? Ektepakt som arvinger legger til: Er det dato for når ektepakten er signert som retten spør etter, og hva brukes denne informasjonen til?
- (DA) I en førsteversjon, vil det likevel kunne gi verdi å få oversendt et testament som f.eks. er oppbevart hjemme / ikke-tinglyst ektepakt sammen med Erklæring om privat skifte? For så at arvinger evt. ettersender original/rett-kopi i bakhånd via brevpost?
- (DA) Hvorfor er det interessant å vite om avdøde var separert eller skilt? Hvilken virkning har det på skifteoppgjøret?
- (DA) Hvilken hensikt har det at arvinger fyller ut "til tingretten/byfogdembetet i..." i den digitale versjonen av skjemaet? (Ikke inkludert i v.1 av skjema per nå)
- (DA) På hvilket tidspunkt legger Domstolen inn informasjon i API-et om at et testament er registrert hos dem? Er det etter søk i testamentregisteret, er det etter de faktisk har funnet det deponerte testament i arkivet, eller når? Har betydning for hvem som er kilde til informasjonen, om det er en spesifikk tingrett eller domstolen som sådan. Har også betydning for tekster, eks et testament deponeres hos en tingrett, mens deponeringen i seg selv registreres i testamentsregisteret.

## Interessenter

- Domstoladministrasjonen
- Oslo Tingrett
- Arvinger

**Comment by lillelars** [comment]
Denne er delvis løst. Resterende oppgaver realiseres i #489. Lukker derfor denne saken.
