### ISSUE TITLE
Fyll ut erklæring om privat skifte

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#372]
## Brukerhistorie

> Som en arving
> ønsker jeg å fylle ut erklæring om privat skfite
> slik at jeg (og eventuelt flere arvinger) kan foreta et privat skifte

**Utfyllende beskrivelse**
Arvingene plikter etter [forskrift til arveloven](https://lovdata.no/forskrift/2020-11-09-2327/§8) å oppgi opplysninger om 
a.     om den avdøde var gift, ugift, separert, skilt, enke, enkemann, samboer eller lengstlevende i et samboerskap
b.	navn og fødselsnummer for person som nevnt i bokstav a
c.	om den avdøde satt i uskiftet bo etter ektefelle eller samboer
d.	dersom den avdøde var skilt, separert eller tidligere samboer, om felleseiet var delt eller om skiftet for øvrig var gjennomført
e.	hvem som er arvinger etter den avdøde
f.	om den avdøde etterlater seg testament
g.	om den avdøde etterlater seg arvinger som er mindreårige eller fratatt rettslig handleevne, og i så fall vergens navn og kontaktopplysninger
h.	navn, personnummer og kontaktopplysninger for den som melder opplysningene.

### Løsningsbeskrivelse

g) Altinn Dødsbo i førsteversjon vil uansett ikke tillatte dødsbo hvor det er arvinger som er mindreårige eller fratatt rettslig handleevne å bruke Altinn Dødsbo
d) tas som en del av veivalgsarbeidet. Avhenger veldig av hvilken opplysninger som oppgis tidligere i skjemaet. For øvrig dekkes alle disse opplysninger på en eller annen måte i de skissene som foreligger per 9.9.21.

### Akseptansekriterier

A)
Gitt at jeg er en arving og fyller ut erklæring om privat skifte i Altinn Dødsbo
Når jeg fyller ut erklæring om privat skifte, så skal jeg kunne fylle ut informasjon om avdøde, kjennskap til testament/ektepakt, arvinger m.v. i henhold til det arveloven § § 89, jf. § 90 og forskriften § 8.

B) Gitt at jeg er en arving
Når jeg fyller ut/endrer erklæring om privat skifte, så skal jeg få informasjon om hvor data er hentet fra hvor det er hensiktsmessig , slik at jeg og de øvrige arvingene vet hvem som er kilden til den dataen

**Comment by lillelars** [comment]
Foreldet. Lukker saken.
