### ISSUE TITLE
Registrere signering om privat skifte og påta seg gjeldsansvar

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#373]
## Brukerhistorie

> Som en arving
> ønsker jeg å signere på at jeg ønsker privat skifte, OG påta meg gjeldsansvaret i dødsboet
> slik at jeg kan påta meg gjeldsansvaret i boet

### Løsningsbeskrivelse
Denne skal løses med en egen Tjenester 3.0 App i sammen med #375 

### Akseptansekriterier

A)
Gitt at jeg er en arving og ønsker å overta ansvaret for avdødes gjeld
Når jeg har signert erklæring om privat skifte, så skal de andre arvingene få varsel

B) 
Gitt at jeg er en arving og ønsker å overta ansvaret for avdødes gjeld
Når jeg har signert, så skal jeg få tilbakemelding om signering er vellykket eller ikke

**Avklaringer**
- [ ] Har vi noe krav til signaturen her? Må være med BankID eller tilsvarende?
Dagens digitale signaturløsning krever (nivå 4) BankID. DA har oppfølging på dette mot Justisdepartementet

**Comment by TageGitHub** [comment]
Ivaretas av annen brukerhistorie
