### ISSUE TITLE
Registrere ønske om privat skifte og ikke påta seg gjeldsansvar

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#375]
## Brukerhistorie

> Som en arving
> ønsker jeg å signere på at jeg ønsker privat skifte, OG **ikke** påtar meg gjeldsansvar
> slik at vi kan gå videre med behandling av privat skifte

### Løsningsbeskrivelse
Denne skal løses med en egen Tjenester 3.0 App i sammen med #373 

### Akseptansekriterier

A)
Gitt at jeg er en arving og har signert at jeg ikke påtar meg gjeldsansvaret
Når jeg har signert, så skal øvrige arvinger få varsel

B)
Gitt at jeg er en arving og ønsker å overta ansvaret for avdødes gjeld
Når jeg har signert, så skal jeg få tilbakemelding om at signering er vellykket

**Avklaringer**
- [ ] Har vi noe krav til signaturen her? Må være med BankID eller tilsvarende?
 Dagens digitale signaturløsning krever (nivå 4) BankID. DA har oppfølging på dette mot Justisdepartementet.

**Comment by TageGitHub** [comment]
Annen brukerhistorie
