### ISSUE TITLE
Sende inn erklæring om privat skifte

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#376]
## Brukerhistorie

> Som en arving
> ønsker jeg at skjema for erklæring om privat skifte sendes inn til tingretten
> slik at jeg (og eventuelt flere arvinger) kan fortsette med oppgjøret av dødsboet

### Akseptansekriterier

A) Gitt at skjema for erklæring om privat skifte er fylt ut korrekt
OG alle arvinger har signert 
OG minst en av arvingene har signert på å påta seg gjeldsansvaret
SÅ skal skjema automatisk sendes til Tingretten

B)
Gitt at jeg er en arving og har sendt inn erklæring om privat skifte
Når skjemaet er sendt inn, så skal jeg OG øvrige arvinger få varsel (utenfor tjenesten?)

C) 
Gitt at jeg er en arving og har sendt inn erklæring om privat skifte
Når skjema er sendt inn, så skal Altinn Dødsbo vise informasjon/status (innad i tjenesten?) om at skjema er sendt inn

D)
Gitt at jeg er en arving og har signert for å påta meg gjeldsansvaret
Når det har gått 60-dager, så skal skjema bli sendt inn, uavhengig om øvrige arvinger har signert

**Avklaringer**
- [ ] Skal vi ta feilhåndtering inn her? f.eks hvordan det skal håndteres dersom innsending feiler?
Kristoffer: Dette vil jeg _anta_ at vi får "gratis" ved bruk av Altinn-plattformen. Bør i midlertidig avklares med arkitekt/utvikler i neste Grooming.

**Comment by lillelars** [comment]
Følger flyten i T3.0.
Lukker derfor denne saken.
