### ISSUE TITLE
Avdødes forsikring og/eller pensjon

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#38]
#### Brukerhistorie:

Som en arving 
ønsker jeg en oversikt over avdødes pensjon og forsikring
slik at jeg vet hvilke avtaler avdøde hadde

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

Løsningsforslag fra Norsk pensjon ligger her:
https://brabts.sharepoint.com/sites/opgj_dodsfall/

Norsk pensjon samler inn og konsoliderer data fra de enkelte pensjons/forsikrings-ordningene/foretak. Norsk pensjon vil skreddersy et API for OED. 

Vi henter fra API for hver enkelt avtale:

| Felt  | Påkrevd | Validering | Lengde | 
| ------------- | ------------- | ------------- | ------------- | 
| Fødselsnummer | Ja | Gyldig norsk fødselsnummer/D-nummer | 11 siffer | 
| Opplysningsdato | Ja | Dato med format YYYYMMDD | | 
| Referanse | Ja | Selskapets interne referanse for polisen (f.eks. polisenr/avtalenr). String, ikke tom. Behøver ikke være unik. | [1..30] | 
| Dekningstype | Nei | Gyldige verdier: alderspensjon, dodsdekning - Med «dodsdekning» menes etterlattepensjon/livsforsikring | | 
| Navn på pensjonsinnretning | Ja |  | [1..50] | 
| Pensjonsinnretnings organisasjonsnummer | Ja | | 9 siffer | 
| Produkttype | | | | 
| Lenke til nesttside | | URL til nettside hos leverandøren av produktet | | 

Relatert til #81 

Følgende ordninger kan bli del av OED:
| Ordningstype | Produkttype | Utbetales til boet ? |  
| ------------- | ------------- | ------------- |
| Kollektiv | Innskuddsbasert kollektiv pensjon | Kanskje |
| Kollektiv | Ekstrapensjon | Kanskje |
| Kollektiv | Personalforsikring | Kanskje |
| Privat | IPS | Kanskje |
| Privat | IPA | Kanskje |
| Privat | Individuell uførepensjon | Kanskje |
| Privat | Barneforsikring | Kanskje |
| Privat | Uføreforsikring | Kanskje |
| Privat | Sykeforsikring | Kanskje |
| Privat | Spareavtale | Ja |

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

TODO:

#### Akseptansekriterier (minimum happy-case):

- [ ] Jeg kan se et visningsvindu med liste over ulike forsikringstyper med navn på selskaper og kontaktinformasjon. 

- [ ] Jeg kan lese at listen nødvendigvis ikke er komplett

- [ ] Jeg vil ikke nødvendigvis se summen på avtale, men blir bedt om å ta kontakt med aktuell(e) selskap(er). 

**Avklaring/forutsetning:**
- Er det behov for  avklaring med NP eller forsikring?
- Dette må avklares med NP, hva slags informasjon som kan vises i boet. 

**SCENARIO X Akseptansekriterier (minimum happy-case):**

#### Testscenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by kajabystol** [comment]
Avklare med aktører: Hvilke forsikringsavtaler (og aktører) er inkludert i MVP? (API fra NP, vil vi kunne hente mer info?)
Hva inneholder informasjonen arvingen mottar? 
Kan informasjonen lagres i Altinn dødsbo dersom hjemmel kommer på plass?

**Comment by curlingnina** [comment]
Viser til:
- informasjonsmodellen som alle aktørene fylte ut i konseptfasen
- at det er kun liv-forsikringer hvor er en arvinger er begunstiget (se sluttrapporten fra forrige fase)
- se NP sin løsningsbeskrivelse

**Comment by TageGitHub** [comment]
Videreføres i #243 og #245
