### ISSUE TITLE
Bankforhold

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#380]

**Comment by OlgaKoz** [comment]
Test https://teams.microsoft.com/_#/docx/viewer/teams/https:~2F~2Fdigdir.sharepoint.com~2Fsites~2FProsjekt_DSOPOppgjretterddsfall~2FDelte%20dokumenter~2FGeneral~2FRealiseringsfasen~2FTest~2FTest%20Planer~2FTest%20plan%20Sprint%201~2FTest%20Cases%20Bank.docx?threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&baseUrl=https:~2F~2Fdigdir.sharepoint.com~2Fsites~2FProsjekt_DSOPOppgjretterddsfall&fileId=f026eb75-a26f-4d7b-9e01-50055aec919a&ctx=files&rootContext=items_view&viewerAction=view
