### ISSUE TITLE
Oversikt over alle bankforhold til avdøde

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#381]
## Brukerhistorie

> Som en arving
> ønsker jeg å skaffe meg oversikt over alle banker den avdøde hadde kontoer hos
> slik at jeg (og eventuelt andre arvinger) får innsikt i hvilke banker jeg bør kontakte for å få oversikt over boets økonomi

### Løsningsbeskrivelse
Som et minimum skal løsningen støtte at vi viser avdødes bankforhold/banker (**navnet på banken**). Slik at arvinger får en oversikt over eventuelle banker de kan/bør kontakte for å få innsikt i bla. konto, saldo, transaksjonshistorikk. 

Dette er det støtte for i KAR og krever ikke integrasjon mot hver enkelt bank.

Eksempel respons fra KAR:

> 
>   "banks":
>       "organizationID": "920426530",
>       "bankName": "SPAREBANK 1 ØSTLANDET",
>       "activeAccount": false
>

KAR
https://teams.microsoft.com/l/file/1D41A9C5-BE81-452B-8758-D7A405F45B88?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FTeknisk%2FReferater%20og%20teknisk%20dokumentasjon%2FAksess%20til%20eksterne%20data%20-%20diskusjonsutkast.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

API - Bank (vår dok på bruk av KAR-API):
https://teams.microsoft.com/l/file/44D1B18E-035D-4852-97E2-C55F921ABD1A?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FDokumentasjon%20fra%20eksterne%20akt%C3%B8rer%2FReferater%20og%20teknisk%20dokumentasjon%2FBits%2FAPI%20-%20Bank.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

### Akseptansekriterier

- [x] A) Gitt at jeg er en arving og ønker en oversikt over alle banker/bankforhold til den avdøde
Når jeg benytter Altinn Dødsbo, så skal jeg kunne se hvilke banker den avdøde hadde/har forhold i

(Navn på bank, alle norske banker må kunne listes opp ved navn)

- [x] B) Gitt at jeg er en arving og ønsker oversikt over alle banker/bankforhold til den avdøde
Når det **ikke** vises treff under bankforhold, så skal jeg se en informativ feilmelding og eventuelt veiledning om hva jeg kan gjøre

- [x] C) Gitt at jeg er en arving og ønsker oversikt over alle banker/bankforhold til den avdøde
Når det vises et større antall treff av bankforhold, så skal jeg bli presentert en brukervennlig og oversiktlig representasjon av bankforholdene

- [ ] D) Gitt at jeg er en arving og ønsker oversikt over alle banker/bankforhold til den avdøde
Når det er feil i kommunikasjonen e.l. med Bits/KAR, så skal jeg få en informative feilmeldinger

**Comment by OlgaKoz** [comment]
Punkt D) ivaretas i #425 
Punkt C) lages Brukerhistorie som ivaretar helhetlig presentasjon av mange forhold (Bank, Forsikring, Eiendom, osv) #430

**Comment by TageGitHub** [comment]
ivaretas av annen bh
