### ISSUE TITLE
Detaljert informasjon om bankforhold til avdøde

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#382]
## Brukerhistorie

> Som en arving
> ønsker jeg å skaffe meg en detaljert oversikt over alle bankforhold til den avdøde
> slik at jeg (og eventuelt andre arvinger) får innsikt i kontoer OG kontodetaljer OG transaksjonshistorikk per konto de siste 3 mnd (fra i dag)
> 

### Løsningsbeskrivelse

Følgende API-er er avklart at kan benyttes: 
1. **Kontoliste** 2. **Kontodetaljer**" 3. **Transaksjonshistorikk**

For de bankene som **har integrert seg** med Altinn Dødsbo skal følgende felter kunne vises (gitt at den avdøde hadde bankforhold i den banken):

**Kontonummer**,

**Kontotype**
Bankene har 10 forhåndsdefinerte verdier som banken velger å putte kontoen i: loanAccount, salaryAccount, currencyAccount, savingsAccount, clientAccount, taxDeductionAccount, businessAccount, credit card account, prepaid card account (ikke DNB, Sparebank1 eller Sbanken), other account

**Saldo** (med angitt valuta)

**Transaksjonshistorikk** (per konto)
Transaksjonshistorikk for de tre siste mnd skal hentes **ved behov**. Dvs. ikke i første spørring/ved lasting av siden, men gjøre ny spørring hvis de etterlatte faktisk ønsker dataene. Alternativt hente alle data, men kun vise transaksjonshistorikk i OED ved behov.

Transaksjonshistorikk, i en førsteversjon, skal ikke vises i brukergrensesnittet, men tilbys i et nedlastbart format - eksempelvis .csv

Her følger et eksempel på respons fra Sbankens API:
[respons_sbanken.txt](https://github.com/Altinn/oed/files/6929563/respons_sbanken.txt)

2. I denne brukerhistorien inkluderer vi IKKE feltet for **Kontostatus**, dette må vi eventuelt komme tilbake til hvis vi ser en verdi for bruker

B) For de bankene som **IKKE har integrert seg** med Altinn Dødsbo skal følgende kunne vises (gitt at den avdøde hadde bankforhold i den banken):

I en førsteversjon skal vi vise en tekstlig beskrivelse at data fra aktuell bank ikke er tilgjengelig.

### Akseptansekriterier

A) Gitt at jeg er en arving og ønsker detaljert oversikt over alle banker/bankforhold til den avdøde
Når jeg ser på hver enkelt konto, så skal jeg få en forståelig beskrivelse av type konto (kontotype)

(Gjelder: loanAccount, salaryAccount, currencyAccount, savingsAccount, clientAccount, taxDeductionAccount, businessAccount, credit card account, prepaid card account (ikke DNB, Sparebank1 eller Sbanken), other account)

B) Gitt at jeg er en arving og ønsker detaljert oversikt over alle banker/bankforhold til den avdøde
Når det ....

C) Gitt at jeg er en arving og ønsker detaljert oversikt over alle banker/bankforhold til den avdøde
Når det ....

**Comment by OlgaKoz** [comment]
Mangler:
1. Filen Transaction history skal kalles på norsk
2. Kontonavn skal ikke vises, men Kontotype 
3. Forskjellige feilmeldinger til når bank integrasjon er nede og når KAR er nede.

**Comment by TageGitHub** [comment]
overtatt av annen bh
