### ISSUE TITLE
Informasjon og veiledning

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#384]
## Introduksjon
Dette eposet tar for seg all informasjon utenom den innledende informasjonen arvingen får.
Informasjon som kan/bør/skal ligge tilgjengelig i OED på en eller annen måte (evt som en lenke til eksterne sider).

Relatert #523 

Relevante lenker:

- https://www.domstol.no/Enkelt-domstol/oslo-byfogdembete/arv-og-skifte/om-arv-og-skifte/hvem-er-arvinger/
- https://www.domstol.no/Enkelt-domstol/oslo-byfogdembete/arv-og-skifte/om-arv-og-skifte/orientering-til-gjenlevende-ektefelle/
- https://www.domstol.no/arv-og-skifte/dodsfall-og-arv/forskjellige-former-for-skifte/

## Funksjonalitet (MVP) _WIP_
Vi trenger informasjon om disse temaene:

- Ofte stilte spørsmål
- Veiledning om skifteformer (eldre sak til referanse 224)
- Ektefelles arverett
- Samboers arverett
- Testament
- Dine/mine rettigheter i dødsboet
- 60 dagers fristen
- Arveloven
- Sitte i uskiftet bo
- Hva er din arverett? Når du er barn? Når du er ektefelle? Når du er særskiltsbarn?
- Hvordan skal arven fordeles?
- Plikter i et dødsbo
- Kontaktinformasjon
- Fullmakt

## Tilleggs funksjonalitet (utenfor MVP)
 
- Informasjon og veiledning på ulike språk
- Tilpassing av informasjon og veiledning basert på person/rolle
 
## Avklaringer

- Hvem som skal ha ansvaret for å veilede arvingene som velger å benytte den digitale løsningen? 
- Skal "veilederen" ha tilgang til de samme opplysningene som arvingene?
- Bør arvinger kunne få informasjon om hvor man kan finne ut mer om digitalt dødsbo evt. uten å logge seg inn på digitalt dødsbo? Altså informasjon som ikke ligger i OED-app, men utenfor? (Skjemaforside i Altinn)
- Hvilke språk er påkrev iht. norsk lov? NOR BM, NOR NN, samisk, engelsk?
- Flere saksbehandlere hos de ulike tingrettene opplyser at de ofte blir stilt spørsmålet "hva ville du gjort". Hvordan skal Altinn Dødsbo informere og veilede iht. hvem/hva/hvor man kan få _rådgiving_?

**Comment by TageGitHub** [comment]
ikke i bruk
