### ISSUE TITLE
Teknisk dokumentasjon, tekniskgjeld og ikke-funksjonelle endringer

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#385]
## Introduksjon
Denne epic-en er en samlepost for tekniske endringer (herunder også teknisk gjeld) og dokumentasjon knyttet Altinn-Dødsbo.

Vi dokumenterer her:
[Lenke til dokumentasjon](https://teams.microsoft.com/l/file/42BE2476-B4B0-40E1-AD56-014009DBAC67?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FTeknisk%2FDokumentasjon%2FOED%20applikasjonsarkitektur.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515
)

**Comment by TageGitHub** [comment]
Ikke i bruk
