### ISSUE TITLE
Navigering i nettside, UU

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#386]
**Beskriv feilen**
Det er betydelige utfordringer med å navigere applikasjon via kun tastatur, som er et UU krav.
Appen bør gjennomgås og finne ut hvor det er utfordringer, og løse disse.

Man kan også skrive tester for dette (Cypress)

Ulike feil:
- På forsiden vil det ikke dukke opp sorte linjer rundt de boksene på høyre siden når man har brukt tab for å navigere seg dit.

**Comment by DanRJ** [comment]
Tabbing skal nå fungere

**Comment by AinaEngen** [comment]
Tabbing funger ok nå

**Comment by DanRJ** [comment]
Ref #558 er denne løst. Jeg lukker
