### ISSUE TITLE
Detaljert informasjon om bankforhold til avdøde ved kommunikasjonsfeil eller lignende

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#388]
## Brukerhistorie
Som en arving
ønsker jeg å få vist detaljert informasjon om bankforhold 
slik at jeg (og eventuelt andre arvinger) får innsikt i kontoer OG kontodetaljer OG transaksjonshistorikk per konto de siste 3 mnd 
HVIS tekniske API-er eller ELLER Altinn dødsbo ikke har kommunikasjon med KAR/Kontroll-API e.l. skal tidligere innhentede data kunne vises

### Løsningsbeskrivelse
Løsningen må ta høyde for feilhåndtering for eksempel i forbindelse med kommunikasjonsfeil med KAR/KontrollAPI-et e.l. enten ved hjelp av informative feilmeldinger og/eller veiledning. I tillegg bør det ses på om eventuelt resultat fra tidligere "spørringer"/innhenting av data kan vises.

## Akseptansekriterie

**Comment by TageGitHub** [comment]
ikke i bruk
