### ISSUE TITLE
Informasjon og veiledning om proklama

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#390]
## Brukerhistorie
Som arving
ønsker jeg informasjon og veiledning om proklama
slik at jeg vet hva proklama er OG kan ta stilling til om jeg ønsker å be om dette før jeg bestemmer skifteform

### Løsningsbeskrivelse
Arvingene kan bestemme at de ønsker proklama utstedt. Denne brukerhistorien omhandler **kun** informasjon og veiledning om proklama. 

### Akseptansekriterier

Gitt at jeg har logget meg på Altinn Dødsbo
når jeg ønsker å se informasjon om proklama
så finner jeg informasjon og veiledning om hva proklama er
og
hvilke konsekvenser det har for prosessen videre
og
at jeg må ta kontakt med Tingretten for den videre saksgangen vedrørende proklama

# Tilleggsinformasjon:
## Introduksjon
Ofte kan det i en tidlig fase etter dødsfallet være uklart hvor stor gjelden er. Er arvingene i tvil om avdøde etterlater seg mer gjeld enn verdier/formue, bør det utstedes det som kalles preklusivt proklama.

Proklama er en kunngjøring som rykkes inn i Norsk Lysingsblad og Aftenposten (evt. en annen alminnelig lest avis på det sted hvor avdøde bodde). og innebærer at alle kreditorene etter avdøde må melde seg **innen 6 uker**. Krav som ikke meldes innen fristens utløp, **bortfaller**. Proklamaet **gjelder ikke** utenlandske kreditorer, pantekrav eller skatte- og avgiftskrav.

En arving som ønsker at retten skal utstede proklama før gjeldsovertakelse, **må be om dette skriftlig**

Denne epic-en dekker en førsteversjon av proklama i Altinn Dødsbo, og hvilken eventuell funksjonalitet som inkluderes/ikke inkluderes.

Relevante lenker:
https://www.domstol.no/arv-og-skifte/dodsfall-og-arv/hva-bor-gjores-etter-dodsfallet/

## Tilleggs informasjon
Det finnes i dag et (digitalt) skjema for innsending av proklama hos Norsk Lysningsblad her: https://norsk.lysingsblad.no/nb/kunngjeringar/proklama/innsending.

![image](https://user-images.githubusercontent.com/1841665/129014918-676fdb58-a070-477b-aaa1-b3856840dc79.png)

**Comment by TageGitHub** [comment]
duplikat
