### ISSUE TITLE
Inngang til Bank

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#391]
Inngang til GUI
Relatert til brukerhistorie/epos: #380

Lenke til design:
https://eggedosis.github.io/oed/redirects/design/dashboard/concept-3.html

- [x] Skal ta bruker til detaljeside om bankinformasjon

**Comment by OlgaKoz** [comment]
Testet ok i B-001, B-002, B-003, B-004 https://digdir.sharepoint.com/:w:/r/sites/Prosjekt_DSOPOppgjretterddsfall/Delte%20dokumenter/General/Realiseringsfasen/Test/Test%20Planer/Test%20plan%20Sprint%201/Test%20Cases%20Bank.docx?d=wf026eb75a26f4d7b9e0150055aec919a&csf=1&web=1&e=pZ9BHN
