### ISSUE TITLE
Frontend bank

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#392]
Side for bank m/ detaljer, feilmeldinger og diverse.

Relatert til brukerhistorie/epos: #381 #382 pg epic #380 
Lenke til design:
https://eggedosis.github.io/oed/redirects/design/fortune/bank/default-one-d.html

- [x] Liste opp alle banker

- [x] Detaljering av alle banker (ved åpning av en bank)

- [x] Feilmelding ved feil fra backend APIet

- [x] Dersom avdød bare har en bank så skal den vises direkte ekspandert
https://eggedosis.github.io/oed/redirects/design/fortune/bank/one-d.html

- [x] Implementasjon dersom avdød ikke har noen bankforhold.

- [x] Knapp for å laste ned transaksjonshistorikk

**Comment by LeneSundsbo** [comment]
Til info @OlgaKoz:
Vi beholder løsningen som Daniel har laget der detaljert kontovisning har samme layout på mobil som for desktop.

**Comment by DanRJ** [comment]
Feilmelding vedr KAR og feilmelding vedr en/flere banker er nede går bort pga kobling mot KAR er ikke implementert og modellen er ikke laget for å håndtere ulike feilmeldinger fra ulike plasser. Det samme gjelder en/flere banker. Modellen er ikke laget for dette ennå

**Comment by lillelars** [comment]
@DanRJ oppretter ny sak på opgpavene mot KAR - tar dette ut fra denne.

**Comment by lillelars** [comment]
@DanRJ @OlgaKoz  Oppretter ny sak på de oppgaver som gikk mot KAR og feilmeldinger.

**Comment by DanRJ** [comment]
Etter design møte torsdag 19.08 er følgende oppgaver som må gjøres før oppgaven går videre:
- [x] Fjern pil på høyre side (Kommentar - Er ikke synlig i tt02 eller prod pga css regler)
- [ ] Legg til tusen skille og million skille og hundre million skille og milliard skille
- [ ] Fjern punktum og bytt ut med komma
- [x] Tekst i tittel skal være h2 og ha font størrelse 28px, tekst innhold skal ha font størrelse 20px
- [ ] Kontotype skal ikke være navn men det skal være typen, da må vi statisk finne korrekt tekst
- [ ] Kontonummer skal ha mellomrom, 97101 05 5829
- [x] Kolonnenavn skal være bold samt kontotype kolonnens verdier skal være bold
- [ ] Implementer mobil versjonen av bankforhold
- [ ] Legge til isimplemented

**Comment by OlgaKoz** [comment]
Testet OK https://teams.microsoft.com/_#/docx/viewer/teams/https:~2F~2Fdigdir.sharepoint.com~2Fsites~2FProsjekt_DSOPOppgjretterddsfall~2FDelte%20dokumenter~2FGeneral~2FRealiseringsfasen~2FTest~2FTest%20Planer~2FTest%20plan%20Sprint%201~2FTest%20Cases%20Bank.docx?threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&baseUrl=https:~2F~2Fdigdir.sharepoint.com~2Fsites~2FProsjekt_DSOPOppgjretterddsfall&fileId=f026eb75-a26f-4d7b-9e01-50055aec919a&ctx=files&rootContext=items_view&viewerAction=view
