### ISSUE TITLE
Lenken til Statenspensjonskasse fungerer ikke på Safari og Android +Chrome

### ISSUE THREAD

**Issue by OlgaKoz** [Altinn/oed#395]
Steps to reproduce:
1. Logg på løsningen i Safari/ Android+Chrome
2. Gå til detaljert oversikt over Forsikning og Pensjon
3. Klikk på lenken under en av pensjonsavtalene

Resultat:
Det skjer ikke redirect.

Forventet resultat:
Brukeren skal bli redirected til lenkens adresse. 

Tilleggsinfo:
Norsk Pensjon sender nå lenken som https:// - det skal React like.

**Comment by DanRJ** [comment]
Denne funker på min mobil, Android + chrome. Det åpner en ny fane som sender meg til lenken definert av søk. Jeg får ikke testet Safari

**Comment by lillelars** [comment]
Ser ut til å funke. Lukker saken.
