### ISSUE TITLE
Logging og monitorering av app

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#398]
Vi må kunne monitorere appen med hensyn til "performance", sette alarmer i tilfelle feil dukker opp o.l.
Feil kan forekomme ved nye versjoner, i en app med vår backend, i en app med våre integrasjoner osv osv.

Relatert til brukerhistorie/epos: #385

**Comment by kristoffervp** [comment]
@lillelars denne må ses på i lys av oppgaven knyttet til dokumentasjon #478

**Comment by lillelars** [comment]
Hvordan blir dette når vi nå har flere apper iT3.0? @HenningNormann

**Comment by kristoffervp** [comment]
@DanRJ @HenningNormann Vi diskuterer denne i neste Planning i Februar hvordan vi går videre.
