### ISSUE TITLE
Redux vs React.Context, behov

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#399]
Hva er behovet i vår løsning? Med Reduxen som er satt opp med Sagaer så blir det mye filer og mye kompleksitet. Jeg er usikker på om vi trenger den kompleksiteten når man kan bruke React Context.

Dette må undersøkes og en avgjørelse burde tas

**Comment by kristoffervp** [comment]
@lillelars kan dere ta stilling til dette er noe som må ses på, evt. bare lukke denne?

**Comment by lillelars** [comment]
Trolig trenger vi ikke tenke på dette når vi tilnærmer oss T3.0 i enda større grad. Lukker saken, tar opp igjen ved behov.
