### ISSUE TITLE
Kvalitet på vergemål - er den god nok til å inkluderes i rolle og rettighet?

### ISSUE THREAD

**Issue by benedicteos** [Altinn/oed#4]
Aktør involvert: Domstoladministrasjon, Sivilrettsforvaltningen og Folkeregisteret

beskrivelse: Kvaliteten på vergemål og hvorvidt den er god nok til å inkluderes i rolle og rettighetskartet må avklares.

Autorisering av arving:
- [ ] 

- [ ] 

Frist: ?

**Comment by lillelars** [comment]
Tas opp ved behov. Avklart med Kristoffer.
