### ISSUE TITLE
Se avdødes kjøretøy

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#40]
### Brukerhistorie:
**Intro**
Som en arving 
ønsker jeg en oversikt over avdødes kjøretøy (som er registrert i kjøretøyregisteret)
slik at jeg ser informasjon om de kjøretøyene som inngår i boet

**Krav/akseptansekriterier**  _(detaljering av BH med tilhørende akseptansekriterier)_
Gitt at jeg har hentet informasjon om avdødes kjøretøy
når... jeg ønsker å se informasjon om kjøretøy på egen side
så... viser jeg informasjon hentet fra Statens Vegvesen (Tage: **Avklaring** - må spesifiseres?)

Gitt at.. jeg har hentet informasjon omkjøretøy og Statens vegvesen
når... jeg velger å klikker på et informasjonselement 
så... vises uttømmende info (eks ekspanderende tekst)? 

**Utfyllende tekst**

### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): under avklaring
Avklaringsområder:   Teknisk kan alle egenskaper ved et kjøretøy hentes ut. Hva som er praktisk/juridisk ønskelig må gås opp. Her en oversikt over informasjon som kan hentes ut: https://vegvesen.github.io/ak-api/filer/api_svar/api_kjoretoyoppslag_dinky_CU10001.json
Fornuftige egenskaper som kan danne et grunnlag vil være:
Kjennemerke (reg. nr)
Merke
Modell
Kjøretøysgruppe (personbil M1, nyttebil, lastebil, varebil)
Farge
År for førstegangsregistrering
Status (registrert/avskiltet/vraket osv)
Tid for neste EU-kontroll

Dokumentasjon: 

**Trådskisser**
Status (ok, under avklaring, n/a): n/a
Avklaringsområder:
Dokumentasjon: 

**GUI** 
Status: (ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon: 

**Teknisk** 
Status(ok, under avklaring, n/a):  
Avklaringsområder:
Dokumentasjon: 
Vegvesenets webtjenester er basert på REST
Mer informasjon er tilgjengelig her om tjenester, miljøer og api: https://vegvesen.github.io/ak-api/
API som må brukes for å finne kjøretøy basert på personnummer er kjøretøysøk:
https://vegvesen.github.io/ak-api/api/#kjoretoysok

**Juridisk**
Status(ok, under avklaring, n/a):  
Avklaringsområder:
Dokumentasjon: 

### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): må
Teknisk modenhet (høy, medium, lav): høy
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, n/a): n/a
Forretningsbehov (høy, medium lav): høy

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier:
 
 
---
### Åpne punkter - lukkes før sprint
 - Teknisk kan alle egenskaper ved et kjøretøy hentes ut. Hva som er praktisk/juridisk ønskelig må gås opp. Her en oversikt over informasjon som kan hentes ut:
https://vegvesen.github.io/ak-api/filer/api_svar/api_kjoretoyoppslag_dinky_CU10001.json .
- Supplerende informasjon SVV ønsker ha med (eks avhending, omreg?)
- Etter at arving har søkt om privat skifte - hvor lenge etterpå skal arving ha mulighet til å se oversikt? Hvor lenge skal digitale dødsbo-instansen leve?
- Hvor mye informasjon skal vi vise arving? 

---
### Annet
 - Ønsker å initiere kontakt med SVV for å få denne oversikten så tidlig som mulig.
---
### Scenario X _Opprettes før lukking av denne BH_

**Forslag nye brukerhistorier Scenario X (MVP)**  

**Avklaringer scenario X**

**Comment by TageGitHub** [comment]
Videreført i #195
