### ISSUE TITLE
Mobilvisning - Veileder

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#400]
Mobilvisning av den komponenten
- [ ] Kan vi gjøre en bestcase versjon av dette for å rette opp i det værste?
NB! Ser bra ut på ipad.

For meg (i simulator Iphone X) ser det slik ut nå:
![image](https://user-images.githubusercontent.com/39513382/146780209-b91ce495-ab56-4f60-bf94-98f7f0db5931.png)
@DanRJ --- dette er nok lurt å få prioritert i Januar 2022

Relatert til brukerhistorie/epos: #363
Lenke til design:
N/A - Mulig Lasse i T3.0 kan bistå her... men i hovedsak må vi nok løse det selv.

- [ ] Implementer mobilvisningen

**Comment by kristoffervp** [comment]
Løses i #551
