### ISSUE TITLE
Feilmeldinger mot KAR

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#401]
Gjenstående oppgaver mot Bank

Relatert til brukerhistorie/epos: #392 
Relatert til brukerhistorie #381 

Lenke til design:

- [ ] Feilmelding ved at KAR er nede

- [ ] Feilmelding ved at en/flere bank(er) er nede

**Comment by kristoffervp** [comment]
@lillelars Håndterer du denne i neste Sprint? Ikke klar til test i følge @OlgaKoz 
Settes tilbake i backloggen til Utvikling

**Comment by lillelars** [comment]
Løses av #388  Lukker saken.

**Comment by kristoffervp** [comment]
Duplikat av #430  og #388
