### ISSUE TITLE
Mobilvisning bank

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#407]
Beskrivelse av oppg.....
Relatert til brukerhistorie/epos: #
Lenke til design:

- [x] .. Implementer mobil versjonen av bankforhold

- [ ] .. 

- [ ] ..

**Comment by OlgaKoz** [comment]
Testet ok https://teams.microsoft.com/l/file/F026EB75-A26F-4D7B-9E01-50055AEC919A?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FTest%2FTest%20Planer%2FTest%20plan%20Sprint%201%2FTest%20Cases%20Bank.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

**Comment by AinaEngen** [comment]
Mobilvisning for Bank ser helt greit ut - testet på Samsung s20. Lukker denne
