### ISSUE TITLE
Tjeneste for kommune/kommunenr og postnummer/poststed

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#409]
Vi ønsker at kommunenavn blir preutfylt etter kommunenr fylles ut.
Hvilket API bør vi benytte for at dette skal være oppdatert til enhver tid?

Relatert til brukerhistorie/epos: #371 #372
Lenke til design:

- [x] Utforsk

- [x] Implementer

- [x] Trenger også kodeliste for postnummer/poststed (sjekk dette)

**Comment by HenningNormann** [comment]
Foreslår at GUI kaller APIene direkte:

- Kommunenummer swagger: https://ws.geonorge.no/kommuneinfo/v1/#/ eksempel: get/kommuner
- Postnummer, komplett liste: https://www.bring.no/postnummerregister-ansi.txt ytterligere beskrivelse: https://www.bring.no/tjenester/adressetjenester/postnummer/postnummertabeller-veiledning

**Comment by AinaEngen** [comment]
Verifisert ok på Eiendom - lukker saken
