### ISSUE TITLE
Frontend - Om skjema

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#413]
Legg til om siden på skjema
Relatert til brukerhistorie/epos: #371
Lenke til design:

- [x] Lag common trekkspill komponent
- [x] Legg til tekster
- [x] Lag siden

**Comment by OlgaKoz** [comment]
Til info ser mobilvisning slik ut nå:
![Screenshot_2021-09-10-12-31-07](https://user-images.githubusercontent.com/82213706/132842688-db67f8ef-ed0e-48dc-ace7-f9275c7eb0c1.png)
![Screenshot_2021-09-10-12-33-59](https://user-images.githubusercontent.com/82213706/132842695-1dff8dd6-e0ce-4f40-85dc-192234ac62e1.png)
![Screenshot_2021-09-10-12-35-14](https://user-images.githubusercontent.com/82213706/132842731-0cee9f0d-31c8-4861-8e4c-db1dc966b3cd.png)
![Screenshot_2021-09-10-12-45-27](https://user-images.githubusercontent.com/82213706/132842736-59baf16a-5fe9-4e18-b874-3ec8d528a91f.png)

**Comment by OlgaKoz** [comment]
Mobilvisning følges opp i #440
Denne er testet ok for desktop.
