### ISSUE TITLE
Oppgjør

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#42]
#### Epos:

Som en arving 
ønsker jeg å utpeke fullmektig og benytte digital representasjon av skifteattest og fullmakt
slik at jeg kan avslutte boet etter den avdøde

#### Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):
Kritisk

Lenke til målarkitektur:

#### Tilhørende brukerhistorier
#
#
#

**Comment by lillelars** [comment]
Benytter labels i stedet for Epics for fasene. Lukker derfor denne.
