### ISSUE TITLE
Backend - Tilgjengeliggjøre ulike feilmeldinger for frontend

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#424]
Hvis det f.eks feiler ved en bank kontra vs KAR.
Ref:
https://eggedosis.github.io/oed/redirects/design/fortune/bank/default-one-d.html

https://eggedosis.github.io/oed/redirects/design/fortune/bank/none-d.html

Relatert til brukerhistorie/epos: #
Lenke til design:

- [ ] .. 

- [ ] .. 

- [ ] ..

**Comment by HenningNormann** [comment]
Har sjekket inn en endring der det legges med en exception på BankInfo objektet hvis vi ikke får kontakt. Dette kan brukes i GUI i henhold til design i issue. Det andre forholdet som påpekes i issue, kan så vidt jeg skjønne implementeres i GUI uten back-end endringer.
