### ISSUE TITLE
Frontend - Utvikle feilmelding mot 1 bank

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#425]
Nå viser vi feilmelding mot KAR, men trenger dette mot en bank også.

Relatert til brukerhistorie/epos: #
Relatert til brukerhistorie #381 

Lenke til design:

- [ ] .. 

- [ ] .. 

- [ ] ..

**Comment by kristoffervp** [comment]
@AinaEngen @DanRJ kan dere undersøke denne sammen? Litt usikker hva som faktisk er implementert her. Se tilknyttede brukerhistorier for hva vi ønsker av evt. feilmeldinger fra hhv. KAR og hver enkelt bank.

**Comment by kristoffervp** [comment]
Overse forrige kommentar. Erstattes av #430
