### ISSUE TITLE
Tredjeparts bibliotek for Transaksjonshistorikk (Excel, CSV)

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#427]
For transaksjonshistorikk benytter vi per dags dato et tredjeparts bibliotek i _trial_-versjon. Det må undersøkes hvorvidt vi skal gå til innkjøp av en Enterprise-lisense av den aktuelle programvaren eller se etter andre f.eks. Open Source / Free Software alternativer.

Det bør undersøkes med Tjenester 3.0 DevOps-teamet hvorvidt de allerede har tatt i bruk et bibliotek/programvare som kan gjenbrukes av Altinn Dødsbo.

**Comment by HenningNormann** [comment]
Har sendt spørsmål til Rune på vår kanal i Slack.

**Comment by HenningNormann** [comment]
Har ikke fått svar fra Rune. Har sendt spørsmålet videre til Eirik.

**Comment by DanRJ** [comment]
Følg opp med Eirik @DanRJ

**Comment by DanRJ** [comment]
Etter diskusjon med Eirik og Finnur, se slack tråden:
https://altinn.slack.com/archives/C02ESDSJN2H/p1654086783978189

Har vi en del spørsmål vi burde stille og forholde oss til. Jeg antar dette har blitt diskutert tidligere uten at jeg husker det / har vært med på det.

**Comment by DanRJ** [comment]
Vedr. kolonnen "Dato", feltet viser datoer og i visning av denne datoen vil formatet på datoen endre seg utifra brukerens satte visningsspråk. Hvis brukeren har norsk visningsspråk vil datoformat være: 01.02.2022. Hvis brukeren har engelsk (USA) visningsspråk vil datoformatet være: 02/01/2022.

**Comment by DanRJ** [comment]
Her brukes det ClosedXML, det funker fint og denne oppgaven kan lukkes
