### ISSUE TITLE
Utforsk om vi kan gjøre noe med performance 

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#429]
De fleste data fra ulike api'ene vises veldig sent. Spesielt bankdata.
Konkret er dette transaksjonsdetaljer...
Siste status: Sendt over til Tonje.
@HenningNormann legg inn svaret her

Kan vi se om vi kan gjøre noe med dette? Hvertfall så det virker bedre for brukerne.

Relatert til brukerhistorie/epos: #
Lenke til design:

- [ ] Hva kan vi gjøre på T3.0 siden?

- [ ] Hva løses når vi går over til prod?

- [ ] Tilbakemeldinger til KAR/Bankene?

**Comment by kristoffervp** [comment]
Basert på undersøkelser er dette på bakgrunn av testmiljøer og responstider fra spesielt bankenes API-er (i test). Lukkes.
