### ISSUE TITLE
Informasjon om utpekelse av fullmektig

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#43]
#### Brukerhistorie:

Som en... arving 
ønsker jeg informasjon om hva det innebærer å utpeke en fullmektig
slik at jeg... kan ta stilling til om jeg trenger en fullmektig til å gjennomføre oppgjøret.

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

#### Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### TODO - Før ferdigstilling:
Gå opp reguleringer i arveloven

#### Akseptansekriterier (minimum happy-case):
Informasjonen må være i overensstemmelse med ny arvelov knyttet til fullmektig for et dødsbo.
Jeg kan se informasjon om fullmektig og hva det innebærer:
•	behov for fullmakt fra alle arvinger
•	rollen er frivillig
•	boet kan velge om det skal være fullmektig eller ikke
•	typiske oppgaver på vegne av boet
•	alle arvinger kan forestå skifte sammen 
•	Videre saksgang i et arveoppgjør

#### Avklaringer for å få realisere denne brukerhistorien:
Skal domstolene være master for denne informasjonen eller skal vi ha egen info?

#### Scenario x:
Tittel:
Gitt at...
og...
når..
så...

**Comment by curlingnina** [comment]
@kajabystol jeg er usikker på hvilken fase denne brukerhistorien tilhører. Den er tagget med Oppgjør, men siden dette omhandler å gi informasjon til arvingene så lurer jeg på om den heller hører inn i fasen Innledende.

**Comment by TageGitHub** [comment]
Lukket, Videreført i #174
