### ISSUE TITLE
Feilmeldinger på dashboard

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#430]
Tar for seg feilmeldinger på dashboardet.

Relatert til brukerhistorie #381 
Lenke til design: https://eggedosis.github.io/oed/redirects/design/dashboard/na-bank-d.html

- [x] Implementer feilmeldinger mot KAR

- [x] Implementer feilmeldinger mot enkelt bank

- [x] Implementer feilmeldinger mot andre aktører

**Comment by kristoffervp** [comment]
Denne kan tas videre til utvikling. Der vi ikke har definert en spesifikk feilmelding, implementeres i førsteomgang en generisk melding - som evt. på et senere tidspunkt kan revideres.

**Comment by DanRJ** [comment]
denne testet vi vel sammen @AinaEngen ? Kan ikke denne lukkes?

**Comment by AinaEngen** [comment]
Ja, denne kan lukkes da @DanRJ og jeg gikk igjennom alle potensielle steder som feilmeldinger skal dukke opp. Hvis det senere dukker opp en mangel, håndterer vi det da som egen sak.
