### ISSUE TITLE
Tildele rolle som fullmektig 

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#44]
#### Brukerhistorie:

Som en... arving 
ønsker jeg å tildele en person rollen som fullmektig 
slik at denne... kan utføre oppgaver på vegne av boet. 

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

#### Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### TODO - Før ferdigstilling:
Hvilke konsekvenser får dette ift at vi oppretter en ny rolle med tilhørende rettigheter? Hypotese: enkelt å tildele rollen, komplekst å gi rollen rettigheter. 
Dele i to brukerhist: 'som en arving', og 'som en fullmektig'.

#### Akseptansekriterier (minimum happy-case):
Må være i overensstemmelse med ny arvelov som regulerer fullmektig for et dødsbo.
•	Jeg kan legge inn fødselsnummer og navn på den fullmektige
- den fullmektige må bekrefte at hen er fullmektig
•	Jeg kan se en bekreftelse fra fullmektige
•	Jeg kan ikke gå videre før alle arvingene som har signert på skifteattesten har valgt den sammen personen som fullmektig (samtykke/signering)

#### Avklaringer for å få realisere denne brukerhistorien:
Gå opp arveloven.

Nødvendig å få klarhet i hva som ligger juridisk og praktisk i å bruke signering kontra fullmakt kontra samtykke kontra andre godkjenningsmønstre for å gjøre forskjellige valg i OED.

Fullmektig-side bør inneholde denne informasjonen:
Fullmektig for bo: Navn (fnr) på den person som er valgt som fullmektig ('Ingen fullmektig er valgt' dersom dette ikke er gjennomført enda. 
Foreslå ny fullmektig: Felter for Fnr og Etternavn som fylles ut av den som initierer prosess for å utpeke fullmektig + Knapp 'Innhent samtykke fra andre arvinger' (dvs samtykke om at foreslått fullmektig faktisk blir fullmektig for bo)
Trekk tilbake fullmakt: Knapp 'Innhent samtykke fra andre arvinger' (dvs samtykke om å trekke tilbake fullmakt)

Mulig prosess:
1. Forutsetning: Skifteattest er utstedt
2. Valgfri arving foreslår person som fullmektig ved å legge inn fnr + etternavn i OED. 
3. Varsel går ut til alle arvinger om at de må samtykke i dette. Varsel inneholder essensiell informasjon om hva det innebærer og hvordan valg foretas og informasjon om hvor mer informasjon kan finnes dvs #43
4. Når alle arvinger har samtykket til en og samme fullmektig går varsler ut til alle arvinger om at valg er foretatt.
5. Videre er med dette digital representasjon av fullmektig etablert via Altinn autorisasjon og aktører får notifikasjon via API

Logg oppdateres med alle stegene over. 

Det må også etableres en egen prosess for å trekke tilbake fullmakt som er tilsvarende prosess over. Men at endepunkt for prosess da er at fullmakt er trukket tilbake. 
Deretter kan prosess over gjennomføres for å tildele fullmakt til ny fullmektig

Alternativt kan et steg innføres mellom steg 3 og 4 over dersom en smidig vil velge en annen fullmektig enn den som er foreslått:
3b. Dersom en arving i steden foreslår et nytt fnummer + etternavn går nye varsler ut til alle arvinger. Feltet hvor en skal fylle inn fnr kan også være en dropdown som inneholder de forskjellige arvingene + verdien 
Alternativt i den andre enden ifht smidighet, dersom en vil ha full kontroll med hva brukerne gjør så bør muligheten til å legge inn nytt forslag på fullmektig låses / ikke være mulig når et forslag er sendt ut inntil alle har samtykket eller forslag er kansellert. Vil gi mest kontroll på prosess + minst smidig. 
Fullmektig-side bør inneholde denne informasjonen:
Fullmektig for bo: Navn (fnr) på den person som er valgt som fullmektig ('Ingen fullmektig er valgt' dersom dette ikke er gjennomført enda. 
Foreslå ny fullmektig: Felter for Fnr og Etternavn som fylles ut av den som initierer prosess for å utpeke fullmektig + Knapp 'Innhent samtykke fra andre arvinger' (dvs samtykke om at foreslått fullmektig faktisk blir fullmektig for bo)
Trekk tilbake fullmakt: Knapp 'Innhent samtykke fra andre arvinger' (dvs samtykke om å trekke tilbake fullmakt)

#### Scenario X:
Tittel:
Gitt at...
og...
når..
så...

**Comment by curlingnina** [comment]
@lillelars og @JanAage99 ref at vi har som mål å scope ned MVP: ber dere vurdere å sette alternativ 3b on hold.

**Comment by TageGitHub** [comment]
Videreført i bh #176

**Comment by TageGitHub** [comment]
Overføres til #176, #215, #216
