### ISSUE TITLE
Kjøretøy på landingssiden - Listepris endrer seg 

### ISSUE THREAD

**Issue by OlgaKoz** [Altinn/oed#441]
I landingssiden, seksjon "Kjøretøy" listepris på Kjøretøyene endrer seg når brukeren klikker på andre skjermbilder

Steg for å gjenskape:
1.  Logg på i OED som arving 
2.  Kontroller/ ta skjermdump av Listepris på Kjøretøy i landingssiden
3.  Klikk deg bort på en annen skjermbilde (f.eks Detaljert oversikt Bank)
4.  Gå tilbake til landingssiden og kontroller listepris på kjøretøyene nå

Resultat:
Oversikten viser listepris som er forskjellig fra listeprisen fra steg 2.
Forventet resultat: Listepris på kjøretøy består 

**Skjermdump av feilen**
Skjermdump fra steg 2, arv etter Jenny Hex
![Skjermbilde 2021-09-17 kl. 12.43.12.png](https://images.zenhubusercontent.com/60780fbb8c86432adea47a17/80ae7a02-e0b5-4f27-b130-ffab7fea4529)
Skjermdump fra steg 4
![Skjermbilde 2021-09-17 kl. 12.44.15.png](https://images.zenhubusercontent.com/60780fbb8c86432adea47a17/7d9526d0-e204-4a5d-81a7-54f24e7e789b)

**Comment by DanRJ** [comment]
Dette er intentional, det er fordi vi ikke har noen kobling for å hente ut listepris og vi ønsket en statisk pris visning. Jeg la til ulike priser som blir satt på hvert kjøretøy på sidevisning. Det er random.

**Comment by lillelars** [comment]
Listepris utgår pga vi ikke fåt dette fra SKE. Lukker saken.
