### ISSUE TITLE
Registrere testament

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#445]
## Brukerhistorie

> Som en arving
> ønsker jeg å registrere testamenter som ikke er oppbevart hos en av Norges tingretter
> slik at jeg, eventuelle andre arvinger og tingretten får kjennskap til den/disse

### Løsningsbeskrivelse
Lages som en egen tjenesten/app ved bruk av Tjenester 3.0 standard komponenter.

Bruker skal kunne sende inn kjennskap til **ett** nattbordstestament per innsending. Arvinger kan sende inn så mange ganger de ønsker.

![image](https://user-images.githubusercontent.com/39513382/145548202-8460618d-0709-4cb5-a37f-820d8932911f.png)

Lenke til design:
https://www.figma.com/file/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=5565%3A52037

### Akseptansekriterier

A) Gitt at jeg er en arving og registrerer testament, 
så skal jeg ha mulighet til å laste opp en kopi av testamentet

### Tilleggsinformasjon
Testament

I Norge er det ingen krav til hvor et testament kan oppbevares, derfor varierer det også hvordan dette gjøres. De vanligste løsningene er å oppbevare testamentet hjemme, i bankboks, hos en slektning, hos en advokat eller i tingretten.

Spørsmål 18: Godtar retten skjema fra arvingene oversendt per e-post?

Svar: Nei. Skjema og testament må innleveres eller sendes retten i original. Vi godkjenner ikke dokumenter som oversendes per e-post.

Spørsmål 25: Hvem kan få utlevert kopi av et testament?

Svar: Du kan få utlevert kopi av testamentet dersom testator er død og du er arving etter loven, eller om du er tilgodesett i testamentet.

**Comment by DanRJ** [comment]
Done, avtalt med Kristoffer
