### ISSUE TITLE
Registrere ektepakt

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#447]
## Brukerhistorie

> Som en arving
> ønsker jeg å registrere ektepakter som ikke er tinglyst i ektepaktregisteret (løsøreregisteret)
> slik at jeg, eventuelle andre arvinger og tingretten får kjennskap til den/disse

### Løsningsbeskrivelse
Lages som en egen tjenesten/app ved bruk av Tjenester 3.0 standard komponenter.

### Akseptansekriterier

A) Gitt at jeg er en arving og registrerer ektepakt, 
så skal jeg ha mulighet til å laste opp en kopi av ektepakten

**Comment by lillelars** [comment]
ferdigstilt.
