### ISSUE TITLE
Info om forhåndsfastsetting skatt

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#45]
#### Brukerhistorie
Som en arving 
ønsker jeg informasjon knyttet til forhåndsfastsetting av skatt
slik at jeg kan få hjelp til å beregne hvor mye jeg må avsette (før fordeling av arven)

**Krav/akseptansekriterier**  
Gitt at jeg ønsker informasjon om å beregne forhåndsfastsetting av skatt.
Når jeg leser innledende informasjon i Altinn dødsbo 
så ser jeg tekst om forhåndsfastsetting av skatt
og
jeg kan velge å klikke meg inn på Skatteetatens sider for å få mer informasjon om dette
og
jeg kan laste ned 'skattemelding-for-forhandsfastsetting'

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): under avklaring
Avklaringsområder: 
- [ ] Skal Skatteetaten  eie/vedlikeholder info? JÅB

Dokumentasjon

- Data som kan mottas fra skatt pr 02.12.2020

https://teams.microsoft.com/l/file/319BCB85-93D1-4251-B236-21B186627912?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FDokumentasjon%20fra%20eksterne%20akt%C3%B8rer%2FReferater%20og%20teknisk%20dokumentasjon%2FSKS%2FAPI%20-%20Skatt.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

- Forhåndsfastsetting av skatt pr 02.12.2020
https://www.skatteetaten.no/skjema/skattemelding-for-forhandsfastsetting/

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder: 
Kan vi hente info direkte fra Skatt som vi presenterer ? Jan Å
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): bør
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

- KK: Ved gjevne tidspunkt, sjekke, rapporterer og har mulighet til å endre 'råtne' linker

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by kajabystol** [comment]
Må gåes opp med Skatt - veiledning

**Comment by curlingnina** [comment]
@JanAage99 ref din kommentar om det kan hentes data direkte fra SKS. Dette må diskuteres med deres tekniske ressurs (er pt ikke allokert). Det beste hadde vært om vi fikk til en automatisert prosess for beregning av forhåndsskatt, men det har aldri vært diskutert med SKS.

**Comment by curlingnina** [comment]
@jan åge og @benedicteos kan dere oppdatere denne BH når avklaringene med Skatt er landet?

**Comment by JanAage99** [comment]
Tror neppe det blir noen oppdatering på denne da Skatts prosess ganske sikkert fortsatt er den samme. Men vi kan jo uansett se om vi får skivset inn spørsmål på tirsdag om det. Ellers kan jeg jo bare fyre avgårde en forespørsel til han som var i møtet i høst fra Skatt om tema. Tror han kom fra Skatt avd Nordfjordeid. Husker jeg snakket med ham om Ronny Heggen taxi-eier i Eid, felles bekjent.

**Comment by curlingnina** [comment]
@TageGitHub du må oppdatere flytskjemaet slik at det er korrekt ift denne BH.

**Comment by kristoffervp** [comment]
Dette leveres ikke fra SKD ifbm. MVP.

**Comment by TageGitHub** [comment]
Ikke del av MVP
