### ISSUE TITLE
Vise informasjon om innhentet testament fra DA

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#454]
Beskrivelse av oppg.....
Relatert til brukerhistorie/epos: #
Lenke til design:

- [ ] Vise informasjon om innhentet testament fra DA (Tenker vi avventer med denne inntil videre)
- [x] Ikke vis knapper før responsen har kommet

**Comment by DanRJ** [comment]
Vi oppretter ny når DA integrasjon er på plass.
