### ISSUE TITLE
Alle forestår skifte sammen

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#46]
#### Brukerhistorie
**Intro**
Som en arving 
ønsker jeg at kun de  som har påtatt seg gjeldsansvar forestår skifte sammen 
slik at alle utfører oppgaver på vegne av boet

**Krav/akseptansekriterier**
•	Jeg kan se hvem som har påtatt seg gjeldsansvar (#221)
JÅB: Med dette menes å se hvem som har påtatt seg gjeldsansvar både før skifteerklæring er oversendt, før skifteattest er mottatt og etter at skifteattest er mottatt ? 
•	Jeg trenger ikke å gjøre et valg i tjenesten ELLER 
•	Jeg kan velge at alle forestår skifte sammen - 
JÅB: Blir ikke dette automatisk konsekvensen når skifteattest er utstedt og fullmektig ikke er valgt ? Trenger altså ikke å velge dette eksplisitt at alle forestår skifte sammen. 

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 

- [ ] Det er kun slektsarvinger som i utgangspunktet skal få formuesfullmakt (dvs. ikke testamentarvinger? )

- [ ] Hvilken funksjonalitet ønsker vi i denne brukerhistorien?

- [ ] JÅB: Dersom en velger å forestå skifte sammen, dvs at fullmektig ikke velges; Bør aktørene da få tilgang til hvem arvingene er (fnr) via API slik at aktørene kan verifisere at rette vedkommende forestår skifte / ber om skifte/oppgjør hos den enkelte aktør 

Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by kajabystol** [comment]
Uavklart. Hvis arvingene skal forestå skifte sammen vil det ikke være nødvendig å foreta et valg? 
Slik som feks bare 1 arving i et bo. Da vil vel denne arvingen automatisk være «fullmektig»?

**Comment by TageGitHub** [comment]
Dersom man er Arving i OED, Har man automatisk formuesfullmakt dvs. informasjon kan hentes inn til boet?

**Comment by curlingnina** [comment]
> Dersom man er Arving i OED, Har man automatisk formuesfullmakt dvs. informasjon kan hentes inn til boet?

@TageGitHub Ja
