### ISSUE TITLE
Spinner / loading bar ved innlasting av data

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#466]
Alle steder vi henter inn data fra eksterne aktører bør det være en spinner/loading bar eller lignende for å bedre brukeropplevelse.

- [x] Estimere oppgaven
- [x] _TBD_

**Comment by DanRJ** [comment]
Denne er ferdig, alle steder vi laster inn relevant informasjon skal vise en spinner

**Comment by AinaEngen** [comment]
Ok, ser spinner der det er relevant;
Ektepakt - ok
Må testet på nytt igjen senere når integrasjonene er oppe:
Skatt
Eiendom
Kjøretøy
Bank
Forsikring
