### ISSUE TITLE
Beskrive de ulike navnene fra ulike koder fra rettigheter kartverket

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#469]
Når vi får inn ulike RegisterenhetsrettstypeKode så bør vi vise om det er "Eiendomsrett" (E), "Festerett" (F), "Fremfesterett" (F1) "Fremfesterett 2 (F2)", "Frefesterett 3 (F3)","Borett" (B).

Disse begrepene skal også forklares med en hover.

https://www.grunnbok.no/grunnbok/modell/grunnbok-domene-v2-modell/index.html?goto=3:274

![image](https://user-images.githubusercontent.com/39513382/137742939-d2dd6c36-9d7d-4c91-a413-9f3b906c5db8.png)

Relatert til brukerhistorie/epos: #
Lenke til design:

- [ ] .. 

- [ ] .. 

- [ ] ..

**Comment by DanRJ** [comment]
Denne må vi spesifisere i mer detalj.
Vi har ingen beskrivelse tilknyttet en av kodene ovenfor og hvis vi ønsker å ta i bruk eventuelle beskrivelser fra grunnboken, må vi potensielt gjøre de mer lesbare

**Comment by kristoffervp** [comment]
Dette løses i forbindelse med innholdsdesign-arbeidet og klart språk. Lukker utviklingsoppgaven.
