### ISSUE TITLE
Ektepakt - skal ikke kunne registrere frem i tid

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#472]
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/0d04f1fc-59dd-4078-90c1-42bd1e355f2b)

**Beskriv feilen**
Testet i .... browser

**Gjenskape feilen**
Steg for å gjenskape:
1. 
2. 
3. 
4. 

**Skjermdump av feilen**

**Comment by lillelars** [comment]
re-tester når ferdig implementert. Per nå vises fortsatt alle feilmeldinger ved klikk på fremtidig dato.

**Comment by DanRJ** [comment]
Nå er datepicker today implementert, og det skal ikke være mulig å velge fremtidig dato (dette gjelder kun ektepakt for nå da de andre små appene som bruker datepicker ikke har blitt oppdatert). Man kan fortsatt skrive inn fremtidig dato men da skal det dukke opp en feilmelding og man skal få opp feilmeldinger når man prøver å sende inn.

**Comment by lillelars** [comment]
Dette funker som det skal! Lukker saken.
