### ISSUE TITLE
Dokumentasjon av Altinn Dødsbo

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#478]
Det må opprettes et sted for å samle all teknisk dokumentasjon for Altinn Dødsbo-tjenesten. 
For eksempel ved at det opprettes en egen GitHub-side. Det er viktig at det lages rutiner/guider slik at eksterne aktører kan hente opp relevant informasjon (eks. hvis flere banker skal kobles på løsningen).

Vi dokumentere her:
[Lenke til dokumentasjon](https://teams.microsoft.com/l/file/42BE2476-B4B0-40E1-AD56-014009DBAC67?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FTeknisk%2FDokumentasjon%2FOED%20applikasjonsarkitektur.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

[Lenke til dokumentasjon på docs](https://docs.altinn.studio/nb/app/launched-apps/digdir/oed/)

)
- [x] Sjekk med Eirik om hva og hvordan vi skal dokumentere løsningen vår
- [x] dokumenter arkitekturskisser for lovprop 
- [x] Generell teknisk dokumentasjon
- [x] Utforsk hvilke juridiske skille må vi se på? Tjenesteeier vs 
- [x] Utviklingsdokumentasjon - Hvis en annen utvikler skal komme inn i prosjektet - Hva trenger vedkommende?
- [x] Hvor sikker er tjenesten? Hvordan benytter vi maskinporten for aut/auth
- [x] Ta en gjennomgang av dokumentasjon for frontend
- [x] Opprette område og dokumentasjon på Altinn Docs
- [x] Guide: Hvordan sette opp en ny underapp i Altinn Dødsbo
- [x] Guide: Hvordan sette opp utviklingsmiljø (lokalt) for Altinn Dødsbo?
- Arkitektur
- Forvaltning og videreutvikling av dette
- Hvordan er dette bygd opp? Backend/Frontend?

**Comment by tblix** [comment]
en måte å tenke på i allefall :) https://c4model.com

**Comment by lillelars** [comment]
@AinaEngen Kanskje det er lurt om du legger til noe om Test og teststrategi i dokumentasjonsarbeidet vårt

**Comment by kristoffervp** [comment]
@DanRJ @HenningNormann se tasks i beskrivelsen til Issue. Dette må også dokumenteres på Altinn Docs. 
Hvor det kan lenkes til A3-dok gjør det, men det som er spesifikt for OeD må spesifiseres i vår dokumentasjon.

**Comment by HenningNormann** [comment]
Har lagt inn pull request nr470 i altinn docs.

**Comment by TageGitHub** [comment]
utgår
