### ISSUE TITLE
Arving under 18 år

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#48]
#### Brukerhistorie:

Som en arving 
ønsker jeg å vite saksgangen hvis en arving er under 18 år 
slik at jeg tar hensyn til dette i arveoppgjøret

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):

•	Jeg kan se informasjon om bestemmelser ved arving under 18 år 

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by TageGitHub** [comment]
Verken barn under 18, særkullsbarn under 18 år, eller verge av barn under 18 år ed med i MVP ref Nina
