### ISSUE TITLE
Visning av hvilke eiendomer som er landbrukseiendom

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#480]
Vi trenger en logo eller i minste fall en egen seksjon som viser hvilke eiendomer fra kartverket som er landbrukseiendomer...

Relatert til brukerhistorie/epos: #
Lenke til design:

- [ ] Vise denne dataen på skifteerklæringssiden

- [ ] Implementere en visning av at det er en landbrukseiendom på kartverket sin side (Dan-design-company)

- [ ] ..

**Comment by kristoffervp** [comment]
Lukker denne. Revideres eventuelt i forbindelse med neste versjon av Eiendomssidene.
