### ISSUE TITLE
Logge bruker ut av appen

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#483]
Vi har fortsatt ingen måte å logge oss ut av appen.
Dette må vi implementere.

Per nå har vi bare selve logoen - men uten funksjonalitet

Relatert til brukerhistorie/epos: #
Lenke til design:

- [ ] .. 

- [ ] .. 

- [ ] ..

**Comment by DanRJ** [comment]
Dette ligger i planen hos T3.0:
https://github.com/Altinn/altinn-studio/issues/6815

Det er ikke noe vi får gjort med per nå.

**Comment by DanRJ** [comment]
T3.0 har implementert det å logge seg ut, det er delvis implementert i appen vår men det ser forferdelig ut, jeg utvikler en pen versjon
