### ISSUE TITLE
Legge til listeelement uten dato - på en fin måte

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#485]
Vi trenger en måte vi kan legge til listelement uten at arving behøver å registrere dato... Kommentar?  Boolean?
Dan-the-man will fix!

Relatert til brukerhistorie/epos: #
Lenke til design:

- [ ] .. 

- [ ] .. 

- [ ] ..

**Comment by lillelars** [comment]
Må testes om dette fungerer på vår side også - selv om det meste her bør være løst av T3.0? @DanRJ  ?

**Comment by kristoffervp** [comment]
@DanRJ Kan du ta dette opp med Cecilie og løse dette i designet (les: designe oss rundt denne problematikken) når vi reviderer alle underappene som bruker datovelger.

**Comment by DanRJ** [comment]
Cecilie har designet oss rundt denne problematikken, ref bilde:
![image](https://user-images.githubusercontent.com/3437949/152156078-0431c0b1-d41a-457e-a886-9f574421754e.png)

Ser bra ut, dato velgeren vil alltid være synlig og når man klikker på checkboxen eller datovelgeren vil den tilknyttet checkboxen bli huket av.

@kristoffervp

**Comment by DanRJ** [comment]
Kan denne lukkes da, @kristoffervp ?

**Comment by kristoffervp** [comment]
Denne tar vi opp med Cecilie i Sprint Planning på mandag 14.02.

**Comment by DanRJ** [comment]
Utgår da listeelementer uten dato problemstillingen ikke lenger er aktuelt
