### ISSUE TITLE
Add optional flag "disableFutureDates" to DatepickerComponent 

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#486]
Beskrivelse av oppg.....
Relatert til brukerhistorie/epos: #
Lenke til design:

~~- [ ] Oppdatere [dokumentasjon på altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs/)~~ Steffen hos T3.0 nevnte at den under er mer relevant for nå

- [x] oppdatere [layoutSchema på altinn-cdn](https://github.com/Altinn/altinn-cdn/blob/master/schemas/json/layout/layout.schema.v1.json)

[Lenke til PR](https://github.com/Altinn/altinn-studio/pull/7238/) 

[Følges opp hos T3.0 her](https://github.com/altinn/altinn-studio/issues/7228)

**Comment by AinaEngen** [comment]
@DanRJ - er det denne endringen som gjør at fremtidige datoer ikke kan velges i kalenderen, eller er det noe annet som må testes her?

**Comment by DanRJ** [comment]
Det stemmer @AinaEngen. At man ikke kan velge fremtidig dato i en datovelger. Man kan fortsatt skrive en fremtidig dato men det skal da komme opp en feilmelding

**Comment by AinaEngen** [comment]
Da lukker jeg denne da den er testet ok. Det er ikke mulig å velge fremtidige datoer i datovelger. Kommer korrekt feilmelding når man skriver inn en fremtidig dato.
