### ISSUE TITLE
Veiledning i skifteprosessen Del 1: Send inn opplysninger om avdøde og arvinger

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#489]
## Introduksjon

Denne epicen omhandler tilpassing av forsiden slik at den veileder brukerne gjennom den digitale skifteprosessen mot et privat skifte. Denne Epicen omfatter Del 1 av skifteprossen - "Send inn opplysninger om avdøde og arvinger". I hovedsak erstatter "Del 1" i Altinn Dødsbo det eksisterende skjemaet for Erklæring om privat skifte.

Aktuelt resultatmål: 
Et grafisk grensesnitt for de etterlatte som gir de **oversikt over boet** og **som veileder dem gjennom prosessen**

Relevante lenker:
https://www.domstol.no/arv-og-skifte/dodsfall-og-arv/privat-skifte
https://www.domstol.no/arv-og-skifte/dodsfall-og-arv/forskjellige-former-for-skifte
https://www.domstol.no/arv-og-skifte/dodsfall-og-arv/hvem-er-arvinger

Flytdiagram for informasjonsflyten finnes her:
https://www.figma.com/file/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=6265%3A68638

![image](https://user-images.githubusercontent.com/39513382/146338315-b23bfc27-e0f7-4cd0-b988-65c637f6144c.png)

## Tilleggsinformasjon

Det tilbys per dags dato en løsning for å signere erklæring om privat skifte digitalt som kan benyttes først etter at skjema er sendt inn per brevpost eller e-post, hvor enkelte eller flere av arvingene ber om å få signere digitalt.

Hvis alle arvingene har påtatt seg gjeldsansvaret, vil domstolen sende skifteattesten i løpet av 1-2 uker etter å ha mottatt skjemaet.

Arvingene plikter etter forskrift til arveloven § 8 å oppgi opplysninger om
a. om den avdøde var gift, ugift, separert, skilt, enke, enkemann, samboer eller lengstlevende i et samboerskap
b. navn og fødselsnummer for person som nevnt i bokstav a
c. om den avdøde satt i uskiftet bo etter ektefelle eller samboer
d. dersom den avdøde var skilt, separert eller tidligere samboer, om felleseiet var delt eller om skiftet for øvrig var gjennomført
e. hvem som er arvinger etter den avdøde
f. om den avdøde etterlater seg testament
g. om den avdøde etterlater seg arvinger som er mindreårige eller fratatt rettslig handleevne, og i så fall vergens navn og kontaktopplysninger
h. navn, personnummer og kontaktopplysninger for den som melder opplysningene.

etter samme bestemmelse siste ledd, jf. § 6 bortfaller meldeplikten dersom dette er opplysninger som kan innhentes fra offentlige registre. Legger til til grunn at DA preutfyller alle felter som kan preutfylles, og i de feltene må arvingen ha mulighet til å endre/komplementere opplysningene.

## Funksjonalitet (MVP)

Avdødes sivilstand #515 
Registrere sivilstand til avdød #516 
Integrasjon med DA for avdødes sivilstand _TBD_

Testament og arvepakt #517
Registrere testament #445
Integrasjon med DA for testament _TBD_ 

Ektepakt #518
Registrere Ektepakt #519 
Integrasjon med DA for ektepakt _TBD_ 

Arvinger etter avdøde #520
Registrere arvinger #505 
Integrasjon med DA for arvinger _TBD_ 

Landbrukseiendom #521 
Registrere Landbrukseiendom #522
Integrasjon med DA for landbrukseiendom_TBD_  

Registrere ønske om privat skifte og ikke påta seg gjeldsansvar #375
Registrere ønske om privat skifte og påta seg gjeldsansvar #373

## Funksjonalitet (utenfor MVP)
- Synliggjøring av kontaktperson i boet #30 30
## Funksjonelle krav

Prinsipper og funksjonelle krav for Veileder (1 Sende inn Opplysninger om Avdøde-->Avdødes Sivilstand, Testament og Arvepakt, Ektepakt, Arvinger etter avdøde og Landbrukseiendom):

![image](https://user-images.githubusercontent.com/1841665/144198093-42d86fc3-89fe-44a5-8ba7-2398d9c530ce.png)

Prinsipper og funksjonelle krav for Veileder (3 Signere på ønske om privat skifte):

![image](https://user-images.githubusercontent.com/1841665/144199229-664db272-a342-4176-b137-18e378832485.png)

- Det skal ikke være mulig å endre preutfylt informasjon, det skal kun være mulig å legge til ny informasjon, dersom arving mener den preutfylte informasjonen er feil. All informasjon som ikke er preutfylt (utenom fødselsnummer), hvor arvingene legger inn informasjon selv, skal kunne ses og endres av alle arvinger.
- Minst en av arvingene må påta seg fullt ansvar for avdødes gjeld før Erklæring om privat skifte sendes inn
- Ønske om privat skifte må være signert av en arving som påtar seg gjeldsansvaret innen 60 dager etter dødsfallet
- Arvingene skal fylle ut på samme instans på alle underskjemaer, bortsett fra ønske om/signering på privat skifte som skal være unik per bruker/arving
- Skjemaet skal kunne sendes inn så mange ganger arvingene ønsker
- Samtykke til privat skifte fra verger for arvinger som er mindreårige eller fratatt rettslig handleevne er out of scope
- For all data som eventuelt preutfylles skal det tydelig fremkomme hvem som er kilden

## Design

![image](https://user-images.githubusercontent.com/1841665/144202114-578c9d75-219d-4829-a409-c1db9b6fe76a.png)

https://www.figma.com/file/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=5745%3A54569

## Interessenter
Domstoladministrasjonen
Tingretten
Arvinger

**Comment by TageGitHub** [comment]
ukjent opphav
