### ISSUE TITLE
Som Verge ønsker jeg å logge meg inn i riktig bo

### ISSUE THREAD

**Issue by kajabystol** [Altinn/oed#49]
#### Brukerhistorie:

Som en arving ønsker 
jeg å vite saksgangen hvis en arving har vergemål 
slik at jeg tar hensyn til dette i arveoppgjøret

#68 
#4 

#### Forretningsverdi 4 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:
JÅB: Verge er vel ikke del av MVP ?

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):

•	Jeg kan se informasjon om bestemmelser ved arving med vergemål

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by TageGitHub** [comment]
@curlingnina - Er vergemål del av MVA? (ikke nevnt i MVP beskrivelsen)

**Comment by curlingnina** [comment]
@TageGitHub vergemål er utenfor MVP. Uansett så er det mismatch mellom tittelen og beskrivelsen i denne BH. La den ligge inntil videre.

**Comment by TageGitHub** [comment]
Lukket,  utenfor MVP
