### ISSUE TITLE
Integrasjon mot Sparebank1

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#495]
Vi skal få inn data via API'et til SB1 når de har skrevet under testavtalen.
Relatert til brukerhistorie/epos: #
Lenke til design:
gjenbruk bankdesign as is.
- [ ] .. 

- [ ] .. 

- [ ] ..

**Comment by kristoffervp** [comment]
@AinaEngen kan testes. Sp1 er implementert vha. DAN

**Comment by AinaEngen** [comment]
Testet ok - får inn data fra Sparebank1 når jeg testet med Stein Eidem og dødsbo for Oddvar Muller
