### ISSUE TITLE
Innhenting av kontaktperson fra byråmelding fra DA

### ISSUE THREAD

**Issue by benedicteos** [Altinn/oed#5]
***Beskrive brukerhistorie***

Tidligere:
Aktør involvert: Domstoladministrasjonen

Beskrivelse: Kan være vanskelig for DA å levere kontaktperson for dødsbo fra byråmelding, man vet ikke når man får byråmeldingen. Bør være mulig å legge til kontaktperson fra byråmelding etter hvert? Eller at arvingene selv utpeker en kontaktperson for dødsboet? Må ikke sammenblandes med kontaktperson for dødsbo som kommer fra skifteattest, og som registreres i Folkeregisteret. Denne kontaktpersonen fra skifteattest kommer for sent for å dekke aktørens behov for å ha kontakt med arvingene før skifteattest er utstedt.

Frist:

**Comment by lillelars** [comment]
Kan vi ta et standpunkt hvorvidt dette er et behov eller ikke, så må vi beskrive brukerhistorien :) @JanAage99

**Comment by JanAage99** [comment]
Ble tatt opp i møtet i dag med DA. Vi jobber videre for en god løsning på dette i samarbeid med DA i august

**Comment by benedicteos** [comment]
Når alle arvinger har digital representasjon av formuesfullmakt, er ikke behovet da dekket? Det som gjenstår er eventuelt om aktørene (bank, forsikring m.v.) har behov for en kontaktperson i boet om de skal gjøre noe som omhandler kundeforholdet til den avdøde, og arving har behov for informasjon eller evt. godkjenning. Imidlertid kan nok dette behovet dekkes på annet vis, nå som prosessene effektiviseres og digital representasjon realiseres.

**Comment by JanAage99** [comment]
Aktørene har vel sagt klart ifra at de ønsker en kontaktperson. Det kan jo være tilfeller hvor aktører er i stand til å ta imot informasjon om hvem som er kontaktperson (ren tekstlig info som saksbehandler hos aktør kan lese), men det er ikke sikkert at de dermed er klare for å ta imot den digitale representasjonen (Xacml e.l. maskin-til-maskin basert format). Mulig vi bare skal sette det som krav, altså at det kan mottas som Xacml og ikke mer tekstlig ? Må rafineres og avklares.

**Comment by lillelars** [comment]
Lukker denne - Håndteres i #383
