### ISSUE TITLE
Oppdatere design på testaments app til nytt design

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#504]
Skal løse Brukerhistorie #445

Relatert til brukerhistorie/epos: #
Lenke til design:
https://www.figma.com/file/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=5565%3A52037
- [ ] Oppdatere tekst i "headeren" inne i appen

- [ ] .. 

- [ ] ..

**Comment by kristoffervp** [comment]
Ny revidering kommer til neste Sprint.
