### ISSUE TITLE
Registrere arvinger

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#505]
## Brukerhistorie

> Som en arving
> ønsker jeg å registrere arvinger som ikke har tilgang til Altinn Dødsbo
> slik at Tingretten får opplysninger om øvrige arvinger

### Design

![image](https://user-images.githubusercontent.com/1841665/148928220-1729645f-d5e3-4b8f-8d7e-bb83b3c22d20.png)

### Løsningsbeskrivelse
Lages som en egen tjenesten/app ved bruk av Tjenester 3.0 standard komponenter.

1) Det skal være mulig å registrere så mange arvinger man ønsker per innsending.
2) Følgende felter skal finnes i skjemaet per arvinger:
Fornavn, Etternavn, Fødselsdato og Relasjon til avdøde
3) Relasjon til avdøde presenteres som en liste med følgende alternativer:
Forelder, Søsken, Niese/Nevø, Barn av Niese/Nevø, Barn, Barnebarn, Oldebarn, Ektefelle/Samboer, Tante/Onkel, Fetter/Kusine, Besteforeldre
4) Alle felter er påkrevde

**Comment by DanRJ** [comment]
Første versjon implementert.
Done, avtalt med Kristoffer
