### ISSUE TITLE
Oppdatere design på ektepakt-undertjeneste

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#507]
Beskrivelse av oppg.....
Relatert til brukerhistorie/epos: #519
Lenke til design:
https://www.figma.com/file/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=5565%3A52037
- [ ] .. 

- [ ] .. 

- [ ] ..

**Comment by kristoffervp** [comment]
Lukkes. Cecilie og kommer evt. med revidering ifbm. neste Sprint.
