### ISSUE TITLE
Noen UU-issues med banner

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#513]
**Beskriv feilen**
Testet i chrome
--> @DanRJ  Bør dette evnt gå via designere først?

- [ ] 1) Ved å zoome inn til 175% blir tekstene forskjøvet og relativt "uleselig" - kan vi se om vi kan gjøre noe med dette?
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/98bc0045-48f3-4f11-8c03-c1a55e57f237)

- [ ] 2) Ved å zoome til 200% blir illustrasjonen meget stor og kravene for kontrast mellom bilde og tekst ikke godkjent ![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/e2dee972-54ed-4dcc-97db-140635252434)

**Gjenskape feilen**
Steg for å gjenskape:
1. 
2. 
3. 
4. 

**Skjermdump av feilen**

**Comment by DanRJ** [comment]
Denne skal være fikset nå mtp støtte for 400% mtp WAD / WCAG 2.1.
Får du retestet @AinaEngen ?

**Comment by AinaEngen** [comment]
Testet ok - lukkes
