### ISSUE TITLE
Bostedsadresse dukker opp to ganger

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#514]
**Beskriv feilen**
Testet i .... chrome

Bostedsadresse dukker opp to ganger?

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/3b180097-e598-421c-b8e2-999669c348dc)

**Gjenskape feilen**
Steg for å gjenskape:
1. 
2. 
3. 
4. 

**Skjermdump av feilen**

**Comment by DanRJ** [comment]
Dette er på grunn av testdataen som inneholder den fulle adressen innunder adresse feltet der det hovedsakelig skal stå gatenavn og nummer, ikke poststed og postnummer i tillegg.

Kan lukkes @kristoffervp ?

**Comment by kristoffervp** [comment]
@AinaEngen kan du reteste og bekrefte med muligens andre testbrukere (les: annen testdata)?

**Comment by AinaEngen** [comment]
Dette er nok testdata-relatert.
Adresse ser ok ut på avdøde Mio Sommer og Oddvar Müller, mens Jarle Berger og Jenny Hex ikke har adresse.
Lukker denne, så får vi se om vi fikser opp i adressene senere
