### ISSUE TITLE
Avdødes sivilstand

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#515]
### Brukerhistorie
> Som en arving 
> ønsker jeg å bli informert om arveloven § 8 at jeg plikter å oppgi opplysninger om den avdøde var gift, ugift, separert, skilt, enke, enkemann, samboer eller lengstlevende i et samboerskap
OG informert om hvilke opplysninger det offentlige allerede innehaver
> slik at jeg kan ta stilling til hvorvidt jeg må endre/komplimentere og sende oppdatert informasjon til Tingretten

### Løsningsbeskrivelse

![image](https://user-images.githubusercontent.com/1841665/144201018-549237a1-629d-4f2a-a6e5-7e0ca3b9d953.png)

Oppdatering 18.01:
Vi vil alltid finne noe i FREG. Se tabell under.

....

### Akseptansekriterier
Gitt at det offentlige allerede har/kan innhente opplysningene fra offentlige register (i dette tilfellet Folkeregisteret)
Når jeg som arving benytter Altinn Dødsbo
så skal aktuelle opplysningene hentes og vises preutfylt
og i de tilfeller det ikke finnes informasjon i et offentlig register skal det også opplyses om at Altinn Dødsbo ikke innehaver

### Avklaringspunkter

- [ ] Legge inn designskisse

**Comment by DanRJ** [comment]
@AinaEngen kan du se på sivilstatusene vi får fra FREG og de vi har i underappen, jeg er ganske sikker på at det er vesentlige forskjeller her.

**Comment by DanRJ** [comment]
Denne blir gjort i #619 , denne følger 619

**Comment by TageGitHub** [comment]
Utgår. Videreføres i #619
