### ISSUE TITLE
Testament og arvepakt

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#517]
### Brukerhistorie
> Som ...
> ønsker jeg å ....
> slik at ...

### Løsningsbeskrivelse
![image](https://user-images.githubusercontent.com/39513382/144202082-dcff41dd-9bb3-45c7-9523-6eecd8797609.png)

### Akseptansekriterier
Gitt at..
Når ...
så skal ... 
og...

**Comment by DanRJ** [comment]
Done, avtalt med Kristoffer
