### ISSUE TITLE
Registrer ektepakt

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#519]
### Brukerhistorie

> Som en arving
> ønsker jeg å registrere ektepakter som ikke er oppbevart hos en av Norges tingretter
> slik at jeg, eventuelle andre arvinger og tingretten får kjennskap til den/disse

### Akseptansekriterier
Gitt at jeg ønsker å laster opp en kopi av et testament/ektepakt
Når OG før jeg har lastet opp en kopi
så skal jeg også bli opplyst om at en rett-kopi også må sendes per brevpost i bakhånd av innsendt digitalt skjema

### Design

![image](https://user-images.githubusercontent.com/1841665/148928406-792e28fe-e3e0-4656-a5bf-c17e309de6e5.png)

https://www.figma.com/file/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=5565%3A52037

### Løsningsbeskrivelse

Lages som en egen tjenesten/app ved bruk av Tjenester 3.0 standard komponenter.

### Tilleggsinformasjon
Ektepakt

Loven stiller ikke opp spesielle krav til hvorledes ektepakten skal oppbevares. Dette vil normalt heller ikke være noe stort poeng, idet ektepakten som forutsetning alltid bør tinglyses i Ekteskapsregisteret, selv om dette ikke er nødvendig for gyldigheten av ektepakten mellom ektefellene eller i forhold til deres arvinger.

Dersom ektepakten ikke er tinglyst, bør den oppbevares på et trygt sted, helst en bankboks som begge ektefelle disponerer, med en kopi i hjemmet. Begge ektefeller bør i så fall ha en bekreftet kopi av originalen med påtegning om hvor originalen befinner seg.

**Comment by DanRJ** [comment]
Første versjon implementert
Done, avtalt med Kristoffer
