### ISSUE TITLE
Arvinger etter avdøde

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#520]
### Brukerhistorie
> Som ...
> ønsker jeg å ....
> slik at ...

### Løsningsbeskrivelse
![image](https://user-images.githubusercontent.com/39513382/144203303-4de87a7f-808b-4206-bf1f-239467535076.png)

### Akseptansekriterier
Gitt at..
Når ...
så skal ... 
og...

**Comment by DanRJ** [comment]
Implementert første versjon
Done, avtalt med Kristoffer

**Comment by DanRJ** [comment]
Utgår etter avtale mellom oss og DA. DA sender arvinger og vi legger de på instansen. Dette er implementert i #171

**Comment by TageGitHub** [comment]
ok

Fra: DanRJ ***@***.***>
Sendt: tirsdag 12. september 2023 13:39
Til: Altinn/oed ***@***.***>
Kopi: Bryn, Tage ***@***.***>; State change ***@***.***>
Emne: Re: [Altinn/oed] Arvinger etter avdøde (Issue #520)

[ Ekstern e-post ]

Closed #520<https://github.com/Altinn/oed/issues/520> as completed.

-
