### ISSUE TITLE
Landbrukseiendom - veileder

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#521]
### Brukerhistorie
> Som ...
> ønsker jeg å ....
> slik at ...

### Løsningsbeskrivelse
![image](https://user-images.githubusercontent.com/39513382/144203910-049e3635-f3d2-4043-94a5-d4b34862b3ae.png)

### Akseptansekriterier
Gitt at..
Når ...
så skal ... 
og...

**Comment by DanRJ** [comment]
Done, etter avtale med Kristoffer
