### ISSUE TITLE
Registrer landbrukseiendom - underapp

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#522]
### Brukerhistorie
> Som en arving
> ønsker jeg å registrere informasjon om landbrukseiendom
> slik at jeg, eventuelle andre arvinger og tingretten får kjennskap til den/disse

### Akseptansekriterier
Gitt at..
Når ...
så skal ... 
og... 

### Design

![image](https://user-images.githubusercontent.com/1841665/148928676-3d288389-01fd-40c8-abf3-eaa8c90a981a.png)

### Løsningsbeskrivelse
Lages som en egen tjenesten/app ved bruk av Tjenester 3.0 standard komponenter.

**Comment by DanRJ** [comment]
Første versjon implementert
Done, avtalt med Kristoffer
