### ISSUE TITLE
Onboarding: innledende informasjon og veiledning

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#523]
## Introduksjon
Denne epicen omhandler de første interaksjonene med sluttbruker/arvinger når det startes et dødsbo i Altinn.

Aktuelt resultatmål:
Et grafisk grensesnitt for de etterlatte som gir de oversikt over boet og **som veileder dem gjennom prosessen**

## Funksjonalitet (MVP)

SMS/E-post #524 
Melding i Altinn Innboks #525 
Introduksjon til tjenesten #526
 
## Design

SMS:
![image](https://user-images.githubusercontent.com/1841665/144205344-711eedba-e4b2-4957-b108-8c1b5ea3655f.png)

Melding i Altinn Innboks:
![image](https://user-images.githubusercontent.com/1841665/144205400-a36f7f00-ebc6-49d5-9495-1fdff7795815.png)

Introduksjon til tjenesten:
![image](https://user-images.githubusercontent.com/1841665/144205474-0dc2308e-e819-40d1-ac65-9f1f02d9b44a.png)

https://www.figma.com/proto/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=6681%3A84048&scaling=min-zoom&page-id=6265%3A68638&starting-point-node-id=6681%3A84329&show-proto-sidebar=1

## Interessenter
Arvinger

## Avhengigheter/Relasjon
#489

**Comment by TageGitHub** [comment]
utgår
