### ISSUE TITLE
Introduksjon til "Skifte av dødsbo"-tjenesten

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#526]
### Brukerhistorie
> Som arving 
>  ønsker jeg å forstå hva jeg må foreta meg i skifte av dødsbo og hvordan Altinn Dødsbo appen kan brukes
> slik at jeg stiller forberedt når jeg har kommet inn i løsningen

Lenke til design:
https://www.figma.com/file/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=7425%3A103249

Dette er utgangspunktet vi har arbeidet frem til nå - men det kreves en runde til @kristoffervp 
![image](https://user-images.githubusercontent.com/39513382/146765703-22a204e1-8f04-4674-bc5b-99c161c6ac03.png)

### Løsningsbeskrivelse

Vi har jobba med (minst) fire alternativ dei siste vekene:
1. Ingen onboarding i sjølve tenesta, men all informasjonen som brukarane treng i informasjonsbrevet i Altinn. To grunnar til at det er ei middels løysing: Brevet blir litt for langt og overveldande, og det er eigentleg ikkje rom for å gjere slike ting i brevet. 

2. Tre blå ruter med tekst som "overlay" før brukeren får starte. Kanskje den beste løysinga vi har testa, med eitt unntak - folk er utolmodige og vil komme i gang. Dei har allerede lest eit halvlangt brev og er klare til å sjå tenesta og finne ut av ting.

3. Ideen vi diskuterte, men som vi aldri fekk testa, var å låne inspirasjon frå Vibbo (ein OBOS-app for borettslag) sin Hjelp-funksjon. Her dukkar det opp små snakkebobler over dei ulike delane av tenesta, med korte forklaringar til kva og korleis. Det fine med løysinga er at beskrivelsane er kobla direkte til der eg faktisk skal utføre handlingane. Vi (eg og Julie) har trua på å teste ei slik løysing for Skifte av dødsbo

4. Kompromisset til brukertesten 16.desember var å legge skjermbilder av tenesta inn i dei blå rutene, ein variant av alternativ 2 over. Ved sidan av skjermbilda var det forklaringar til kva og korleis, for å gi oversikt og oppfordre til handling. Begge dei to som testa skikkeleg trudde at dei kunne klikke i skjermbilda - dei var utolmodige etter å komme i gang.

Eg har trua på noko i retning alternativ 3 eller 4, men det vil kreve ein del testing og utforsking. Men det er på rett veg!

### Akseptansekriterier
Gitt at..
Når ...
så skal ... 
og...

**Comment by TageGitHub** [comment]
lukkes
