### ISSUE TITLE
Mocke opp testament / arvepakt fra DA

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#530]
Vi ønsker å mocke opp testamentsdata fra DA før DA kommer på banen.
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/441d37ba-5c7b-4402-9505-0ae85a9a0cd7)
Relatert til brukerhistorie/epos: #
Lenke til design:

- [ ] Oppdatere modellen

- [ ] Oppdatere frontend

- [ ] Oppdatere batch i OED

**Comment by kristoffervp** [comment]
@HenningNormann kan du vurdere i dialogen nå videre med DA hvorvidt dette er noe vi skal prioritere eller om vi venter på at de implementerer det faktiske grensesnittet? FYI @DanRJ

**Comment by DanRJ** [comment]
Vi bruker ikke tid på mock, vi fikser dette når vi har koblet oss mot DA

**Comment by kristoffervp** [comment]
Lukkes, vi mocker ikke dette i forkant av integrasjon med DA.
