### ISSUE TITLE
FAQen påvirker høyde på innhold på venstre side av veileder

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#531]
**Beskriv feilen**
På den nye veilederen, når man åpner FAQen på høyre side vil innholdet på venstre side bli høyere.
Dette skal ikke skje, FAQen skal ikke påvirke venstre siden av veilederen.

**Gjenskape feilen**
Steg for å gjenskape:
1.  Gå til ny veileder
2.  Åpne alle FAQ
3.  Se at venstre innhold øker i høyde

**Skjermdump av feilen**
Normalt:
![image.png](https://images.zenhubusercontent.com/5d765941eb71d10001e81ae7/90ad461c-cf84-43e8-87b1-6248d46e34dd)

Feil:
![image.png](https://images.zenhubusercontent.com/5d765941eb71d10001e81ae7/ac5bce4d-583b-4944-a6cd-595ad9fa342b)

**Comment by DanRJ** [comment]
Avventer denne inntil nytt designforslag for Q/A kommer fra Cecilie

**Comment by kristoffervp** [comment]
Enig. Setter denne tilbake til meg og lukker hvis vi faktisk går for å "flytte FAQ-en" eller vice versa.
