### ISSUE TITLE
Finne ut hvem som sendte inn på en app

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#532]
Vi trenger å finne ut hvem som trykket på Send inn knappen og sendte inn informasjon.
Det skal ligge en issue på dette hos Tjenester 3.0.

Navnet skal vises i veilederen når en arving har registrert og sendt inn informasjon via en app.
Relatert til brukerhistorie/epos: #

**Comment by HenningNormann** [comment]
Se kommentar nederst i https://github.com/Altinn/altinn-studio/issues/3116. Ser ut som vi må fikse det selv.

**Comment by HenningNormann** [comment]
Er ferdig implementert i OED-backend. Kan ikke tas i bruk før 3.0 har rettet feil 8000. Jeg har lagt inn pull request 8001 med løsningsforslag.

**Comment by HenningNormann** [comment]
Backend-endring er rullet ut nå.

**Comment by AinaEngen** [comment]
Testet ok - opplysninger om hvem som har sendt inn vises. Lukker issue
