### ISSUE TITLE
Fjern formuesverdi/listepris på eiendom/kjøretøy

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#534]
Informasjon om listepris utgår...
vi må oppdatere designet på denne siden.

Relatert til brukerhistorie/epos: #
Lenke til design:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/c98ca866-4471-4ba4-99c9-37ecc14b93b5)

**Comment by AinaEngen** [comment]
Listepris og formuesverdi er korrekt fjernet fra visning - lukker saken
