### ISSUE TITLE
Veiledning i skifteprosessen Del2: Formue og Gjeld

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#536]
Denne epic'en tar for seg veiledning av DEL 2 i skifteprossen: Formue og gjeld
## Introduksjon
Denne epicen omfatter all informasjon og GUI som går på avsnittet under del 2 i veiledningen.

Relevante lenker:

## Tilleggs informasjon
![image](https://user-images.githubusercontent.com/39513382/146763554-6745f8f4-fb0f-467f-ad0c-7fe37e26021b.png)

## Avhengigheter
- #380 
- #201

**Comment by TageGitHub** [comment]
Ukjent opphav
