### ISSUE TITLE
Veiledning i skifteprosessen Del3: Signer på ønske om privat skifte

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#537]
## Introduksjon
Denne epic'en tar for seg informasjon, veiledning og funksjonalitet for Del 3 av skifteprossen: Signering.

Relevante lenker:

## Tilleggs informasjon

Lenke til design: https://www.figma.com/file/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=6265%3A68638

![image](https://user-images.githubusercontent.com/39513382/146763903-234ca021-99a5-45aa-90f7-9052c52facc2.png)

**Comment by TageGitHub** [comment]
ukjent opphav
