### ISSUE TITLE
Veiledning i skifteprosessen Del 4: Motta skifteattest og gjennomfør skifte

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#538]
## Introduksjon
Denne epic'en tar for seg veiledning, funksjonaltiet og brukergrensesnitt for Del 4 av skifteprosessen: Motta skifteattest og gjennomføring av skifte.
Relevante lenker:

## Tilleggs informasjon
Lenke til design:
https://www.figma.com/file/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?node-id=6681%3A83954

![image](https://user-images.githubusercontent.com/39513382/146764540-afab3a0e-dc12-483e-a078-c7b00f6c191c.png)

## Avhengigheter
 #217 
#173

**Comment by lillelars** [comment]
Duplikat av #217  - lukker saken.
