### ISSUE TITLE
Enhetlig design for aktører innenfor formue og gjeld

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#540]
### Brukerhistorie
Per nå har vi ikke et design som er konsistent gjennom løsningen. Dette må vi se på en gang til - det gjelder undersider til Formue og gjeld. Ref:
![image](https://user-images.githubusercontent.com/39513382/146777259-43cd4aea-5eac-4218-bf7d-609e766f9649.png)

vs
![image](https://user-images.githubusercontent.com/39513382/146777300-7dc109b4-b6fd-4975-abc3-e08a617c3c5c.png)

### Akseptansekriterier
Gitt at..
Når ...
så skal ... 
og...

**Comment by TageGitHub** [comment]
utgår
