### ISSUE TITLE
Fjerne "beregnet formuesverdi" - redesign

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#541]
**Beskriv feilen**
Denne verdien får vi ikke av skatt likevel... Vi må ta en ny runde hvordan dette skal se ut...
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/1ebc10aa-2568-452e-95bc-353d87eea3fb)

**Gjenskape feilen**
Steg for å gjenskape:
1. 
2. 
3. 
4. 

**Skjermdump av feilen**

**Comment by kristoffervp** [comment]
Erstattes av #534
