### ISSUE TITLE
Verifisering av UU mot Wcag 2.1

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#542]
Vi må teste dette skikkelig. Dette er ikke prioirtert inn hittil.

https://www.uutilsynet.no/fremtidig-regelverk/wcag-21-standarden/140

Lenke til design:

- [ ] .. 

- [ ] .. 

- [ ] ..

**Comment by kristoffervp** [comment]
@AinaEngen @DanRJ dere bør synke rundt hvordan vi setter opp gode tester på dette. Er også relevant ifbm. det Daniel jobber med i inneværende Sprint.

**Comment by DanRJ** [comment]
Vi hadde møte med Lasse idag, og fikk tips om ymse verktøy, vi skal ha møte med han imorgen for å teste løsningen vår for UU, jeg ser allerede en del ting vi må forbedre, jeg har laget følgende liste over de nye kravene som vi må undersøke nærmere eller som vi kan ignorere:

1.3.4: Visningsretning
- Vi støtter dette mtp responsiv design per dags dato 2.2.2022

1.3.5: Identifiser formål med inndata
- Såfremt vi ikke har skjemaelementer i hovedappen, ligger ikke dette ansvaret på oss da skjemaene våre ligger hos T3.0

1.4.10: Dynamisk tilpasning
- Vi støtter dette mtp responsiv design per dags dato 2.2.2022

1.4.11: Kontrast for ikke-tekstlig innhold
- Vi støtter dette per dags dato 2.2.2022

1.4.12: Tekstavstand
- Usikker, må undersøkes

1.4.13: Pekerfølsomt innhold eller innhold ved tastaturfokus
- Her må vi sjekke om informasjonsboksene våre oppfyller kravene og evt fikse slik at de oppfyller kravene.
Jeg er usikker på om vi har andre steder dette er relevant

2.1.4: Hurtigtaster som består av ett tegn
- Vi har ingen hurtigtaster så denne gjelder ikke oss

2.5.1: Pekerbevegelser
- Ettersom vi ikke har spesiell funksjonalitet der man må bruke flere pekerinput samtidig, gjelder ikke dette kravet for oss.

2.5.2: Pekeravbrytelse
- Denne må undersøkes mtp input de ulike stedene man åpner bokser / navigerer seg andre steder.

2.5.3: Ledetekst i navn
- Denne må undersøkes mtp lenker og knapper i løsningen, der man navigerer seg / åpne / lukker bokser.

2.5.4: Bevegelseaktivering
- Usikker på om dette kravet gjelder for vår del, da eksemplene UU tilsynet kommer med, burde ligge i nettleseren.
Vi forhindrer ihvertfall ikke funksjonaliteten nevnt i eksemplene.

4.1.3: Statusbeskjeder
- Denne må implementeres mtp ventetilstand / at det finnes feil, usikker på om vi må støttte framdriften av en prosess da vi forsåvidt ikke har funksjonalitet for å starte en prosess
https://github.com/Altinn/oed/issues/466
https://github.com/Altinn/oed/issues/430
Dette kravet gjelder for all henting av data og feil tilknytttet dette.

**Comment by DanRJ** [comment]
Det er potensielt en del oppgaver her som vi burde lage for seg selv / samle oppgave, men jeg er litt usikker på hvordan vi skal gå frem @kristoffervp @AinaEngen  hva tenker dere?

**Comment by kristoffervp** [comment]
#466 og #430 tas videre til utvikling. Øvrige oppgaver legges under en epic (samlesak) for WCAG 2.1 og prioriteres evt. i neste Sprint Planlegging mandag 14.02.

**Comment by DanRJ** [comment]
Denne kan lukkes ref #558
