### ISSUE TITLE
Pdf av innsendt skjema mangler innhold

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#543]
Pdf av innsendt skjema mangler innhold, den viser kun overskrift/header.
Gjelder pdf man åpner fra kvittering for både innsendt Testamente og Sivilstand

![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/f1c01ef5-0056-482d-b42f-2ecdeb04dced)

Spørsmål også stilt i Slack: https://altinn.slack.com/archives/C02ESDSJN2H/p1640082773051000

**Gjenskape feilen**
Steg for å gjenskape:
1. Åpne Sivilstand eller Testament skjema
2. Fyll ut og Send Inn
3. I kvitteringssiden - åpne pdf 
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/9ba42b1d-8c8c-4771-9186-eddfe897d91d)

**Comment by AinaEngen** [comment]
Denne er også fortsatt aktuell - gjelder også kvittering fra Signering @kristoffervp

**Comment by kristoffervp** [comment]
Se også følgende Slack-samtale: https://altinn.slack.com/archives/C02ESDSC929/p1643277106031400

@DanRJ Følger du opp med T3.0?

**Comment by DanRJ** [comment]
Denne skal være løst nå @AinaEngen

**Comment by AinaEngen** [comment]
Testet ok, lukker bug
