### ISSUE TITLE
Arvinger - mangler en arving i visningsliste

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#546]
Logge inn som Stein Eidem - 01066800187
Velg Oppgjør etter Oddvar Muller i innboks
Gå til Arvinger

Her vises ei liste over arvingene som er registrert:
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/b1d39d86-c568-4f31-a361-e0cb6b8d092f)
 
Trykker på «Fortsett på utkast til arving»
Får opp oversikt over de arvinger som er registrert, men her vises ikke Stein Eidem (som jeg er innlogget som og som vises i forrige oversikt). 
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/a79f49ba-7d74-4204-aa94-ab3c74b4ff7d)

Alle arvingene burde vel komme opp i denne lista?

**Comment by DanRJ** [comment]
Ja, Stein Eidem er en arving hentet fra Folkeregisteret og kan ikke endres på, de andre arvingene er innsendt fra en arving. Så dette er korrekt oppførsel.

**Comment by AinaEngen** [comment]
Lukker bug
