### ISSUE TITLE
Får tom rad i oversikt over arvinger når man starter å registrere ny arving

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#547]
Kan gjenskapes ved å logge inn som Stein Eidem - 01066800187
Velg Oppgjør etter Oddvar Muller i Innboks
********

Trykker på «Legg til ny arving»: 
Ser ut som det ligger en tom rad til slutt der. Ikke så synlig i full skjerm visning, men det er veldig synlig i mobil visning. Se bilder under
Slik vises det i full skjerm visning:
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/93c7a816-380e-4428-9397-bfb8d7ece35b)

Slik ser det ut på mobilvisning:
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/38a98273-7b1c-4d87-9e0f-c26ac7ad6839)

Trykket på «Rediger» på det tomme feltet og får da masse feilmeldinger på feltene under, så det viser at det er raden for det elementet man er i ferd med å registrere:
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/283c8ca8-50c5-40c0-960e-60bb3620c98c)

Denne raden bør ikke vises før man har registrert og lagret en ny arving?

**Comment by kristoffervp** [comment]
Er dette noe vi har innført i implementering av appen eller er dette en "feature" hos Tjenester 3.0? Hvis sistnevnte må vi spille denne inn til deres backlog. Sjekker du og gir beskjed @DanRJ

**Comment by kristoffervp** [comment]
Dette er forventet oppførsel iht. Tjenester 3.0. Vet at det arbeides med nye versjoner av repeterende tabeller som eventuelt utbedrer dette på sikt. 

Ikke høyt prio for OeD. Legger derfor i backlog.
