### ISSUE TITLE
Får feilmelding ved innlogging etter time out

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#548]
Får feilmeldingen "Ukjent feil" når jeg forsøker å logge meg inn i Altinn etter at sesjonen min har timet ut.
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/123f37e5-9efa-49a3-8337-01f65fb1b20a)

I Altinn 2/3 så kommer man tilbake til der man var i løsningen hvis man logger seg inn igjen etter time out. 

For å gjenskape denne må man logge seg inn i Altinn og velge et oppgjør, og la dette stå urørt i 1 time(??) - litt usikker på timeout-tiden i TT02....

**Comment by HenningNormann** [comment]
Feilen ligger i Altinn II. Har opprettet bug57823 - https://dev.azure.com/digdir/Altinn/_workitems/edit/57823.

**Comment by HenningNormann** [comment]
Jeg har fikset bug57823 med PR5718. Denne kommer med Altinn II V22.2 - TT02 7. februar. Den er nå hotfikset og verifisert i TT02, men eventuelle nye deployer før 7.2 vil overskrive hotfiksen. @AinaEngen, hvis du vil verifisere før deploy, så kan vi avtale at jeg sørger for at hotfiks er på plass i forkant.

**Comment by kristoffervp** [comment]
@AinaEngen Du kan reteste denne i TT02 nå. Den skal være hotfixed.

**Comment by AinaEngen** [comment]
Har retestet i dag med to scenarier - Innlogget som Stein Eidem (01066800187), dødsbo til Niclas Trones

1) Stod inne i Kjøretøy-oversikten når jeg timet ut => Testet både i Edge og Firefox
    Edge: Kom tilbake til Kjøretøy etter ny innlogging og oversikt over kjøretøy ble korrekt lastet opp
    Firefox: Kom tilbake til Kjøretøy etter innlogging, men oversikten over kjøretøy ble ikke lastet opp. Fikk bare opp overskrift og  tekst

2) Stod inne i Kvitteringssiden i en app (Arvinger) => Her får jeg fortsatt Ukjent Feil når jeg har logget inn på nytt etter time out (både Edge og Firefox)
Skal sjekke hva som skjer med en 3.0 app når jeg står i kvittering og timer ut

**Comment by HenningNormann** [comment]
Timeout fra kvitteringsside: Dette ser ut til å være en T3.0 bug. Jeg har opprettet https://github.com/Altinn/altinn-studio/issues/7963. Daniel lager en pull request.

**Comment by kristoffervp** [comment]
Setter tilbake til backlog. Daniel tar fatt på denne når pull request er godkjent og vi har oppdatert vår app med siste endringer (etter fiks)

**Comment by DanRJ** [comment]
Her er PR hos T3.0:
https://github.com/Altinn/altinn-studio/pull/8039/

**Comment by DanRJ** [comment]
PR er inne, det ligger inne og skal være løst

**Comment by AinaEngen** [comment]
Har retestet timeout fra kvitteringsside, og nå fungerer OED-app'er og 3.0 app'er likt; kommer tilbake til kvitteringsside etter timeout. Lukker bug.
