### ISSUE TITLE
Mobilvisning av forside/veileder, og innspill til forbedringer, samt bugs funnet i førsteversjon

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#551]
Generell test av veileder på mobil
(testet i Chrome med F12, valgt Samsung S20 størrelse)

[ ] **Header i veileder**
* Hvit tekst over bildet blir lite synlig når det treffer et lyst/hvitt punkt i bildet
* Fødselsnr og Dødsdato blir «trykket» inn i ledetekst
* Bostedsadresse: Denne linja kommer utenfor det blå feltet og er dermed «usynlig» (hvit tekst på lys grå bakgrunn)
Se bilde:
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/247f6d2d-79c5-4388-b0dc-d7f8f51162db)

[ ] **Spørsmål og svar om skifte av dødsbo** 
* Den legger seg oppå annen tekst
* Når man åpner et av punktene med mye tekst, vises dette som ei lang remse med tekst og man må scrolle mye for å lese alt => ser ikke så pent ut
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/03eb89d7-accc-4e37-bbd9-ade34cf72fe2):

[ ] **Ikon for nummerering** blir litt "dradd" i forhold til i vanlig skjermstørrelse
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/b83def8a-c697-4520-9d47-e0aa867363bd)

[ ] Tekstbokser og undermeny-bokser har forskjellig bredde
Eks.
* Det er full bredde i tekstboksen/menyene under "Send inn opplysninger om avdøde", mens tekstboksen/meny under "Få oversikt over formue og gjeld" har luft på høyreside.
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/4a9fe26e-59b3-4b8b-9a94-16567b9b6e23)
* "Signer på ønske om privat skifte" har en tredje variant av bredde, hvor tekstboksen har samme bredde som "Formue og gjeld", mens undermeny "Signering" har full bredde
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/1a06cb10-aed5-4ae5-9d46-2e0bc3c2537c)
* "Motta skifteattest" har en fjerde bredde på undermenyene
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/a9b7bac3-6e95-4b3f-a2a5-9644a176576b)

Hvis man øker skjermstørrelse til Ipad, så ser bredden helt lik ut på alle tekstbokser/menyer.

[ ] **Testamentet** (Gjelder forsåvidt for alle disse undermenyene)
Altfor mye luft på venstre side og altfor tett på høyre kanten. 
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/4c7dad4a-9201-44b9-9eda-ef4049d45ef7)
[ ] **Arving**
Her er det mye luft på venstre side og det hadde sett bedre ut om man kunne fått justert tekst/tabell litt
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/310da36e-1cd7-411a-81f4-806d9cd77ca8)

[ ] **Ektepakt**
Ektepakt-appen – her vises teksten "Når ble ektepakt..." og så dato, mens det er masse luft etter dato.
Burde denne tabellen justeres litt slik at mer av teksten ble synlig?
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/a5c2fad4-6d43-4adb-97c8-bfc0d265dab7)

[ ] **Formue og Gjeld**
Skatt blir ikke synlig
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/1f7c1b15-2129-4bb8-b83f-fa2d7917a1b0)

**Comment by AinaEngen** [comment]
@DanRJ @kristoffervp - har samlet en del innspill fra testing i mobilvisning i denne saken. Ingen av funnene hindrer bruk av løsningen, men det er kanskje noe som kan vurderes å forbedre

**Comment by DanRJ** [comment]
Da er forsiden ihvertfall responsiv, ta gjerne en titt på det @AinaEngen 

Vedr ektepakt appen, får vi ikke gjort noe med det dessverre, det må vi si ifra til Tjenester 3.0.

Vedr luft, så har jeg fjernet en del padding men det er fortsatt litt luft der fortsatt, hovedsakelig er det der pga at titler og tekster skal ligge med samme indent

**Comment by kristoffervp** [comment]
@AinaEngen Denne kan retestes.

**Comment by AinaEngen** [comment]
Lukker denne. Mobilvisning ser bra ut nå. Skulle det dukke opp noe senere på mobilvisning, oppretter vi egne bugs på det
