### ISSUE TITLE
Backend: innhente sivilstand til avdøde fra FREG

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#552]
Beskrivelse av oppg.....
Relatert til brukerhistorie/epos: #516
Lenke til design:

Felter i FREG: Uoppgitt, Ugift, Gift, Enke(mann), Skilt, Separert, Partner, Separert Partner, Skilt Partner og Gjenlevende partner.

**Comment by AinaEngen** [comment]
Får ikke lukket denne før bug #553 er fikset, da jeg kun ser "ikke spesifisert" som verdi der det egentlig burde stått gift/ugift fra FREG
