### ISSUE TITLE
Frontend: visning av innhentet sivilstand til avdøde fra FREG

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#553]
Beskrivelse av oppg.....
Relatert til brukerhistorie/epos: #516 #552
Lenke til design:

- [x] Synkroniser OED og FREG sine koder tilknyttet sivilstand.
Skal ligge i oed-marital-status i prefill koden

- [ ] .. 

- [ ] ..

**Comment by AinaEngen** [comment]
På testbrukerne våre står det **Sivilstand: Ikke spesifisert** på det som er hentet fra Folkeregisteret (FREG).
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/17c87e0b-82ee-4179-9af9-de94b1da23e5)

Er det riktig? 
@DanRJ

**Comment by DanRJ** [comment]
Er litt usikker her @AinaEngen. Kanskje @HenningNormann vet hvor sivilstand tilknyttet den avdøde kommer fra? Om den er hardkodet eller hva?

**Comment by HenningNormann** [comment]
Sivilstand hentes fra FREG og legges på instansen når boet opprettes. Denne funksjonaliteten ble implementert etter at instansene i TT02 ble opprettet, så det ligger sikkert ukjent på alle boene der. Hvis ønskelig kan instansene/boene slettes og instansieres på nytt. Da vil man få den sivilstanden som ligger på avdøde i FREG.

**Comment by AinaEngen** [comment]
@HenningNormann Da forslår jeg at man instansierer boene på nytt, så vi får testet ulike verdier av sivilstand. Regner med at all annen informasjon om boet blir likt som det er i dag (bank, landbruk osv). 
cc: @DanRJ @kristoffervp

**Comment by HenningNormann** [comment]
Det er instansiert på nytt nå.

**Comment by AinaEngen** [comment]
Sivilstand vises fortsatt som "ikke spesifisert" på opplysninger hentet fra Folkeregisteret, selv etter at instansene/boene ble slettet og opprettet på nytt. Henning mente at verdien ikke hentes fra instansen, men er hardkodet i GUI.
Setter denne tilbake til Backlogg, slik at dette kan fikses
@kristoffervp @DanRJ

**Comment by DanRJ** [comment]
Nå skal det fungere 👯‍♂️

**Comment by AinaEngen** [comment]
Testet ok, lukker bug
