### ISSUE TITLE
Visning av dato - Testament og Ektepakt

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#554]
Ved registrering av **TESTAMENT**, så vises dato på et format (riktige) når man velger dato i kalender, mens det i oversikten over registrerte testament vises på et annet format. Visning av dato bør være på samme format, spesielt når man er på samme side:
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/d94941f4-93e1-4aa6-8175-0925a370ea0b)

Etter innsending, så vises det slik i oversikten i Veilederen:
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/f163a7a2-5217-4e1d-937e-e56738d04ba1)

Samme gjelder for **EKTEPAKT**
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/7b4ed936-5a49-4fa2-9fe4-dae88823c02e)

![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/82e0b111-09ce-4d90-9766-cb9bb5f09a99)

**Comment by kristoffervp** [comment]
@DanRJ sjekker om dette er konfigurasjon, eventuelt om det er noe vi må spille videre til Tjenester 3.0-teamet.

**Comment by DanRJ** [comment]
@AinaEngen @kristoffervp https://altinn.slack.com/archives/C02ESDSJN2H/p1643794653590049
TLDR: Datoen som vises i tabellen er basert på innstillingene i nettleseren, så hvis man har norsk, får man norsk dato

**Comment by AinaEngen** [comment]
@DanRJ - jeg har norsk språk i nettleseren min (Tester i Edge og det står i innstillinger, under språk, at jeg har norsk bokmål). Alt i browser vises på norsk. MEN, jeg får denne datoen på engelsk format, så er det andre steder man må sette språk? 
Hvorfor vises dato ulikt, når man først har satt et språk i browser. Dette er ulogisk for meg...
cc: @kristoffervp

**Comment by DanRJ** [comment]
Etter slack diskusjon er dette en oppgave for Tjenester 3.0 der vi kan lage en bug / lage en PR for å fikse det. Det jeg derimot er usikker på er hvorfor de baserer datoen i datepickeren på nettleser innstillingen istedenfor Altinn språk valget. Og det vil også påvirke hvordan man eventuelt løser denne oppgaven i en PR mot Tjenester 3.0 @kristoffervp

**Comment by kristoffervp** [comment]
Etter diskusjon med Daniel forstår jeg at dette er en "bug" / slik man kan forvente det ved bruk av denne T3.0 komponenten. Foreslår at vi lukker vårt Issue, og samtidig oppretter et Issue hos T3.0 for å gjøre dem bevisst på oppførselen og ta det der i fra. @AinaEngen kan du fikse når du er tilbake? :)

**Comment by DanRJ** [comment]
Lukkes etter enighet med @AinaEngen 
Vi registrerer ny hvis det dukker opp igjen
