### ISSUE TITLE
Veileder - header ser ikke pen ut

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#555]
I headeren i Veilederen ser det ut som om informasjon om avdøde ligger en blå boks som legger seg over bildet.
Skal det være slik? I så bør bildet dekke bakgrunnsbilde og ikke gå over i det hvite feltet.
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/7ad768ce-6c68-4933-9f13-3d9794dc29b0)

(så slik ut tidligere, se bort fra røde streker her:
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/e59a46b8-1e0b-42d6-b151-5df81cd1e699) )

**Comment by AinaEngen** [comment]
@kristoffervp - her er en bug til

**Comment by kristoffervp** [comment]
@AinaEngen mulig du må bistå Daniel med hvordan denne reproduseres. Han tar kontakt.

**Comment by kristoffervp** [comment]
@AinaEngen denne kan retestes.
