### ISSUE TITLE
Formue og Gjeld flyttes til forsiden + Fjerne FAQ + Gå fullbredde

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/oed#559]
## Beskrivelse av oppgaven

Formue og Gjeld sidene flyttes fra å være undersider i Altinn Dødsbo-applikasjonen til å være en integrert del av "veilederen" / forsida. Samtidig ønsker vi å skjule seksjonen for "Spørsmål og Svar" for å kunne vise veilederen i full bredde.

Relatert til brukerhistorie/epos: #536 
Lenke til design:

![bilde](https://user-images.githubusercontent.com/1841665/153880552-14d09324-3312-4394-bf22-8addb3c78105.png)

NB! Bilde illustrerer ikke full bredde-oppgaven.

- Formue og Gjeld flyttes til Forsiden, dette gjelder:
- [x] Kjøretøy
- [x] Skatt
- [x] Eiendom
- [x] Bank
- [x] Pensjon

- [x] "Spørsmål og Svar" skjules midlertidig inntil vi har funnet nytt plassering

- [x] Hele veileder/forsiden skal skaleres til full bredde NB! Dette gjelder da også de øvrige seksjonene (1, 3 og 4)

**Comment by AinaEngen** [comment]
Testet ok mobil/pc
