### ISSUE TITLE
Populere roller rettigheter Altinn

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#56]
#### Brukerhistorie
**Intro**
Som  Tjenesteeier 
ønsker jeg at roller og rettigheter skal oppdateres i AA 
slik at riktig tilgang til informasjon i OED app gis til riktige brukere av OED

**Krav/akseptansekriterier**  _(detaljering av BH med tilhørende akseptansekriterier)_
Gitt at
Når 
så
og 

**Utfyllende tekst**
Denne tabellen må lages og populeres.

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: Hvilke roller og rettigheter skal inngå i AA for OED?
Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:

- [ ] Skal DA gjøre spørring mot reservasjonsregisteret for å finne ut om arving er reservert mot digital kommunikasjon? #158

Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:

- [ ]  Hvilke oppgaver skal Autorisasjon gjøre for oss?

Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---
### Forslag nye bh scenarie 2+

**Comment by lillelars** [comment]
@JanAage99 har vi laget noen rolletabell enda? Denne er vel fortsatt på "analysere" ?

**Comment by lillelars** [comment]
@TageGitHub er denne duplikat at #172 ?

**Comment by TageGitHub** [comment]
JA - overtatt av #172
