### ISSUE TITLE
Last ned transasaksjonshistorikk fungerer ikke

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#560]
Åpne Bankforhold
Linken "Last ned transaksjonshistorikk for alle kontoer som regneark" fungerer ikke.
Får denne meldingen:
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/445f84ce-7027-4232-85d2-3281d8c4262f)

**Comment by AinaEngen** [comment]
@kristoffervp @DanRJ

**Comment by AinaEngen** [comment]
Testet på nytt igjen i dag, får fortsatt samme feil

**Comment by DanRJ** [comment]
Skal være fikset nå, var en tom liste vs null feil
