### ISSUE TITLE
Testament - mulig å lagre et tomt utkast

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#561]
Logg inn og Gå til Testament og Arvepakt

Klikker på "Send inn testament og arvepakt"-knappen (første gang, før noe er sendt inn)
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/fe78d752-6857-4c89-9039-06659c7b7a65)

Så ombestemmer man seg, og avbryter uten å fylle ut noe som helst (altså et tomt skjema) - trykker på X i høyre hjørne.
Neste gang man går inn på Testament og Arvepakt med denne brukeren står det "fortsett på utkast av testament og arvepakt"
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/bb78abf7-f7f6-44ef-b196-7fc897fd51a8)

Men, det er tomt.
Her burde det ikke bli lagret et utkast, det forvirrer brukeren da det ikke finnes noe utkast.

Jeg tenker at hvis man avbryter uten å ha skrevet noe i app'en, så avslutter man uten å lagre.
Det forventer i hvert fall jeg som bruker og det er det som skjer med en 3.0 app i dag
Kan testes med følgende 3.0 app: ![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/e3a16729-bde1-411b-9d79-0d1b4e149f5c)

Teksten på knappen burde derfor være "Send inn testament og arvepakt" neste gang man går inn på på Testament og Arvepakt.

**Comment by AinaEngen** [comment]
@kristoffervp @DanRJ

**Comment by CecilieFjellsoy** [comment]
Design ønsker gjerne bruk av alle tre statusene (Send inn, Fortsett på utkast og Lag ny kopi), men "Fortsett på utkast....." bør ikke aktiviseres før det er skrevet/lagret noe i instansen. Er det mulig?

**Comment by DanRJ** [comment]
Vi endrer til at knappen ser på data, og ikke instans statusen, slik at hvis det er ikke noe data, vil det vises "Send inn", hvis det finnes noe data, vil det vises "fortsett på utkast", og hvis det er sendt inn, vil man få opp "lag ny kopi". Det vil si at hvis en arving har lagt til data, mens en annen arving sletter den dataen, vil det stå "send inn" på knappen.

**Comment by DanRJ** [comment]
Denne utgår da dette designet er ikke lenger gyldig. Det finnes heller ingen knapp for å komme til testament
