### ISSUE TITLE
Automatisk gå tilbake til seksjonen man var på, etter navigering til subapp

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#563]
Hvis man går inn på en subapp, og trykker X for å komme tilbake, ønsker vi at brukeren lander på samme seksjon som brukeren forlot.

- [x] Legg til #navn sånn som i docs.altinn.no
- [x] Pass på at #navn sendes med til subapp return URLen
- [x] Pass på at den scrollmotoren tar brukeren til korrekt seksjon (kanskje åpne den og?)

Etter samtale med Håkon fra Studio-teamet ble vi enige om å lage en React hook, som identifiserer innholdet i URLen, som igjen finner hvilken accordion som skal åpnes basert på href

**Comment by AinaEngen** [comment]
Fungerer ok - man blir stående på samme seksjon man var når man sendte inn en subapp. Lukker derfor denne.
Men tror at denne endringen har innført en bug, som er registrert på [#576](url)
