### ISSUE TITLE
Feil i ingress-tekst på kjøretøy

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#564]
Feil i ingress-tekst på kjøretøy

Teksten henviser til Svein Svendsen, mens det er Oddvar Muller som er avdøde.

![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/5d4d7a3d-49da-4d40-8fce-1fee696b6cf9)

**Comment by DanRJ** [comment]
Utgår. Gammelt design, teksten er ikke der lenger.
