### ISSUE TITLE
OED Startsiden er "korrupt"

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#568]
Logget inn i Altinn med testbruker Stein Eidem - 01066800187, åpner oppgjør for Oddvar (øverste i lista).

Når jeg kommer inn i OED, ser det slik ut:
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/19482e60-7331-4ccb-90e7-a9419b30a1e8)

Trodde først det kom av at språk var engelsk på brukeren når jeg logget inn i Altinn (siden det ser ut som en språk-fil feil), men jeg endret språk til norsk og det så like ens ut.
logget ut og inn igjen med norsk som språk, så slik ut da også.

Etter noen sekunder (5-10) "forsvinner" bare hele bildet og jeg får ei hvit side:
![image.png](https://images.zenhubusercontent.com/5dd6976a415dab00019d1d7a/ccf98567-e688-4826-92c7-c973af9fe531)

**Comment by AinaEngen** [comment]
@DanRJ - jeg logget inn og besøkte OED rett etter hverandre. Ser uansett riktig ut nå, men får ha øynene åpne for om det samme skjer igjen. Da kan denne lukkes hvis du ikke har tenkt å forske mer på dette.

**Comment by DanRJ** [comment]
Ja, vet ikke helt hvordan jeg skal sjekke mer. Jeg lukker.
