### ISSUE TITLE
Tekst i Transaksjonshistorikk (Excel dokumentet)

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#569]
Burde det være tekst i excel dokumentet som beskriver at det er de siste 3 månedene transaksjonshistorikk?
Hvis en konto ikke viser noen transaksjoner, burde det stå noe tekst som forklarer hvorfor det ikke vises noen transaksjoner?

Hvis ja, kan vi få noe tekst på dette, så får vi slengt det inn?

**Comment by CecilieFjellsoy** [comment]
Har opprettet en hjelpetekst i løsningen for informasjon til excel filen som sier at den inneholder 3 måneders transaksjonshistorikk. Dette i tillegg til melding i selve filen dersom kontoen ikke har transaksjoner. 

Se delen for bank her: 
https://www.figma.com/proto/IcY5YuDiedu72nIpHIrKhA/OED-%F0%9F%96%A5-desktop?page-id=5746%3A54574&node-id=9436%3A201581&viewport=-6369%2C-2650%2C0.25&scaling=min-zoom&starting-point-node-id=9436%3A201581

@DanRJ

**Comment by DanRJ** [comment]
Utgår da vi bruker hjelpetekst for å forklare dette. Det vises i nytt design og er implementert
