### ISSUE TITLE
Inbound events Altinn 3 app for DA samhandling

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#589]
Opprett en Altinn 3 app som skal brukes for samhandling / kun inbound mellom Digitalt Dødsbo apper og DA.

Se skisse for arkitektur:
https://lucid.app/lucidchart/33f473e3-a53b-4cd4-a7a8-7b62e64f2261/view#

- [x] Les om Altinn 3 stateless apps og se om det er noe for denne appen
(Det er aktuelt å bruke stateless apps da det er ikke behov for instansiering)

Relatert til brukerhistorie/epos: #157 og mange av brukerhistoriene under den eposen

**Comment by DanRJ** [comment]
Opprettet skall:
https://altinn.studio/designer/digdir/oed-inbound-events
https://altinn.studio/repos/digdir/oed-inbound-events

**Comment by elsand** [comment]
Trenger FREG-integrasjon for å kunne gjøre oppslag på navn og adresse på avdød og arvinger/formuesfullmektige.
