### ISSUE TITLE
Bruker får melding om opprettelse av det aktuelle dødsboet

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#59]
#### Brukerhistorie:
Som en arving
ønsker jeg å motta melding om at det digitale dødsboet er opprettet
slik at jeg kan begynne å bruke tjenesten

#### Forretningsverdi (2):

Lenke til trådskisser: N/A
Lenke til design: N/A
Lenke til arkitektur:

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Må vurderes om dette er OK juridisk

#### TODO:
- finne ut hva en slik melding må inneholde. Bør kunne ha informasjon om hvor bruker kan finne ut mer om digitalt dødsbo evt uten å logge seg inn på digitalt dødsbo. Altså informasjon som ikke ligger i OED-app, men utenfor. 
- Finne ut hvorvidt 3.0 har noe vi kan bruke til denne meldingen
- Hvor leser bruker denne meldingen (f.eks om arving må benytte Altinn innboks?)

#### Akseptansekriterier (minimum happy-case):
- Arving skal motta varsling ihht brukers ønsker (sms/epost) satt opp i KRR
- Melding skal inneholde link til OED-instans
- Arving skal klare å logge seg inn og komme til landingsside
- Dette sendes ut etter 5-7 dager etter domstolene har registrert dødsfall

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

#### Forbehold 
- Må avklares om vi skal vente 5 eller 7 dager etter melding om dødsfall, før vi sender ut digitalt brev.

**Comment by TageGitHub** [comment]
Overført til #170
