### ISSUE TITLE
Etablere første versjon av rolle- og rettighetskart

### ISSUE THREAD

**Issue by benedicteos** [Altinn/oed#6]
**Oppgave knyttet til brukerhistorie: 172**

Beskrivelse:
Det må etableres et rolle- og rettighetskart. På ulike tidspunkt i prosessen skal arvingene ha ulike roller og rettigheter. Det kan være tilstrekkelig for formuesfullmakt at man benytter Domstolens kategorisering: Arving med fulle rettigheter, som har formuesfullmakt, og Arving med begrensede rettigheter, som ikke har formuesfullmakt. Men det må gås opp - både hva fulle og begrensede rettigheter innebærer, og det må vurderes om det er behov for flere roller i Altinn autorisasjon, evt om det løses med rettigheter. Feks er det under avklaring om det kun er arving som har påtatt seg ansvar for avdødes forpliktelser som kan utpeke fullmektig.

I første omgang er det bare rollen 'arving' vi benytter. Vi kan motta flere av denne typen rolle. Beskrevet utvidelse av dette vises i epos/brukerhistorie om "Fullmakt".

Frist:

Gammel tekst:
Beskrivelse: Løsningen må utvikles iht til ny arvelov. Må klargjøres hvem som kan gjøre hva med hvilken rolle og hvilke rettigheter. Arving som fellesbegrep, men ulike regelsett for arving etter testament og arving etter slekt bl.a. Må gås opp hva disse har lov til å se eller ikke. Selv om en har formuesfullmakt, kan det være tilfeller hvor de ikke har rett til å se informasjon fra aktør? 

Alle rolle- og rettigheter må være inkludert, også i beslutte - hvor det kommer nye rolle- og rettigheter fra skifteattest. I tillegg til oppgjør - nye rettigheter for eventuell fullmektig

Rolle:
- Arving:
En myndig Person som er arving, arver fra eget barn der barnet ikke er gift og ikke har barn selv.
Forutsetning: Begge foreldre til avdøde lever.

- Arving:
En myndig Person arver fra sin avdøde forelder som er ugift og ikke samboer.

Rettighetskart:
- Formuesfullmakt

Arving: 
- Formuesfallmakt
Frist:

Kontaktperson

**Comment by curlingnina** [comment]
Det må i første omgang opprettes et rolle- og rettighetskart for scenario1. Jeg kan lage begynne på et i excel

**Comment by lillelars** [comment]
Vi lukker denne for nå - dersom det blir behov for dette må vi vurdere på nytt. Ta evnt opp med Kristoffer hvis det er viktig.
