### ISSUE TITLE
oed-authz app for håndtering av autorisasjon

### ISSUE THREAD

**Issue by elsand** [Altinn/oed#600]
Altinn autorisasjon trenger et API for å hente informasjon om hvem som er arvinger/fullmektige. Dette implementeres i en egen mikrotjeneste, som håndterer ~~"ny arving"/"ny fullmekting"~~"oppdatert liste med parter"-events for å oppdatere en database, og eksponerer et API som lar en gjøre oppslag.

- [x]  Avklare format på CloudEvent
- [x]  Legge til kolonne for relasjon til avdøde
- [x] Legge til kolonne for timestamp
- [x]  Lage API for Altinn Autorisasjon
- [x]  Lage API for Digitalt Dødsbo-master-app (for et fnr, returner alle personer med roller inkl. relasjon)

_Se #614 for oppdaterte eksempler av cloud event innhold._

For å håndtere potensiell out-of-order, må authz-appen forholde seg til `time`. Så hvis det kommer inn en event med `time` som er mindre enn noen av oppføringene med samme `roleObjectNin` skal eventen forkastes.

**Comment by elsand** [comment]
Foreløpig versjon på https://github.com/data-altinn-no/oed-authz, deployed til altinn-digdir-oed-tt02-rg/oed-test-authz (https://oed-test-authz-app.azurewebsites.net)

**Comment by b-brodie-digdir** [comment]
Forslag til cloud event format for endring av roller:

```
{
    "specversion": "1.0", 
    "type": "no.altinn.events.digitalt-dodsbo.heir-role-updated", 
    "resource": "urn:altinn:rr:dodsbo.domstoladmin.api"
    "source":  "https://hendelsesliste.test.domstol.no/api/objects/fd635f35-6df5-4f39-8809-dbd797e40380",
    "resourceinstance": "91f2388f-bd8c-4647-8684-fd9f68af5b14", 
    "id": "288f71f2-8cbd-3442-1532-ac14f3fd9faa",
    "time": "2020-02-20T08:00:06.4014168Z",
    "datacontenttype": "application/json",
    "data": {
       "nin": "<personnummer som har rollen>",
       "role": "MOR",
       "roleObjectNin": "<personnummer til avdøde>",
    }
}
```

Usikker på verdien for `resourceinstance` i dette tilfellet da disse eventer kan og vil forekomme før et dødsbo er opprettet.

**Comment by elsand** [comment]
@b-brodie-digdir @DanRJ Dette vil kunne fungere hvis vi noen gang skal sende events UT av authz, men eventet som skal komme INN til authz fra feedpoller vil ikke kunne inneholde noe informasjon om hva som faktisk er endret - det er det bare authz som har forutsetninger for å gjøre. Så authz vil måtte gjøre oppslaget på `source` (da gjennom proxyen i feedpoller, som vi må legge inn en eller annen secret-i-header-autentisering på), hente den gjeldende lista og selv finne ut hva som skal legges til/fjernes/endres i databasen utfra hva som allerede ligger der.

**Comment by elsand** [comment]
CloudEvent-formatet ser bra ut, har bare gjort et par småjusteringer:
- `no.altinn.events.digitalt-dodsbo.heir-role-updated` til `no.altinn.events.digitalt-dodsbo.heir-roles-updated` (flertallsform)
- Bruke `"urn:altinn:resource:`-prefix ref. avklaringer med autorisasjons- og eventtteam
- Array in data for å kunne sende hele lista.

**Comment by elsand** [comment]
@b-brodie-digdir 

Ref #590 og #614; i stedet for at vi legger inn en egen kolonne for relasjon til avdøde er det bedre at vi rett og slett har relasjonen i seg selv som en egen rolle. Dette gjør oss bedre rustet mht fremtidig "søk om formuesfullmakt"-funksjonalitet som skal være tilgjengelig for arvingene.

Dette betyr at et dødsboobjekt fra DA som inneholder 

```json
{
    "sakId": "fd635f35-6df5-4f39-8809-dbd797e40380",
    "avdode": "16904498932",
    "embeteId": "JVIN",
    "parter": [
        {
            "nin": "21891849688",
            "role": "BARN",
            "formuesfullmakt": "INGEN",
            "signertDato": null,
            "onsketSkifteform": null,
            "paatarGjeldsansvar": false,
            "godkjennerSkifteattest": false
        },
        {
            "nin": "16861749510",
            "role": "GJENLEV_EKTEFELLE_PARTNER",
            "formuesfullmakt": "ALTINN_DODSBO",
            "signertDato": null,
            "onsketSkifteform": null,
            "paatarGjeldsansvar": false,
            "godkjennerSkifteattest": false
        }
    ],
    "receivedDate": "2023-03-15",
    "skifteform": "IKKE_AVGJORT"
}
```
skal medføre lista at det genereres følgende event for å håndtere oppdatere rollelista

```json
{
    "specversion": "1.0", 
    "type": "no.domstol.dodsbo.v1beta.roles-updated", // TODO! Dette må landes i #614
    "resource": "urn:altinn:resource:dodsbo.domstoladmin.api",
    "source":  "https://hendelsesliste.test.domstol.no/api/objects/fd635f35-6df5-4f39-8809-dbd797e40380",
    "id": "288f71f2-8cbd-3442-1532-ac14f3fd9faa",
    "time": "2020-02-20T08:00:06.4014168Z",
    "datacontenttype": "application/json",
    "data": {
      [
         "nin": "16861749510",
         "role": "urn:digitaltdodsbo:arving:barn",
         "roleObjectNin": "16904498932"
      ],
      [
         "nin": "16861749510",
         "role": "urn:digitaltdodsbo:formuesfullmakt",
         "roleObjectNin": "16904498932"
      ],
      [
         "nin": "16861749510",
         "role": "urn:digitaltdodsbo:arving:gjenlevEktefellePartner",
         "roleObjectNin": "16904498932"
      ]
    }
}
```

Ønsker at vi gjør en mappingav rollekodene som vi får fra DA til vår egne verdier som legges i database/policies:

```csharp

    private static readonly Dictionary<string, string> HeirMapping = new Dictionary<string, string>
    {
        {"PART_ANNEN", "urn:digitaltdodsbo:arving:partAnnen"},
        {"GJENLEV_EKTEFELLE_PARTNER", "urn:digitaltdodsbo:arving:gjenlevEktefellePartner"},
        {"GJENLEV_PARTNER", "urn:digitaltdodsbo:arving:gjenlevPartner"},
        {"GJENLEV_SAMBOER", "urn:digitaltdodsbo:arving:gjenlevSamboer"},
        {"BARN", "urn:digitaltdodsbo:arving:barn"},
        {"BARNEBARN", "urn:digitaltdodsbo:arving:barnebarn"},
        {"SAERKULLSBARN", "urn:digitaltdodsbo:arving:saerkullsbarn"},
        {"SAERKULLSBARN_BARN", "urn:digitaltdodsbo:arving:saerkullsbarnBarn"},
        {"FAR", "urn:digitaltdodsbo:arving:far"},
        {"MOR", "urn:digitaltdodsbo:arving:mor"},
        {"SOESKEN", "urn:digitaltdodsbo:arving:soesken"},
        {"SOESKENS_BARN", "urn:digitaltdodsbo:arving:soeskensBarn"},
        {"SOESKENS_BARNEBARN", "urn:digitaltdodsbo:arving:soeskensBarnebarn"},
        {"HALV_SOESKEN", "urn:digitaltdodsbo:arving:halvSoesken"},
        {"HALV_SOESKENS_BARN", "urn:digitaltdodsbo:arving:halvSoeskensBarn"},
        {"FARFAR", "urn:digitaltdodsbo:arving:farfar"},
        {"FARMOR", "urn:digitaltdodsbo:arving:farmor"},
        {"MORFAR", "urn:digitaltdodsbo:arving:morfar"},
        {"MORMOR", "urn:digitaltdodsbo:arving:mormor"},
        {"ONKEL", "urn:digitaltdodsbo:arving:onkel"},
        {"TANTE", "urn:digitaltdodsbo:arving:tante"},
        {"FETTER", "urn:digitaltdodsbo:arving:fetter"},
        {"KUSINE", "urn:digitaltdodsbo:arving:kusine"},
        {"STATEN", "urn:digitaltdodsbo:arving:staten"},
        {"AVDOEDE", "urn:digitaltdodsbo:arving:avdoede"},
        {"FORDRINGSHAVER", "urn:digitaltdodsbo:arving:fordringshaver"},
        {"AVDOEDE_EKTEFELLE_PARTNER", "urn:digitaltdodsbo:arving:avdoedeEktefellePartner"}
    };

    public static string GetHeirUrn(string input)
    {
        ArvingMapping.TryGetValue(input, out string urn);
        return urn;
    }

```

`urn` blir her null hvis vi får en ukjent verdi. Ignorer dem og `LogError(...)`

**Comment by elsand** [comment]
@b-brodie-digdir Ser nå et lite minus med denne modellen; det legges opp til at det kan være ulike `roleObjectNin` per innslag i `data`, men for en gitt `source` er bare bare én mulig `roleObjectNin`. Vi har bare ett `time`-felt, som vi er avhengige av å kunne sjekke mot det vi allerede har i databasen for å sikre at vi ikke overskriver autorisasjonsdata med gamle events.

Jeg tror ikke vi skal la denne event-typen strekke seg over ulike dødsbo, og da gir det mening å ta ut `roleObjectNin`. Jeg tenker derfor det er mest rimelig å ha denne som "subject". Innspill på det? Har oppdatert eksemplet.
