### ISSUE TITLE
Publish `declaration-submitted` event

### ISSUE THREAD

**Issue by elsand** [Altinn/oed#608]
Komponent som abonnerer på sub-apphendelser og konverterer disse til eksterne DD-hendelser som refererer til API i master app (#592)

Forslag til outbound event innhold:

```
{
    "specversion": "1.0", 
    "id": "<generated uuid>",
    "type": "no.altinn.events.digitalt-dodsbo.v1.declaration-submitted"
    "resource": "urn:altinn:resource:dodsbo.domstoladmin.api",
    "source":  "https://digdir.apps.tt02.altinn.no/digdir/oed/api/declarations/<partyId>/<instanceId>",
    "subject": "<NinAvdøde?>",
    "time": "2020-02-20T08:00:06.4014168Z",
    "datacontenttype": "application/json",
    "data": {}
}
```

**Comment by b-brodie-digdir** [comment]
Mener vi ble enig om at oed master app tar seg av publisering av "declaration-submitted" eventer.

**Comment by erlendoksvoll** [comment]
Note to self: Masterappen håndterer declaration-submitted - når skifteerklæringsappen er "sendt inn" vil den generere en event, og så plukker masterapp opp det og konverterer til riktig custom event.

**Comment by DanRJ** [comment]
Skifteerklæringsappen er satt opp til å sende app eventer og vil sende en app event når skifteerklæringen sendes inn via Send Inn knappen til A3.

Deretter er en subscription registrert i Altinn Eventsystem med id 24774 og lytter på events:
 "sourceFilter": "https://digdir.apps.tt02.altinn.no/digdir/oed-declaration",
 "resourceFilter": "urn:altinn:resource:altinnapp.digdir.oed-declaration",
 "typeFilter": "app.instance.process.completed"

Den har webhook mot følgende API:
https://digdir.apps.tt02.altinn.no/digdir/oed/api/cloudevents/declaration?code=a26af348-acca-411f-8f10-df53e7d8a9d9

Det nye APIet vil konvertere innkommende event til en ny event med:
"type": "no.altinn.events.digitalt-dodsbo.v1.declaration-submitted"
"resource": "urn:altinn:resource:dodsbo.domstoladmin.api"

der en subscription med id 4413 lytter, og sender eventer til DA sin notifyer.

Deretter vil DA ta spørre etter skifteerklæringen via det gamle APIet vårt.

Hele regla er testa og fungerer.

**Comment by jost67** [comment]
Testes i integrasjonstest
