### ISSUE TITLE
Endre master-app til å abonnere på "heirroles-updated"-event

### ISSUE THREAD

**Issue by elsand** [Altinn/oed#611]
Vi fortsetter å lagre arvingene i OED-datamodellen, men denne må oppdateres med å gjøre et kall til oed-authz (https://github.com/data-altinn-no/oed-authz), som kalles for å hente ut liste med arvinger per dødsbo. Disse fnr-ene må det hentes navn for via party-API-et.

* [x] Oppdatere oed-events til å utvide case-status-updated til å inkludere informasjon om roller
* [ ] (WONT FIX) _Oppdatere master-app til å ta i mot heir-roles-updated. Hvis bo ikke finnes, returner 412 for å "utsette" eventen. Hvis bo finnes, sjekk at timestamp for forrige hendelsesendring på dødsboet er mindre enn innkommende event => oppdater lagret liste med navn og oppdater timestamp på dødsboet til innkommende events timestamp.
Hvis timestamp på innkommende event IKKE er større enn siste endring på dødsboet - returner 200 ok for å kvittere ut event og logg en warning_

Den utgår ettersom eventene kan være så tette på hverandre at timestampen vil ikke være lagret på instansen innen de andre eventene har hentet ut instansen. Vi må også da håndtere flere pods i kubernetes. Vi tar kun nå imot case-status-updated istedenfor flere event-typer samt OED-events de-duper eventene og garanterer kun 1 event per sak per timestamp. 

Vi vil ikke trenge å sjekke timestamp på event vs sist endret på instansen i hovedappen ettersom det vil ikke forekomme mtp det ovenfor.

* [x] For å få til oppgaven under, trenger vi å oppdatere skifteerklærings-appen til å inneholde signaturer
* [x] For å få til signaturer, må vi "hacke" til appen slik at vi kan separere mellom unike felter per bruker og felles felter per bruker
* [x] Hvis signaturer finnes, fjern de som ikke lengre er fra arving.

**Comment by AinaEngen** [comment]
Får jeg testet denne på noen måte, eller er dette noe utv.teamet må teste selv? @DanRJ @erlendoksvoll

**Comment by DanRJ** [comment]
Vi har testet dette og det fungerer. Denne er dog viktig å ha med på integrasjonstest. @AinaEngen
