### ISSUE TITLE
Implementere ny skifteerklæring-app ref "2023"-skisser

### ISSUE THREAD

**Issue by elsand** [Altinn/oed#617]
Er fremdeles WIP; så avvent denne inntil videre.

https://www.figma.com/file/oBtm6UxIjZzOg0xzJganiL/OED-desktop-2023?node-id=0%3A1&t=cFwFjnMglZ8mWwg6-0

Det opprettes en ny app for dette:
https://altinn.studio/editor/digdir/oed-declaration

**Comment by DanRJ** [comment]
Relaterte issues som er i utvikling eller klar for utvikling:
#354
#337
#230
#181 (epic)
#184
#257(?)
#256 (når skifteerklæring sendes inn)
#349 (koblet til 257-ish)
#225
#227
#228
#226
#550
#578
#621

**Comment by aadnehm** [comment]
- [ ] Feil med validering på "neste" knapp. Virker i v3, men ikke v4. triggers: [validatePage] i bunn av alle layout filer skal ikke slippe bruker videre hvis noe required ikke er besvart.

- [ ] Datovalg på testament og ektepakt burde ha en maks-dato på dødsdatoen til avdøde og en minimum dato på (fødselsdato eller noe logisk?) til avdøde.

- [ ] "CurrentUserHasAcceptedTerms" er bool, men burde være string. Reagerer kun ved første klikk på checkbox, men kan ikke velge den bort hvis den først er valgt. Checkboxen kan trykkes av og på, men ingenting skjer i backend etter første klikk.

- [ ] Mer utdypende logikk for endring av valg av skifteform. Implementert at man tar bort alle "CurrentUserHasAccepted(Terms/Public/Undivided/SmallValue)", men ikke at man tar bort signering eller påtatt gjeldsansvar.

- [ ] Implementere "send inn" knapp.
