### ISSUE TITLE
Status per instans i Altinn Dødsbo

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#62]
#### Brukerhistorie:
Som en saksbehandler fra domstolene
ønsker jeg å kunne se i mitt saksbehandlingssystem en status fra Altinn Dødsbo per arving
slik at jeg kan se om arving har logget seg på i Altinn Dødsbo..?!

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser: N/A
Lenke til design: N/A
Lenke til arkitektur:

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- Saksbehandler kan se status om prosessen er i gang
- Saksbehandler skal se status dersom Altinn dødsbo er gått over til papirbehandling
- DA har signalisert at bruker må kunne trekke seg fra digital behandling selv om vedkommende ikke er reservert. Feks dersom bruker/arving opplever det som for belastende å bruke OED. 

#### Spørsmål knyttet til behov:
Hvordan skal vi tilgjengeliggjøre enne statusen/informasjonen?
JÅB: Vi må etableres notifikasjon/API, 

#### Forbehold for å få realisere denne brukerhistorien:
- [ ] 

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by TageGitHub** [comment]
Overtatt av #159, #167, #166, #169
