### ISSUE TITLE
Visning av arvinger som kan gi skiftefullmakt

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#649]
Vis arvinger som kan gi skiftefullmakt til andre i løsningen i henhold til design

Relatert til epos: #173
Lenke til design:
https://www.figma.com/file/LKehgWYM3l2HalVyp7oREQ/OED-%F0%9F%9B%A0-komponenter?node-id=2249%3A15153&mode=dev

- [ ] Sjekk at boet har mottatt skiftefullmakt og det er privat skifte (feltet ProbateResult på instansdatamodellen)
- [ ] Sjekk hver arving om de har tatt på seg gjeldsansvaret og har valgt privat skifte, da kan de vises i lista hvis det stemmer

Det som er markert med rødt skal implementeres

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkRYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fc1d3eada1a80d9c2d770b74b22b15d26cd4e2a6/image.png)

**Comment by nlundee** [comment]
Når informasjonboksen vises så er tittelen: 

> Arving(er) som kan gi skiftefullmakt

Mens når informasjonsboksen er borte så er tittelen:

> Arvinger som kan gi skiftefullmakt

Regner med dette bare er en liten glipp, så jeg legger inn den første "Arving(er)". Veldig fort gjort å endre, så gi en lyd om det er feil.
