### ISSUE TITLE
Kartlegging av behandlingsaktiviteter og behandlingsansvarlig

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#65]
- [ ] Vi må ha en form for innsynstjenestelogg der vi kan presentere alle funksjoner vi benytter personopplysninger og hvordan vi benytter de

- [ ] Vi er behandlingsansvarlig for personopplysninger i tjenesten

- [ ] Hvem har konkret behandlingsansvar for personopplysninger gjennom hele MVP'en?

- [ ] Vi må ha konkrete skiller på hva Altinn skal håndtere og hva Altinn dødsbo skal håndtere?

Identifiser og kartlegg behandlingsaktiviteter og behandlingsansvarlige
- Kartlegge flyten av personopplysninger og hvordan forskjellige opplysningstyper behandles og utveksles.
- systematisere dette i en samlet oversikt over opplysningstyper, og oversikt over de forskjellige aktørenes hjemler for å utveksle opplysningene eller manglende hjemmel. 
- må avklares hvem som er behandlingsansvarlig og databehandler for de forskjellige delene av dataflyten, samt når behandlingsansvaret går over på datamottaker

**Comment by benedicteos** [comment]
Dette må gås opp nærmere. Hva som er nice to have, og hva som vil gjøre det enklere for tjenesteeier av Altinn dødsbo mtp å gi innsyn. Og hva som eventuelt må være på plass hos ASF mtp innsyn relatert til Altinn dødsbo.
