### ISSUE TITLE
API for skiftefullmakt

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#651]
Opprette API for å hente ut skiftefullmektige, legge til skiftefullmektige og slette skiftefullmektige.
Dette APIet skal ligge i DD og skal kommunisere med [oed-authz](https://github.com/data-altinn-no/oed-authz).

Relatert til brukerhistorie/epos: #173

- [x] Opprette API for uthenting av skiftefullmektige
- [x] Opprette API for å legge til skiftefullmektige
- [x] Opprette API for å slette skiftefullmektige

**Comment by jost67** [comment]
API er opprettet og fungerer men inngår ikke i MVP

**Comment by DanRJ** [comment]
@jost67 Denne er ferdig implementert. frontend og backend (sikkert rom for forbedring frontendmessig) men hvorfor tas denne ut da?
