### ISSUE TITLE
Hindre uthenting/manipulering av instansdata via storage-API-er

### ISSUE THREAD

**Issue by elsand** [Altinn/oed#653]
Storage-API-ene lar en autentisert arving enkelt søke frem alle instanser av `digdir/oed` hen har tilgang til, og [hente ut](https://docs.altinn.studio/api/storage/spec/#/Data/get_instances__instanceOwnerPartyId___instanceGuid__data__dataGuid_) og [endre](https://docs.altinn.studio/api/storage/spec/#/Data/put_instances__instanceOwnerPartyId___instanceGuid__data__dataGuid_) informasjon i et dødsbo uten engang å gå via appen. 

![image](https://github.com/Altinn/oed/assets/723303/f0dce08a-fb6a-487b-81b0-eef00693dea8)

- [ ] Hindre uthenting/endring av data via app-API-er
- [ ] Se på muligheter for å hindre uthenting/endring av data via platform-API-er

**Comment by elsand** [comment]
fyi @erlendoksvoll @DanRJ

**Comment by nlundee** [comment]
Vi har fjernet fødselsnummer til fordel for partyId. API'et er bare readonly.
