### ISSUE TITLE
Vurder å ytterligere sIkre banking-plugin

### ISSUE THREAD

**Issue by elsand** [Altinn/oed#655]
Banking-pluginen kan aksesserer gjennom DAN-API-ene direkte, som er by design. Men det er kun appen som sikrer at dette gjøres mot en død person og initiert av noen med formuesfullmakt.

Vurder om dette bør sikres ytterligere (enten som nye requirements, eller implementert direkte i plugin-banking)

- [ ] Vurder innføring av oppslag mot oed-authz i DAN for å sikre at subject er en død person
- [ ] Vurder innføring av parameter for formuesfullmektig i Banktransaksjoner, som blir validert mot oed-authz

**Comment by DanRJ** [comment]
Denne issuen burde isåfall ligges hos DAN
