### ISSUE TITLE
Feil med integrasjon mot Kartverket

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#664]
**Describe the bug**

Får feilmelding når jeg trykker på Eiendom under Eiendeler og Gjeld.
Meldingen kommer med en gang så det er ikke timeout.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVY2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5cbe5e3027f315517ed8484e85fe0b9d70d82ce7/image.png)

@erlendoksvoll hentet ut følgende fra loggen:
There was a permanent error with the input to one the evidence codes requested. The evidence source cannot process this request with the provided parameters; detailCode: KARTVERKET-2; detailDescription: External API call to Kartverket failed (404 - NotFound), details: <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1></body></html>

**Comment by erlendoksvoll** [comment]
registrerte supportticket hos kartverket
