### ISSUE TITLE
Feil i integrasjon mot Norsk pensjon

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#666]
Får feilmelding når jeg klikker på Forsikring (under Eiendeler og Gjeld).
Dukker opp med en gang, så ikke timeout.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWg2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1fed309bd183d11a23ff6fcafcdf4dc07dc918d/image.png)

@erlendoksvoll

**Comment by erlendoksvoll** [comment]
DAN-plugin er falt ut og er utilgjengelig ... ser på det.

**Comment by DanRJ** [comment]
Denne er fikset for lenge siden. Jeg lukker denne
