### ISSUE TITLE
Feil i datoformat på arvingers fødselsdato

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#668]
Fødselsdato for arvinger viser "feil datoformat".
Mulig dette er pga Tenor testbrukere? I så fall må vi få lagt til et dødsbo på en Altinn testbruker, slik at vi ser at datofeltet er korrekt.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2g3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb72a98088981bd64f225d56345185f94215d3be/image.png)

**Comment by AinaEngen** [comment]
@erlendoksvoll @DanRJ

**Comment by DanRJ** [comment]
Dette er mest sannsynlig pga Tenor-brukere, det er en bevisst feilmelding hvis det er noe galt med datoen. Usikker på dette er noe vi bør fikse. La gjerne buggen være her, også får vi heller drøfte litt rundt det @AinaEngen
