### ISSUE TITLE
Fiks relasjon som vises på Arvinger-siden

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#670]
Se bildet. Det må fikses i frontend slik at korrekt relasjon vises og at man får inn språk.

[Pic](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0dQQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--17ae27811469e2caf9e3fcf8e1a44ac27e41ff5c/image.png)

**Comment by AinaEngen** [comment]
30.11.23: Trenger å få lese inn ny instanser, da det fortsatt vises feil med de testdataene vi har
