### ISSUE TITLE
Feil i visning av Arvetype

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#674]
Logg inn med en testbruker, eks. 15835896169
Gå til informasjon om Arvinger. 
I tabellen over arvinger vises arvetype feil. 
Se skjermdump:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3ZDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0afdcaf297d5f11ff290ebd276d853eef7fd239d/image.png)

I tillegg står det "ugyldig fødselsnummer" etter fødselsnummer (til info: f.nr vises korrekt på avdøde, under Personalia)
Dette er tidligere registrert i bug #668

**Comment by AinaEngen** [comment]
@erlendoksvoll @DanRJ

**Comment by DanRJ** [comment]
@AinaEngen Ugyldig datoformat er feilmelding hvis vi ikke klarer å parse dato men nå som vi har fjerna fødselsnummer, skal den klare å parse datoene korrekt. Arvetype har vi oppgave på her #670

**Comment by AinaEngen** [comment]
Testet ok, lukker bug

**Comment by DanRJ** [comment]
Jeg legger til at datoen for noen arvinger vil potensielt vise feilmeldingen som beskrevet i starten ettersom det er Tenor-brukere, som ikke har gyldig datoer. De legger til 8 på tredje tallet i fødselsnummeret, som vi baserer fødselsdagen på.
