### ISSUE TITLE
Manglende språkstøtte

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#684]
Må ligge i textresources:
<img width="1278" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3RMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88b83ad57c2f133fab91f8b1a7fcc16ddaa26200/image.png" alt="image.png" />

**Comment by nlundee** [comment]
Fikset i #685
