### ISSUE TITLE
Testdata

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#688]
Fikse testdata i tt02.

FNumber_AK	PartyID_PK
10858099833	50791154
12876698461	50756302
13867298112	50586395
17916697651	50684398
24817296595	50807378
25878598566	51029920
28885697463	51062864
30840048558	50552094
30844298354	50980142
30920049571	50795680
31853649603	51359454

**Comment by AinaEngen** [comment]
Liste med testdata er lest inn i tt02 og fungerer, så lukker denne
