### ISSUE TITLE
Formue og gjeld: Ingen data funnet

### ISSUE THREAD

**Issue by nlundee** [Altinn/oed#699]
Det må ligge en beskjed til brukeren dersom det ikke finnes noen data på eiendom, kjøretøy, bank eller pensjon.

<img width="535" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM01CQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--307ed26f93192b40622f950f1981f7c9c83f8d75/bilde.png" alt="bilde.png" />

**Comment by AinaEngen** [comment]
Ser korrekt ut på Pensjon, de øvrige er ikke testet (pga testdata). @CecilieFjellsoy - du kan jo sjekke om dette ser korrekt ut i forhold til skissene dine.

**Comment by AinaEngen** [comment]
@DanRJ Vi har fått testet denne ok for Pensjon, men ikke fått sjekket Bank, Kjøretøy, Eiendom da vi ikke har testbrukere som mangler dette. Kan du bare sjekke at tekstene er oppdatert for alle disse fanen. Dvs for øvrige faner, ikke Pensjon

**Comment by AinaEngen** [comment]
Da lukker vi denne! @CecilieFjellsoy @DanRJ @nlundee
