### ISSUE TITLE
Feil i Tab, det er en usynlig boks man må tabbe gjennom

### ISSUE THREAD

**Issue by AinaEngen** [Altinn/oed#705]
"Når man tabber fra en tab-meny for å komme inn i tab-panelet, må man tabbe 2 ganger. Man skal helst kun tabbe 1 gang." -Daniel

**Comment by DanRJ** [comment]
https://www.w3.org/WAI/ARIA/apg/patterns/tabs/

WCAG-messig skal ikke tabbing gå videre til fane2 men til neste. Via tastatur navigerer man videre med piltastene som det står på nettsiden innunder Keyboard Interaction
