### ISSUE TITLE
Vise personvern uten pålogging

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#715]
### Brukerhistorie
Som en person som er interessert i informasjon om Digitalt dødsbo uten å være logget på 
ønsker jeg å kunne søke  informasjon på nettet  og bli ledet til dette inklusive personvernerklæring (tilgjengelighetserklæring?) i Altinn
slik at jeg blir  informert om tjenesten.

### Akseptansekriterier
Gitt at jeg ønsker informasjon om Digitalt Dødsbo.
Når jeg søker på nettet etter informasjon om Digitalt dødsbo
så skal jeg se at dette er tilgjengelig i Altinn sin skjemakatalog
og
 jeg får informasjon om Digitalt dødsbo inklusiv personvernerklæring (tilgjengelighetserklæring?)
og
dette skal være den samme informasjonen som også vises når en person er logget på Digitalt dødsbo
og
informasjonen skal oppdateres kun ett sted.

### Kvalitetskrav/akseptansekriterier
Gitt at..
Når ...
så skal ... 
og... 

### Utfyllende tekst
..

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Test (sprint)**
Akseptansetest bh (ok ev avvik):
Systemtest (ok ev avik?): 
Integrasjonstest (ok ev avvik):

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent):
Teknisk modenhet (høy, medium, lav):
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na):

---
### Test (sprint)
**Funksjonelt**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**System**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Integrasjon**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Comment by DanRJ** [comment]
Dette er ikke en issue som skal utvikles. Dette går utenfor vår kompetanse mtp hvor personvernerklæringen skal ligge. @TageGitHub
