### ISSUE TITLE
Hvor finner vi Avdødes eiendom og rettigheter?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#72]
Aktør involvert:

Knyttet til brukerhistorie:
#39 

beskrivelse:
Må avklares om det er inkludert i skatteoppgjør eller om opplysninger skal hentes fra Kartverket.
JÅB: Kartverket er det stedet hvor vi kan få nok informasjon om eiendommen. Vi tenker å bruke skattemelding som et utgangspunkt for eiendommer/rettigheter som avdøde hadde. 

Frist:

**Comment by curlingnina** [comment]
@JanAage99 det er allerede besluttet at vi skal hente eiendomsinformasjon fra kartverket. Det vil gi oss korrekt info ved dødstidspunktet, mens det som står i skattemeldingen kan være foreldet.

**Comment by lillelars** [comment]
@curlingnina så vi kan lukke denne avklaringen?

**Comment by curlingnina** [comment]
@lillelars ja det er korrekt. Gjør det nå
