### ISSUE TITLE
Bruker skal se om det finnes en ektepakt som er tinglyst

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#74]
#### Brukerhistorie:
Som en arving 
ønsker jeg å se om det finnes tinglyst ektepakt
slik at jeg tar hensyn til dette i skifteoppgjøret 

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case)

- Jeg kan se informasjon fra BRREG når svaret er NEI
- Jeg kan lese en kopi av ektepakten (i et visningsvindu) i Altinn dødsbo  

#### Detalering av brukerhistorie m/ tilhørende akseptansekritere:
Tittel:
Gitt at...
og...
når..
så...

**Avklaring/forutsetning:**
- Når vil vi få API fra BRREG?
- 

**SCENARIO X Akseptansekriterier (minimum happy-case):**
- Jeg kan se informasjon fra BRREG  JA/NEI  
- Jeg kan lese en kopi av ektepakten (i et visningsvindu) i Altinn dødsbo 

**Avklaring/forutsetning:**
- Rett til innsyn i ektepakt for alle arvinger som vil ha rettighet formuesfullmakt? 
- Ektepakt hentes fra Ektepaktregisteret i Brreg via API
- Skal det ikke være en sanntidsversjon (fra API) av ektepakten og ikke en kopi som vi laster ned til OED og viser til arving 

TODO:

**Comment by TageGitHub** [comment]
Videreføres i #253
