### ISSUE TITLE
Skifteform feltet fra et DA bo

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#743]
Sjekk hvor vi bruker den og om vi kan evt fjerne den

**Comment by DanRJ** [comment]
Vi bruker Skifteform for å sjekke om det er privat skifte, hvis det er privat skifte og part har tatt på seg gjeldsansvar, vil vi sette rollen til skifteattest, kan hende vi skal endre til å sjekke lista med arvingerSomPaatarSegGjeldsansvar istedenfor evt sjekke resultattype kategorisering.

**Comment by DanRJ** [comment]
Denne kan vel lukkes ettersom skifteform ikke er i bruk i løsningene lenger? @larsolavk Hva tenker du?

**Comment by larsolavk** [comment]
> Denne kan vel lukkes ettersom skifteform ikke er i bruk i løsningene lenger? [@larsolavk](https://github.com/larsolavk) Hva tenker du?

Ja, Skifteform er borte fra oed-event. Lukker saken.
