### ISSUE TITLE
Informasjon til Domstoler om testamentet

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#75]
Aktør involvert:
Domstolene

Knyttet til brukerhistorie:
#35 

beskrivelse:
Hvordan skal domstolene få informasjon om det finnest testamentet eller ikke?
JÅB: Vi må sende notifikasjon til domstolene via API når en arving har angitt i OED-app at et skrivebords-testamente eksisterer

Frist:

**Comment by TageGitHub** [comment]
Slått sammen med #184
