### ISSUE TITLE
Bekrefte kjennskap til ektepakt

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#77]
#26 Brukerhistorie:
Som en arving
ønsker jeg jeg å bekrefte at jeg har gjort meg kjent med ektepaktens bestemmelser 
slik at arven fordeles etter ektepaktens innhold. 
#### Forretningsverdi 2 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:
JÅB: Forutsetter at arving enten har fått tilgang til ektepakt digitalt fra ektepaktregisteret eller analogt fra advokat eller annen kilde

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
•	Jeg kan avhuke for å bekrefte

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by lillelars** [comment]
@kajabystol @benedicteos  Skal denne være med?

**Comment by benedicteos** [comment]
Tror denne kan utgå. Mener arving ikke skal bekrefte kjennskap til innhold i ektepakt til domstoene per i dag? må undersøkes.
