### ISSUE TITLE
Skal tingretten få beskjed dersom arving krysser av for JA til at det finnes ektepakt

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#78]
Aktør involvert:

Knyttet til brukerhistorie:
#74 

beskrivelse:
"Nattbordsektepakt"
- Dersom det ikke finnes en ektepakt registret hos Brreg, men det finnes en ektepakt og arving vedgår det.... Skal tingretten få beskjed om dette og hvordan skal de få beskjed?
JÅB: Notifikasjon/API etableres slik at DA mottar notifikasjon når det hukes av for skrivebordstestamente i OED

**Comment by TageGitHub** [comment]
Videreført i #255
