### ISSUE TITLE
Skal informasjon fra aktørene lagres? 

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#79]
Aktør involvert:

Knyttet til brukerhistorie:

beskrivelse:
og Kan de lagres?
JÅB: Kan være fordelaktig å kunne lagre ifht at en da kan ha historikk på / oversikt over hva som har skjedd med aktiva og passiva i boet over tid fra avdøde gikk bort til skifte foretas. 
Feks en eiendel tilhørende avdøde som selges dagen etter at vedkommende døde. Vil ikke bli returnert til kall mot aktør med mindre de har historikk for eierskap og vi utformer vår spørring slik at den får tak i denne historikken. Helt klart vanskeligere enn å få tak i nåværende eier vil jeg tro. 
Fordel også ifht om noen aktører sine tjenester skulle være nede og ifht offline bruk

Frist:

**Comment by lillelars** [comment]
@benedicteos  for denne avklaringen, er brukersamtykke tilstrekklig her?

**Comment by benedicteos** [comment]
Nei, her er det ikke (i utgangspunktet) personopplysninger som er beskytta av personopplysningsloven som innhentes, for som regel er den det omhandler død. On the top of my head, det er den avdøde vi innhenter informasjon om fra aktørene, og det er den informasjonen som skal lagres. Men må gjøres konkret vurdering mtp personvern. I tillegg fins aktørenes særlovgivning, feks taushetsplikt som må håndteres og hva vi har lov å gjøre med data vi henter fra dem.

**Comment by lillelars** [comment]
Benytter API til den grad det lar seg gjøre.
