### ISSUE TITLE
Skifteattest rollen blir ikke satt riktig

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#795]
Når vi får beskjed fra DA om at skifteattest er utstedt, ønsker vi å sette skifteattest rollen på arvinger som fikk utstedt skifteattest på seg i nye rader i oed-authz db.

I modellen fra DA er det to relevante felter som har med skifteattesten å gjøre.
Feltet **resultatType** (som er splitter nytt og ikke automagisk oppdatert, er egen issue på det, #745) er feltet som sier hva slags skifteform tingretten har bestemt seg for å gi på boet. (Det er et identisk med et annet felt, forklarer mer nedenfor)

Feltet **skifteattest** som inneholder 3 felter.
1. **Arvinger** (arvinger som er registrert på det tidspunktet dette utstedes)
2. **ArvingerSomPaatarSegGjeldsansvar** (dette er arvinger som har fått skifteattesten utstedt på seg)
3. **Resultat** (dette er feltet som skal være identisk resultatTypen men som er gammelt)

Hvis skifteattesten er utstedt, og skifteformen er av privat form, ønsker vi å gi rollen skifteattest til arvinger som har fått utstedt skifteattesten.

Rollestyring logikken ser ut til å ligge i oed-events men sjekk gjerne oed-authz, om at den ikke overrider roller der.

**Comment by larsolavk** [comment]
Ferdig utviklet, avventer merge av PR til vi har avklart eksisterende feil i autentisering mot DA.
https://altinn.studio/repos/digdir/oed-events/pulls/3

**Comment by thomas-oestdahl** [comment]
Har pushet en branch (https://altinn.studio/repos/digdir/oed/src/branch/795_updated-heirs-text-mapping) med endringer i frontend, som gir støtte for de nye relasjonene fra DA-hendelsene.
