### ISSUE TITLE
Navngivning og implementasjon av felt for skifteattest utstedt eller ikke

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#796]
Når Skatt henter ut rollen tilknyttet en person, er det ønskelig at det er vi som utarbeider logikken hvorvidt det finnes arvinger på boet som har fått utstedt skifteattest, og ikke Skatt. 

For å kunne kommunisere dette til Skatt må vi utvide respons-modellen med 1 felt, det feltet burde være true hvis skifteattest er utstedt på boet (m.a.o hvis minst en arving på boet har fått rollen "skifteattest").

Oppgaven her går ut på å finne et godt navn på dette, kommunisere dette til Skatt og deretter implementere det / lage ny issue på å implementere dette.

**Comment by larsolavk** [comment]
Har foreslått for skatt at vi legger til et boolsk felt "isRestricted" med verdien false dersom personen har alle rettigheter til et bo og verdien "true" dersom personen har begrensede rettigheter etter utstedelse av skifteattest.
