### ISSUE TITLE
Kan vi få lov til å vise informasjon om arvings bankforhold utover Sparebank1 og SBanken?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#80]
Aktør involvert:

Knyttet til brukerhistorie:

beskrivelse:
Andre banker som ikke er inkludert i MVP. Hvordan forholder vi oss til de?
JÅB: Snakke med prosjektledere fra de bankene som er med (Spbank1 og Sbanken) og finne ut hva som gjøres i kontrollinformasjons-prosjektet i slike tilfeller. 

Frist:

**Comment by curlingnina** [comment]
@TageGitHub denne BH kan lukkes, den er ikke relevant for MVP

**Comment by lillelars** [comment]
JA - dette får vi fra KAR.
