### ISSUE TITLE
Informasjon om ektepakt og lantbrukseiendom vises ikke i infoboksen ved valg av skifteform

### ISSUE THREAD

**Issue by jost67** [Altinn/oed#801]
Vi har fått inn data fra Ektepaktregistret, Kartverket og Lantbruksdirektoratet og denne info vises under "Sjekk den dødes opplysninger" og "Sett deg inn i formue og gjeld"

<img width="977" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL05IQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1abd2149b628b7c7a2614c1431ab2719fb71cf3/image.png" alt="image.png" />

<img width="831" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1JIQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8803372a12f3827cc9e627de33974c71e53e230e/image.png" alt="image.png" />

Men når samme arving skal velge skifteform vises ikke denne informasjon.

<img width="1180" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2RIQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d37d53b944300ac874d49d54317c61c92cea953c/image.png" alt="image.png" />

F.nr på den døde: 29918874273
F.nr på arving: 17815799798

**Comment by DanRJ** [comment]
Her fantes skifteerklæring instansen før vi fikk data fra de aktørene, ergo ble ikke dataen med da vi opprettet erklæringen. Det er bare å slette skifteerklæring instansen og opprette ny ved å klikke på Gå til skifteerklæringen.
