### ISSUE TITLE
Pensjon - hvilke forsikringsavtaler er inkludert?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#81]
Aktør involvert:
Norsk Pensjon

Knyttet til brukerhistorie:
#38 

beskrivelse:
Hvilke forsikringsavtaler (og aktører) er inkludert i MVP? (API fra NP, vil vi kunne hente mer info?)
Frist:

**Comment by curlingnina** [comment]
@lillelars dette er beskrevet i NP sin løsningsbeskrivelse. Jeg laster den opp på teams

**Comment by lillelars** [comment]
Ferdigstilt med Norsk Pensjon. Lukker saken.
