### ISSUE TITLE
Roller fra DA er oppdatert og Feil på rollemapping undertrykkes?

### ISSUE THREAD

**Issue by kurt70** [Altinn/oed#821]
Hvis det i dataene fra DA kommer parter med roller som er ukjente for rollemappingen i oed-events, så vil mapping returnere null og parten vil bli droppet fra arvingRolle-listen som igjen resultere i at arvingen ikke får tilgang til boet.

Denne bør oppdateres med nye rollemappinger samt det bør feile og logges at det er feil i rollemappingen.

**Comment by larsolavk** [comment]
Bruker vi PartRole (far, mor, etc) til noe i løsningen, annet enn å vise som tekst i frontend? Spørsmålet stilles fordi det kanskje vil legge føringer på hvordan vi skal behandle eventuelle ukjente roller som måtte komme på en part.

1. Eksisterende implementasjon - Parten får ingen rolle og vil ikke få tilgang til løsningen
2. Kaste exception ved mapping i oed-events - All videre prosessering av hendelseslisten fra DA vil stoppe opp inntil feilen er fikset.
3. Mappe til en default verdi, type "ukjent" - Parten vil få tilgang til boet, men i listen over arvinger vil hen vises med arvetype "ukjent" eller "?"

**Comment by larsolavk** [comment]
Ett konkret eksempel fra tt02:

Her inneholder data fra DA tre arvinger med partRoles "BARN", "BARN" og "GJENLEV_EKTEFELLE". Siden "GJENLEV_EKTEFELLE" ikke finnes i vår mappingtabell blir det ikke laget noen "heirRole" i CloudEventet for denne arvingen og derfor er det kun to av disse arvingen som finnes i oed-authz databasen.

https://oed-test-feedpoller-func.azurewebsites.net/hendelsesliste.test.domstol.no/api/objects/1626d191-0a5d-49bb-9ad3-4720abc69cf9

![Image](https://github.com/user-attachments/assets/035936d2-5934-436e-a37e-b802856a75ee)

**Comment by larsolavk** [comment]
Ukjente verdier vil nå bli mappet til "urn:digitaltdodsbo:arving:ukjentRelasjon"
