### ISSUE TITLE
Feil i visning av grunnlaget for utstedt skifteattest

### ISSUE THREAD

**Issue by DanRJ** [Altinn/oed#828]
Ser ut som det er feil når man skal henvise til hvilken paragraf skifteattesten ble utsatt på. 
Jeg tror det er feilen men jeg er ikke 100%.

Ref bilde:
![Image](https://github.com/user-attachments/assets/5710e6a2-69e9-49f4-b1b6-39be080d59d4)

Vi har fått et nytt felt fra DA som heter resultatType og som egentlig skal brukes men tror resultatType blir brukt for å sette den verdien jeg peker på (resultat). Avklar gjerne med Lars Olav. Men ser ikke ut som verdien blir funnet i resources.nb.json

**Comment by thomas-oestdahl** [comment]
Her ser det ut til å være problem med received-datoen:
```javascript
probateDeclarationTitle = `${formData?.probateResult?.received} - ${probateDecidedTitle}`;
``` 

Jeg kan legge til en undefined/null-sjekk i front, men her er det også noe krøll backend for dette feltet

**Comment by larsolavk** [comment]
Skal være fikset av #844
