### ISSUE TITLE
Konsekvenser ved bruk av proklama

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#83]
Denne omhandler hva som skal skje i løsningen dersom arving velger å utstede proklama. Proklama har egne frister, disse kan påvirke 60-dagers frist, dersom vi setter opp dette i løsningen. Domstol kan forlenge 60-dagers frist. Informasjon må nå Altinn dødsbo, dersom det kan få konsekvenser..

#### Forretningsverdi (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by benedicteos** [comment]
Denne brukerhistorien er ikke riktig. Arvingene kan bestemme at de ønsker proklama utstedt, dette er noe de må betale for og gjøre via domstol. Proklama er ikke inkludert i MVP, det er kun informasjon om proklama som skal være med. For å utstede proklama må arving ut av løsningen. Det vi må finne ut er hvordan evt proklama i et dødsbo påvirker løsningen vår, tidsfrister m.v.

**Comment by TageGitHub** [comment]
Lukkes. Videreføres i #41

**Comment by TageGitHub** [comment]
test
