### ISSUE TITLE
Trenger domstolene beskjed dersom bruker aktivt avlsutter tjenesten? 

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#84]
Aktør involvert:

Knyttet til brukerhistorie:

beskrivelse:
Dersom ingen av eksterne aktører trenger beskjed om at bruker aktivt avslutter tjenesten, så vil denne funksjonalitet bortfalle i første omgang.

Frist:

**Comment by TageGitHub** [comment]
Videreført i #18
