### ISSUE TITLE
Datoformatering på "Skifteattest for dødsboet" er undefined

### ISSUE THREAD

**Issue by thomas-oestdahl** [Altinn/oed#844]
Datoformateringen feiler fordi probateResult.received ikke eksisterer (null). 
![Image](https://github.com/user-attachments/assets/2c84c757-29f5-4f63-966f-8d85a8f2cbd9)

**Comment by larsolavk** [comment]
Setter nå data på det deserialiserte eventet, som igjen blir benyttet til å sette tidspunkt for utstedelse av skifteattest i instansdataene. Dette vil ikke fikse eksisterende bo med manglende dato, men bør gjøre at alle bo som fra nå får utstedt skifteattest vil få satt dato korrekt.
