### ISSUE TITLE
Påstander vises ikke korrekt i DD

### ISSUE THREAD

**Issue by thomas-oestdahl** [Altinn/oed#847]
Det skal vises tydelig hvis andre parter har kommet med påstander/ny informasjon om sivilstand, ektepakt og eiendom.

De følgende visningene skal vise påstand, hvis det har blitt lagt inn i skifte-erklæringen:

![Image](https://github.com/user-attachments/assets/2fe0fa10-a0ed-48c3-87ee-bc46147c71ba)
![Image](https://github.com/user-attachments/assets/5648c57f-a9b8-4ba6-9746-634cb96981e7)
![Image](https://github.com/user-attachments/assets/513946b6-e832-4a61-a961-1a288797e793)

**Comment by jost67** [comment]
Har testet denne bugfix og det fungerer.
