### ISSUE TITLE
Ønsker oppsummert av innhentet data

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#85]
#### Brukerhistorie:
Som en arving
ønsker jeg å få se informasjon om data som er innhentet fra aktørene
slik at jeg har oversikt over avdødes aktiva og passiva

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:
Data hentes inn gjennom en rekke API'er beskrevet i individuelle brukerhistorier for hver enkelt aktør.

**Godkjent Juridisk (OK // N/A // Ikke godkjent)**
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- Bruker skal se aktiva og passiva fra aktører som er med i MVP-samarbeidet på egen side/kort for aktiva/passiva
- Bruker skal bare kunne lese og ikke endre data fra aktører

**SCENARIO X:**

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by benedicteos** [comment]
Samme brukerhistorie som #25

**Comment by TageGitHub** [comment]
Slått sammen med #191
