### ISSUE TITLE
Logge og vise hendelser/Status  i DD

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#86]
### Brukerhistorie

Som  arving
ønsker jeg at hendelser i DD skal logges og vises
slik at jeg kan se hva som har skjedd i boet

**Krav/akseptansekriterier**
Gitt at jeg logger meg på boet og utfører aktiviteter i DD
Når dette skjer
så skal DD logge/lagre mine hendelser
og
hendelsene skal vises i DD 
og
hendelsene skal være synlig for alle som har tilgang til løsningen.
og
det skal logges når hendelsen oppsto, hvem som trigget  en og hvilken  hendelse det gjelder.

~~itt at det oppstår hendelser som følge av forhold som IKKE er relatert til brukere av DD.
Når DD oppdager dette 
så skal DD logge/lagre hendelsen
og
hendelsen skal vises i DD 
og
hendelsen skal være synlig for alle som har tilgang til løsningen.
og
det skal loggers når hendelsen oppsto, hva som er grunn til at den skjedde  og hvilken hendelse det gjelder.~~

**Utfyllende tekst**
Eksempler på hendelser som skal logges (ikke uttømmende):
Bruker av DD:
 -   logger seg på
Andre:
 - erklæring om privat skifte er sendt inn og av hvem
 - skifteattest er utstedt
 - Arvinger uten skifteattest er gitt begrenset innsyn til formue/gjeld.
 
---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): OK
Avklaringsområder: 

**Dokumentasjon**

**GUI**
Status: (ok, under avklaring, n/a): 
Avklaringsområder:
- [ ] 
**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder: 
- [] 

Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:

Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): bør
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): n/a

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Test (sprint)
**Funksjonelt**
Akseptert (j/n): 
Avvik:
- [ ] 
- [ ] 
- [ ] nn

**System**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

**Integrasjon**
Akseptert (j/n): 
Avvik:
- [ ] nn
- [ ] nn
- [ ] nn

-----------------------------------------------------------

**Comment by TageGitHub** [comment]
@DanRJ @CecilieFjellsoy 
Brukerhistorien gjenåpnes da den ikke skulle vært lukket.

**Comment by DanRJ** [comment]
@TageGitHub Her må aktivitetene defineres mer tydelig. @CecilieFjellsoy og jeg har forslag om å starte med eksisterende korrespondanser slik at vi kan redusere "spam"-inntrykket for arvinger. Deretter kan vi eventuelt spe på med ikke-korrespondanse-verdige aktiviteter. 

Vi begge mener at det at noen er logget på, er ikke nødvendig å ha med i aktivitetslista

**Comment by TageGitHub** [comment]
Lukkes. Overtas av #64

**Comment by TageGitHub** [comment]
Overtas av #64
