### ISSUE TITLE
Ikke mulig å velge "Uskiftet bo"

### ISSUE THREAD

**Issue by jost67** [Altinn/oed#860]
**Beskriv feilen**
Det er ikke mulig å velge "Uskiftet bo" på tross av at kriteriene for at få velge denne skifteform (Sambo, Ektefelle, Enke, Ektemann eller partner) er oppfylt. 

**Gjenskape feilen**
Steg for å gjenskape:
1. Fra valgfri dødsbo, velg arving som er Sambo, Ektefelle, Enke, Ektemann eller partner
2. Gå til valg av skifteform og velg "Uskiftet bo"
3. Du får nå feilmelding
4. 

**Skjermdump av feilen**
![Image](https://github.com/user-attachments/assets/47f17b7b-0f76-4ce0-90fc-c2f95d799e3d)
![Image](https://github.com/user-attachments/assets/a3221624-4c4c-4380-bd0a-34185bce14fa)

**Comment by larsolavk** [comment]
I koden i oed-declaration ser det ut til at den gjør en string compare på navn for å finne current user i listen over arvinger. Problemet er bare at fornavn/etternavn er snudd om i disse feltene, så man vil jo aldri finne korrekt arving:
`"SF_PartyName": "HAI TROSSIG"`

```
"Heirs": [
                {
                    "altinnRowId": "c89d16dc-5dbc-4709-8529-7723d4a946b4",
                    "Name": "BLID STOKK",
                    "Kinship": "urn:digitaltdodsbo:arving:barn",
                    "PartyId": 51234898
                },
                {
                    "altinnRowId": "55fec255-2afa-408e-8c39-f0ff60504452",
                    "Name": "TROSSIG HAI",
                    "Kinship": "urn:digitaltdodsbo:arving:gjenlevEktefellePartner",
                    "PartyId": 51234897
                }
            ],
```

**Comment by larsolavk** [comment]
Da er denne fikset og deployet til tt02
