### ISSUE TITLE
Avklare videre prosess dersom alle arvinger har tatt aktiv stilling til skifteform

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#87]
Aktør involvert: domstolene

Knyttet til brukerhistorie: #28 

Beskrivelse: En arving vil ikke påta seg gjeldsansvar, men de øvrige ønsker det – og de vil videre i prosessen før 60 dager er gått. Skifteattesten utstedes til den eller de av arvingene som innen utløpet av fristen på 60 dager, jf. ny arvelov §118. For å unngå å vente på svar fra alle arvinger i denne digitale tjenesten før skifteattest utstedes, så bør vi ha en løsning som sørger for at man aktivt kan si at man ikke ønsker å påta seg gjeldsansvar. 
JÅB: Kan ha det så enkelt som at i trinnet hvor arving skal ta et aktivt valg har man valgene
- [ ] Jeg påtar meg med dette fullt og solidarisk ansvar for avdødes gjeld og andre forpliktelser
- [ ] Jeg påtar meg IKKE fullt og solidarisk ansvar for avdødes gjeld og andre forpliktelser

Dette som radio-buttons, dvs at bare en av alternativene kan velges. 
Så bør man spørres om man er sikker på valget før det gjennomføres.

Frist:

**Comment by lillelars** [comment]
Løses av #371
