### ISSUE TITLE
Tinglyst ektepakt vises ikke under velg skifteform

### ISSUE THREAD

**Issue by jost67** [Altinn/oed#875]
**Beskriv feilen**
I den dødes opplyninger/Ektepakt ser man at det finnes en tinglyst ektepakt. Men når en skal velge skifteform mangler denne informasjon. Lantbrukseiendom vises der, men altså ikke Ektepakt.

**Gjenskape feilen**
Steg for å gjenskape:
1. Logga på med 11855497427
2. 
3. 
4. 

**Skjermdump av feilen**
![Image](https://github.com/user-attachments/assets/9f128247-ce71-406f-87eb-ecb75e6d2a25)
![Image](https://github.com/user-attachments/assets/b7d824d3-562f-46b3-8212-af2640c5af3f)

**Comment by DanRJ** [comment]
Oppgaven løst, ektepakter ble ikke hentet ut før man gikk til ektepakt, og da var det ikke lagret noe på instansen.

**Comment by jost67** [comment]
Retested og godkjent.
