### ISSUE TITLE
Det skal ikke være mulig å sende inn skifteerklæring hvis ingen arving har valgt å ta på seg gjeldsansvar

### ISSUE THREAD

**Issue by jost67** [Altinn/oed#876]
**Beskriv feilen**
En av hodekriteriene for å kunne sende inn skifteerklæring er at man tatt på seg gjeldsansvar. Nå vises knappen for innsending men det er ikke noe i veien for å faktisk klikke på den å starte innsending. 
**Gjenskape feilen**
Steg for å gjenskape:
1. Logge inn med valgfri arving
2. Gå til velg skifteform 
3. Velg privat skifte 
4. Velg å ikke ta på deg gjeldsansvar

**Skjermdump av feilen**
![Image](https://github.com/user-attachments/assets/68c7d75b-adf4-4f85-bf1d-39ae56cada62)

**Comment by DanRJ** [comment]
Identisk til #748

**Comment by jost67** [comment]
Retested og godkjent.
