### ISSUE TITLE
Pre-utfylling av erklæring

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#88]
Aktør involvert:

Knyttet til brukerhistorie:

beskrivelse: kan vi generere en forhåndsutfylt erklæring? Må sørge for at alle krav til erklæring om privat skifte er oppfylt, samt signeringskrav. Ønsker å preutfylle erklæringen med personinformasjon om arvingene, samt innhentet data fra aktørene (ikke sikkert vi skal sende informasjon vi har innhentet fra aktører, tror ikke det er krav om det, og domstolene bør heller innhente dette selv via eksisterende API) og legge ved signering.

JÅB: I vår app bør det være mulig for arvingene (å generere og) å vise en skifteerklæring/oppsummering når en har kommet langt nok i prosessen. Når denne er klar for å sendes til tingrett/DA kan arvinger initiere signeringsprosess for denne skifteerklæring/oppsummering slik at når alle ha signert så sendes den til tingrett/DA.
Skifteerklæring/oppsummering skal være preutfylt med data som er kommet fram gjennom prosessen som feks hvem arvinger er og personalia/data om den avdøde. 
Data fra aktører er ikke med i skifteattest i dag så det vil forenkle løsning og hensiktsmessig i første omgang å droppe data fra aktører. 

Frist:

**Comment by lillelars** [comment]
Løses av #371
