### ISSUE TITLE
Ikke mulig å gi skiftefullmakt

### ISSUE THREAD

**Issue by jost67** [Altinn/oed#887]
**Beskriv feilen**
Min bruker har tatt på seg gjeldsansvar og står som en arving som kan gi skiftefullmakt. Men knappen "Gi skiftefullmakt" fungerer ikke lenger. Det skjer ikke noe når en klikker på denne knappen.

**Gjenskape feilen**
Steg for å gjenskape:
1. Logget på med F.nr 14908499760
2. 
3. 
4. 

**Skjermdump av feilen**
![Image](https://github.com/user-attachments/assets/e6302ba3-0583-45ae-8f36-8ac9f330197e)

**Comment by larsolavk** [comment]
Hvis dette skjedde rett etter at det ble utstedt skifteattest så kan det være rollene som er cachet i altinn-systemet.. Prøv igjen etter noen minutter. Dette vil sannsynligvis ikke være et problem i produksjon da det naturligvis vil gå tid fra man får melding om utstedt skifteattest til man faktisk går inn og skal gjøre flere handlinger.
