### ISSUE TITLE
Hvordan håndteres kommunikasjon mellom Altinn dødsbo og domstolene dersom arving ikke gjør noe?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#89]
Aktør involvert:

Knyttet til brukerhistorie:
#29 

beskrivelse:
Hvordan håndteres kommunikasjon mellom Altinn dødsbo og domstolene dersom arvingen ikke foretar seg noe?
hvordan håndterer vi dette i Altinn dødsbo og informerer arving på dette?
JÅB: Mot arvingene: Varsel sendes ut og minner om at OED ikke er benyttet og info om hva konsekvensene evt blir. 
Mot domstolene: Etter en viss tid sendes notifikasjon via API til domstolene om at ingenting er skjedd etter at arvinger har fått varsel

Frist:

**Comment by TageGitHub** [comment]
Videreført i #226 #228
