### ISSUE TITLE
Håndtering av manglende pålogging i Altinn dødsbo

### ISSUE THREAD

**Issue by benedicteos** [Altinn/oed#9]
Som  arving
ønsker jeg at Domstolene skal informeres dersom minst en av arvingene ikke har logget seg på OED
slik at Domstolene kan ta kontakt med arving og avklare om arving ikke ønsker digital støtte gjennom OED

**Krav/akseptansekriterier** 
Gitt at OED oppdager at en arving ikke har logget seg på løsning etter et parametersatt tidspunkt
Når det skal meldes fra om dette 
så skal Domstolene informeres (og arvingen/er?) 
og
OED bli oppdatert med resultate som kan være utvidet frist, eller at boet skal avsluttes i OED.

Gitt at OED boet skal avsluttes i OED
Når Arvinger og andre berørte har fått beskjed om dette 
så avsluttes boet etter et parametersatt tidspunkt

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon: 

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent):  må
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint
Gå opp reguleringer i arveloven (kaja)

---
### Annet
Beskrivelse: Hva skal skje dersom arvingene velger å ikke logge seg på løsningen? Må da være en stopp, kommunikasjon mellom Altinn dødsbo og domstolene, og sørge for at behandlingen går over i papirprosess?
JÅB: Vi må vel i alle fall sørge for  notifikasjon/API ut mot DA/tingrett når dette skjer

---

**Comment by lillelars** [comment]
Håndteres i #387
