### ISSUE TITLE
Trenger eksterne aktører informasjon om status til dødsbo?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#91]
Aktør involvert:
`Bankene, SVV, forsikringer osv

Knyttet til brukerhistorie:

beskrivelse:
Trenger eksterne aktører informasjon om status til dødsbo f.eks at det foreligger en boet ikke ska skiftes privat, eller ved skifteattest?
JÅB: Aktører ønsker notifikasjon om at skifteattest for boet er utstedt. Vil lette saksbehandling på deres side. For å oppnå effektivisering bør dette leveres fra vår side. 

Frist:

**Comment by TageGitHub** [comment]
Videreført i #222
