### ISSUE TITLE
Hva hvis det er behov for å endre på skifteattesten etter at den er utstedt

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#92]
Aktør involvert: domstolene

Knyttet til brukerhistorie:
Må evt gås opp med DA hvordan vanlig prosess da er manuelt i dag, dersom skifteattest må endres. 
- Hvem kan sette eksisterende Skifteattest som ugyldig ? 
- Hvilke entry punkter inn i prosess i app igjen trengs ? 
- Status'er må oppdateres
- Informasjon må gå ut til arvinger/interessenter

beskrivelse:

Frist:

**Comment by lillelars** [comment]
Ute av scope for OED - håndteres manuelt.
