### ISSUE TITLE
Må vi ha noe som sørger for avslutning av instansen?

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#93]
Aktør involvert:

Knyttet til brukerhistorie:
#47 
beskrivelse:
 Må gåes opp. Skal dok for: arvinger, aktører og eier av tjenesten. evnt?
JÅB: Må instans avsluttes eller kan den være flytende dvs aldri avsluttet ? Teknisk sett finnes det mange flytende instanser i Altinn allerede og ifh bo har vi begrepet flytende bo selv om det er noe helt annet enn en flytende instans. 
Det finnes vel ingen analog versjon av å avslutte et bo, slik det fungerer i dag ?  Dvs eiendeler etter en avdød kan stå i den avdødes navn lenge etter dennes død uten at det nødvendigvis skjer noe / eiendel blir skiftet. 
Derfor vil det ikke være nødvendig å avslutte bo/instans med mindre dette er et krav om dette fra en av partene som er med i OED-samarbeidet ? Men en rapport som gir oversikt over bo vil være praktisk. Ref #47 
En praktisk løsning på å unngå flytende instanser er at instans avsluttes automatisk etter en gitt periode. 
Ønsker man i størst mulig grad å avslutte instans må det kunne gjøres av fullmektig eller ved samtykke fra alle arvinger. 

Frist:

**Comment by TageGitHub** [comment]
Videreført i #260
