### ISSUE TITLE
Varsel til aktørene om at skifteattest er utstedt

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#95]
Aktør involvert: alle aktører (ex domstolene)

Knyttet til brukerhistorie:

beskrivelse: aktørene ønsker ikke en hendelsesbasert trigger om at skifteattest er utstedt. I dag er det slik at arvingene leverer skifteattesten, og vi antar derfor at det må være en tilsvarende løsning i OED. Dvs skal vi legge opp til at arvingene i løsningen kan benytte den digitale representasjonen av skifteattesten til å informere aktørene om at de kan starte sine oppgjørsprosesser? Dette må også gås opp juridiske.
JÅB: Når dig repr av skifteattest, som er en rettighet, er etablert etter behandling hos DA må arvingene kunne sende bevis for denne rettigheten til ønskede aktører. To mulige scenarier kan da tenkes: 
1. Aktør har etablert mottak av dig repr av skifteattest i sine systemer via API. Når arving ønsker det sendes dig repr av skifteattest fra OED til aktørs mottak. Aktør kan dermed avslutte kundeforhold for den avdøde i sine systemer. 
2. Strøm på papir: For aktører som ikke har etablert mottak av dig repr av skifteattest. Arving kan få ut dig repr av skifteattest på fil, pdf e.l. Denne kan i sin tur sendes til aktør hvor avdøde hadde kundeforhold. 
Må gås opp mer detaljert hva aktører faktisk ønsker samt juridiske konsekvenser av dette.

Frist:

**Comment by TageGitHub** [comment]
Videreført i #222
