### ISSUE TITLE
Bruk av digital representasjon av utstedt skifteattest

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#96]
#### Brukerhistorie:

Som en... arving
ønsker jeg å bruke den digitale representasjonen av utstedt skifteattest
slik at jeg... kan informere aktørene om at det foreligger skifteattest for dødsboet

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur: 

#### Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- jeg skal kunne velge å distribuere skifteattesten til aktører
- jeg skal kunne få bekreftelse på at aktører har fått info om at skifteattest er utstedt

#### Avklaringer for å få realisere denne brukerhistorien:
Digital representasjon av skifteattest etableres i Altinn autoriasjon når DA utsteder denne.

#### Scenario X:
Tittel:
Gitt at...
og...
når..
så...

**Comment by curlingnina** [comment]
Denne brukerhistorien ble assignet til meg ift fordeling av brukerhistoriene under scenario1, men jeg har ikke innsikt nok til å skrive akseptansekriteriene. Jeg assigner den derfor til @JanAage99 .

**Comment by TageGitHub** [comment]
Hensyntatt i #222
