### ISSUE TITLE
Varsel til aktører når fullmektig er utnevnt

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#97]
#### Brukerhistorie
Som en arving
ønsker jeg å informere aktørene om at det er utpekt en fullmektig
slik at aktørene kan starte sine interne oppgjørsprosesser

**Krav/akseptansekriterier** 
Gitt at  fullmektig er utpekt og har tilgang til OED
Når dette er oppdatert i OED og 
Så skal det sendes informasjon til de aktører som er registrert som mottagere av denne informasjonen.

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
- [ ] Gå opp med AA. 
- [ ] Hvordan registreres de som skal være mottager av informasjon om fullmektig?

Avklaringsområder: 
Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:

- [ ] Fullmakt etablert gjennom altinn autorisasjon tilgjengeliggjøres for aktører via API?

Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): bør
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by curlingnina** [comment]
Jeg forstår ikke helt sammenhengen mellom tittelen og beskrivelsen, og asssigner den til @JanAage99

**Comment by lillelars** [comment]
Håndteres senere. Lukker denne saken.
