### ISSUE TITLE
Generere utskriftsvennlig versjon av utstedt skifteattest

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#99]
#### Brukerhistorie
**Intro**
Som en arving
ønsker jeg å kunne velge å skrive ut utstedt skifteattest
slik at jeg kan bruke den til å starte oppgjøret

**Krav/akseptansekriterier**  _(detaljering av BH med tilhørende akseptansekriterier)_
Gitt at skifteattest er lagret i OED/Altinn
Når jeg ønsker å bruke denne mot aktører som ikke har kobling til OED app
så skal jeg kunne skrive ut denne
og
utskriften skal være i samsvar med krav til original skifteattest.

**Utfyllende tekst**

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
- [ ] Hva er krav til gyldig utskrift av skifteattest?
- [ ] Hvem skal skrive ut skifteattest? 

Dokumentasjon

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder: 
Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by curlingnina** [comment]
Se Avklaring #100

**Comment by lillelars** [comment]
Håndteres i eget issue om mottatt skifteattest
